### ISSUE TITLE
Using "as" polymorphic prop with custom tag name (dashed) doesn't work like the document example

### ISSUE THREAD

**Issue by ChrisKuBa** [styled-components/styled-components#3582] opened 2021-09-17 05:20 UTC
Styled components can be used with the
- "as" polymorphic prop 
- "forwardedAs" prop .

Using "as" with a styled component results in an "Autonomous custom elements" (replacing the original tag).
Using "forwardedAs" with a styled component result in a "Customized built-in elements" (with original tag + as attribute).

The aim is to use "Autonomous custom elements", but when using custom element names (with dash), the style won't be applied.

See document example with native element vs. reproduction:
https://styled-components.com/docs/api#as-polymorphic-prop

## Environment
```
## System:
 - OS: Windows 10 10.0.19042
 - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 15.41 GB / 31.84 GB
## Binaries:
 - Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
 - npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - babel-plugin-styled-components: ^1.13.2 => 1.13.2
 - styled-components: ^5.2.3 => 5.3.1
```

## Reproduction

https://codesandbox.io/s/gifted-goldberg-bgesg

## Steps to reproduce

```javascript
// import styled from "styled-components";

const Component = styled.div`
  color: red;
`;

export default function App() {
  return (
    <>
      <div>OK - example of the documentation</div>
      <Component as="button">button tag - use as button</Component>
      <br />
      <br />
      <div>OK - also works, but without native button style</div>
      <Component forwardedAs="x-button">
        div as="x-button" - use forwardedAs x-button
      </Component>
      <br />
      <br />
      <div>FAILS - styled component style was not applied</div>
      <Component as="x-button">x-button tag - use as x-button</Component>
    </>
  );
}
```

## Expected Behavior

```javascript
<Component as="x-button">x-button tag - use as x-button</Component>
```
also gets the color red style

## Actual Behavior
The style is missing.

**Comment by kitten** [comment] 2021-09-17 05:40
Duplicate of #3179 

I believe this is related to custom elements in React needing the `classNams` prop to be switched over to a regular `class` one that the custom element can see.

Please also take care to debug this yourself. I don't really believe given the reproduction that this qualifies as an issue given the duplicate and that it could've also gone as a question onto a different platform ✌️ I'd try wrapping a component here that can use the `className` prop however you need and pass it on as whatever you want

**Closed by kitten** 2021-09-17 05:40 UTC

**Comment by ChrisKuBa** [comment] 2021-09-17 12:01
Thx. I overlook this.
I updated the reproduction with an additional running example. But boilerplate code is necessary.
```javascript
lass MyComponent extends HTMLElement {
  static get observedAttributes() {
    return ['classname'];
  }
  
  attributeChangedCallback(name, oldValue, newValue) {
    this.setAttribute('class', newValue);
  }
}

window.customElements.define('x-button-y', MyComponent);
```
