### ISSUE TITLE
Server side rendering breaks if you after styleSheet.reset()

### ISSUE THREAD

**Issue by ForbesLindesay** [styled-components/styled-components#378] opened 2017-01-14 14:47 UTC
## Version

v2 branch in github

## Reproduction

```js
import React from 'react';
import {renderToString} from 'react-dom/server';
import styled, {styleSheet} from 'styled-components';

const Heading = styled.h1`
  color: red;
`;

renderToString(<Heading>Hello World</Heading>);

console.log('run 1:')
console.dir(styleSheet.getCSS());

styleSheet.reset();

renderToString(<Heading>Hello World</Heading>);

console.log('run 2:');
console.dir(styleSheet.getCSS());
```

Outputs:

```
run 1:
'.styled-components-bug__Heading-ecpbxy {}\n.kDmCMo { color: red; }'
run 2:
''
```

## Steps to reproduce

Attempt to render a component server side by resetting the style sheet, rendering it, then getting the css.

## Expected Behavior

You should get the same css every time you render.

## Actual Behavior

After resetting, you get empty css.

**Comment by mxstbr** [comment] 2017-01-14 15:23
Thanks for testing the v2 branch, much appreciated!

/cc @thisguychris any ideas what's up here?

**Comment by teonik** [comment] 2017-01-14 16:43
I can confirm this issue.Also happens on `master` if you call styleSheet.flush().

I think this happens because components are imported once in the server so the `ComponentStyle` constructor, which calls `inject()` on the styleSheet, is also called once for every styled component.
`reset()` clears all cssRules on the stylesheet and the components are left with dangling pointers to previous rule entries.

I will look more into it when i got the time and provide some feedback.

**Comment by geelen** [comment] 2017-01-15 08:54
Ah yep I put in a cache in `ComponentStyle`. That should be moved across to `StyleSheet` and cleared when you call reset. I'd do it but I'm on my phone :)

**Comment by wmertens** [comment] 2017-03-09 10:27
in the mean time, you can do SSR by simply not calling `reset()` 😄 . It's a little less efficient byte-wise but not terrible.

**Comment by wmertens** [comment] 2017-03-30 10:06
My little workaround results in weird styles after a while :( I'd like to see this fixed before we go into production, soon.

@geelen is fixing this really as easy as moving a cache var to a different place or does it mean updating the code all over the place?

**Comment by mxstbr** [comment] 2017-04-01 09:34
This will be fixed with the new API I'm pretty sure (ref #386) since you won't need to call `reset` anymore.

**Closed by mxstbr** 2017-04-01 09:34 UTC
Labels: bug

**Comment by ehd** [comment] 2017-04-14 14:28
Would you accept a fix for `reset()` in an interim 2.0.0-xx release until #386 has replaced the current API?

**Comment by mxstbr** [comment] 2017-04-14 15:25
Sure!

**Comment by ehd** [comment] 2017-04-15 09:19
@geelen Could you nudge me in the right direction here? I saw @thisguychris’s [commit](https://github.com/thisguychris/styled-components/commit/67f6889d695272031f41bdee3b1c88ab806affb2) but it breaks the `styleSheet.reset()` test.
