### ISSUE TITLE
[Flow] Coverage on Flow 0.59.0

### ISSUE THREAD

**Issue by verydanny** [styled-components/styled-components#1321] opened 2017-11-21 21:01 UTC
## Steps to reproduce
1. Installed:
- `flow-bin@0.59.0 flow-typed@2.1.5 styled-components@2.2.0`
-  .flowconfig
```
[ignore]
.*/dist/.*
.*/node_modules/styled-components/.*
```
- `flow-typed install styled-components@2.2.0`

2. Shows following code is uncovered resulting in 67% coverage which is below my 90% requirement.

![screenshot 2017-11-21 15 54 30](https://user-images.githubusercontent.com/13333822/33096364-ae4bc8e2-ced4-11e7-8b1a-4892323d0afa.png)

## Expected Behavior

Expected full coverage due to flow-typed typings

## Actual Behavior

Says that `styled` is unknown.

**Comment by verydanny** [comment] 2017-11-21 22:27
Gotta make a note. I tracked down that the issue is that there's flow typing for this:

```javascript . 
export default styled('div')`
  background-color: gray;
  color: #fff;
  padding: 10px;
`;
```

But not this:  
```javascript
export default styled.div`
  background-color: gray;
  color: #fff;
  padding: 10px;
`;
```

Why was the typing written to behave differently from documentation?

**Comment by philpl** [comment] 2017-11-22 02:24
@styled-components/typers: coincidentally I’ve noticed today that I couldn’t figure out how to assign a styled.X component a new type. That might be related; I’m not sure whether that’s a new issue with the >=0.59 typings

**Comment by mwalkerwells** [comment] 2017-12-02 18:35
Looks like a bug. Not sure what the issue is at first glance, but I'd take a look at updating this:

```js
  declare module.exports: {
    $call: $npm$styledComponents$Call<ComponentListKeys>,

    injectGlobal: TaggedTemplateLiteral<void>,
    css: TaggedTemplateLiteral<Array<Interpolation>>,
    keyframes: TaggedTemplateLiteral<string>,
    withTheme: $npm$styledComponents$WithTheme,
    ServerStyleSheet: typeof Npm$StyledComponents$ServerStyleSheet,
    StyleSheetManager: typeof Npm$StyledComponents$StyleSheetManager,
    ThemeProvider: typeof Npm$StyledComponents$ThemeProvider,

    ...$npm$styledComponents$StyledComponentsComponentList,
  };
```
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/styled-components_v2.x.x/flow_v0.53.x-/styled-components_v2.x.x.js#L289-L301

When I wrote the library definition for this, there were some weird gotchas with ``module.exports``, object spreads, and exact object types.

**Comment by shrynx** [comment] 2018-05-09 03:30
@mxstbr 
I have opened a PR fixing this issue
https://github.com/flowtype/flow-typed/pull/2190

**Comment by shrynx** [comment] 2018-05-23 17:52
should be fixed now 😃

**Comment by probablyup** [comment] 2018-06-21 17:17
Thanks @shrynx!

**Closed by probablyup** 2018-06-21 17:17 UTC
Labels: help wanted :sos:, typings :wrench:
