### ISSUE TITLE
Overriding media queries with higher specificity doesn't work in production

### ISSUE THREAD

**Issue by mkrds** [styled-components/styled-components#1587] opened 2018-03-07 23:00 UTC
## Version
styled-components: 3.2.1
react: 16.2.0
react-scripts: 1.1.1

## Reproduction

https://codesandbox.io/s/4jq0owx054/

## Steps to reproduce
This problem occurs only in served production ready bundle. I'm using newest CRA..
## Expected Behavior
While overriding styles of component using styled() method all styling works except for media queries.
## Actual Behavior
Media queries working in such caces :)

**Comment by kitten** [comment] 2018-03-07 23:02
Duplicate of https://github.com/styled-components/styled-components/issues/1576 or rather: https://github.com/thysultan/stylis.js/issues/99

It will hopefully be addressed soon over at stylis.

For now, all you have to unfortunately reverse the order of `@media` rules and style rules, meaning `@media` rules must wrap style rules, not the other way around 😞

**Closed by kitten** 2018-03-07 23:02 UTC
