### ISSUE TITLE
Wrong CSS output for using other Styled component reference + pseudo selector?

### ISSUE THREAD

**Issue by RowanDZ** [styled-components/styled-components#3314] opened 2020-10-20 16:32 UTC
## Environment
Locally and also in CodeSandbox. Styled-components v5.2.0

## Reproduction
https://codesandbox.io/s/styled-component-playground-forked-6r0uf?file=/src/index.js

## Steps to reproduce
- Open the code sandbox. Styled-Components 5.2.0 should be selected. You'll see a blue, blue and green box
- Now change to Styled-Components 5.1.1, and see how the first box turns yellow (as expected behaviour)
- Comment out the middle box, the 'I should be blue'

## Expected Behavior
Initially: Yellow, blue, none
After commenting out the middle one: Yellow, none.

## Actual Behavior
**Initially: Blue, blue, none** << WRONG
After commenting out the middle one: Yellow, none. As it should

## Extra
It looks like it's dependent one other usages of the component and order maybe.

**Comment by binhxn** [comment] 2020-10-26 19:08
I'm encountering the same issue as above. When upgrading to v5.2.0, I noticed the classNames are now shared between components. It seems like the className obfuscation algorithm (or lack of a better term) is not working as expected:

Here's a screenshot of the unexpected shared className based on the Codesandbox above:

<img width="394" alt="Screen Shot 2020-10-26 at 12 04 04 PM" src="https://user-images.githubusercontent.com/8155387/97216991-d82e4e00-1783-11eb-84b5-b0d979eaa958.png">

**Comment by fernandosouza** [comment] 2020-11-05 13:20
Facing the same issue but for components which are created from another styled component.

```
const NewStyledComponent = styled(AnotherStyledComponent)
```

**Comment by RowanDZ** [comment] 2021-01-28 14:47
Any news on this?

**Comment by jojkos** [comment] 2021-04-06 09:41
I tried to update to the latest styled-components version (5.2.3) and the issue still persists

**Comment by RowanDZ** [comment] 2021-07-28 14:53
Bump 5.3, still an issue

**Comment by kitten** [comment] 2021-08-09 16:49
Duplicate of #3265

**Closed by kitten** 2021-08-09 16:49 UTC
