### ISSUE TITLE
Adding prefix to grid layout

### ISSUE THREAD

**Issue by igor-ribeiro** [styled-components/styled-components#1184] opened 2017-09-27 17:44 UTC
## Version
2.1.2
## Reproduction
```js
const Container = styled.div`
  display: grid;
`
```

## Expected Behavior
Output:
```css
.sc-sc-gzVnrw {
  display: -ms-grid;
  display: grid;
}
```
## Actual Behavior
Output:
```css
.sc-sc-gzVnrw {
  display: grid;
}
```

https://github.com/postcss/autoprefixer/issues/603#issuecomment-168979519

**Comment by philpl** [comment] 2017-09-28 15:46
cc @thysultan

**Comment by thysultan** [comment] 2017-09-28 15:58
Related discussion – [stylis.js/issues/51](https://github.com/thysultan/stylis.js/issues/51).

**Comment by philpl** [comment] 2017-09-28 15:59
Alright, I'll go ahead and close this as it's something related to stylis and not SC. Makes sense unfortunately that it won't work ^^"

**Closed by philpl** 2017-09-28 15:59 UTC

**Comment by JeroenReumkens** [comment] 2018-12-04 19:47
@kitten @mxstbr   I won't create a new ticket right away, but wanted to check in with you if you think we as Styled Components community could do anything to make sure this will be added to Stylis. It's a year later,  and there is a new issue over at the Stylis repo: https://github.com/thysultan/stylis.js/issues/119

I was thinking that if we'd open an issue at the Styled Components repo as well, we might get some additional attention and find the right people who have the time and knowledge to fix this. I've already asked for some directions on how to fix this in the Stylis repo, because I really don't know where to start in all of the switch cases :( 

I also have a feeling that since Grid is becoming more popular every day, the lack of grid prefixing could one day could become a reason for users not to use Styled Components, which would be a shame I think.

I'ld love to hear your opinion on this.

**Comment by probablyup** [comment] 2019-01-08 14:31
So the problem is it’s not that simple. IE11 grid is missing a lot of
functionality that can’t be easily replicated with prefixing alone. If you
need to support IE11 in your browser matrix, it’s better not to use grid
layout at all.

**Comment by JeroenReumkens** [comment] 2019-01-08 15:07
Didn't find a solution either for Styled Components. 
But @probablyup you know that Autoprefixer did a first effort of implementing it a few months back, which seems to work quite good? https://github.com/postcss/autoprefixer#grid-autoplacement-support-in-ie But then again this should be fixed in the Styllis repo, or Styled Components should switch to a different library than Styllis? 

---

Ps; @rnnyrk Hahaha, awesome to meet you again here ;)

**Comment by probablyup** [comment] 2019-01-08 15:13
> Styled Components should switch to a different library than Stylis?

We're certainly open to it, but there aren't any competitors with similar size and performance as far as I know.

**Comment by JeroenReumkens** [comment] 2019-01-08 15:20
It's also totally unknown territory for me unfortunately. Maybe an idea to open up a ticket again to find other people interested in helping to improve this?

**Comment by rnnyrk** [comment] 2019-01-08 16:00
Did flexbox now by default and overwritten it by using `@supports (display: grid) {}`

**Comment by JeroenReumkens** [comment] 2019-01-08 16:03
Fair solution. But the biggest downside is that you now need to style every thing twice. That’s why I just kept using flexbox.

**Comment by rnnyrk** [comment] 2019-01-08 16:05
True, but I made a simple layout using flexbox and overwrite with more complex layouts using grid. On IE it just needs to work ;)

**Comment by vjs3** [comment] 2019-03-21 11:03
Just curious if there is any updates on this issue from last few months? I am using css grid for a project so was curious, what are some ways you guys create a fallback for IE assuming it's not supported in IE using Styled Components so autoprefixer can't be used I guess?

**Comment by probablyup** [comment] 2019-03-21 13:45
Go to the linked issue, we don’t manage that code.

**Comment by Chun-Lin** [comment] 2019-11-04 10:50
`autoprefixer` 9.7.0 is out, and looks like the performance has been improved.
https://github.com/postcss/autoprefixer/releases/tag/9.7.0

Should we consider to switch the prefixer from `stylis` to `autoprefixer`? Since `autoprefixer` does great jobs on CSS Grid.

**Comment by probablyup** [comment] 2019-11-04 13:04
Not unless they’ve massively shrunk their library size

**Comment by edxv** [comment] 2020-06-07 15:40
For anyone finding this from Google, I published a small plugin which adds IE11 prefixes to some CSS Grid properties: [styled-griddie](https://github.com/edxv/styled-griddie).

Check out the readme to see which properties are supported so far. I'll aim to add more grid features soon!

**Comment by Jojocaster** [comment] 2020-09-29 22:40
Not quite an universal solution, but if anyone uses styled-system along with styled-components, I've got a workaround. 

Here's my `Col` component which I use as a grid-column:
`export const Col = styled.div<SpaceProps & FlexboxProps & GridProps & DisplayProps>`
  ${system({
    gridColumn: {
      //@ts-ignore - msGridColumn isn't part of CSS.Properties for some reason
      properties: ['gridColumn', 'msGridColumn'],
      scale: 'breakpoints',
      transform: value => `${value}`,
    },
    gridRow: {
      //@ts-ignore - msGridRow isn't part of CSS.Properties for some reason
      properties: ['gridRow', 'msGridRow'],
      scale: 'breakpoints',
      transform: value => `${value}`,
    },
  })}`

This will add the prefixes for our beloved IE11. Obviously this is a fairly simple example, and there's only so much we can do with prefixes. But with "simple" grids, that'll do the trick (and I'm sure we can do more with the `transform` attribute).

PS: I'm using a set of breakpoints as a scale so I can pass an object to my component, and handle columns via media queries.
