### ISSUE TITLE
Several instances of 'styled-components' error when upgrading to v4 beta 1

### ISSUE THREAD

**Issue by janosh** [styled-components/styled-components#1986] opened 2018-09-07 17:49 UTC
#### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
 - Memory: 23.36 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
#### Binaries:
 - Node: 10.2.1 - ~/.nvm/versions/node/v10.2.1/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v10.2.1/bin/npm
#### npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.6.3 
 - styled-components: ^4.0.0-beta.1 => 4.0.0-beta.1 

## Steps taken

I'm using `styled-components` to design a Gatsby site. I just updated to v4 beta 1, followed the [migration guide](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4) (which was surprisingly easy) and ran `gatsby develop`. It compiled just fine. However, opening the site in a browser produces only a blank page with the console complaining:

> It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.
> 
> See https://s-c.sh/2BAXzed for more info.

I read through the suggestions at the above address. However, only

> You have another styled-components library somewhere in your dependencies

might apply in my case and running `yarn list styled-components` returns
```
styled-components@4.0.0-beta.1
```
Any other ideas what might be causing this issue? Could the warning

```
warning " > styled-icons@2.4.0" has incorrect peer dependency "styled-components@>=3 <4".
```
I received when clean installing all node modules have anything to do with it?

**Comment by probablyup** [comment] 2018-09-07 19:05
Do you use yarn? If so you can try using the “resolutions” package.json
field to force using the beta in the whole app.

**Comment by janosh** [comment] 2018-09-07 19:14
Tried adding
```
  "resolutions": {
    "styled-components": "^4.0.0-beta.1"
  }
```
to my `package.json` followed by re-running `yarn install` but no change.

**Comment by probablyup** [comment] 2018-09-07 19:19
Omit the caret

**Comment by kachkaev** [comment] 2018-09-07 19:27
I confirm this issue in a project that uses `next.js@7.0.0-canary.14`.

There is v3 referred as a dependency of a dependency, however I suppress it in my package.json:

```
"dependencies": {
   ...
   "styled-components": "4.0.0-beta.1-1",
},
"resolutions": {
  "styled-components": "4.0.0-beta.1-1"
},
```

Nevertheless, the warning gets shown in the browser console.

Running `yarn list styled-components` returns:

```
warning Resolution field "styled-components@4.0.0-beta.1-1" is incompatible with requested version "styled-components@3.2.6"
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ styled-components@4.0.0-beta.1-1
```


Looking into yarn.lock reveals only one instance of the lib:

```
styled-components@3.2.6, styled-components@4.0.0-beta.1-1:
  version "4.0.0-beta.1-1"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-4.0.0-beta.1-1.tgz#ae8958af1404ce7a721be2ef46c2c03a81aef1a4"
  dependencies:
    ...
```

BTW installing `4.0.0-beta.1-2` does not work at all – it fires:

```
/path/to/project/node_modules/st
yled-components/dist/styled-components.esm.js:1
(function (exports, require, module, __filename, __dirname) { import St
ylis from 'stylis';
```

**Comment by janosh** [comment] 2018-09-07 19:32
@probablyup Issue persists without the carot.

**Comment by probablyup** [comment] 2018-09-07 19:33
`4.0.0-beta.1-2` is a dev release and wasn't put on the beta channel.

**Comment by probablyup** [comment] 2018-09-07 19:35
In general please don't use versions that aren't tagged as "beta" because they are not guaranteed to work. Always use `yarn upgrade styled-components@beta` vs a specific version to make sure you're getting the right thing.

**Comment by kachkaev** [comment] 2018-09-07 19:39
@probablyup you're right about this – I was just exploring various versions to see if this makes any difference. Dealing with `4.0.0-beta.1` (i.e. current `@beta`) produces the same result.

**Comment by probablyup** [comment] 2018-09-07 19:40
Weird. And you definitely only see one copy of styled-components in node_modules? :(

**Comment by probablyup** [comment] 2018-09-07 19:46
@janosh have a repo up I can look at?

**Comment by kachkaev** [comment] 2018-09-07 19:50
> And you definitely only see one copy of styled-components in node_modules

Yep. Can it be that Next.js imports the ES version and the common js one at the same time? 😅 

I can try crafting an MWE out of my app like I did in https://github.com/styled-components/styled-components/issues/1972#issuecomment-418891184 if @janosh cannot share his source.

**Comment by kachkaev** [comment] 2018-09-07 20:12
When I removed all components sourced from my dependency [react-styled-grid](https://github.com/ihenvyr/react-styled-grid), the warning went away.

Removing that dependency entirely, wiping out `"resolutions": ...` and running `yarn && yarn dev` was also fine.

I still don't have a good idea about where the second instance of styled-components could come from – here's all the diff in my yarn.lock:

```diff
- react-styled-grid@^2.0.1:
-   version "2.0.1"
-   resolved "https://registry.yarnpkg.com/react-styled-grid/-/react-styled-grid-2.0.1.tgz#84af2bf4329f9b3856e7790a5b2cd9d7e31ba2f2"
-   dependencies:
-     styled-components "3.2.6"

- styled-components@3.2.6, styled-components@4.0.0-beta.1-1:
+ styled-components@4.0.0-beta.1-1:
    version "4.0.0-beta.1-1"
    resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-4.0.0-beta.1-1.tgz#ae8958af1404ce7a721be2ef46c2c03a81aef1a4"
    dependencies: ...
```

It's either yarn.lock is lying about resolving the conflicting versions or webpack doing something strange (e.g. importing ES version from the main code and a commonjs version from the dependency).

**Comment by janosh** [comment] 2018-09-07 21:17
@probablyup Of course, this is the [repo in question](https://github.com/StudentenBildenSchueler/homepage).

**Comment by probablyup** [comment] 2018-09-07 21:35
Ok, I know what the issue is.. Thinking about how to fix it.

styled-icons is transpiled but without the "no-tags" import replacement, but the main does have it... so there ends up being two instantiations of s-c from the same library version because of the different entry paths

**Comment by probablyup** [comment] 2018-09-07 22:29
Alright everyone, go ahead and upgrade your babel plugins latest and the error should go away. We decided to remove the no-tags functionality because of this sort of edge case and also because react-dom ships these strings anyway, so ultimately there is no useful bundle savings.

**Closed by probablyup** 2018-09-07 22:29 UTC

**Comment by azat-io** [comment] 2018-09-22 12:51
Not works for me. Have the same warning. Here is my demo:
https://github.com/azat-io/react-router-dom-demo/blob/master/App.js

**Comment by ackvf** [comment] 2020-02-14 16:03
@azat-io Has this been solved? Did you create new issue for it?
