### ISSUE TITLE
How to share same attributes in styled components?

### ISSUE THREAD

**Issue by marek8623** [styled-components/styled-components#3683] opened 2022-02-03 16:26 UTC
I am using "useWindowDimensions" from react native:

    import { useWindowDimensions } from 'react-native';

I am getting the width and height like this:

    const dimensions = useWindowDimensions();

...and passing it as a prop:

    return (
    	<Component dimensions={dimensions}>
           ...
    	</Component>
    );

Using styled components I use attributes:

    const Component = styledNative(View).attrs((props) => ({
    	dimensions: props.dimensions,
    }))`
    	${(props) => (console.log(props.dimensions))}
    `;

In console log above I am getting what I need.

I want to reuse the same component like this:

    const Copy = styledNative(Component)`
    	${(props) => (console.log(props.children[0].props.dimensions))}
    `;

I am getting dimensions using 'props.children[0].props.dimensions'.

Is there a better way how to reuse styled component and share same attributes?
I do not want to repeat the dimensions prop like this:

    return (
    	<Component dimensions={dimensions}>
           <Component1 dimensions={dimensions}>
               <Component2 dimensions={dimensions}>
                  ...
    	       </Component2>
    	   </Component1>
    	</Component>
    );

I want to use it like this:

    return (
    	<Component dimensions={dimensions}>
           <Copy>
              ...
    	   </Copy>
    	</Component>
    );

Thanks for help.

**Comment by imran-prog** [comment] 2022-02-04 22:51
Hy! @marek8623, The best possible way to perform this task is by nesting the child tag in the parent tag. This will make the parent attributes available for a child too

```js
const Copy = styled.View``

const Component  = styled.View`
  ${(props) => {
    console.log(props.dimensions);
  }}

  ${Child} {
    ${(props) => {
      console.log(props.dimensions);
    }}
  }
`
```

Just remember that you have to initialize the child class before the parent class. I hope this solution will help. You can see it live working in [SandBox](blissful-hooks-62mkl). And please do post a sandbox link from next time onward, so that it is easier to debug the code and find the solution.

**Comment by marek8623** [comment] 2022-02-05 18:27
Hi @imran-prog,

thank you very much for answer.

Basically what I want to achieve is that I need to get dimensions for every screen in React Native using

`import { useWindowDimensions } from 'react-native';`

and have access to them in every component like this:

```
const Container = styledNative(View)`
${(props) => (props.dimensions.width <= 820 ? css`height: auto;` : css`height: 100vh;`)}
`;
```

Is there something similar to React create context in styled components so that I will declare dimensions one time and have access to them in every component?

Thanks

**Comment by ubeid** [comment] 2022-02-07 08:14
hi @marek8623 

I'm not a 100% sure this is what you want, but you can have a look at [Theming](https://styled-components.com/docs/advanced)

All styled-components under the `ThemeProvider` will have access to the provided theme

**Comment by marek8623** [comment] 2022-02-07 08:57
@ubeid I am already using Theming in app. But I want to somehow include "useWindowDimensions" result from react native in theme provider.

From "useWindowDimensions" I am getting, for example, this object:

```
{
    "fontScale": 1,
    "height": 768,
    "scale": 2,
    "width": 1024
}
```

And this object I want to include in ThemeProvider and have access to these data. Is it possible?

The outcome will be something like this:

`${(props) => (props.theme.dimensions.width <= 1024 ... `

**Comment by imran-prog** [comment] 2022-02-07 11:54
@marek8623 If you are specifically trying to implement styling on the base of screen width and height then the best solution is to use a **media query** from CSS. It would be a much better way of implementing this functionality. Or you can even try storing these values in the redux state and then access them in any component. But if you want to know the best solution to implement styling on the base of width and height then I would recommend using media Query instead of props

```css
const Container = styled.View`
  height: 100vh;

  @media screen and (max-width: 820px) {
    height: auto;
  }
`
```

For this code implementation
```js
const Container = styledNative(View)`
${(props) => (props.dimensions.width <= 820 ? css`height: auto;` : css`height: 100vh;`)}
`;
```

**Comment by marek8623** [comment] 2022-02-07 12:29
@imran-prog But when I try to use it with attributes, it is not working:

```
const NativeTextInputWrapper = styledNative(View).attrs(
	(props: {
		customVar?: number }) => ({
		customVar: props.marginTop,
	}),
)`
	max-width: 1120px;
	max-height: 184px;
	${(props) => (props.customVar ? css`margin-top: 20px;` : null)};

       // this is not working:
       @media screen and (max-width: 820px) {
                height: auto;
       }
`;
```

**Comment by ubeid** [comment] 2022-02-07 13:35
@marek8623  To the best of my knowledge, media queries is not supported in styled-components for react native - else @imran-prog solution makes more sense.

You are not limited to one ThemeProvider in your app. 

You can have default values for the dimension object in your root theme element.

e.g.: 

```
{
  ...,
  dimensions: {
      fontScale: 1,
      height: 768,
      scale: 2,
      width: 1024
  }
}
```

You can also leave the dimensions object empty - but do make sure you have null check when using it.

Then, whenever you are using the `useWindowDimensions` hook, you can just wrap whatever you are rendering with a `ThemeProvider` overriding the dimensions object. 

```
const dimensions= useWindowDimensions(); 
return <ThemeProvider theme={(theme) => ({ ...theme, dimensions })}>
  {...}
</ThemeProvider>;
```

**Comment by imran-prog** [comment] 2022-02-07 14:56
Oh sorry, @marek8623 and @ubeid, I forgot that they don't support media queries for React Native, my bad. But I have tried using a theme provider as you said and it isn't quite working for me as intended. I have even read the documentation of [Styled-Components](https://styled-components.com/docs/advanced#theming) and the problem is we have to define the default theme for every specific Component/Tag.

```js
Button.defaultProps = {
  theme: {
    main: "palevioletred"
  }
}
```

**Comment by probablyup** [comment] 2022-03-24 15:59
Going to close this as its a usage question, which should go in Discussions or elsewhere. Thanks for using styled-components!

**Closed by probablyup** 2022-03-24 15:59 UTC

**Comment by code-by** [comment] 2024-10-14 16:29
In style file I'd like to create constant with props, it is possible to this?
Say I need something like this in `myComponent.style.jsx` (don't mind how this styles is correctly, main purpose create a constant I can use in few styled Views):

```
const DIVIDER = props.insets ? 16 : 0;

export const Container  = styled.View`
  ${(props) => {
    flex: 1;
    height: props.height - DIVIDER;
  }}

export const Header  = styled.View`
  ${(props) => {
    min-height: DIVIDER;
  }}
```

if I try use `props` in `const`, I got error (
