### ISSUE TITLE
Parent selector doesn't work with current state

### ISSUE THREAD

**Issue by itayganor** [styled-components/styled-components#3364] opened 2021-01-04 21:50 UTC
## System:
 - OS: Windows 10 10.0.19041
 - CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
 - Memory: 7.41 GB / 15.80 GB
## Binaries:
 - Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD

(and CodeSandbox)

## Reproduction

https://codesandbox.io/s/ancient-bush-8r0l6?file=/src/App.tsx

Demo goal: highlight the switch with a green background color when it's selected and children of another element.

## Steps to reproduce

1. See that both switches have black backgrounds.
2. Toggle the switches (they're of the same state). Only the contained one gets a green background. So far so good.
3. Toggle them again. Now the contained one is stuck with the green one.

## Expected Behavior

The contained toggle should be back to have a black background, since the condition block should color it green anymore.

```js
${(p) => p.$isOn && css`
    #foo & {
        background: green;
    }
`}
```

## Actual Behavior

The contained one is stuck with the green one.

Is anything wrong?

Thanks!

@danielmitrov

**Comment by nautidpk** [comment] 2021-01-18 19:24
adding `&&`  works for me
```
${(p) => p.$isOn && css`
    #foo && {
        background: green;
    }
`}
```

**Comment by itayganor** [comment] 2021-01-19 20:31
> previously it works without &&

When did it work? I mean, in which version?

**Comment by ostrebler** [comment] 2021-05-03 01:06
> When did it work? I mean, in which version?

Before version 5.2.0

**Comment by kitten** [comment] 2021-08-09 16:28
Duplicate of #3265

**Closed by kitten** 2021-08-09 16:28 UTC
