### ISSUE TITLE
Add warning on StyleSheet rehydration when styled-components is duplicated 

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components#1011] opened 2017-07-19 21:44 UTC
When styled-components is duplicated in the client runtime, the rehydration will either throw a rather cryptic error on rehydration, or stop injecting new, dynamic styles.

Instead of failing this catastrophically we should add a warning that notifies the user of this mistake.

cc @geelen @mxstbr 

Reproduction: https://glitch.com/edit/#!/sc-duplicate-module-reproduction

This issue replaces #992 and #987

**Comment by mxstbr** [comment] 2017-07-20 00:18
Sounds great!

**Comment by morajabi** [comment] 2017-07-20 11:31
I want to take this but need more information I think.

**Comment by morajabi** [comment] 2017-07-20 11:44
OK I read the two issue threads and now I think we must throw a warning with a message to warn them about having a duplicate styled-components modules. But how can I detect that then?

**Comment by philpl** [comment] 2017-07-20 11:55
@morajabi We need to clarify this error here: https://github.com/styled-components/styled-components/blob/master/src/models/BrowserStyleSheet.js#L105

This should happen after SSR rehydration with two styled-component modules.
And for duplication detection it would be enough to just set a global flag on `window` maybe?

@geelen Maybe has an idea where best to put this.

**Comment by morajabi** [comment] 2017-07-20 11:57
@philpl Thanks for the information. I need to reproduce the error case, Do you have an idea on how to reproduce it? (as in #987 I think)

**Comment by philpl** [comment] 2017-07-20 12:08
@morajabi I can create a bundle for you I think

**Comment by philpl** [comment] 2017-07-20 12:52
@morajabi oh, actually that one should be quite simple.

1. the server needs to implement ssr
1. the client needs to load styled-components 2x in two different chunks
1. one of them is going to be unable to rehydrate

**Comment by morajabi** [comment] 2017-07-20 15:01
I will try it  @philpl Thanks

**Comment by philpl** [comment] 2017-07-20 22:33
@morajabi If you'd like to pick this up, I've created a small reproduction that showcases the error. It should help you to set something up yourself to test it: https://glitch.com/edit/#!/sc-duplicate-module-reproduction

**Comment by morajabi** [comment] 2017-08-11 13:46
I don't know how to test my code before publishing to npm correctly, so I'm making a PR for you to review it, and sorry if I didn't get what you mean properly.

**Comment by tmeasday** [comment] 2017-08-25 02:13
Not sure what the status is here, but I'd be happy to take a look at it if you are stuck @morajabi

**Comment by morajabi** [comment] 2017-08-25 06:48
I think that'd be good to take a look and help me with that. @tmeasday

**Comment by tmeasday** [comment] 2017-08-26 11:47
@morajabi do you have a branch/fork somewhere with your changes I can look at?

**Comment by morajabi** [comment] 2017-08-26 13:59
@tmeasday no I deleted my repo because I found my approach was wrong. If you can help, provide me a suggestion on how this should be done. Then I can finish this. Thanks.

**Comment by tmeasday** [comment] 2017-09-01 04:31
Hi @morajabi, 

I would just imitate what mobx does: https://github.com/mobxjs/mobx/pull/1083/files

Although they are doing something complicated because they want to give users a way to indicate that they indeed do want to run multiple copies. AFAICT no one wants to do that for styled-components so this should be even simple.

**Comment by ivanakimov** [comment] 2017-10-11 16:22
We have a plugin that is embedded on customers' websites (our plugin uses `styled-components`, and the customer's website *could be* using `styled-components`). So right now, as @philpl has mentioned, at some point the customer's website stops injecting new dynamic styles.

If it's not possible to run multiple copies, am I right to assume that our plugin shouldn't use `styled-components` at all because it might interfere with the hosting website? (or will #1102 fix the issue in the future?)

I'm kinda lost on what to do and the direction we should take...

**Comment by mxstbr** [comment] 2017-10-13 09:55
Interesting use case @ivanakimov, haven't thought about that at all to be honest. I think #1102 will fix your woes?

**Comment by ivanakimov** [comment] 2017-10-13 14:43
@mxstbr, yes with #1102, if we can specify a target element for `styled-components` then I'm guessing our plugin's css (or rehydration?) would stop colliding with our customers'. I think anyone that uses `styled-components` for plugins would appreciate this, not only us.

The only question is when will it go live, cause it's a blocker for our own website too (dashboard uses `styled-components` to preview the plugin which causes the same issue).

**Comment by philpl** [comment] 2017-10-13 15:13
@mxstbr We should probably close this issue in favour of #1102, since this was just meant as a temporary relief

**Closed** 2018-02-06 15:46 UTC
Labels: enhancement, good first issue, help wanted
