### ISSUE TITLE
Styles break when certain characters are inserted dynamically, ie. ( and [

### ISSUE THREAD

**Issue by purplecones** [styled-components/styled-components#622] opened 2017-03-27 17:40 UTC
While creating www.cssgridplayground.com I found an interesting issue that happens when dynamically updating the CSS for a styled component. For example, on CSS Grid Playground, I have two textareas at the top that hold text within them. This text is the styling that corresponds to certain HTML elements on the page. Normally, updating this CSS works just fine. However, in cases where I need to enter the characters ( and [, the styling for the whole app breaks. A refresh is required to get the styling back. Has anyone experienced this?

Here is an example:
![2017-03-27 13 36 55](https://cloud.githubusercontent.com/assets/136654/24369613/93fce0aa-12f2-11e7-947c-f0c06978e8d7.gif)

## Version
1.4.4

## Reproduction
I have a simple reproduction here: https://styled-components-bug.now.sh/
The code can be found here: https://github.com/purplecones/styled-components-bug/blob/master/src/App.js

## Steps to reproduce
Enter a ( or [ into the textarea.

## Expected Behavior
Nothing should happen until a valid css property has been completed

## Actual Behavior
All styling break that use styled components

![2017-03-27 13 31 02](https://cloud.githubusercontent.com/assets/136654/24369365/be907be8-12f1-11e7-9ad7-91e67e0b5af4.gif)

**Comment by philpl** [comment] 2017-03-28 00:09
Sanitising invalid CSS strings is tough and I don't think it's sth that can be done easily without large perf hits.

Also, I don't think you should trust the user's input in this way. I've done sth similar for a spectacle presentation is basically a custom version of the component-playground By formidable. It allows the user to input some js code whole the rendered components update live.

It handles invalid input by putting in some error boundaries for both parsing and rendering. Let me search for the code really quick...

**Comment by philpl** [comment] 2017-03-28 00:19
This renders everything in an unsafe wrapper:

https://github.com/philpl/rxjs-guide/blob/master/components/Playground/Preview.js

You probably won't need transpilation, but just in case:

https://github.com/philpl/rxjs-guide/blob/master/utils/transpile.js

**Comment by thysultan** [comment] 2017-03-28 15:16
The question is why doesn't it recover when you remove it. Maybe v2 will fix this?

**Comment by purplecones** [comment] 2017-03-28 15:28
I ended up doing some validation on my side before passing the CSS string down to styled-components. Works for now I'm curious as well why it does not recover. Strange.

**Comment by mxstbr** [comment] 2017-04-01 09:31
Can you try v2 @purplecones? `npm install styled-components@next` and let us know if that fixes it!

**Comment by purplecones** [comment] 2017-04-01 16:45
@mxstbr It does indeed 🎉  🎊

![2017-04-01 12 40 54](https://cloud.githubusercontent.com/assets/136654/24580596/8401dbda-16d8-11e7-9e93-93a940b9d5d9.gif)

However, typing the opening bracket character [ still causes it to break.

![2017-04-01 12 44 30](https://cloud.githubusercontent.com/assets/136654/24580620/00b198b4-16d9-11e7-9e3a-afb88307deeb.gif)

**Comment by thysultan** [comment] 2017-04-01 16:53
@purplecones does it recover after you fix the invalid css?

**Comment by purplecones** [comment] 2017-04-01 17:07
@thysultan sorry forgot to mention that. It does **not**. This only happens with the [ character, not ].

**Comment by thysultan** [comment] 2017-04-01 17:18
I don't think the problem is with the parser, looking at the DOM of [https://styled-components-bug.now.sh/](https://styled-components-bug.now.sh/) new repeated styles are created every time something changes.

**Comment by geelen** [comment] 2017-04-03 09:14
Yeah, we don't remove any CSS at the moment, so as soon as you have something that fully breaks the CSS file's validity, it'll never get removed. User-driven input like this isn't a use-case we've really looked at, and I'm... not convinced we should, personally. But, it would be good to prevent broken chars like `[` from reaching the DOM at all.

For this use-case, I'd actually use a global CSS class on your grid, and a `<style>` tag local to the component, and wire it up with the textarea's `onChange` handler. Might make things a bit more predictable.

**Comment by purplecones** [comment] 2017-04-03 11:03
Thanks @geelen, I'll look into that option. The interesting bit is that if the [ is followed by a closing ], then the problem doesn't happen. If you paste both [] into https://styled-components-bug.now.sh, it doesn't break. So it only breaks when the [ is on its own.

Currently I've got it working by making sure all opening brackets have a closing bracket before passing the string down to styled-components.

**Comment by mxstbr** [comment] 2017-12-15 12:43
Going to close this out as this use case is not something we'll be optimizing for anytime soon. (sorry @purplecones!) That being said, we'll be looking towards removing injected, but now useless, styles in the future, which might or might not fix this behavior!

**Closed by mxstbr** 2017-12-15 12:43 UTC
Labels: question
