### ISSUE TITLE
Injectglobal in theme function only updates once

### ISSUE THREAD

**Issue by rsouthgate** [styled-components/styled-components#1052] opened 2017-08-01 08:26 UTC
This seems very similar to the discussion in #277 but not identical.

In my scenario I'm using the ThemeWrapper and the corresponding theme functions to injectGlobal fontFamily style declarations for the theme. From what I read this seems a legitimate use of injectGlobal...

I'm using Storybook to render the components and dynamically switching themes (using a storybook 'knob' to select the theme). The component page will render with the correct font family the first time and when a different theme is selected the font family updates correctly. But from then on it never updates. The hashed class name with these declarations in are different and the className on the relevant component does change that first switch, but then never changes. The font-family declarations are different in the different themes and are written into the head in different hashes. It just seems more like something to do with the theme change coming up from setState which is asynchronous and the theme still being the old value at the point at which my component is being told to render with what should be the newly selected theme in it's props.

**Comment by rsouthgate** [comment] 2017-08-03 01:19
To follow up... this is identical to #277 or at least a comment in it.

Since declaration blocks are cached would it make sense to have an ejectGlobal() method which can both remove the block from the style tag and remove the matching key from the internal cache?

Then ThemeProvider could also provide a hook at the point at which an old theme is 'unmounted'... something along the lines of:
```javascript
componentWillReceiveProps(nextProps: ThemeProviderProps) {
    if (this.props.theme !== nextProps.theme) {
      if (typeof this.props.theme.unmount === 'function') {
        this.props.theme.unmount.apply(null);
      }
      this.broadcast.publish(this.getTheme(nextProps.theme))
    }
  } 
```

And then if a functional theme has itself injected global styles it would, at this point be able to 'ejectGlobals'

**Comment by vukk** [comment] 2017-08-04 13:00
Not the proper way to fix this, but while the `ejectGlobal()` or another fix is in discussed/developed, you could use a hack like this to get around the content hashing & lazy loading:
```javascript
injectGlobal`
  body {
    background-color: ${this.theme.bodyBackground};
    /* etc... */
  }

  /* HACK! I'm not using the table tag so this does not affect any styles. */
  table {
    border-image-width: ${Math.random()};
  }
`;
```

The random number chances the hash (well, unless you happen to be unlucky and hit the same random number twice), and hence appends the styles again, and in CSS the latest definitions override the previous ones.

Just noting this here in case anyone else needs it.

**Comment by k15a** [comment] 2017-08-04 18:20
@rsouthgate could you please share a reproduction on codesandbox or webpackbin?

You can find the boilerplates in the issue template :)

**Comment by rsouthgate** [comment] 2017-08-04 23:28
Hi,
Here's a slightly contrived demo: https://www.webpackbin.com/bins/-KqjXlFCyDD4QtZ7GKcV

Theme is updated every 5 seconds. Theme changes a color value through the object it returns, but each theme also injects a global style (in this case the size of the h1). Color continues to be reapplied correctly, but the caching mechanism means the size only cycles once, before styled-components stops injecting because the global declaration is already there (but not applied since the later styles are injected after). Just as an aside this worked with 2.0.0 but not with latest since it seems like there was no caching check so globals just kept getting appended before.

Obviously applying a color to all h1 tags goes against the point of styled-components, but in my actual project I have things like accessibility settings and things like ":selection" colors that I think should be applied to the page globally and if I had to define on every component would go against the DRY principle.

I have forked the repo and made changes here: https://github.com/rsouthgate/styled-components/blob/eject-globals-on-theme-change... it's not ready for a PR - but it does the job for my purposes... no idea whether it's a good approach though!

**Comment by philpl** [comment] 2017-08-05 00:15
@rsouthgate This is not really a question of how to do it, or should you do it. It's a question of whether it concerns our API, and the answer is: Maybe. But not in the way it's being applied in your example, since that's general best practice. It's applying a side effect on every render, which is supposed to be side effect-less. So while we can consider ejecting global stylings with a suggested API in another issue (not finding it at the moment, since it's half a year old), it's not going to look like this and is not high up the priority list.

So, why is it not high up the list? You can replicate this behaviour using:

- manual DOM manipulations
- a single initial injectGlobal
- "nested" style rules inside your root/wrapper component around the entire app
- ... get mad

So this is A) possible already, and B) we'd entice people to apply bad practices, which we're trying to prevent. So unfortunately it's not looking like we'll solve this in a trivial way, i.e. it's already possible in a few ways that are not very direct, since *direct* corresponds with bad practices in these cases more often than not :/

cc @mxstbr @geelen any thoughts?

**Closed** 2017-08-05 00:18 UTC

**Comment by rsouthgate** [comment] 2017-08-05 01:34
Thanks @philpl My motivation was a particular project where I'm developing a component library rather than an app. If I were the app developer I would say totally - any one of those alternatives would be fine. But as a component library developer I'm already asking any app developer to ensure their app is wrapped by a <ThemeProvider>, they probably already have a store provider wrapping that and I just thought it was nicer to use the ThemeProvider so the developer picking up the library didn't have to remember to do one more thing.

I was contemplating using a HOC to generate a NormalizingThemeProvider which actually output a tag so the classes could go on that - much like your third option above and avoid injectglobal for everything except the font-family definitions. Sound sensible?
