### ISSUE TITLE
[V2] Media queries are ordered incorrectly when passed in an object in 2.0

### ISSUE THREAD

**Issue by bhough** [styled-components/styled-components#789] opened 2017-05-13 14:07 UTC
✨ polished has several mixins that return media queries with fallbacks in a single object. Media queries always end up first due to javascript object key ordering. V1 compensated for this, but it appears V2 is processing them in order and causing the fallbacks to override the media query values.

## Version
2.0.0-17

## Reproduction
Broken in 2.0.0-17: https://www.webpackbin.com/bins/-Kk16YIwW7B2oHaQ3k5p
Working in 1.4.6: https://www.webpackbin.com/bins/-Kk13eeA9MLhQhWDLOEt

## Steps to reproduce
To simplify the example I created an object that matches the output of a polished mixin (including the ordering)

## Expected Behavior
fontSize should be 100px because the window > 100px.

## Actual Behavior
fontSize is using the fallback value because it is being placed after the mediaQuery in the CSS.

**Comment by timjacobi** [comment] 2017-05-17 00:26
Seems to be fixed on latest master

**Comment by bhough** [comment] 2017-05-17 05:44
@timjacobi V2 is moving away from `Postcss` to `stylis` so my guess is that it is possibly an issue in `stylis`.

**Comment by timjacobi** [comment] 2017-05-17 06:23
Good to know thanks. I literally just dived into the code base last night. Will have a look at stilis then.

**Comment by timjacobi** [comment] 2017-05-17 08:22
I can confirm it is related to stylis as demonstrated here https://www.webpackbin.com/bins/-KkKQqJlGOsVcsDDMX29

I will raise an issue with them later.

**Comment by thysultan** [comment] 2017-05-17 08:46
@timjacobi Though invalid css the output is correct.

```
@media (min-width: 100px): {.hello {fontSize: 100px}}.hello {fontSize: 12px}
```

**Comment by bhough** [comment] 2017-05-17 10:24
@thysultan Please look at the original example in the issue and what happens with the PostCSS version of `styled-components` and the one using `stylis`. JS object ordering will always reorder the properties to put `@media` first. Without `stylis` compensating for this what should be treated as a a fallback (like in `styled-components` V1) is instead treated as an override (V2)

On `polished` we use the object versions because most other CSSInJS libraries use objects, which I believe is what @timjacobi was demonstrating for his example.

**Comment by thysultan** [comment] 2017-05-17 10:39
If `stylis` does try to compensate for this case it will have the opposite effect when using strings so it might be better to compensate for this in polished's `toString` function.

```css
@media (min-width: 100px) {.before {font-size: 100px}}
.after {font-size: 12px}
```

**Comment by bhough** [comment] 2017-05-17 11:03
@thysultan I'll let one of the maintainers comment from here, as I don't have anymore to add other than what I've said about. Either way it is something that does need accounted for somewhere.

**Comment by geelen** [comment] 2017-05-19 02:35
Just saw this, thanks reproducing on webpackbin. I'm pretty sure the behaviour in 1.4 is wrong—CSS should be output exactly in the order it is specified, so all you need to do is reorder the keys of your object:

https://www.webpackbin.com/bins/-KkTYWMFH5tD2j16c9Yx

> Media queries always end up first due to javascript object key ordering.

I... don't think that's true. JS keys are specifically not ordered, but in practice they are iterated in the order they're defined. Sounds like a bug in polished?

**Comment by bhough** [comment] 2017-05-19 04:29
Thanks for the reply @geelen. Sorry I wasn't clear...didn't mean that JS was physically resorting the keys, but that a basic sort was being done on the properties that was alphabetizing them. We always (wrongly) assumed this was being done on purpose as styled-components V1 was not the only library we had to hack around this problem in some cases (using `!important` for example). 

Let me revisit the mixins (as it wasn't just happening with media queries) where we have this hack and see where this is all happening for `polished`.

Are you open to fixing this issue in V1 before V2?

**Comment by geelen** [comment] 2017-05-19 04:40
Wait, where's the sort being applied? Is it in polished before the object is sent to SC or somewhere in SC itself?

I'm probably not going to go back and patch anything in 1.x. It sounds like postcss-nested has one behaviour and stylis has another, and I'm happy for the new behaviour (which is more correct imo) to be part of the breaking changes for v2.

**Comment by bhough** [comment] 2017-05-19 05:00
Let me dig in on that first question. Given the reproduction, it is clear that something under the hood on SC was reordering in some cases (my guess is to try and save the user from themselves when they don't properly order media queries in objects?). Looking at a sampling, I don't see any of our modules where we are doing explicit sorting. More seeing things like this:

```javascript
return {
    'border-color': backgroundColor,
    'width': '0',
    'height': '0',
    'border-width': getBorderWidth(pointingDirection, unitlessHeight, unitlessWidth),
    'border-style': 'solid',
    /*
    * javascript Object sorting orders 'border-color' after 'border-bottom-color'
    * (bottom-b) is before (bottom-c) - !important is needed
    * { border-bottom-color: 'red', border-color: 'transparent' }
    */
    [`border-${reverseDirection[pointingDirection]}-color`]: `${foregroundColor} !important`,
  }
```

It may very well be the case where others saw the media query behavior and started unnecessarily compensating for it in other instances. I also agree that the stylis behavior is preferred here (especially if there is no intentional sorting going on in SC beforehand). If it is in postcss-nested, that would also explain why we saw the behavior in other libraries as well. Given I didn't write all these polished `modules`, I myself am not 100% clear on what we saw initially that lead us down this path. Could just be a case of us happily marching each other over a cliff 😬

Give me some time today to make sure we aren't seeing anything else odd. If it turns out to just be this one weird case, I will just patch the affected `polished` to not assume this weird object sorting and then things should work fine in both versions. Apologies if this ends up being a false alarm.

**Comment by bhough** [comment] 2017-05-21 19:06
@geelen we should be good to close this, noting that moving to `stylis` will cause this to technically be a breaking change in V2 (if someone is knowingly or unknowingly relying on this behavior). Any other re-ordering we were seeing wasn't happening specifically with `styled-components`.

**Comment by philpl** [comment] 2017-05-22 02:17
@bhough Sounds good, seeing that SC v2 actually behaves more predictably here.

**Closed by philpl** 2017-05-22 02:17 UTC
Labels: bug
