### ISSUE TITLE
Use defaultprops in style

### ISSUE THREAD

**Issue by brunovandamme** [styled-components/styled-components#1556] opened 2018-02-26 11:02 UTC
When using a style for a custom component, I can not use the defaultProps from the component in the style itself. I would like to do something like the following and have the component use its default color.

```
import React from "react";
import Style from 'styled-components'
import { render } from "react-dom";

class Base extends React.Component {
  static defaultProps = {
    color: "blue"
  };

  render = () => {
    return <div {...this.props}>Base component</div>;
  };
}

const StyledBase = Style(Base)`
  color: ${({ color }) => color };
`

render(<StyledBase />, document.getElementById("root"));
```

This does not work as the defaultProps is on the Base component and not on the StyledBase component. I know I could also define the defaultProps on StyledBase, but this is tedious and error prone to have the defaultProps defined twice (as I sometimes want to use the component without a style). Would it be possible to have the defaultProps hoisted to the styled component when styling custom components?

**Comment by Amritha777** [comment] 2018-02-26 11:37
Hey, @brunovandamme, me and @riyak1998 are working on this project as a part of our RGSOC application. We'd love to contribute to this.
First, let's make sure we're on the same page. You want that if a StyleComponent does not have defaultProps, the defautProps of the regular React element should be used. Kindly confirm if this is what you wanted to convey.

@kitten @mxstbr We are relatively new to the codebase and are trying to understand it these days. We want to contribute to this project as a part of RGSOC. Should we go ahead to try fixing this, or would it break something by bringing regular React components into the mix?

**Comment by brunovandamme** [comment] 2018-02-26 11:46
Merging the component defaultProps into the styledcomponent defaultProps, or just using the component defaultProps if there is no styledcomponent defaultProps would both be fine for my use case. 

Maybe someone more familiar with the project can comment if such a change would even be desirable, or if it would break something.

**Comment by kitten** [comment] 2018-02-26 14:13
@brunovandamme For completeness sake, can you please adhere to the issue template's requirements: https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

Specifically a quick reproduction would be great! We have a pre-made codesandbox template:

> https://codesandbox.io/s/rkmNRByE4

First of all, this is not the recommended usage :wink: As you're just creating a styled div you should reverse the order of your component definition as outlined in the docs, i.e.:

```js
const Container = styled.div``

/* it's best to just leave this up to the component that needs the props */
Container.defaultProps = {
  color: "blue"
};

class Base extends React.Component {
  render() {
    return <Container {...this.props}>Base component</Container>;
  };
}
}
```

@Amritha777 That's very kind of you, but let's try to understand this first. I've seen you comment on other issues, and before we triage and try to fix bugs, we must first understand
whether it even is a bug.

In this case it's not a bug, but `<div {...this.props}></div>` will never be able to influence the StyledComponent, as it is **above** the component with `defaultProps`.
I have noticed that `defaultProps` doesn't default `color` actually, but it seems that this could be caused by React's prop filtering logic, not ours.

Reversing the order as seen above should work, additionally to circumvent React's prop filtering by renaming the prop to something sensible & non-HTML-y, like `textColor`,
should make it work ultimately.

@brunvandamme Let me know if you have any success using this. Remember that it's A) better to have styled elements (lowest point in the tree), and B) that when you wrap a component
in a StyledComponent, that component's props won't traverse upwards.

I'm going to go ahead and close this as a usage issue, but I'd be happy to reopen if there's actually anything weird going on :+1: :wink:

**Closed by kitten** 2018-02-26 14:13 UTC

**Comment by kitten** [comment] 2018-02-26 14:16
@Amritha777 btw, your best bet is either helping ppl out with questions, which is already very valuable as it saves us a tremendous amount of time :heart:, or you could search for issues which are labelled as "good first" or "help wanted" 🙌

**Comment by chrillewoodz** [comment] 2020-04-16 13:33
Setting defaultProps on the styled component rather than the "base" component worked brilliant. Was pulling my hair out why the defaultProps weren't affecting the styles at all.
