### ISSUE TITLE
Accessing props.theme in a keyframes object

### ISSUE THREAD

**Issue by vincentmvdm** [styled-components/styled-components#852] opened 2017-05-29 19:57 UTC
Hey!

I would love to be able to access my theme in a keyframes object. I am making a div's background-color cycle through the various brand colors, but currently seem to have to hard-code the hex values. 

My use case is something like this:

```js

import styled from 'styled-components';
import { keyframes } from 'styled-components';

const colorize = keyframes`
    0% {
        background-color: palevioletred;
    }

    100% {
        background-color: papayawhip;
    }
`;

const Wrapper = styled.div`
    animation: ${colorize} 4s ease-in-out infinite;
`;

```

It would be great if I could write `background-color: ${props => props.theme.brandColorOne};`

**Comment by k15a** [comment] 2017-05-29 20:29
Duplicate of https://github.com/styled-components/styled-components/issues/397

```js
import styled from 'styled-components';
import { keyframes } from 'styled-components';

const colorize = props => keyframes`
    0% {
        background-color: ${props => props.theme.brandColorOne};
    }

    100% {
        background-color: ${props => props.theme.brandColorTwo};
    }
`;

const Wrapper = styled.div`
    animation: ${colorize} 4s ease-in-out infinite;
`;
```

**Closed by k15a** 2017-05-29 20:29 UTC

**Comment by leoselig** [comment] 2017-07-09 11:21
@k15a You referenced an already closed issue
Is this feature implemented? Then I seem to be missing something because it's not available to me

**Comment by leoselig** [comment] 2017-07-09 11:26
Turns out that opposed to how the tag names are imported, `keyframes` is a named export **only**
So, 
```javascript
// works
import { keyframes } from 'styled-components';
keyframes`
  ...
`

// does not work
import styled from 'styled-components';
styled.keyframes`
  ...
`
```

I believe this should be documented somewhere. Any idea where?

**Comment by philpl** [comment] 2017-07-09 17:14
This is obvious in ES modules, since the styled factory is the default export. And everything else is not.

We haven't though added some sections in getting started that would clarify this.

The issue is closed as a won't fix. It's not a feature we can or will implement with our current vision for SC and the key frames helper

Thanks for raising it though :)

**Comment by ckknight** [comment] 2019-06-24 21:39
```tsx
type MyTheme = { ... };
const keyframeCache =
  typeof WeakMap === 'undefined' ? new Map() : new WeakMap();
export function themedKeyframes(
  fn: (theme: MyTheme) => Keyframes,
): (props: { theme: MyTheme }) => Keyframes {
  return ({ theme }) => {
    let result = keyframeCache.get(theme);
    if (!result) {
      result = fn(theme);
      keyframeCache.set(theme, result);
    }
    return result;
  };
}
```
