### ISSUE TITLE
major performance regression since SC5: using insertBefore instead of appendData injects styles an order of magnitude slower

### ISSUE THREAD

**Issue by Schipy** [styled-components/styled-components#3638] opened 2021-12-10 10:58 UTC
Hi there, a bit surprised this hasn't surfaced yet

Measuring the same UI component rendering in our application, Styled Components 5 performs style injection ~6x  slower (!) than SC 4 did, due to using `insertBefore` per rule, instead of accumulating styles using `CharacterData.appendData`

SC 5:
![Screenshot 2021-12-10 at 11 29 14](https://user-images.githubusercontent.com/2234706/145560349-5770b567-6f9a-4e1b-b299-7552860889ee.png)

total time spent by SC5 with generateAndInjectStyles: 251ms (insertBefore 239ms)

same component tested under same circumstances in SC4:
![Screenshot 2021-12-10 at 11 50 25](https://user-images.githubusercontent.com/2234706/145562455-0ae93517-d673-4e98-9ba4-b5f863457e39.png)

total time spent by SC4 with generateAndInjectStyles: ~43ms (appendData 34ms)

the two profiles have the same parent node selected in the same render frame
platform: Chrome 96 on macOS 11.4

**Comment by kitten** [comment] 2021-12-10 21:08
This seems like a duplicate of this to me 👋 https://github.com/styled-components/styled-components/issues/3632#issuecomment-980445511

**Comment by kitten** [comment] 2022-01-06 12:25
Closing due to inactivity.

Please don't forget to be a good netizen on GitHub and revisit issues, especially ones that have been resolved and need to be closed, or ones that have received replies ❤️

**Closed** 2022-01-06 12:24 UTC
