### ISSUE TITLE
Toggling background image in styled component will refetch all images in the page

### ISSUE THREAD

**Issue by jackylee941130** [styled-components/styled-components#3315] opened 2020-10-24 01:48 UTC
Hi, I have a <ImageList> component and when some component updated the state, e.g. setActiveItemIndex(2), all images imported will be refetched and caused image flickering. Can anyone help me to solve this issue?

```
import activeImage1 from 'somepath...'
import inactiveImage1 from 'somepath...'
import activeImage2 from 'somepath...'
import inactiveImage2 from 'somepath...'
....

const Item = styled.div`
  background-image: ${props => props.src};
  ...other css properties
`

const images = [
  {
    active: activeImage1,
    inactive: inactiveImage1
  },
  {
    active: activeImage2,
    inactive: inactiveImage2
  },
  ....
]

export default function ImageList() {
  const [activeItemIndex, setActiveItemIndex] = useState(0)

  return (
    <div>
      ...some components would call setActiveItemIndex()
      {
        images.map((itemImages, i) => (
          <Item src={activeItemIndex === i ? itemImages.active : itemImages.inactive} />
        ))
      }
    </div>
  )
}
```

**Comment by ZambranoBeicker** [comment] 2020-10-28 02:12
Mmm i have tried to reproduce that bug: 
https://codesandbox.io/s/modest-jepsen-nenr6?fontsize=14&hidenavigation=1&theme=dark 

But i couldn't see some flickering. Tell me if i'm doing something bad.

The only difference i can see is that i put the images inside a div. That's all.

**Comment by sweetliquid** [comment] 2020-10-30 06:11
Maybe you should add the prop `key={i}` on `Item` like:

```
images.map((itemImages, i) => (
  <Item key={i} src={activeItemIndex === i ? itemImages.active : itemImages.inactive} />
))
```

**Comment by raksooo** [comment] 2020-10-30 16:13
I've run into this as well. My guess is that this is very similar to https://github.com/styled-components/styled-components/issues/400 and https://github.com/styled-components/styled-components/issues/2205. For me it seemed like all CSS properties with a `url()` value was refetched each time styles were inserted into the DOM.

**Comment by gpoole** [comment] 2020-11-06 03:31
Also seeing this issue with images in v5.1.1. I believe it's related to or similar fundamentally to the font flashing issue described in #1593 as you've mentioned @raksooo: when styles are updated by SC, the entire text content of the style tag is replaced, which causes the browser to re-evaluate it. Because it re-evaluates, the browser has to re-fetch any background images again, which will cause flashing if the images are not cached, since they need to be re-downloaded before showing. Most dev environments and browser dev tools will disable caching, which is probably why you're seeing so much flickering. It's not likely to happen in production environments because caching is not likely to be disabled there.

The resolution on #1593 was that it won't be fixed because it's apparently an almost impossible problem to work around and doesn't cause problems if the images (or fonts in their case) are cached. If it's causing problems for you, you can try passing background images via the `style` attribute instead [as suggested in one of the comments](https://github.com/styled-components/styled-components/issues/1593#issuecomment-508748098). Otherwise make sure your images are cached and that should stop the flashing, but won't fix the underlying problem.

I think this should probably be added to the FAQ since it's a bit of a confusing problem to track down and the existing answer there only talks about fonts. If someone who knows can confirm I'm right about the cause I'd be happy to write that up.

**Comment by tatsmaki** [comment] 2021-07-20 09:50
> Most dev environments and browser dev tools will disable caching, which is probably why you're seeing so much flickering. It's not likely to happen in production environments because caching is not likely to be disabled there.
That is true, enabling caching in Chrome dev tools made flickering dissapear. I still wonder what exactly is happening in my case, because I do not change images url. I use some styled component props in my button component, but they cause images on the whole page to rerender. Everything is ok, when I am using style attribute for my button without styled components props.

**Comment by gpoole** [comment] 2021-07-24 00:54
The important point here is that it's not specific to background images and that the browser doesn't see a clear boundary between individual styled components like you're seeing in the code @tatsmaki. Generated styles for all styled-components are grouped into a `<style>` tag in the `<head>` which is updated whenever the styles change for any of the styled-components anywhere in your app. When a style tag is updated it seems like most browsers will treat the update like loading a completely new stylesheet and throw out the old state, which means they need to re-load any assets you're referencing. I'm assuming there's probably a fair bit of other re-evaluating happening too but it's fast enough you don't see it. If the assets needed like fonts and images are available in cache, this reload happens so quickly that it's ready before the next render so you don't see it, but if it takes time like needing to fetch the assets over the network again then you'll notice a flicker while it loads. If you look in the network tab of dev tools you'll see that even when the flickering isn't visible the assets are still being requested from cache on every style change.

I'd say that based on what happens here there are probably some performance implications to using dynamic styles at all, so it's also probably something you want to avoid for frequent updates.

You can avoid or minimise the reloading and therefore the flashing by:
* Not using dynamic styles often e.g. avoid ``styled.div`color: ${props => props.color};` ``
* Putting font face definitions in their own `style` block or external stylesheet not managed by styled-components
* Using style attributes like you said e.g. `style={{ backgroundImage: `url(${url})` }}`
* Passing props using custom properties instead of using interpolation e.g. `style={{ '--bg-img': url }}` and ``styled.div`background-image: url(var(--bg-img));` ``

**Comment by gpoole** [comment] 2021-07-30 23:56
> When a style tag is updated, even if it's only a tiny difference, it seems like most browsers will treat the update like loading a completely new stylesheet and throw out the old state, which means they need to re-load any assets you're referencing.

Actually I wasn't exactly right about that part, [apparently there's a difference between how styled-components handles updates in dev and prod mode](https://github.com/styled-components/styled-components/issues/1593#issuecomment-497329240) which apparently will make this problem a lot worse in dev. If I understand correctly, in prod mode the updates are more targeted to just the rules that have changed so you're less likely to be getting assets reloaded and styles recalculated from the sound of it.

**Comment by kitten** [comment] 2021-08-09 16:55
This is an issue in Chromium actually, and it's been filed, but until then we can't really do much about it. https://bugs.chromium.org/p/chromium/issues/detail?id=1216451

In general, although we're using the CSSOM API, Chromium will mostly reevaluate all rules of a given `style` element, if a new rule is inserted. This isn't the intended behaviour of the CSSOM API and inconsistent with other browsers. That said, in terms of images and fonts, this can be worked around by having a proper `Cache-Control` header present on them in production, which is how many sites actually don't experience this issue without realising.

**Closed by kitten** 2021-08-09 16:55 UTC
