### ISSUE TITLE
FlowType errors in 2.0.0

### ISSUE THREAD

**Issue by hmeerlo** [styled-components/styled-components#865] opened 2017-06-02 10:08 UTC
## Version
2.0.0

## Reproduction
https://github.com/hmeerlo/styled-flow

I just created a new project using create-react-app
npm install --save styled-components
added flow support and a styled component in App.js. Then running 'npm run flow' results in the following list of errors (and many more):

```
node_modules/styled-components/lib/constructors/constructWithOptions.js.flow:10
 10:       throw new Error(`Cannot create styled-component for component: ${tag}`)
                                                                            ^^^ class type: C. This type cannot be coerced to
 10:       throw new Error(`Cannot create styled-component for component: ${tag}`)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/models/InlineStyle.js.flow:3
  3: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/models/StyleSheet.js.flow:135
       v----------------------
135:   static get instance() {
136:     return instance || (instance = StyleSheet.create())
137:   }
       ^ Potentially unsafe get/set usage. Getters and setters with side effects are potentially unsafe and disabled by default. You may opt-in to using them anyway by putting `unsafe.enable_getters_and_setters=true` into the [options] section of your .flowconfig.

node_modules/styled-components/lib/models/StyleSheetManager.js.flow:13
 13:     // $FlowFixMe
         ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/styled-components/lib/models/StyledComponent.js.flow:216
           v--------------------
216:       static get extend() {
217:         const { displayName: _, componentId: __, ...optionsToCopy } = options
218:         const newOptions = { ...optionsToCopy, rules, ParentComponent: StyledComponent }
219:         return constructWithOptions(createStyledComponent, target, newOptions)
220:       }
           ^ Potentially unsafe get/set usage. Getters and setters with side effects are potentially unsafe and disabled by default. You may opt-in to using them anyway by putting `unsafe.enable_getters_and_setters=true` into the [options] section of your .flowconfig.

node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:184
           v--------------------
184:       static get extend() {
185:         const { displayName: _, componentId: __, ...optionsToCopy } = options
186:         const newOptions = { ...optionsToCopy, rules, ParentComponent: StyledNativeComponent }
187:         return constructWithOptions(createStyledNativeComponent, target, newOptions)
188:       }
           ^ Potentially unsafe get/set usage. Getters and setters with side effects are potentially unsafe and disabled by default. You may opt-in to using them anyway by putting `unsafe.enable_getters_and_setters=true` into the [options] section of your .flowconfig.

node_modules/styled-components/lib/native/index.js.flow:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/utils/create-broadcast.js.flow:20
 20:       listeners.forEach(listener => listener(currentValue))
                                                  ^^^^^^^^^^^^ unused function argument
   10:   subscribe: (listener: () => void) => () => void
                               ^^^^^^^^^^ function type expects no arguments

node_modules/styled-components/lib/utils/create-broadcast.js.flow:26
 26:       listener(currentValue)
                    ^^^^^^^^^^^^ unused function argument
   10:   subscribe: (listener: () => void) => () => void
                               ^^^^^^^^^^ function type expects no arguments
```

## Steps to reproduce

See above

## Expected Behavior

No flowtype errors

## Actual Behavior

Lots of errors

**Comment by relekang** [comment] 2017-06-02 15:24
These errors go away when you follow the flow docs. Use 1.4 libdef until 2.x libdef is available. 

On a related note, should we stop shipping the flow types in the npm package?

**Comment by philpl** [comment] 2017-06-03 12:30
Addressed here: https://github.com/styled-components/styled-components/pull/868
This is now a duplicate of: https://github.com/styled-components/styled-components/issues/843

cc @relekang

**Closed by philpl** 2017-06-03 12:30 UTC
Labels: bug
