### ISSUE TITLE
Styled component loses props in typescript after second wrap

### ISSUE THREAD

**Issue by IIIristraM** [styled-components/styled-components#1070] opened 2017-08-08 08:57 UTC
styled-components v2.1.2
typescript v2.4.2

Double wrapping of custom react component in `styled` function has component without origin props in the result.

```
export default class Icon extends React.PureComponent<IconProps, {}> {
  public render() {
    const { className, icon, style = {}, ...others } = this.props;
    const { id, viewBox } = icon.default;
    const size = viewBox.length ? viewBox.split(' ') : [];
    const iconStyle = Object.assign({width: `${size[2]}px`, height: `${size[3]}px`}, {}, style);

    return (
      <styled.IconWrap className={className} {...others} style={iconStyle}>
        <svg viewBox={viewBox} className={styled.svg}>
          <use xlinkHref={`#${id}`} />
        </svg>
      </styled.IconWrap>
    );
  }
}
...
export const InputIcon = styled(Icon)``;
...
export const IconErase = styled(InputIcon)``;
```
and finally

`<IconErase { ...{ icon: iconErase } />`

**Expected result**
No errors, IconErase component has same props as origin Icon component

**Actual Result**
```
Type '{ icon: IconSVG }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Theme
dOuterStyledProps<WithOptionalTheme...'.
```
Component has only default themed styled component props (i.e.  theme, innerRef etc.)

**Comment by JonWallsten** [comment] 2017-08-08 09:08
Probably the same as the previous bug report: https://github.com/styled-components/styled-components/issues/1068

**Comment by IIIristraM** [comment] 2017-08-08 09:14
There is custom theme in my case, that is set by code

```
const {
  default: styled,
  css,
  injectGlobal,
  keyframes,
  ThemeProvider,
} = styledComponents as ThemedStyledComponentsModule<any> as ThemedStyledComponentsModule<Theme>;

export { css, injectGlobal, keyframes, ThemeProvider, ThemeProps, styled };
```

**Comment by philpl** [comment] 2017-08-08 13:55
This is definitely a duplicate of #1068. Although it proves that there's different ways to reproduce that bug :) If you'd like you can copy over the description of your `Theme` interface there :wink:

**Closed by philpl** 2017-08-08 13:55 UTC

**Comment by 0x80** [comment] 2018-12-13 10:40
This was an old issue, but I'm getting a similar error with v4. Is this related somehow? I shared my problem on SO: https://stackoverflow.com/questions/53724583/why-this-wrapped-styled-component-errors-has-no-properties-in-common-with
