### ISSUE TITLE
Loosing style classes while editing from the dev console

### ISSUE THREAD

**Issue by fjaskolski** [styled-components/styled-components#381] opened 2017-01-17 20:13 UTC
## Version
1.2.1

## Reproduction
This issue was discovered while using native Tizen web browser to render an app based on styled-components. Every time the page was reloaded, styles were lost after few seconds of flawless performance.

The guess was the Tizen browser performs some kind of faulty manipulation with the styles (like optimisation). While trying to reproduce the same behaviour within the desktop environment, we noticed the following behaviour (replicable across other styled-components projects).

You'll just need Chrome (gif was recorded with v55.0.2883.95, 64-bit).

## Steps to reproduce
1. Go to https://styled-components.com/ in Chrome.
2. Open the Console, locate `<style type="text/css">` tag.
3. Double click any class to edit and then click away at **any other element** (NOTE: hitting ESC doesn't reproduce the issue).

![styled-components-breaks](https://cloud.githubusercontent.com/assets/5114422/22031342/9dbb9700-dce0-11e6-8790-5123b72abd33.gif)

*BTW: While using Safari (v8.0 10600.1.25) the page (styled-components.com) doesn't render at all (`ReferenceError: Can't find variable: Symbol – index.js:498`). Same thing for the Tizen browser.*

## Expected Behavior
Nothing should change.

## Actual Behavior
Some of the classes disappear.

**Comment by mxstbr** [comment] 2017-01-17 20:17
Wow that's a funky bug you found there! Let me try this with the v2 branch.

`Symbol` should definitely not be an issue, that's our fault. Probably a `for-of` or something that snuck in.

**Comment by mxstbr** [comment] 2017-01-17 20:26
The double-clicking "bug" isn't actually a styled-components bug, that's solely due to the fact that Chrome for some reason removes classes from inline `style`s when you double click them and then click somewhere else. The same thing applies to anything that inlines `style` tags.

The Symbol is more interesting, as searching for Symbol in the `dist` version of styled-components gives you this result:

![screen shot 2017-01-17 at 21 24 04](https://cloud.githubusercontent.com/assets/7525670/22038402/51965660-dcfb-11e6-97d9-207385e2617f.png)

(all the further down results are in comments)

As far as I can tell, all of the usages of Symbol are actually just compatibility checks to make sure it exists, but it isn't used anywhere. Is there any way you could get me a specific location in the source that breaks and/or a way to download the Tizen browser?

**Comment by vdanchenkov** [comment] 2017-01-17 20:52
@mxstbr I happen to have old enough Safari (8.0.3). It's website-specific. Check https://styled-components.com/static/js/main.ae0abfa5.js.

All `[].forEach` are transiped to this.

My demo project runs fine in Safari 8.

**Comment by fjaskolski** [comment] 2017-01-17 21:10
@vdanchenkov Yup, exactly! In that last line by "page" I meant styled-components.com. I guess some polyfill  may be missing. 

As for Tizen browser – there is an [emulator](https://01.org/web-simulator/online/), but I couldn't reproduce any of those issues there.

I'm still wondering what's up with Chrome (and Safari as well, at least v8) when it comes to removing classes after touching the inline styles. Do you happen to have any insights on this? I did a quick test and this doesn't happen for a static page.

**Comment by mxstbr** [comment] 2017-01-18 09:41
> All [].forEach are transpiled to this.

Sorry, are transpiled to what? This is what I get on the Babel REPL: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=new%20Array().forEach(bla%20%3D%3E%20%7B%0A%20%20%0A%7D)

I think that's something to do with how we insert the styles, but @threepointone would know more about this!

**Comment by vdanchenkov** [comment] 2017-01-18 10:32
@mxstbr source of the problem is here: https://unpkg.com/styled-components@1.0.0/lib/vendor/postcss/container.js It's fixed in the latest version.

**Comment by fjaskolski** [comment] 2017-01-18 10:34
Thanks @mxstbr for your interest on this case!

Tinkered a little more with the weird `<style>` issue. It turns out that for some reason both Chrome and Safari interprets the style class definitions as separate blobs. 

Selecting one blob to edit makes the browser think it is the **only one** within the whole `<style>` tag. I guess that is why the rest of the definitions disappear. Probably this gif explains it better:

![console-bug](https://cloud.githubusercontent.com/assets/5114422/22060448/12464436-dd71-11e6-9b91-ed05f10f1859.gif)

I tried to reproduce the "segmented" css definitions by injecting styles tag with JS like this:
```js
var style = '<style type="text/css"> \n' +
'.bRQaUB { ... }\n' +
'.deCEdq { ... }\n' +
'</style>';
document.write(style);
```
But it always ends up as a single, not fragmented blob. I suspect there may be something tricky with how the class definitions are concatenated (probably [somewhere here](https://github.com/styled-components/styled-components/blob/master/src/models/GlobalStyle.js)?).

**Comment by mxstbr** [comment] 2017-01-18 10:38
> It's fixed in the latest version.

Ahh I remember that! Please update to the latest version of `styled-components` @fjaskolski and this will all disappear.

> Selecting one blob to edit makes the browser think it is the only one within the whole <style> tag. I guess that is why the rest of the definitions disappear

This is definitely something to do with how we inject styles. (cc @threepointone @geelen who are responsible for that code) I _assume_ (please wait for them to confirm) the tradeoff here is that it's a lot faster, for the downside that you cannot edit them like that.

I think that's perfectly reasonable and I don't think we can/want to fix that at the moment, so I'll close this issue for now. If this does turn out to be a bug on our side, fixing which doesn't have any performance regression, I'll happily reopen it.

Thanks for kicking off this super interesting discussion!

**Closed by mxstbr** 2017-01-18 10:38 UTC
Labels: bug

**Comment by geelen** [comment] 2017-01-18 10:53
Actually, it's here: https://github.com/styled-components/styled-components/blob/8f2906e840f25a462a00f02a2655688535c556c0/src/vendor/glamor/sheet.js#L125-L127

We inject text nodes into the `<style>` tag so that we can inject more text nodes in between them. When you use devtools I'm guessing it's concatenating all the text nodes together, and so SC is getting confused. Not sure how we'd go about detecting and recovering from this, but maybe the code for SSR rehydration could help, since it's all about restoring state from the DOM...

Thanks for pointing this out I'll keep it mind in the future but yeah I don't think we can fix it at the moment.

**Comment by fjaskolski** [comment] 2017-01-18 11:21
@geelen @mxstbr Thank you so much, everything is clear now and I learned something today! An awesome project with outstanding support.

We'll do a test run to determine whether Tizen browser falls for this or is it completely unrelated. I'll update this post in case anyone else faces the problem.

Please make sure to take care about old Safari users and update `styled-components` at [styled-components.com](https://styled-components.com) though! ;)

**Comment by mxstbr** [comment] 2017-01-18 12:08
Will do!
