### ISSUE TITLE
5.2 createGlobalStyle mess up the globally created style

### ISSUE THREAD

**Issue by Nagarian** [styled-components/styled-components#3293] opened 2020-09-27 17:55 UTC
## System:
 - OS: Windows 10 10.0.19041
 - CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
 - Memory: 2.39 GB / 7.92 GB
## Binaries:
 - Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD

## Reproduction
<https://github.com/Nagarian/optc-box-manager/>

## Steps to reproduce

This issue occur only on production build, on dev environment nothing happen.

- clone the repo <https://github.com/Nagarian/optc-box-manager/>
- then :

```bash
npm i styled-components@5.2
npm run build
cd build
npx serve
```

## Expected Behavior

![image](https://user-images.githubusercontent.com/3041932/94371980-a8dfdf00-00fa-11eb-8b90-5f103e18b990.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/3041932/94371966-906fc480-00fa-11eb-8b3d-2d6e77bc8572.png)

After upgrading from 5.1.1 to 5.2, my global style is completely messed up. I think the problem come from the ordering of the different Global Components I have (see file `src/styles/index.tsx` where I import 3 `createGlobalStyle` components)

```
<>
      <ResetCss />
      <FontCss />
      <FormsCss />
</>
```

**Comment by xeladejo** [comment] 2020-10-02 16:07
I think it is the expected behavior. See the [release changelog](https://styled-components.com/releases#v5.2.0):

> Preallocate global style placement to ensure cGS is consistently inserted at the top of the stylesheet; note that this is done in runtime order so, if you have multiple cGS that have overlapping styles, ensure they're defined in code in the sequence you would want them injected (see #3239)

**Comment by Nagarian** [comment] 2020-10-02 16:18
But I want ResetCss being injected before FontCss, which is not the case on production build while in dev mode they are loaded like I've defined them.This is this inconsistency, that let me think there is a bug.

I think that their behaviour shouldn't vary between this two mode because that rise silent issues detectable only in production.

**Comment by fabb** [comment] 2020-10-12 19:38
Could you change your css specificity? Relying on a specific order is rarely a good idea.

**Comment by kitten** [comment] 2021-08-09 17:01
Duplicate of #3146

**Closed by kitten** 2021-08-09 17:01 UTC
