### ISSUE TITLE
Rollup Issue with Macros

### ISSUE THREAD

**Issue by nathanaelphilip** [styled-components/styled-components#2717] opened 2019-08-14 21:28 UTC
## System:
 - OS: macOS 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Memory: 406.95 MB / 16.00 GB
 - Shell: 2.7.1 - /usr/local/bin/fish
## Binaries:
 - Node: 12.3.1 - ~/.asdf/installs/nodejs/12.3.1/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.asdf/installs/nodejs/12.3.1/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^4.3.2 => 4.3.2 
### package.json
```
"dependencies": {
    "prop-types": "^15.7.2",
    "styled-components": "^4.3.2",
    "styled-theming": "^2.2.0",
    "styled-media-query": "^2.1.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/plugin-external-helpers": "^7.2.0",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "@storybook/addon-actions": "^5.1.11",
    "@storybook/addon-knobs": "^5.1.11",
    "@storybook/addon-links": "^5.1.10",
    "@storybook/addon-viewport": "^5.1.11",
    "@storybook/addons": "^5.1.11",
    "@storybook/react": "^5.1.11",
    "babel-loader": "^8.0.6",
    "babel-plugin-styled-components": "^1.10.6",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "3.1.0",
    "rollup": "^1.19.4",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-commonjs": "^10.0.2",
    "rollup-plugin-json": "^4.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-peer-deps-external": "^2.2.0",
    "rollup-plugin-replace": "^2.2.0",
    "rollup-plugin-url": "^2.2.2"
  },
  "peerDependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
```

### .babelrc
```
{
  "presets": [
    ["@babel/env", {"modules": false}],
    "@babel/preset-react"
  ]
}
```

### rollup.config.js
```
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import resolve from 'rollup-plugin-node-resolve'
import external from 'rollup-plugin-peer-deps-external'
import json from 'rollup-plugin-json'
import url from 'rollup-plugin-url'
import pkg from './package.json'

export default {
  input: './src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true
    }
  ],
  external: ['styled-components'],
  globals: { 'styled-components': 'styled' },
  plugins: [
    external(),
    json(),
    url(),
    babel({
      exclude: ['node_modules/**', '../../node_modules/**'],
      plugins: ['@babel/external-helpers'],
    }),
    resolve(),
    commonjs({
      ignoreGlobal: true,
      namedExports: {
        'node_modules/babel-plugin-macros/dist/index.js': ['createMacro'],
        'react-is': ['isElement', 'isValidElementType', 'ForwardRef'],
      }
    })
  ]
}
```

## Steps to reproduce
Use `create-react-app` to create a new instance
Add in the listed dependencies above ^^^
Run `npm run build`

## Expected Behavior
Should roll things up nicely 🥳

## Actual Behavior
Throws an error when using `import styled, { css } from 'styled-components/macro'` – says:
```
[!] Error: 'css' is not exported by node_modules/styled-components/dist/styled-components-macro.esm.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/styles/button.js (1:17)
```

**Comment by wintercounter** [comment] 2019-10-01 20:21
I'm not so familiar with rollup, but I guess Babel should run on your file first. Without Babel there is no macro. It's being resolved by babel-macros-plugin at build time.

**Comment by kitten** [comment] 2021-08-09 18:28
Most of the time Rollup build issues are caused by:

- Misordered or misconfigured plugins
- Transpilation (sometimes even double) to CJS which isn't needed
- Misconfiguration of the commonjs plugin
- Bundling externals when that isn't even necessary or intended

All of these lie outside of what makes sense as an issue here, so Rollup may have more helpful help channels.
But for now I'll go ahead and close this

**Closed by kitten** 2021-08-09 18:28 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:, integration

**Comment by dguzman5** [comment] 2022-07-22 22:11
Maybe it has something to do with this recommendation from Rollup 

> Using With @rollup/plugin-commonjs
When using @rollup/plugin-babel with @rollup/plugin-commonjs in the same Rollup configuration, it's important to note that @rollup/plugin-commonjs must be placed before this plugin in the plugins array for the two to work together properly. e.g.

https://www.npmjs.com/package/@rollup/plugin-babel
