### ISSUE TITLE
Unexpected flash of unstyled content when using with next.js

### ISSUE THREAD

**Issue by jimthedev** [styled-components/styled-components#162] opened 2016-11-02 22:42 UTC
## Version
1.0.10

## Reproduction
https://github.com/jimthedev/next-styled-components-fouc

## Steps to reproduce
```
mkdir next-styled-components-fouc
cd next-styled-components-fouc
git init
npm init
npm install --save next styled-components
mkdir pages
touch pages/index.js
Copy the following to pages/index.js

import React from 'react'
import style from 'styled-components'
import css from 'next/css'

// Example of a component styled by styled-components
const StyledComponent = style.div`
  background-color: #000000;
  color: white;
`;

// Example from Next's home page
const glamorStyle = css({
  color: 'red',
  ':hover': {
    color: 'blue'
  },
  '@media (max-width: 500px)': {
    color: 'rebeccapurple'
  }
})

export default () => {
  return (
    <div>
      <div style={{color:'green'}}>I am being styled by React's built in styling</div>
      <StyledComponent>I am being styled by styled components</StyledComponent>
      <div className={glamorStyle}>I am being styled by next & glamor</div>
    </div>
  )
}

Add a script to the package.json like this:

{
  "scripts": {
    "dev": "next"
  }
}
and run:

npm run dev
```

## Expected Behavior

I would expect the styled-components styles to be rendered in the same way (without FOUC) as the glamor and react built in styling.

## Actual Behavior

There is a FOUC before the styled-components are applied. Specifically the component with the black background color takes longer to apply styles than the other components.

Tweet for reference: https://twitter.com/JimTheDev/status/792849817907007488
Corresponding next.js issue: https://github.com/zeit/next.js/issues/184

**Comment by geelen** [comment] 2016-11-03 01:03
Interesting! I wonder if this is a regression with #137? Can you try with `v1.0.9`?

**Comment by vdanchenkov** [comment] 2016-11-03 07:46
I had not specifically checked it, but I think that I've seen it before 1.0.10. 

Source of FOUC is the fact that next.js uses server side rendering. It correctly handles glamor stylesheet on server and sends builded styles to the client right away.

Styled-components is based on glamor stylesheet implementation, but it uses modified copy of it. Next.js do not do anything special about styled-component's stylesheet implementation and as a result you do not get any styles on first render.

My guess is that it would work in this situation if styled components could work with stylesheet from glamor module. We could at least use webpack's resolve alias to make both libraries reference the same stylesheet instance.

**Comment by geelen** [comment] 2016-11-03 12:06
Ah ok you get the flash when loading from the client after rendering on the server. Yep, that sounds like something we haven't considered yet. I'll take a look.

**Comment by luisrudge** [comment] 2016-12-04 02:26
I'm also having this issue 😭

**Comment by mxstbr** [comment] 2016-12-04 08:31
We're working on this @luisrudge, see #214 and #227. Soon!

**Comment by luisrudge** [comment] 2016-12-04 20:21
@mxstbr awesome 🎉

**Comment by camsjams** [comment] 2017-01-30 23:50
Shortcut for TLDR; folks - looks like it's almost ready! Final discussion [here](https://github.com/styled-components/styled-components/issues/386)

**Comment by migueloller** [comment] 2017-02-25 23:14
Take a look here: https://github.com/zeit/next.js/tree/master/examples/with-styled-components

**Comment by pencilcheck** [comment] 2017-03-28 01:24
Is this solved? I'm still seeing this behavior. And the example on zeit doesn't really work for me, getting error about undefined `token`

**Comment by migueloller** [comment] 2017-03-28 01:58
@pencilcheck,

The example should work just fine as long as you're creating at least one styled component. As a temporary fix you can add the following in your `_document` file:

```es6
// hack until https://github.com/styled-components/styled-components/issues/124#issuecomment-257875646 gets fixed
injectGlobal``
```

**Comment by pencilcheck** [comment] 2017-03-28 02:51
Ok, I also delete and reinstall node_modules folder with the latest nextjs 2.0.0 release (I was using beta) and I think that fixed the issue.
Thanks!

**Comment by pencilcheck** [comment] 2017-03-28 03:00
I found out why I had the token error, I was using nextjs, and in their example _document.js I removed the Head element and that's why it was complaining. That was not expected!

**Comment by mxstbr** [comment] 2017-04-01 09:28
I'm closing this since Next has an official example that works perfectly fine now, and we're adding an official API for v2.

**Closed by mxstbr** 2017-04-01 09:28 UTC
