### ISSUE TITLE
A different prop value create same style (since 5.2)

### ISSUE THREAD

**Issue by joccd** [styled-components/styled-components#3376] opened 2021-01-13 18:15 UTC
Hello,

## System:
 - OS: Windows 10 10.0.18363
 - CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
 - Memory: 2.69 GB / 15.68 GB
## Binaries:
 - Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - babel-plugin-styled-components: 1.12.0 => 1.12.0
 - styled-components: ^5.2.1 => 5.2.1

## Reproduction

https://codesandbox.io/s/javascript-forked-0sjtn?file=/index.js

## Steps to reproduce

Send a prop to the component and use it with &

## Expected Behavior

Only one box is red (since isRed is only on the first one)

## Actual Behavior

Both box are red

Regards,
Joccd

**Comment by nautidpk** [comment] 2021-01-18 17:59
you are using `body & > div` inside wrapper . 
use `& > div ` instead as -  
`const Wrapper = styled.div`
  padding: 4em;
  display: inline-block;

  & > div {
    background: ${(props) => props.isRed && "red"};
  }
`;`
and it should work

**Comment by xemlock** [comment] 2021-01-18 23:01
If I'm not mistaken, the following should also work as expected, but it doesn't. This time both squares are green. 

```
const Container = styled.div`
`;

const Wrapper = styled.div`
  padding: 4em;
  display: inline-block;

  ${Container} & > div {
    background: ${(props) => props.isRed && "red"};
  }
`;
```

**Comment by nautidpk** [comment] 2021-01-19 07:02
i think there is conflicts in styling so you have to increase the specificity of comonent . 
According to docs **the ampersand can be used to increase the specificity of rules on the component; this can be useful if you are dealing with a mixed styled-components and vanilla CSS environment where there might be conflicting styles:**
So the below code works perfectly - 
```
const Container = styled.div`
`;

const Wrapper = styled.div`
  padding: 4em;
  display: inline-block;

  ${Container} & > div {
    background: ${(props) => props.isRed && "red"};
  }
`;

const App = () => {
  return (
    <Container>
      <Wrapper isRed>
        <Box />
      </Wrapper>
      <Wrapper>
        <Box />
      </Wrapper>
    </Container>
  );
};
```

**Comment by xemlock** [comment] 2021-01-19 08:59
Ok, but the question is, why would I need to boost the specificity in 5.2.0? Where can I find some more information that handling of selectors have changed between the versions?

Also, if I take [this example from the docs](https://styled-components.com/docs/advanced#referring-to-other-components), and use props instead of a fixed color, I expect this to work:

```js
  ${Link}:hover & {
    fill: ${( props ) => props.isRed ? 'red' : 'rebeccapurple' };
  }
```

but it doesn't unless I change the selector to `${Link}:hover &&`. Shouldn't the docs be corrected, then?

See example here: https://codesandbox.io/s/brave-jones-jpb91

**Comment by nautidpk** [comment] 2021-01-19 14:03
yes you are right ,
i also faced that issue in 5.2.0 
and the above workaround works for me

**Comment by joccd** [comment] 2021-01-19 14:46
Thanks for your answers.
This is a huge breaking change (at least for me with hundreds of components).
Is there any option to disable this behaviour ?

**Comment by xemlock** [comment] 2021-01-19 16:28
I may have found possible explanation [here](https://github.com/styled-components/styled-components/issues/3244#issuecomment-687648237).

But since this is a rather huge compatibility break, I believe it should be addressed in the docs.

For now, it looks like the only solution is to stick with 5.1.0

**Comment by BartJanvanAssen** [comment] 2021-02-05 13:03
Any update on this one?

**Comment by richardxia** [comment] 2021-02-26 23:59
For other people like me who just found this issue from a search and couldn't easily find the solution/workaround in the comments of this issue (which BTW, contain some great investigation!), the workaround is to use the **double ampersand** (`&&`) in the selector instead of a single ampersand (`&`).

For example:

```js
// Original
const Wrapper = styled.div`
  ${Container} & {
    background: ${(props) => props.isRed && "red"};
  }
`;

// Fixed
const Wrapper = styled.div`
  ${Container} && {
    background: ${(props) => props.isRed && "red"};
  }
`;
```

**Comment by kitten** [comment] 2021-08-09 15:57
Duplicate of #3265

**Closed by kitten** 2021-08-09 15:57 UTC
