### ISSUE TITLE
Warning - Several instances of styled-components in a micro-frontend application

### ISSUE THREAD

**Issue by ShimiSun** [styled-components/styled-components#3450] opened 2021-04-02 17:59 UTC
### System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 53.87 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
### Binaries:
 - Node: 15.7.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.4.3 - /usr/local/bin/npm

## Reproduction
https://github.com/grommet/micro-frontend
Run the application on Dev mode and see the following warning:

> react_devtools_backend.js:2430 It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.
See https://s-c.sh/2BAXzed for more info.

(The warning isn't displayed in production, so don't use the Netlify deployment on this project and run it on dev mode instead.)

## Steps to reproduce
See the micro-frontend example app attached https://github.com/grommet/micro-frontend
![micro-frontend-archticture](https://user-images.githubusercontent.com/6320236/113429320-8f636c80-9395-11eb-8d25-3ad9011e318d.png)
Each micro frontend app has its own React + Styled-components + Grommet dependencies on its package.json and is built with CRA. The application is working as expected and is performing lazy loading for the React components as expected, although a warning is being thrown about styled-components: 
> react_devtools_backend.js:2430 It looks like there are **several instances of 'styled-components' initialized in this application**. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.
See https://s-c.sh/2BAXzed for more info.

## Expected Behavior
No warnings on the console while using a dev mode.

## Actual Behavior
During development, a warning about several instances of styled-components is displayed on the console.

Any idea of how to handle the warning will be appreciated. I checked the [docs](https://s-c.sh/2BAXzed) and while I understand micro frontend wouldn't be the best way to maintain your file structure, I'm still interested in getting this console warning resolved.

I've also tried to deduce solutions/workarounds from existing issues [How to use babel-plugin-styled-components with create-react-app?](https://github.com/styled-components/styled-components/issues/1679) and [[Micro Frontend] Duplicate class name if there are multiple styled-components](https://github.com/styled-components/styled-components/issues/2974) but none of those solutions helped to eliminate the warning.

I'd appreciate any tips that might help solve the warning.

**Comment by tu4mo** [comment] 2021-04-07 09:29
Related: #3440

**Comment by motevallian** [comment] 2021-04-27 11:21
We had the same issue which we solved by externalising `react`, `react-dom` and `styled-components` dependencies for all micro-frontends. 
We have an initial skeleton app which is loaded in every page before any other apps. Its responsibility is to expose the above deps to `window` object. 
Also all micro-frontend apps will now have settings in `WebPack` which receives `react`, `react-dom` and `styled-components` from the window object (`window.React, window.ReactDOM, window.styled`).

**Comment by kitten** [comment] 2021-08-09 15:14
Duplicate of #2974

**Closed by kitten** 2021-08-09 15:14 UTC
