### ISSUE TITLE
Styles Not Injected When Dynamically Importing

### ISSUE THREAD

**Issue by jckhang** [styled-components/styled-components#992] opened 2017-07-13 17:36 UTC
Hey guys, we are experiencing a problem with styled components. One of our styled components' styles are not being injected into the DOM. A classname hash is being generated, but the styles are simply not there.

## Version
2.1.1

## Reproduction

 It seems like the issue is related to [dynamic imports](https://facebook.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html#code-splitting-with-dynamic-import).

## Steps to reproduce

* Follow the dynamic import guide [here](https://facebook.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html#code-splitting-with-dynamic-import).
* Render two components as siblings that both use this dynamic import pattern

## Expected Behavior

All of the styles are loaded and displaying correctly

## Actual Behavior

The second sibling's outermost div's styles are not being injected into the DOM.

## More info

We have two components being dynamically imported as siblings. The first sibling is loading just fine, and all of the second component's styles are being loaded except for the outermost div. Here are a couple things we have checked/tried:

* rendering the first sibling without dynamically importing makes it so that the second sibling renders just fine. it is only when the first sibling is being dynamically imported that the second sibling's styles are messed up
* the style tags in the chrome inspector are showing up but the tag related to our problematic component is not showing the outermost div's style
* we tried editing the styles so that the hash changes but that doesn't help
    * our application hot reloads and when we changed the style, the styles were hot loaded and it looked fine, however a hard refresh reset it back to nothing

**Comment by mxstbr** [comment] 2017-07-13 18:11
I remember having this problem when I investigated code splitting in our app. (didn't work out for other reasons) I thought that was an issue with our setup but maybe it's not.

Any chance you could put together a reproduction? Also /cc @geelen since he's the one most likely to know what's going on here.

**Comment by jckhang** [comment] 2017-07-13 18:45
We created this issue after reading @philpl in #977:

> Also, I suspect it's either related to SSR or a duplicated SC lib in your case. At least it sounds like it

After thinking about it, this makes sense. Code splitting with dynamic imports downloads a separate build file from the server for the component that's being imported, so this separate build file likely has its own instance of styled-components. We will put together a simple reproduction and post it here when we can.

**Comment by mxstbr** [comment] 2017-07-13 20:34
I would've thought that `styled-components` would be in the shared vendor bundle that's downloaded for all pages/routes?

**Comment by philpl** [comment] 2017-07-13 22:06
> Reproduction
> It seems like the issue is related to dynamic imports.

@jckhang deeply sorry for the trouble again, but we need a reproduction / isolation of the bug :/ otherwise it's just speculation and a stab in the dark for us, since we won't be able to start debugging. In the meantime:

> The second sibling's outermost div's styles are not being injected into the DOM.

Can you check that div's classnames. And search them in the `style` tag that we inject, and post the results here?

Also, if it's an issue with dynamic bundles, can you try to export the webpack json/stats and look at them in the bundle analyser. Specifically it should be useful to find out what's happening with the dynamic splitting behaviour: https://webpack.github.io/analyse/

I suspect it might even be an issue with create-react-app's dynamic import behaviour, but that's pure speculation

**Comment by mxstbr** [comment] 2017-07-13 22:28
Yeah we use `create-react-app` too so it might have something to do with that?  Looping in @gaearon for good measure, maybe he has a quick idea what the issue could be.

**Comment by Kinzeng** [comment] 2017-07-14 15:06
Hey guys I'm working on a simple reproduction and the same behavior doesn't seem to be showing up. However another source of possible duplication is that we are using [lerna](https://github.com/lerna/lerna), and we have multiple packages with their own installed `styled-components` packages. Maybe we should declare `styled-components` as a peer dependency and grab it from the root project?

**Comment by mxstbr** [comment] 2017-07-14 17:01
Hmm, we don't use lerna, just have a big cra app and it happens. 🤔

**Comment by Kinzeng** [comment] 2017-07-18 13:35
Maybe with a large enough app the styles interfere with each other somehow? Hmm..

**Comment by philpl** [comment] 2017-07-18 14:08
@Kinzeng then we'd see problems across the board. This must obviously be a clear cut problem with a list of causes. I think the most likely explanation is: Duplicated styled-components modules

**Comment by Kinzeng** [comment] 2017-07-18 14:28
It seems the common factor between @mxstbr and I is that we're both using `create-react-app`. They don't let us change any of the webpack settings and I think that's the likely source for duplicated modules.

**Comment by DeividasK** [comment] 2017-07-19 08:53
I think the issue may be caused for the same reasons as here #987.

**Comment by Kinzeng** [comment] 2017-07-19 13:46
Hey @DeividasK, thanks for the heads up! To be clear, you have multiple npm packages that you maintain, correct? And more than one of these packages had `styled-components` as a dependency?

**Comment by DeividasK** [comment] 2017-07-19 14:05
Yes. We have `marketing` repository which depends on `nested-react-components` 
and `styled-components` packages. `nested-react-components` itself used to depend on `styled-components`. This caused us an issue described in #987. Now I moved that dependency to `devDependencies` and `peerDependencies` and added `styled-components` to `externals` in webpack config in `nested-react-components` package. This means that `styled-components` are no longer bundler with the package and depend on the project to have `styled-components` as a dependency.

**Comment by Kinzeng** [comment] 2017-07-19 19:40
@DeividasK thanks for info! We have essentially the same setup as you did, and after analyzing the bundles using `source-map-explorer`, we found that we do have duplicate packages.

@mxstbr and @philpl `source-map-explorer` also let us know that `styled-components` is not being duplicated as a result of dynamic imports. We will try @DeividasK's fix and let you know how it goes. I agree with @DeividasK that it is a good idea to try to detect duplicate packages and let developers know about the consequences.

**Comment by philpl** [comment] 2017-07-19 21:46
I've created a new issue that tracks a solution for this problem and am going to go ahead and close this in favour of it, to track the resolution rather than a symptom of the actual bug.

I'm not sure whether one of us will have time to look into this, but if anyone is interested in contributing a fix, shoot a comment over at the other issue. Thanks! :)

**Closed by philpl** 2017-07-19 21:46 UTC
Labels: bug
