### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by dbertella** [styled-components/styled-components#471] opened 2017-02-07 18:26 UTC
This is not an issue itself, and it's a follow up from #465.

Using a styled-component as the following in RN can lead to some performance problem in your opinion?
```js
const Container = styled.View`
    flex: ${({ flex }) => flex || 1};
    flex-direction: ${({ direction }) => direction || 'column'};
    justify-content: ${({ justify }) => justify || 'flex-start'};
    align-items: ${({ align }) => align || 'stretch'};
    margin: ${({ m }) => m || 0};
    padding: ${({ p }) => p || 0};
`;
```
I know the stylesheet Object is heavily cached, and I think styled-component will use it at some point, am I right?
What about passing props at runtime? What's going to happen?
Because I'm really happy using this component it's really fast to prototype, but if it can be a problem I will find another solution.

I report @jacobp100's answer since it's a good point to start. 
 
> I'm don't think anything has been benchmarked, but it's something I'd like to see. Most of the time spent in styled-components will be parsing, but I don't think we know how much time is spent here.
> 
> In RN, every time your props change in a way that changes the CSS text, it gets re-parsed. This is probably negligible for a single component. However, when you load the app, you'll have to parse CSS for every component that gets mounted. If you have a global theme and change a value, that'll trigger a large re-parse for every component that depends on the theme.
> 
> If you're concerned about perf, you can set the default styles with styled-components, and override the styles in the style property.
> ```js
> const ContainerDefaults = styled.View`
>     flex: 1;
>     flex-direction: column;
>     ...
> `;
> 
> const Container = ({ flex, direction ... }) => (
>     <ContainerDefaults style={{ flex, direction ... }} />
> );
> ```
> This will only require one parse, no matter what styles you pass in.
> 
> If you want to eliminate the parse time, you can look at my [almost identical project](https://github.com/jacobp100/cssta). It's more limited in what you can do, but I think the limitations are a good thing!

**Comment by jacobp100** [comment] 2017-02-07 19:10
As a first step, we need to gather example projects to see how people use styled-components.

We can benchmark the startup time using react-test-renderer.

**Comment by mxstbr** [comment] 2017-02-08 09:32
I've been meaning to try to benchmark our stuff for ages, but couldn't figure out a reproducible way to do it. Maybe related to #348?

**Comment by jacobp100** [comment] 2017-02-08 12:02
See #474

**Comment by jacobp100** [comment] 2017-02-08 15:45
I've done some benchmarking with `benchmark.js` over on [my project](https://github.com/jacobp100/cssta/blob/master/benchmark/tests.js).

![screen shot 2017-02-08 at 14 51 15](https://cloud.githubusercontent.com/assets/7275322/22742286/2493cdb8-ee0e-11e6-8694-56a0ebfabde4.png)

If you want to move this benchmarking into the styled-components repo, I'm more than happy for you to do so!

The shorthands are definitely slowing things down, but I expect that to drop a lot with styled-components v2. I'm not sure if it's possible to test v1 and v2 at the same time, but that would definitely be cool!

It does seem like the caching isn't working though. The last result is from running,

```js
const instance = render(<Component />);
instance.update(<Component danger />);
instance.update(<Component />);
instance.update(<Component danger />);
instance.update(<Component />);
instance.update(<Component danger />);
instance.update(<Component />);
instance.update(<Component danger />);
```

Which should only parse two stylesheets, and then reuse the results. 😕

**Comment by mxstbr** [comment] 2017-02-11 18:43
> If you want to move this benchmarking into the styled-components repo, I'm more than happy for you to do so!

Yes please!! Let's switch to Jest too, and finally get #94 done?!

**Comment by jacobp100** [comment] 2017-02-12 17:35
Added the project! We might want to consider how to better structure the tests, but for a first cut, it looks fine!

I actually didn’t end up using Jest for the benchmarks—I use benchmark.js instead!

**Comment by mxstbr** [comment] 2017-02-12 19:07
I'd rather we move this to the main repo? That way we can run the benchmarks for each PR and see if we get slower over time…

**Comment by jacobp100** [comment] 2017-02-14 10:20
I added it to the v2 repo, but I accidentally did it to master rather than a branch 🤦‍♂️ Sorry about that!

**Comment by mxstbr** [comment] 2017-12-15 12:29
Closing since https://github.com/styled-components/benchmarks exists now.

**Closed by mxstbr** 2017-12-15 12:29 UTC
Labels: discussion

**Comment by mattnedrich** [comment] 2018-10-07 16:11
@mxstbr The link you posted no longer works
