### ISSUE TITLE
Parent reference styles with props being set to last prop value rather than the one set on the component.

### ISSUE THREAD

**Issue by JohnCollett** [styled-components/styled-components#3459] opened 2021-04-12 13:12 UTC
## System:
 - OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
 - Memory: 1.18 GB / 23.24 GB
 - Container: Yes
 - Shell: 4.4.20 - /bin/bash
## Binaries:
 - Node: 14.10.1 - ~/.nvm/versions/node/v14.10.1/bin/node
 - npm: 6.14.8 - ~/.nvm/versions/node/v14.10.1/bin/npm
## npmPackages:
 - styled-components: 5.2.0

## Reproduction

https://codesandbox.io/s/styled-components-issue-hts93

## Steps to reproduce

-Create a styled component parent container
-Create a styled component child that references the parent 
`${Parent}:hover & {}`
-Have that reference include a prop variable 
`${Parent}:hover & {color: ${props => props.colorProp}}`
-setup a component 
```
const Example = ({colorProp}) => (<Parent>
    <Child colorProp={colorProp}/>
</Parent>)
```
-Have two different version of Example
```
<Example colorProp='red' />
<Example colorProp='blue' />
```
both will now turn the text of the child blue when the parent is hovered over.

## Expected Behavior

When hovered over the parent the child should use the style of specified rather than the child of the last component.

## Actual Behavior

When hovered over the parent the style of the last component gets applied to all previous version.
This behaviour was last seen in version 5.1.1

**Comment by arimah** [comment] 2021-04-22 11:54
Hello! This appears to be another case of #3265, for which there is no proper fix. As a hacky workaround, you can use `&&` instead, but be aware it has higher precedence than a single `&`. :)

**Comment by kitten** [comment] 2021-08-09 14:56
Duplicate of #3165, indeed. Let's close this and keep that one open.

**Closed by kitten** 2021-08-09 14:56 UTC
