### ISSUE TITLE
React.StrictMode throws warning because of `findDOMNode` use

### ISSUE THREAD

**Issue by optunetobi** [styled-components/styled-components#2154] opened 2018-10-25 11:21 UTC
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of StyledComponent which is inside StrictMode. Instead, add a ref directly to the element you want to reference.
```

I am aware that it is only run in development-mode, but it clutters console output when trying to find errors.

@Fer0x Could we change this here somehow? (by not using findDOMNode)

I don't think it is a problem, not even sure if there is a proper solution. Keeping it for later reference.

_Originally posted by @optunetobi in https://github.com/styled-components/styled-components/pull/2073/review_comment/create_

**Comment by Fer0x** [comment] 2018-10-25 13:21
@optunetobi 
I have tried to replace findDOMNode with ref. I made it like it described in following issue https://github.com/facebook/react/issues/13029, but it doesn't work for cases with functions like `styled(() => <div />)` which are main target for classNameUseCheckInjector warning.
So this issue needs further investigation.

**Comment by Fer0x** [comment] 2018-10-25 13:39
I think will drop findDOMNode only when ref for Fragments be implemented. See https://github.com/facebook/react/pull/13841#issuecomment-430066195

**Comment by BofEmptiness** [comment] 2018-10-30 17:30
Oh, so that was styled component's that is throwing this error. Took me a long time to find after react update. Any plans to fix this?

**Comment by probablyup** [comment] 2018-10-30 17:43
It’s not possible to until some new stuff lands in React core.

**Comment by sag1v** [comment] 2018-11-01 15:32
@probablyup for now `findDOMNode` will stay?
`StrictMode` is killing it :man_shrugging:

**Comment by sag1v** [comment] 2018-11-01 17:41
Yeah, the problem is when my lib depends on sc and others depends on my lib while using `StrictMode`. But i guess there's nothing sc can do about it now

**Comment by ganapativs** [comment] 2018-11-03 15:09
Same issue here while using React Suspense. Not using `StrictMode` explicitly, but using `ReactDOM.createRoot(rootElement).render(<App />)`. Is `StrictMode` enabled by default while using `ReactDOM.createRoot` syntax?

*Demo:*
[![Edit 91xnz9j44r](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/91xnz9j44r)

**Comment by hagnerd** [comment] 2018-11-06 15:03
`StrictMode` is enabled by default when using `ReactDOM.createRoot` and/or `React.ConcurrentMode`.

**Comment by Macil** [comment] 2018-11-06 23:51
@Fer0x The Fragment ref solution will only give you the DOM elements if the React elements immediately inside the Fragment are raw HTML elements rather than React components. (Or it will work if they're React components that forward their ref to a raw HTML element.) This might be fine for the case here, just pointing out that it has restrictions and there are alternatives you can do now with similar restrictions.

If you're fine with the above restriction, and also fine with the restrictions that there's only one DOM element and that the user can't use string refs on the element, then you can implement this now by using React.cloneElement: (I'm using some Flow/TypeScript-like syntax for type annotations here)

```js
class Foo extends React.Component {
  _childEl: ?HTMLElement;
  _childRef = (el: ?HTMLElement) => {
    this._childEl = el;
    if (this.props.children.ref) {
      setRef(this.props.children.ref, el);
    }
  };

  render() {
    return React.cloneElement(
      this.props.children,
      {ref: this._childRef}
    );
  }
}
```

where setRef is defined [as this](https://github.com/StreakYC/react-menu-list/blob/fab95ff47c90a8704ff895e9a3ea4ec764a2f780/src/lib/setRef.js). I'm planning on using a solution like this in react-draggable-list (to re-implement the dragHandle function [seen here](https://github.com/StreakYC/react-draggable-list/blob/73a2fe7f317a69a0494fb79c3e0dd95879c6c748/example/Example.js#L51)) to avoid findDOMNode.

----

Another more general solution is to change `styled(() => <div />)` so that the user has to pass a ref onto their DOM element: `styled(domRef => <div ref={domRef} />)`. I used this solution when upgrading [react-float-anchor to not use findDOMNode](https://github.com/StreakYC/react-float-anchor/blob/master/CHANGELOG.md#300-2018-10-30). The downside is that it's explicit, and if the end-user wants their own ref on the same element they need to pass the given ref onto, then things get awkward (the user has to implement setRef and [use it like this](https://github.com/StreakYC/react-menu-list/blob/fab95ff47c90a8704ff895e9a3ea4ec764a2f780/src/MenuButton.js#L163)). In my case, end-users can usually just add a separate wrapper div, pass the ref from react-float-anchor onto the wrapper div, and then put their ref on their element, so users can often avoid awkwardness, but I'm not especially happy with it.

**Comment by zaguiini** [comment] 2018-11-14 21:15
Any news on this?

**Comment by probablyup** [comment] 2018-11-14 21:17
Hound the React team if you want movement on this... there's nothing we can do until a replacement API is available other than disabling the checker for strict mode (and is there even a way to detect that you're inside strict mode?)

**Comment by zaguiini** [comment] 2018-11-14 21:30
Yeah :( But luckily the only trade-off in this case is this annoying warning.

**Comment by Kovensky** [comment] 2018-11-15 02:11
That warning is also incorrect when `styled` is used as a HOC HOC 😆

```ts
function ClassNameProvider(props: {
  className?: string
  children(className: string): React.ReactNode
}) {
  return props.children(defined(props.className)) as JSX.Element | null
}
```

```ts
const FooClass = styled(ClassNameProvider)`/* styles */`

; (
  <FooClass>{fooClass => (
    <>
      {/* use fooClass, possibly conditionally,
        * possibly as another prop that only uses it conditionally, etc
        */}
    </>
  }</FooClass>
)
```

**Comment by Fer0x** [comment] 2018-11-15 07:13
@Kovensky I believe that such cases are quite rare, so you can disable warning with `suppressClassNameWarning` prop.

**Comment by probablyup** [comment] 2018-11-15 07:39
Honestly I wouldn’t be surprised if they decide to undeprecate it
eventually. No solid proposals have been raised for a replacement that
handles all the same use cases.

**Comment by sag1v** [comment] 2018-11-15 08:19
> The Fragment ref solution will only give you the DOM elements if the React elements immediately inside the Fragment are raw HTML elements rather than React components. (Or it will work if they're React components that forward their ref to a raw HTML element.)

@Macil How do you know? is there any RFC or draft implementation for this?

>Honestly I wouldn’t be surprised if they decide to undeprecate it
eventually

@probablyup I'm not sure, it seems they don't think there is a solid case for keeping it.  see [this tweet](https://twitter.com/sag1v/status/1060598811758915584?s=19)

**Comment by Macil** [comment] 2018-11-15 10:08
@sag1v Actually, I'm much less sure about that now. (One of the reasons I saw about removing findDOMNode was because it breaks encapsulation, which the Fragment ref feature wouldn't be much of an improvement if it operated on DOM nodes. Also, the Fragment ref feature would be really handy in a number of situations I've run into if it operated on components instead of DOM nodes. But it was suggested in a thread specifically about alternatives to findDOMNode and it may address the "it becomes difficult to know if any given DOM node might need to be found [later]" technical issue, so I'm not sure what to think on re-reading the thread.) I've [asked for clarification in that thread](https://github.com/facebook/react/pull/13841#issuecomment-438986352).

**Comment by zaguiini** [comment] 2018-11-15 12:38
> @zaguiini Deprecating of `findDOMNode` in Strict mode is not only our pain. Third party libraries actively use it. For example: [mui-org/material-ui#13394](https://github.com/mui-org/material-ui/issues/13394), [jasonslyvia/react-lazyload#209](https://github.com/jasonslyvia/react-lazyload/issues/209), [akiran/react-slick#1406](https://github.com/akiran/react-slick/issues/1406), [reactjs/react-transition-group#429](https://github.com/reactjs/react-transition-group/issues/429), [necolas/react-native-web#1151](https://github.com/necolas/react-native-web/issues/1151)

I see that. Luckily I'm very skeptical about adding new libraries to a project so I keep my package.json short and simple

**Comment by gaearon** [comment] 2018-12-04 01:09
It looks like you're using `findDOMNode` only for a DEV-time warning. Is that warning really so valuable?

**Comment by gaearon** [comment] 2018-12-04 01:15
>Hound the React team if you want movement on this... there's nothing we can do until a replacement API is available other than disabling the checker for strict mode (and is there even a way to detect that you're inside strict mode?)

Has anyone filed an issue on the React repo detailing a specific use case?

I don't know much about how `styled-components` uses this but solution with `cloneElement` in https://github.com/styled-components/styled-components/issues/2154#issuecomment-436452167 sounds reasonable to me if you want to preserve this behavior. Could you please describe why it doesn't work for you? Thanks.

**Comment by gaearon** [comment] 2018-12-04 01:16
>Unless you're using React in Concurrent mode.

You shouldn't be though. It's not stable. Less stable than Hooks, even.

**Comment by gaearon** [comment] 2018-12-04 01:17
>No solid proposals have been raised for a replacement that
handles all the same use cases.

Please file issues for those use cases. No solid proposal *will* be raised if those use cases are only described in other repos, and nobody comes to file them to ours. :-)

**Comment by Kovensky** [comment] 2018-12-04 01:21
The cloneElement approach will only get you a ref to the immediate React element child, which is still not necessarily a DOM element. I think the check doesn't even run if the child is a known DOM node. The debug check specifically wants to see if the className made it onto the DOM.

**Comment by sag1v** [comment] 2018-12-04 09:37
Thanks @gaearon will do!

@probablyup I think we can close this issue as `styled-components` can't really do much without a new API replacement as you mentioned in [this comment](https://github.com/styled-components/styled-components/issues/2154#issuecomment-434401222). right?

**Comment by zaguiini** [comment] 2018-12-04 09:57
> > Unless you're using React in Concurrent mode.
> 
> You shouldn't be though. It's not stable. Less stable than Hooks, even.

Not doing in production and please, whomever is doing: stop it.
I was just messing around and found the warning 🤷‍♂️

**Comment by exogen** [comment] 2018-12-05 01:55
What if the check were just slightly less focused and did `document.querySelector(selector)` to see if *any* DOM node contains the class name that styled-components generated? I think the only issue would be potential false negatives (missed warnings) if another styled element on the page ends up using the same generated class name, right?

**Comment by probablyup** [comment] 2018-12-05 03:32
I guess that’s the ultimate fallback if they do remove the API. It’s not
scopes enough otherwise.

**Comment by probablyup** [comment] 2018-12-05 03:32
Scoped*

**Comment by 42shadow42** [comment] 2018-12-06 21:42
Strict mode also appears to produce the following warnings: 

> Warning: Unsafe lifecycle methods were found within a strict-mode tree:
>     in StrictMode
> componentWillMount: Please update the following components to use componentDidMount instead:

> Warning: Unsafe lifecycle methods were found within a strict-mode tree:
>     in StrictMode
> componentWillReceiveProps: Please update the following components to use static 
> getDerivedStateFromProps instead:

> react-dom.development.js:506 Warning: Legacy context API has been detected within a strict-mode tree: 
>     in StrictMode
> 
> Please update the following components:

**Comment by probablyup** [comment] 2018-12-06 21:46
We don’t use cWM in v4

**Comment by sag1v** [comment] 2018-12-06 21:47
@42shadow42 I think it would be better to open a separate issue for "Unsafe lifecycle methods" as this issue is mostly focused on `findDOMNode`.

**Comment by probablyup** [comment] 2018-12-06 21:48
We don’t use any unsafe lifecycle methods... he’s probably looking at v3 or
something

**Comment by sag1v** [comment] 2018-12-06 21:52
@probablyup I think the same, but a new issue (with the detailed initial template) may discover that, or maybe a closed issue about this topic will pop up on people's search if they have the same issue instead of it being on the bottom of this long and unrelated issue. just my 2 cents

**Comment by gaearon** [comment] 2018-12-06 22:14
Big thanks to @Fer0x for actually [explaining](https://github.com/facebook/react/issues/14357#issuecomment-444045535) what `styled-components` is doing with `findDOMNode` and *why*  — which is missing from this thread and made it difficult to respond to it initially. For future cases where you feel React is getting in your way I’d appreciate if you could provide similar explainers. This was very helpful.

>That's issue can be reproduced when custom React component is passed to styled() factory. In this case styled-components create className and pass it as prop to that custom React component. If component is not supposed of supporting className prop, warn of incorrect usage should be thrown.
So, in styled-components code, we need to find DOM node with generated className.

This approach seems a bit flawed to me in general because it seems to me that should be valid for a child component to *not render* the node with a class name (e.g. due to some early exit condition) and render it later. So it’s a bit of a heavy handed assumption that I *must* render that `className` regardless. 

Of course I did not design SC API and don’t have context on your decisions — I’m just looking from the point of view of a React component user. I generally expect that I can add `return null` into any component at any point in time and it shouldn’t cause me to see warnings. It’s a valid React feature.

```js
function Story({ className, story }) {
  if (story.isLoading) {
    return null; // This shouldn't cause a warning but seems like it would?
  }
  return <div className={className} />;
}
```

Fragments present a different issue (`findDOMNode` will only find the first node) that can also cause misleading warnings. So I think we can agree the warning seems to stand in the way of using normal React features somewhat.

Now, maybe the mistake is very common and so the benefits of having a warning outweigh the false positives and other issues. I would argue that the issue might be inherent to this API that “pretends“ to override component’s styles with `styled(Button)` and might give people the wrong mental model. But maybe that’s also part of the appeal of styled components — it feels more familiar than e.g. CSS-in-JS, and `styled(Button)` kinda feels like selector overrides.

One thing you could do is to make `className` an object with custom `toString` that returns a class name in DEV. React would (AFAIK) `toString` it before rendering. That would let you detect that `toString` was called. If it's not called within some timeout, you could warn in DEV. In production you could still use strings.

Yet another thing you could is to add a unique identifier to the `className` in DEV. (So, effectively, it would be two class names — one for the component and one for the instance — separated by spaces.) Then you could do the `document.querySelector` check suggested in https://github.com/styled-components/styled-components/issues/2154#issuecomment-444329164 without worrying about conflicts. Seems like that would be the easiest fix unless I’m missing something.

Hope that helps. As always, we’re happy to support you and try to find solutions to problems you encounter. But since we don’t use `styled-components` it’s difficult to understand the challenges you’re running into until we get a nice explanation like https://github.com/facebook/react/issues/14357#issuecomment-444045535. Instead of arguing whether the API needs to be brought back or not I think it would be much more productive if we always frame a discussion about a specific use case you need to solve.

**Comment by probablyup** [comment] 2018-12-06 22:16
> This approach seems a bit flawed to me in general because it seems to me that should be valid for a child component to not render the node with a class name (e.g. due to some early exit condition) and render it later. So it’s a bit of a heavy handed assumption that I must render that className regardless.

That's a valid criticism. It's meant to be a dev-time warning that the consumer can opt out of via prop flag.

**Comment by liuyangc3** [comment] 2018-12-09 07:33
in some case, it has to use `getBoundingClientRect` to get postion of a DOM element, 
so it need to use `findDOMNode` to get DOM element from a react component.

**Comment by OzairP** [comment] 2018-12-12 16:56
@liuyangc3 sounds like a use case for refs or portals. Regardless you should make your use case known on the React issue [here](https://github.com/facebook/react/issues/14357)unless you're talking about StyledComponenets which it doesn't look like you are.

@probablyup would you mind addressing Dan's proposals on replacing the implementation of class name forwarding? Which one would be the best in terms of SC?

**Comment by adrianhelvik** [comment] 2018-12-20 13:10
This would solve 95% of use cases.

```
if (typeof ChildComponent === 'string')
  nextProps.ref = ref
else
  ref(ReactDOM.findDOMNode(this))
```

**Comment by manspaniel** [comment] 2019-01-30 02:06
Getting this when trying to use styled components within WordPress v5's new editor, which uses React, since their editor is wrapped in StrictMode 🤦‍♂️

Until either WP remove StrictMode, or styled-components is updated to use refs, I've been using this little hack to prevent the error from taking up 50 lines of my console each reload. Obviously not a nice one, but it works. Just thought I'd share 👍

```javascript
;(() => {
  const oldLogError = console.error
  console.error = function(...args) {
    if (typeof args[0] !== 'string' || args[0].indexOf('is deprecated in StrictMode') === -1) {
      oldLogError.apply(console, args)
    }
  }
})()
```

**Comment by OzairP** [comment] 2019-01-30 02:22
@manspaniel if you don't want deprecation warnings then you shouldn't use StrictMode. That defeats the whole purpose.

**Comment by manspaniel** [comment] 2019-01-30 03:42
@OzairP I understand. As I mentioned, WordPress' Gutenberg editor is wrapped in a `React.StrictMode`, and I'm interfacing with it by passing it components to render. I have no control over the top-half of the app and so cannot "not use StrictMode".

Like I said, it's a hack so that I can continue working without interruption and I thought it might be useful for others in a similar situation.

**Comment by OzairP** [comment] 2019-01-30 05:51
@manspaniel yikes! Thought you were developing it!

**Comment by probablyup** [comment] 2019-04-20 17:37
I'm open to a PR just removing this dev check

**Comment by rwieruch** [comment] 2019-05-28 07:36
I ran into this warning with styled-components 4.2. 

Is this possible or is it something on my side?

**Closed** 2019-05-29 08:15 UTC

**Comment by f22hd** [comment] 2020-04-19 10:49
Disabling strict mode will remove the warning messages, 
You can find the tag in index.js file .

**Comment by gaearon** [comment] 2020-04-19 22:15
Update your `styled-components`.

**Comment by Preshonyee** [comment] 2020-04-23 17:17
> Update your `styled-components`.

I'm actually using `styled-components` and I have the latest version of `styled-components` installed. 
Although, I'm also using `antd` design library and I particularly get this error when I render a `button` component. I'm still looking into this.

Here's the error I'm getting below:

`   
    
    index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an 

    instance of Wave which is inside StrictMode. 

    Instead, add a ref directly to the element you want to reference. 

    Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

    in button (created by Context.Consumer)

    in Wave (created by Context.Consumer)

    in Button (at primaryButton.tsx:46)

    in div (created by styled.div)

    in styled.div (at primaryButton.tsx:45)

    in PrimaryButton (at login.tsx:57)

    in div (created by FormItemInput)

    in div (created by FormItemInput)

    in div (created by Context.Consumer)

    in Col (created by FormItemInput)

    in FormItemInput (created by FormItem)

    in div (created by Context.Consumer)

    in Row (created by FormItem)

    in FormItem (at formItem.tsx:12)

    in FormItem (at login.tsx:56)

    in form (created by ForwardRef(Form))

    in ForwardRef(Form) (created by ForwardRef(InternalForm))

    in SizeContextProvider (created by ForwardRef(InternalForm))

    in ForwardRef(InternalForm) (at forms.tsx:17)

    in Forms (at login.tsx:30)

    in div (created by styled.div)

    in styled.div (at layouts.tsx:9)

    in Layouts (at login.tsx:23)

    in Login (created by Context.Consumer)

    in Route (at App.tsx:17)

    in Switch (at App.tsx:16)

    in Router (created by BrowserRouter)

    in BrowserRouter (at App.tsx:13)

    in App (at src/index.tsx:9)

    in StrictMode (at src/index.tsx:8)
`

**Comment by rogemus** [comment] 2020-05-15 11:01
@gaearon Sadly updating `styled-components` to `5.1.0` didn't resolve this issue. 

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefFindNode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in button (created by Button)
    in RefFindNode (created by Ref)
    in Ref (created by Button)
    in Button (created by LoginForm)
    in form (created by Form)
    in Form (created by LoginForm)
    in LoginForm (created by Login)
    in div (created by styled.div)
    in styled.div (created by Login)
    in div (created by styled.div)
    in styled.div (created by Login)
    in div (created by styled.div)
    in styled.div (created by Login)
    in Login (created by LoginView)
    in LoginView (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in App
    in ApolloProvider
    in StrictMode
```

**Comment by rogemus** [comment] 2020-05-15 11:03
@probablyup Can we reopen this issue or do you want me to create new one?

**Comment by kitten** [comment] 2020-05-15 14:18
@rogemus Are you sure this warning is coming from `styled-components`? From that stack it could also be `RefFindNode` going off its name 😅

**Comment by probablyup** [comment] 2020-05-15 14:20
Yeah it's definitely not s-c, we don't use `findDOMNode` anymore

**Comment by kfekairi** [comment] 2020-05-22 23:04
> > Update your `styled-components`.
> 
> I'm actually using `styled-components` and I have the latest version of `styled-components` installed.
> Although, I'm also using `antd` design library and I particularly get this error when I render a `button` component. I'm still looking into this.
> 
> Here's the error I'm getting below:
> 
> `
> 
> ```
> index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an 
> 
> instance of Wave which is inside StrictMode. 
> 
> Instead, add a ref directly to the element you want to reference. 
> 
> Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
> 
> in button (created by Context.Consumer)
> 
> in Wave (created by Context.Consumer)
> 
> in Button (at primaryButton.tsx:46)
> 
> in div (created by styled.div)
> 
> in styled.div (at primaryButton.tsx:45)
> 
> in PrimaryButton (at login.tsx:57)
> 
> in div (created by FormItemInput)
> 
> in div (created by FormItemInput)
> 
> in div (created by Context.Consumer)
> 
> in Col (created by FormItemInput)
> 
> in FormItemInput (created by FormItem)
> 
> in div (created by Context.Consumer)
> 
> in Row (created by FormItem)
> 
> in FormItem (at formItem.tsx:12)
> 
> in FormItem (at login.tsx:56)
> 
> in form (created by ForwardRef(Form))
> 
> in ForwardRef(Form) (created by ForwardRef(InternalForm))
> 
> in SizeContextProvider (created by ForwardRef(InternalForm))
> 
> in ForwardRef(InternalForm) (at forms.tsx:17)
> 
> in Forms (at login.tsx:30)
> 
> in div (created by styled.div)
> 
> in styled.div (at layouts.tsx:9)
> 
> in Layouts (at login.tsx:23)
> 
> in Login (created by Context.Consumer)
> 
> in Route (at App.tsx:17)
> 
> in Switch (at App.tsx:16)
> 
> in Router (created by BrowserRouter)
> 
> in BrowserRouter (at App.tsx:13)
> 
> in App (at src/index.tsx:9)
> 
> in StrictMode (at src/index.tsx:8)
> ```
> 
> `

i have the same problem, is there any solution ?

**Comment by probablyup** [comment] 2020-05-22 23:05
It’s. Not. In. The. Library. Anymore.

Wherever the issue is it’s not us.

Sent via mobile, please excuse brevity and/or typos.
________________________________

**Comment by kitten** [comment] 2020-05-24 14:15
If you're seeing this, you can check findDOMNode` across our codebase, and you'll see, _it does not occur_ there anymore. Hence, please check your other dependencies or your own code instead. It's fine to ask for help (preferably on Spectrum or another help platform though) but posting a stack/console output won't lead to any new revelations or any ability for anyone else to help you unfortunately 😅
