### ISSUE TITLE
Default Props not working when using withTheme in HOC in class based component

### ISSUE THREAD

**Issue by rahulrsingh09** [styled-components/styled-components#3173] opened 2020-06-14 14:25 UTC
I have a simple class based component in React which uses withTheme HOC.

```
static defaultProps: Partial<CompProps> = {
 someProp1:'hello',
 someProp2:'hello2'
}
```

when i donot use the withTheme HOC the default props works fine, But as soon as i add the withTheme HOC it starts giving error in the consuming component and tells me to define all the props even though it has default props defined .

```
static defaultProps: Partial<CompProps> = {
 someProp1:'hello',
 someProp2:'hello2',
 theme:DEFAULT_THEME
}
```
Is there any workaround for this to make default props work with withTheme provider

I think this is the most relatable issue but is it fixed or we have any solve 
https://github.com/styled-components/styled-components/issues/1428

**Comment by rahulrsingh09** [comment] 2020-07-18 14:06
@probablyup any update on this issue ?

**Comment by amhorton** [comment] 2020-08-08 08:06
hello!

i hope this is the right place to post this type of thing -- feel free to delete if it's not!

i'm new to the project and was hoping to contribute (since it's a blast to use!), so i started browsing issues and saw that this one was earmarked for beginners. i've done a bit of digging and wanted to surface my findings here.

i'm not super familiar with typescript, for the record, but i tried some things out in a test project and it seemed like if we just attached the `defaultProps` of the wrapped component to the returned component (in `withTheme.js`), it satisfies typescript and allows us to compile. however, flow does not like this one bit! here's an issue i found about the topic -- it was created in feb 2019 but it's still getting comments to this day...

https://github.com/facebook/flow/issues/7467

with regards to this issue, we may be in an awkward position between flow and typescript. of course, it's also possible that i'm missing something. if anyone sees a potential way forward for this, i would be very interested to hear it!

**Comment by rahulrsingh09** [comment] 2020-08-08 08:16
@amhorton can you please ellborate this point 
`it seemed like if we just attached the defaultProps of the wrapped component to the returned component (in withTheme.js)`

even thought it might only work for TS

**Comment by amhorton** [comment] 2020-08-08 14:38
@rahulrsingh09 sure!

what i was saying was that maybe things would work out if you just added `defaultProps` as a static on the component we return from `withTheme`... this violates rules in `flow` but is fine in a `typescript` environment. i anticipated that you might try to do this yourself (i.e., within your own component file) so i tried it out and unfortunately it still fails to compile. typescript want either a function definition with default arguments, or a class definition with `defaultProps` -- it sees neither, so it gets mad.

the only workaround i have gotten work from the level of the hoc consumer is something like this:

```
import React from 'react';
import PropTypes from 'prop-types';
import { withTheme } from 'styled-components';

//...

class MyComponent extends React.Component<TestThemeProps> {
    static defaultProps = {
        content: "hey it content",
        theme: { red: "default red" },
    }
    //...
}

const WrappedComponent = withTheme(MyComponent);

class WrappedClass extends React.Component<MyComponentProps> {
    static defaultProps = MyComponent.defaultProps;

    render() {
        return <WrappedComponent {...this.props} />
    }
}

export default WrappedClass;
```

this works in that it gets typescript to compile and the default props are respected. this approach does have some problems though. the first is that it's pretty verbose! the second has to do with `ref`... it wont work properly if you use this approach. so if you define some ref in `TestThemeComponent`, and then pass a `ref` in a consuming component expecting to be able to use the `ref` inside of `TestThemeComponent` to do something, it won't work. this is why the code in `styled-components` uses `React.forwardRef`.

so, in essence, there are workarounds to get this code to compile how and work how you'd expect in most cases, but i don't recommend standardizing this approach, and if you use it you should probably at least document the limitations with `ref`. your mileage may vary though! and it certainly wouldn't work to standardize this approach in `styled-components` itself.

**Comment by rahulrsingh09** [comment] 2020-08-08 15:27
Yes , i think the ref kind of messes it up, i would much rather define all the props in the component  rather than just for the sake of defaultProps try and go without the ref as functionality, Looking for some proper fix from styled components soon ..

**Comment by sarathps93** [comment] 2020-09-29 15:21
@probablyup Can I take this up?

**Comment by kitten** [comment] 2020-11-19 17:27
The canonical solution is to add `defaultProps.theme` to the output of `withTheme`. The output of it is a _new component_ so it has separate default props. That's indeed the right implementation and we even do this on purpose, so I'll close this as expected behaviour.

You can see the hoisting here: https://github.com/styled-components/styled-components/blob/28b4c28f1ebd1ea5a34717df2fe49634461285b1/packages/styled-components/src/hoc/withTheme.js#L35

**Closed by kitten** 2020-11-19 17:27 UTC
Labels: bug :bug:, good first issue :octocat:, help wanted :sos:
