### ISSUE TITLE
dynamically changing a styled component property re-renders whole page - Reopened

### ISSUE THREAD

**Issue by mimiqkz** [styled-components/styled-components#3345] opened 2020-12-08 19:53 UTC
The problem is described in https://github.com/styled-components/styled-components/issues/356 since 2017, which hasn't been solved. 
The author of the problem suggested to reopened the issue due to lack of response or any solution at all.

**Comment by mimiqkz** [comment] 2020-12-08 19:54
For me, the problem happens when I try to change the property as followed

```
const Switch = styled.div<{isChecked: boolean}>`
  position: relative;
  min-width: 34px;
  width: 34px;
  height: 17px;
  cursor: pointer;
  background-color: ${ifProp('isChecked', palette('primary20'), palette('dark20'))};
  border-radius: 100px;

  span {
    position: absolute;
    transform: ${ifProp('isChecked', 'translateX(17px)', 'translateX(0px)')};
    height: 13px;
    width: 13px;
    left: 2px;
    bottom: 2px;
    background-color: ${ifProp('isChecked', palette('primary'), palette('dark50'))};
    transition: transform 0.4s;
    border-radius: 50%;
  }
`
```

**Comment by kitten** [comment] 2020-12-09 01:56
Without a reproduction it's unlikely that it will be looked into, e.g. a CodeSandbox or something that reliably reproduces it in an environment.

Thank you for creating a new issue. Since 2017 the CSS insertion pipeline has already changed twice. So the original issue is unlikely to apply. What's curious is that it does seem to be WebKit related, but no one bothered to give any hint of a reproduction or trace. (Debug and share your info, if you read this and are also affected please)

Now, I know the original issue always said "render". This is a misnomer and means nothing, because it can't be a React render technically, so I assume it means some kind of browser render. Even then, the question is: how would it be styled-components' fault and not an individual browser's if an entire page is repainted in response to a CSSOM change?

So, "redender" without explanation makes no sense. Repaint is what was meant maybe? Who knows, I guess.

Pending information and a reproduction, I'll close this if it gets inactive again though.

**Comment by mimiqkz** [comment] 2020-12-15 11:42
@kitten it has been mentioned here https://github.com/facebook/create-react-app/issues/5224

**Comment by kitten** [comment] 2020-12-15 11:47
@mimiqkz Sorry, but this seems entirely unrelated. It also doesn't seem to contain any information or comments related to `styled-components` apart from a small misunderstanding of how it works 😅 So given the staleness of this and the misunderstanding, until this issue is updated with some information (as per above) I'll go ahead and close it, but I'm happy to revisit any questions here as they come up

**Closed by kitten** 2020-12-15 11:47 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:

**Comment by mimiqkz** [comment] 2020-12-15 12:15
@kitten  Is this me or have you not read the discussion they're having about `style-components`?
![image](https://user-images.githubusercontent.com/19761446/102213856-42838500-3ecf-11eb-9f3b-7fbc0d1fa54b.png)

**Comment by kitten** [comment] 2020-12-15 12:18
This is inaccurate and not a bug. We use CSSOM which isn't rerendering anything (which is a React term), it also doesn't cause any page updates (which is the Browser term). What _new_ styles cause is a style recalculation but not even a full one.

We use CSSOM because it causes a _partial_ style recalculation of only what has been added to the style sheet for a specific `StyledComponent` at a time. If you open a page using `styled-components` you can for instance see how that happens. We also have benchmarks related to this and this is a part of the library that has been heavily optimised and would be the first place to also receive future optimisations

**Comment by mimiqkz** [comment] 2020-12-15 13:37
For most of us, it only re-rendering after the time _first time_ dynamically changing the style, after that nothing being re-render. By re-render we don't mean it refresh reload the whole page, but it repainted the whole page again, causing a glitch. It doesn't happen on hover, focus, but just when u change it for example on scroll or on click. For example, it happens [here](https://vordur.is/fjolskyldan-og-fasteignin/brunatrygging), when you toggle the card or when you scroll down

**Comment by kitten** [comment] 2020-12-15 13:45
@mimiqkz What am I looking at here? Are you referring to the anymation in the inline styles, i.e. `width: 100%; opacity: 1; transform: translateY(0px) scale(1);`? We don't recommend to run JS-driven animations in styled-components directly as it'd insert a new rule for each change, which then indeed gets rather expensive.

I'm also not sure if this particular animation even needs to be JS-driven. That being said, browsers recalculate styles and repaint. This process can be very different from browser to browser, but you won't necessarily see a whole-page repaint if the element that is being changed happens to be accelerated. However, if you're affecting an element dynamically that contributed to the layout (so this related to "cummulative layout shift") the calculation and layout repaint will affect potentially more than just that element. This is pretty normal.

I can't quite explain to you when and why this happens when you switch to inline styles; in the case above what I can tell you is that values that change often are better kept in line styles or CSS variables, since the browser otherwise has to recalculate a lot of styles and process a large number of rules (whereas with inline styles it can apply more selective tricks when those change)

That being said this comes down to individual browser behaviour. And if you measure and don't see a performance problem (note; using animations as dynamic interpolations in styled-components would still be an anti-pattern) then don't worry about it and let the browser do its work 😅

**Comment by brunoandradebr** [comment] 2021-03-19 23:42
I was facing the same problem. In my case, I was toggling component className using element ref.current.classList.add and remove as well in effect state. And for some reason, It was "reseting" my component. So, setting inline style solved. BUT, if I toggle component className like this <.... className={`defaultClass ${props.isOpen ? 'open' : 'close'}`>... solved as well. 

The only problem i'm facing right now is that, css animation don't reset when you toggle className as the second one I mentioned above. 

But I'm happy with this research, an entire day just for that lol

**Comment by brunoandradebr** [comment] 2021-03-20 16:18
**"The only problem i'm facing right now is that, css animation don't reset when you toggle className as the second one I mentioned above."**

I found what makes animation play again when component props changes. I was defining animation inside component style, like : 

const myComponent = styled.div`
 @keyframes fade-in {
    from : {.... }
    to: {...}
 }
 
 &.open { animation : fade-in .... }
 &.close { animation: fade-in .... reverse }
 
`

BUT, found that styled handles css animation with a custom : 
import styled , {keyframes } from 'styled-components'

instead, this is the right way : 

const fadeIn = keyframes`
    from {....}
    to {...}
`

const myComponent = styled.div`
 &.open { animation : ${fadeIn} .... }
 &.close { animation: ${fadeIn} .... reverse } 
`

Hope this can help someone else 👍

**Comment by Fuzzypeg** [comment] 2022-06-27 00:28
I had the same problem as others described, and I solved it by passing the prop `type="button"` to the styled button.

I got the same undesired behaviour, causing a page refresh, with the code:
```
    <button onClick={onClick}>Click me</button>
```
This shows a linting warning, though, as `type` is missing. Fix the linting as follows, and there's no longer a page refresh:
```
    <button onClick={onClick} type="button">Click me</button>
```
Making a styled button prevents the linting warning, but `type` is clearly still needed as a prop.
