### ISSUE TITLE
"Warning: Unknown props" when wrapping an external component

### ISSUE THREAD

**Issue by kitze** [styled-components/styled-components#305] opened 2016-12-10 09:54 UTC
I have this styled-component:
```js
import FontAwesome from 'react-fontawesome';

export const Icon = styled(FontAwesome)`
  font-size: 25px;
  margin-bottom: 3px;
  ${props => props.active && `color: ${props.colors.brand}`}
`;
```

Which is wrapping ```FontAwesome``` which is an external component.

I'm passing ```active``` and ```colors``` as props but the component complains that they are unknown.

![](https://i.imgur.com/ByNSMM5.png)

**Comment by vdanchenkov** [comment] 2016-12-10 10:20
Styled components pass props to the underlying component by design. You would get same results with 
```jsx
<FontAwesome active={} colors={}/>
```

Problem is that FontAwesome passes all unknown props to the DOM element. 

One solution is to filter props manually
```jsx
export const Icon = styled(({ active, colors, ...rest }) => <FontAwesome {...rest} />)
```

**Comment by k15a** [comment] 2016-12-10 10:53
How about something similar to this: https://github.com/styled-components/styled-components/issues/291#issuecomment-265292990

```JS
import styled from 'styled-components'
import FontAwesome from 'react-fontawesome'

export const Icon = styled(FontAwesome)`
  font-size: 25px;
  margin-bottom: 3px;
  ${props => props.active && `color: ${props.colors.brand}`}
`

Icon.passProps = false
```

**Comment by diegohaz** [comment] 2016-12-10 14:50
@k15a 

I like it, but most third party components need some custom props. It should be something like this:
```js
export const Icon = styled(FontAwesome).passProps({ active: false, colors: false })``
```

**Comment by k15a** [comment] 2016-12-10 15:56
You could also combine both and allow false to pass no props and a object which will whitelist / blacklist (which one should be decided) props.

**Comment by diegohaz** [comment] 2016-12-10 16:39
That `passProps` would be very useful. I currently have some duplicated code with @vdanchenkov's solution

e.g. A `Button` that renders a `MenuButton` from [react-aria-menubutton](https://github.com/davidtheclark/react-aria-menubutton) or a `Link` from [react-router](https://github.com/ReactTraining/react-router)
```js
const StyledMenuButton = styled(({ disabled, transparent, light, kind, size, ...props }) =>
  <MenuButton {...props} />
)`${styles}`
const StyledLink = styled(({ disabled, transparent, light, kind, size, ...props }) =>
  <Link {...props} />
)`${styles}`
```

**Comment by diegohaz** [comment] 2016-12-10 16:42
Another issue complaining about it: #135

**Comment by k15a** [comment] 2016-12-10 16:46
I will probably look into this and #291 tomorrow if nobody else will solve this.

**Comment by mxstbr** [comment] 2016-12-13 10:11
I think we will need to get rid of our attributes whitelist anyway one day, so we'll need an API like is being discussed here but that requires a lot more considerations than just solving this one use case. 

I'll close this issue for now as I don't think we'll do this in the very near future, but I appreciate all the comments here and we'll definitely use this as a basis for the next discussion about this!

**Closed by mxstbr** 2016-12-13 10:11 UTC

**Comment by aesopwolf** [comment] 2016-12-15 04:44
@mxstbr I know it's only been 2 days since you closed this, but I'd really like to open it up back up.

What do you think about [encouraging users to pass a prop called inputProps separately, and apply it instead](https://github.com/Hacker0x01/react-datepicker/issues/517#issuecomment-230119718)?

For example:

```jsx
render() {
  const { theme } = this.state

  return <Component theme={theme} {...this.props.inputProps} />
}
```

**Comment by manolkalinov** [comment] 2016-12-23 13:46
I read the thread, but am still at a loss as to whether something like FontAwesome can be used with styled-components right now. And if yes, is there an example piece of code I can look at?

**Comment by TimMeade** [comment] 2017-01-08 18:08
Just adding my bit to this.  Would be very nice to have.

I created a <NavItem/> which is a styled link.  I was using a prop to identify to put a left bar on it:

  border-left: 1px solid ${props => props.leftBar ? darkBorder : 'transparent'};

but the underlying link is kicking out the unknown props leftBar warning.  

I guess I'll just create several NavItem components styled each way to clear the warnings.

**Comment by barbalex** [comment] 2017-01-18 21:32
This is completely erroring up the console in my project as I need to pass many props to influence styling :-(

@vdanchenkov: I don't get how your proposal would work to style a complicated component that has a whole bunch of children:  In this case I would have to define the entire jsx outside of the render component? Or did I get something wrong?

**Comment by vdanchenkov** [comment] 2017-01-18 23:13
@barbalex My proposal helps to overcome problematic components putting all the props on the root dom element. Like this `const Comp = ({props}) => <div {...props}>{props.text}</div>`. If you have control over components source code - best way is to not design components this way.

Do not do `<div {...props}/>` and there will be no need in this workaround.

**Comment by barbalex** [comment] 2017-01-19 14:40
o.k., got it: the reason @vdanchenkov 's solution did not work for me was:

- object spread does not work when stage-0 is preset. I also needed to preset es2015 and install "transform-es2015-destructuring" and "transform-object-rest-spread" plugins
- I am using [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate). It includes [tcomb](https://github.com/gcanti/tcomb) which would not accept the way @vdanchenkov 's solution is written

After making babel happy and uninstalling tcomb it works nicely now.

Thanks all for a great tool and your help!

**Comment by barbalex** [comment] 2017-01-19 14:45
oh, just in case other people want to see a complete example (which I missed):

    const Field = styled(({ isPrintPreview, children, ...rest }) => <div {...rest}>{children}</div>)`
      height: ${(props) => (props.isPrintPreview ? '17px' : 'auto')};
      input {
        font-size: ${(props) => (props.isPrintPreview ? '10px' : 'inherit')};
      }
    `

**Comment by cchanna** [comment] 2017-01-23 07:27
For people frustrated with the boilerplate, here's a helper function I knocked out:
```
const props = (component, ...properties) => {
  return (props) => {
    let result = {};
    const keys = Object.keys(props);
    for (let i=0; i < keys.length; i++) {
      const key = keys[i];
      if (!properties.includes(key) && key != 'children') {
        result[key] = props[key];
      }
    }
    return React.cloneElement(component, result, props.children);
  };
}
```
Which you can use like this
```
const StyledDiv = styled(props(<div/>, 'primary', 'active'))`
  background: ${props => props.primary ? red : blue};
  color: ${props => props.active ? white : transparent};
`
```

**Comment by rjhilgefort** [comment] 2017-02-07 20:37
This is a bit of a bummer. Thanks to @vdanchenkov and @barbalex for your examples on a work around. While it works, it promotes having to ignore `eslint`'s `no-unused-vars` rule. I really dislike having to make exceptions every time I need to leverage this pattern.

This is a pretty basic use case when considering `react-router`'s `Link` component- is there a less hacky way to work around the issue? For anyone curious, here's another example (which is exactly @barbalex's example, but using the `Link` component):

```js
// eslint-disable-next-line no-unused-vars
const FooterLink = styled(({ left, right, children, ...rest }) => (
  <Link {...rest}>{children}</Link>
))`
  display: inline-block;
  ${({ left }) => (left ? 'float: left;' : '')}
  ${({ right }) => (right ? 'float: right;' : '')}
`;
```

**Comment by diegohaz** [comment] 2017-02-07 20:39
@rjhilgefort Try this: https://github.com/bryanrsmith/eslint-plugin-no-unused-vars-rest

**Comment by rjhilgefort** [comment] 2017-02-07 20:45
@diegohaz thanks for the heads up. I still think it's a bit strange for this to be the accepted pattern for situations like this.

**Comment by jole78** [comment] 2017-02-20 07:23
While we're waiting for v2 (which will hopefully solve this) I've used this approach which works fine and doesn't pollute the code so much I think. I'll share it so other can maybe benefit.
It used lodash omit to "strip" the custom props (in the example 'direction' and 'align-items') used by the styled component and then happily send the other ones down the chain.

```javascript
import React from "react";
import styled from "styled-components";
import {omit} from 'lodash';

const FlexBox = styled((props) => <div {...omit(props, FlexBox.OmitProps)} />)`
	display: flex;
	flex-direction: ${props => props.direction};
	align-items: ${props => props['align-items']};
`;

FlexBox.OmitProps = [
    'direction',
    'align-items'
]

FlexBox.defaultProps = {
    direction: "row",
    'align-items': "stretch"
};

FlexBox.propTypes = {
    direction: React.PropTypes.oneOf(["row", "column"]),
    'align-items': React.PropTypes.oneOf(["flex-start", "flex-end", "center", "baseline", "stretch"])
};

export default FlexBox;
```

**Comment by mqklin** [comment] 2017-02-21 10:14
@rjhilgefort you don't need that plugin: http://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings

**Comment by mqklin** [comment] 2017-02-21 12:43
@rjhilgefort you can use http://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings (when it will be fixed https://github.com/eslint/eslint/issues/8119#issuecomment-281332156)

**Comment by timscott** [comment] 2017-05-02 16:05
Here's a reusable implementation of the workaround offered by @diegohaz and others:

```javascript
const betterStyled = (WrappedComponent, {swallowProps = []} = {}) => {
  const Component = ({children, ...props}) => {
    swallowProps.forEach(propName => {
      delete props[propName];
    });
    return <WrappedComponent {...props}>{children}</WrappedComponent>;
  };
  return styled(Component);
};
```

Used like so:

```javascript
const Card = betterStyled(Paper, {swallowProps: ['samplesMode']})`
  margin: 0 10px 10px 0;
  padding: 10px;
  flex-flow: ${({samplesMode}) => samplesMode && 'column'};
`; 
```

**Comment by chrisknu** [comment] 2017-05-03 15:48
@jole78 omit works well and is extensible!

**Comment by MatthieuLemoine** [comment] 2017-05-04 15:10
Using [Proxy]() you can do something like that in a ```styled.js``` file : 

```javascript
import React from 'react';
import styled from 'styled-components/native';
import * as RN from 'react-native';

const handler = {
  // Handle styled.tag
  get : (target, name) => (...args) => (...omitProps) => {
    const Wrapped = ({ children, ...props }) => {
      omitProps.forEach(prop => delete props[prop]);
      const WrappedComponent = RN[name];
      return <WrappedComponent {...props}>{children}</WrappedComponent>;
    };
    return target(Wrapped)(...args);
  },
  // Handle styled(Component)
  apply : (target, _, [WrappedComponent]) => (...args) => (...omitProps) => {
    const Wrapped = ({ children, ...props }) => {
      omitProps.forEach(prop => delete props[prop]);
      return <WrappedComponent {...props}>{children}</WrappedComponent>;
    };
    return target(Wrapped)(...args);
  },
};

const proxy = new Proxy(styled, handler);

export default proxy;
```
And then use ```styled``` instead of ```styled-components``` :

```javascript
import styled from 'styled';

const Container = styled.View``;
```

**Comment by philpl** [comment] 2017-05-04 15:15
I think this thread has long reached its limit. The rest of the discussions / suggestions should become - albeit the specific title - part of #439.

There's several proposals on how to solve the whitelist props problem for both HTML and custom components in there, and it would be much appreciated if some more input would go there instead. Cheers!
