### ISSUE TITLE
Improve browser/server detection for static caching

### ISSUE THREAD

**Issue by ghost** [styled-components/styled-components#1417] opened 2018-01-09 18:24 UTC
## Version
styled-components: > 2.2.0

I've just updated my existing project from 2.0.0. to 2.4.0. and noticed that the SSR CSS tags / rules are not generated correctly anymore. It seems that the rules for the first level components are generated correctly, but all the rules for sub (nested) components are not created anymore.

This is the relevant part of the code (mostly taken directly from the SSR documentation):
```
      const sheet = new ServerStyleSheet()
      const html = renderToString(sheet.collectStyles(
        <Router location={req.url} context={{}}>
          <App serverData={serverData} />
        </Router>,
      ))
      const css = sheet.getStyleTags()
```
I did some testing and this code works perfectly up to 2.2.0. Has something changed in 2.2.1 that causes this issue?

**Comment by mxstbr** [comment] 2018-01-09 18:53
Unsure why this wouldn't work, we're running 2.4.0 and SSR perfectly fine. Which part isn't generated anymore? Nothing?

**Comment by pixelscripter** [comment] 2018-01-09 19:15
Nothing is generated for deeper nested components. Pseudo code:

```
<App>
  <Navigation>
    <NavList>
      <NavListItem key="navlink1">
        {getLink('home')}
      </NavListItem>
      ...
    </NavList>
  <Navigation>
</App>
```
Styles for Navigation and NavList are generated but nothing for NavListItem.

**Comment by JonnyBurger** [comment] 2018-01-09 19:20
Funny, I just experienced the same issue at the same time... I located the exact version number where it seems to break and it looks like in the 2.2.0 --> 2.2.1 update it started breaking. Going to dig now and see if I can spot the bug.

**Comment by JonnyBurger** [comment] 2018-01-09 19:49
OK, I found the exact commit where it started breaking:

https://github.com/styled-components/styled-components/commit/5e404c87c686704a31e7c45f0449124eb6225e18

It tries to cache the class name in the browser using `typeof document !== 'undefined'`, but for some reason I have a `document` variable in node.js, so my node is detected as a browser...

Also when you start the server, it works the first time. Only when I reload, the bug is happening. Same symptoms? @pixelscripter

**Comment by JonnyBurger** [comment] 2018-01-09 20:05
OK, I figured it out!

I have set `global.document` in my Node.js. (I need to in order to use some draft-js conversion helper method on the server) 
There is a check [here](https://github.com/styled-components/styled-components/blob/5e404c87c686704a31e7c45f0449124eb6225e18/src/models/StyleSheet.js#L40) that then detects my Node as a browser.

It's not a bug in styled-components, but the browser/node detection could be improved.

**Comment by pixelscripter** [comment] 2018-01-09 20:06
Exactly the same symptoms @JonnyBurger. And guess what: I was using the document global in node as well (global.document.URL = req.getUrl()) in order to be able to use document.URL on both the server and client. Removed it and Presto it started working for me, so thanks a lot! Maybe a better way of checking if we are on the client can be used?

**Comment by pixelscripter** [comment] 2018-01-09 20:08
So yes, posted my previous comment at the same time, reaching the same conclusion :)

**Comment by mxstbr** [comment] 2018-01-09 20:36
That's definitely not ideal: A PR that adds more reliable detection would be much appreciated! :pray:

**Comment by probablyup** [comment] 2018-01-09 20:51
I’m not sure there will be a more reliable way... especially across other Node-like environments. Those globals really shouldn’t be set on the server.

**Comment by pixelscripter** [comment] 2018-01-09 21:23
I agree that those globals should not be overwritten, but a bit more thorough check could still be used like f.e.
```
const stylesCacheable = !!(
  (typeof window !== 'undefined' &&
  window.document && window.document.createElement)
);
``` 
PS. Other things that might be helpful: Checking the process.env variable, which is Node specific, or componentDidMount, which is only ever called on the client-side.

**Comment by probablyup** [comment] 2018-01-09 22:14
I'm 👎 on this because many other libraries that have isomorphic behavior are strict as we are. If there's no `document`, there's no DOM. Monkeypatching it is a bad practice we shouldn't support.

**Comment by philpl** [comment] 2018-01-09 22:40
@schwers Any particular reason why this is in `ComponentStyle.js` btw? It'd be sufficient to check this on the creation of a styled component in their model file as well. This would mean that we wouldn't have to check at all. This would mean that this issue wouldn't occur.

But of course—regardless of this and regarding this issue—I agree with @probablyup here. There shouldn't be a more detailed check. That would only mean that another person who's using JSDom or has `window` set as well, would run into this again. We can only make this check so accurate while someone would emulate a browser environment as accurately as possible.

@JonnyBurger It's explained here why this only occurs after multiple SSR cycles: https://github.com/styled-components/styled-components/commit/5e404c87c686704a31e7c45f0449124eb6225e18#diff-4e63369bd36b3727c0e1c99cd6ef1459R33

And is this your issue? https://github.com/facebook/draft-js/issues/55#issuecomment-189978513

Correct me if I'm wrong—I haven't read through the entire thread—but a commit was pushed and the issue closed. This might mean that this isn't necessary anymore?

**Comment by mxstbr** [comment] 2018-01-10 08:15
I have to monkeypatch `window` for my SSR code as well just because some libraries that I'm using are relying on that existing. (only `window.location` though)

I think it makes sense to be a bit more thorough with that check just to make sure it's relatively certain a browser environment, it doesn't hurt us but also helps users avoid this confusion?

**Comment by schwers** [comment] 2018-01-10 16:59
@philpl I was trying to minimize how often the check happens. Keeping it with the style-sheet just seemed cleanest at the moment as it comes down to, "will this stylesheet cache my styles in the browser" (and there's already another check for server environments in `create`).

> on the creation of a styled component in their model file as well. [...] This would mean that this issue wouldn't occur.

I'm not sure I follow this bit. It seems like it would still depend on the nature of the check we're doing?

I agree with @mxstbr that a more thorough check seems helpful

**Comment by JonnyBurger** [comment] 2018-01-12 18:57
@philpl I have to set global.document because I want to use the [`draft-convert` package on the server](https://github.com/HubSpot/draft-convert/blob/1a87c21ea1135f5c84eacfcf75fef2f16a05af5a/src/convertFromHTML.js#L417).

By the way, my workaround for the moment is 
```js
let _document = global.document;
global.document = undefined;
/* Do SSR*/
global.document = _document
```

**Comment by darthtrevino** [comment] 2018-03-23 18:49
So So I have a slightly different problem, but related to the style caching. I'm using styled-components within an iframe on a PowerBI visual. These are instantiated pretty frequently as you switch around report pages. I'm using the StyleSheetManager to target my iframe and inject styles into the head. This works the first time, but when this frame re-renders the styles are gone from the iframe document, but styled-components is still holding onto the cached names.

**Comment by kitten** [comment] 2018-03-23 19:02
@darthrevino can you open a new issue please? I don’t see this being related and this is a stale issue 😉

**Comment by kitten** [comment] 2018-03-23 19:03
Addressed by https://github.com/styled-components/styled-components/pull/1599

**Closed by kitten** 2018-03-23 19:03 UTC
Labels: bug :bug:, discussion :speaking_head:

**Comment by darthtrevino** [comment] 2018-03-23 19:12
Aye aye
