### ISSUE TITLE
Styles Not Working When Built - NextJS WebComponents

### ISSUE THREAD

**Issue by seanaguinaga** [styled-components/styled-components#3441] opened 2021-03-24 19:07 UTC
After having talked to Evan about this unreleased feature:

## Unreleased

- Use `class` instead of `className` for unidentified DOM elements (better support for styling web components)

I built the version at commit: **01c17a0f** 

Where this was last enabled

it works **flawlessly** <3 when using ```npm run dev```

but when next bundles the code during build, the styles do not work for whatever reason.

I have tried using non-experimental versions of react just to see if that was breaking anything, to not avail.

When this className => class feature was being worked on, did this ever happen?

https://github.com/seanaguinaga/notes-app should be a working example

**Comment by kitten** [comment] 2021-08-09 17:40
Duplicate of #3179

**Closed by kitten** 2021-08-09 17:40 UTC
