### ISSUE TITLE
Some CSS rules are not being injected when running the app inside TestCafé

### ISSUE THREAD

**Issue by rhyek** [styled-components/styled-components#1653] opened 2018-03-31 20:38 UTC
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
 - Free Memory: 1.57 GB
 - Total Memory: 7.87 GB
 - Shell: ¯\_(ツ)_/¯
## Binaries:
 - Node: 8.9.0
 - Yarn: 1.5.1
 - npm: 5.6.0
 - Watchman: Not Found
### babel-plugin-styled-components:
 - wanted: ^1.5.1
 - installed: 1.5.1
### styled-components:
 - wanted: ^3.2.5
 - installed: 3.2.5

## Description

![image](https://user-images.githubusercontent.com/702922/38167197-8b167a36-34ee-11e8-9c75-4b22a6f3f2b8.png)

What I notice here is that the rules that are not being added are for Styled Components that have any sort of nested selectors. The font face rules are also declared in a nested manner:

```js
injectGlobal`
  html,
  body,
  body > #app,
  body > #app > div {
    height: 100% !important;
  }

  * {
    box-sizing: border-box;
    font-size: 14px;
    font-family: "Gordita Light";
  }

  @font-face {
    font-family: "Gordita";
    src: url("${require('./assets/fonts/Gordita/Gordita-Regular.otf')}");
  }

  @font-face {
    font-family: "Gordita Light";
    src: url("${require('./assets/fonts/Gordita/Gordita-Light.otf')}");
  }

  @font-face {
    font-family: "Gordita Bold";
    src: url("${require('./assets/fonts/Gordita/Gordita-Bold.otf')}");
  }

  .swal2-container * {
    font-size: initial;
  }
`
```

Btw, that is the only use of `injectGlobal` in the application. All other css rules not injected are not declared with `injectGlobal`.

I realize this might not be an issue with styled-components per se, but I'm wondering if anyone might have any insight into why this might be happening.

**Comment by rhyek** [comment] 2018-03-31 20:49
Downgrading to 3.0.1 (no `insertRule`) fixes the issue completely.

**Comment by kitten** [comment] 2018-03-31 20:52
Hiya, can you expand on which rules are not being added please? I don’t see any kind of nesting in your example above

A reproduction would be optimal but I understand that this is a little tricky in this case 😅

**Comment by kitten** [comment] 2018-03-31 20:54
Actually this is fortunately a simple issue. The font-face rules need to appear at the top of the StyleSheet. We currently only have a fix in place for import at-rules as reordering is a little trickier in the case of font-face at-rules.

So just make sure that:

- injectGlobal is called before any components are created
- font-face appears at the top of injectGlobal

Sorry for the inconvenience! We have another issue tracking this quirk, as it has some other implications too unfortunately

**Comment by rhyek** [comment] 2018-03-31 21:05
@kitten please give me a chance to respond before you close the issue. I removed the font-faces from my code and this issue is still present.

> Hiya, can you expand on which rules are not being added please? I don’t see any kind of nesting in your example above

I'll give you two examples.

```js
const Added = styled.div`
  background-color: red;
`
```
```js
const NotAdded = styled.div`
  background-color: red;
  > .child {
    background-color: blue;
  }
`
```
So the first example would create 1 rule and no other rules are "children" of it. It is correctly added. The second example would create 2 rules, neither is added.

An example from the screenshot in my original comment:

![image](https://user-images.githubusercontent.com/702922/38167536-ccf764ce-34f3-11e8-9fb6-785d18fe27ec.png)

Those have nothing to do with any font faces and none of them are added:

```js
const Main = styled.div`
  height: 100%;
  overflow-x: auto;

  > #header-body-wrapper {
    min-height: 100%;
    margin-bottom: -${footerHeight};
    background: #333132;

    &::after {
      content: '';
      display: block;
      height: ${footerHeight};
    }

    > header {
      height: 100px;
      display: flex;
      flex-direction: row;
      padding-left: 52px;
      padding-right: 30px;
      background-color: white;
      align-items: center;

      > div {
        flex: 1;
      }

      > #login {
        color: #2c3643;
        font-size: 16px;
        text-decoration: none;
      }
    }

    > #mid {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;

      &:nth-child(2) {
        padding-top: 50px;
      }

      > h1:first-child {
        height: 28px;
        margin-top: 0;
        color: #fff;
        font-size: 30px;
        line-height: 30px;
        text-align: center;
        font-weight: normal;

        & + div {
          box-sizing: border-box;
          height: 0;
          width: 60px;
          border-top: 1px solid #fff;
          margin: 0 auto 40px;
        }
      }
    }
  }

  > footer {
    height: ${footerHeight};
    background-color: #2c3643;
    display: flex;
    flex-direction: row;
    color: white;
    font-size: 12px;
    align-items: center;
    padding-left: 36px;
    padding-right: 53px;

    > nav {
      flex: 1;

      > a {
        color: white;
        text-decoration: none;

        &:not(:last-child) {
          margin-right: 1em;
        }
      }
    }
  }
`
```

**Comment by rhyek** [comment] 2018-03-31 21:11
@kitten I also removed the `injectGlobal` and the issue is still there for the other css rules.

**Comment by kitten** [comment] 2018-03-31 22:53
Alright, can you throw this onto CodeSandbox please? I’d suspect that the rules are malformed, either because of some quirk in stylis or some interpolation.

This sometimes only becomes apparent when insertRule is used, as we don’t yet have a reliable parser that can output some helpful warnings or errors.

Sorry, for closing this prematurely, but my assumptions were that this is either a problem with the input, in which case Spectrum or StackOverflow are the best places to ask for help, or a known issue, ie. what I’ve mentioned before.

Either way, a reproduction would help me to track this down as this would ensure that all variables are accounted for :) We’ve got a CodeSandbox template in the issue template (make sure to upgrade the styled-components version there)

**Comment by rhyek** [comment] 2018-04-01 00:54
Here you go: https://codesandbox.io/s/pyo8ynjkr7

I tested those two components in my project and `<Added>` is getting styled correctly while `<NotAdded>` is completely white (transparent).

Is this helpful to you?

**Comment by rhyek** [comment] 2018-04-01 00:55
Also, just to be clear (and perhaps redundant), the styles *are* being applied when not using TestCafé.

**Comment by rhyek** [comment] 2018-04-01 01:07
Btw, I tried loading that sandbox through TestCafé, but it won't work, sadly:
![image](https://user-images.githubusercontent.com/702922/38168874-ca53e7ec-3516-11e8-9b58-c95c58e5e021.png)

**Comment by probablyup** [comment] 2018-06-20 23:43
@rhyek can you try again with latest styled-components? The sandbox appears to work correctly, but I'm unsure of this "TestCafe" setup.

**Comment by rhyek** [comment] 2018-06-20 23:58
Hi. I am actually not using TestCafé, anymore. You can go ahead and close this issue if you would like to. Love styled-components!

**Closed** 2018-06-20 23:59 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
