### ISSUE TITLE
v5 is not server rendering with stream

### ISSUE THREAD

**Issue by nandosangenetto** [styled-components/styled-components#2632] opened 2019-06-19 18:55 UTC
### System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
 - Memory: 428.67 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 12.4.0 - /usr/local/bin/node
 - Yarn: 1.17.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^5.0.0-beta.3 => 5.0.0-beta.3 

## Reproduction & Steps to reproduce
I have a project running styled-component 4.3.1 using a source code similar to the indicated on docs (https://www.styled-components.com/docs/advanced#streaming-rendering). All my styles render on the server, but when I updated to beta.3, it stopped. 

Here is a chunk of my code:
```javascript
  // Send the HTML as soon as possible
  response.write(`<!DOCTYPE html><html lang="pt-BR"><head>`);
  response.write(renderToString(<Head />));

  // Getting chunks from the JSON file generated by the babel plugin
  const webExtractor = new ChunkExtractor({ statsFile: webStats });

  // Getting stylesheet from styled-components
  const sheet = new ServerStyleSheet();
  let jsx = sheet.collectStyles(application);

  // Getting JSX by collecting all chunks and putting them together
  jsx = webExtractor.collectChunks(application);

  // awaiting the data from Apollo queries
  await getDataFromTree(jsx);

  // Getting apollo state to render on the SSR
  const apolloState = apolloClient.extract();

  // Getting helmet data (title, meta and link)
  const { helmet } = helmetContext;

  // Writing the rest of the HTML markup
  const helmetString = `${helmet.title.toString()}${helmet.meta.toString()}${helmet.link.toString()}`;

  response.write(
    `${webExtractor.getLinkTags()}${helmetString}</head><body><div id="app">`
  );

  // Rendering styles to Node Stream
  const renderStream = sheet.interleaveWithNodeStream(renderToNodeStream(jsx));

  // Render styles inside the app element
  // We render it out of the head element because we need to
  // rehydrate the style content
  renderStream.pipe(
    response,
    { end: false }
  );
```

In this code, I'm using loadable-components (https://github.com/smooth-code/loadable-components), Apollo and react-helmet-async (https://github.com/staylor/react-helmet-async)

## Expected Behavior
Render my styles on the server.

## Actual Behavior
It's not rendering. It only renders on the client side.

**Comment by probablyup** [comment] 2019-06-20 18:26
```
  let jsx = sheet.collectStyles(application);

  // Getting JSX by collecting all chunks and putting them together
  jsx = webExtractor.collectChunks(application);
```

You're collecting and then replacing the variable? `sheet.collectStyles` should be the outermost wrapper.

**Comment by probablyup** [comment] 2019-06-23 13:30
We also need some sort of reproduction to be able to help you, otherwise I can only make offhand recommendations.

**Comment by probablyup** [comment] 2019-07-01 14:39
Closing due to non-response. Will reopen if a reproduction is provided.

**Closed by probablyup** 2019-07-01 14:39 UTC
Labels: 5.0, needs more info :raised_hand_with_fingers_splayed:
