### ISSUE TITLE
position: sticky isn't prefixed for Safari

### ISSUE THREAD

**Issue by oscar-b** [styled-components/styled-components#158] opened 2016-11-01 15:28 UTC
## Version
1.0.10

## Reproduction
```css
position: sticky;
```

## Expected Behavior
Autoprefix should add prefixed version for Safari:
```css
position: sticky;
position: -webkit-sticky;
```

## Actual Behavior
No prefix.

**Comment by mxstbr** [comment] 2016-11-01 15:41
This is a duplicate of #111, could you post your specific issue as a comment in that thread? Thank you very much!

(also, cc @threepointone)

**Closed by mxstbr** 2016-11-01 15:41 UTC
Labels: bug

**Comment by threepointone** [comment] 2016-11-01 19:51
thanks, made an issue.

**Comment by threepointone** [comment] 2016-11-15 14:41
I fixed this on glamor's end with a custom plugin.

**Comment by MbF-Sathya** [comment] 2018-03-28 08:03
thanks
