### ISSUE TITLE
"Unused" Props Generate Classes

### ISSUE THREAD

**Issue by RXminuS** [styled-components/styled-components#1323] opened 2017-11-22 07:42 UTC
## Version
2.2.3

## Reproduction

I recently noticed a `Over 200 classes generated for component styled.div` in our debug window. The component is rendered somewhat like this:

```jsx
const StyledComponent = styled.div`
 background-color: ${({level}) => level > 1 ? red : green};
`;

const IssueComponent = (({id, ...props}) => 
(<Container id={id}>
   <StyledComponent {...props} />
</Container>)
```
Although the props sent in is quite a big object the style only uses one of them. 

## Expected Behavior

I would expect styled-components to be able to ignore unused props and only generate classes for values of props that are actually used in the styles.

## Actual Behavior

Classes are generated for every value for every prop being sent in.

If my component looks like this it fixes the issue:

```jsx
const StyledComponent = styled.div`
 background-color: ${({level}) => level > 1 ? red : green};
`;

const IssueComponent = (({id, level, ...props}) => 
(<Container id={id}>
   <StyledComponent level={level} />
</Container>)
```

## Notes

It's actually a pretty understandable "issue" once I found it so I'm not sure if a fix is even possible / desired. However it might be a good idea to make it very clear in the docs to only send in Minimal Props to your final Styled component classes to avoid excessive class generation. Because the suggestion for that error is to use `refs` which only merges in more props.

**Comment by vzaidman** [comment] 2017-11-23 08:26
Same issue here after a migration to React 16 and the new way props are handled on end nodes:
https://reactjs.org/blog/2017/09/26/react-v16.0.html#support-for-custom-dom-attributes

I think we should maybe use some kind of attribute filter to make sure only the relevant attributes are used.

**Comment by RXminuS** [comment] 2017-11-28 11:04
Either a filter or instead of the `attrs` function we could just provide a `mapProps: (object) => object` function like in recompose. That way we could make it explicit that any combination of props being sent into styled will result in a new class so that you should filter & merge props in this function to optimise performance. Problem is that attrs atm doesn't provide this functionality since it's properties are merged in not replacing the original.

Then we can always introduce some default mapProps like filter that just pick some values but in all honesty I think that belongs in libraries like lodash.

It is possible already of course by wrapping each styled component in a HOC that filters out  these props but then we end up with so many unnecessary explicit React components instead of bundling a few Styled components together.

**Comment by philpl** [comment] 2017-11-28 11:11
This is not intended behaviour as we hash class names. Thus no new class names should be generated when the same props are provided again I.e. when the props stringify to the same CSS.

@RXminuS can you provide a minimal reproduction please? You can find templates for CodeSandbox in the issue template

**Comment by probablyup** [comment] 2018-06-21 00:34
Closing this since it's been some time with no action. Feel free to reopen if you are able to make a reproduction case.

**Closed by probablyup** 2018-06-21 00:34 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
