### ISSUE TITLE
Using injectGlobal/keyframes with StyleSheetManager 

### ISSUE THREAD

**Issue by Fer0x** [styled-components/styled-components#1354] opened 2017-12-15 17:38 UTC
Follow-up from https://github.com/styled-components/styled-components/pull/1324
When using `StyleSheetManager` with frame as target, `keyframes` and `injectGlobal` will be applied only to parent window `<head />`. We need the ability to insert global styles and keyframes inside `<StyleSheetManager />`.

As solution we can add new components: <StyleInjector />`.

Example usage with global styles:

```jsx
import React from 'react';
import { injectGlobal, StyleInjector } from 'styled-components';

const globalStyles = injectGlobal`
  body: {
    // ...
  }
`;

const MyComponent
<StyleSheetManager target={frame}>
  <div>
    <StyleInjector name={globalStyles} />
  </div>
</StyleSheetManager>
```

Example with keyframes:

```jsx
import React from 'react';
import { keyframes, StyleInjector } from 'styled-components';

const animationName = keyframes`
  0% { color: transparent; }
  100% { color: radboats; }
`;

<StyleSheetManager target={frame}>
  <div>
    <StyleInjector name={animationName} />
  </div>
</StyleSheetManager>
```

That component will get `componentId` by provided prop `name`, then grab corresponding styles from global Stylesheet instance and insert them to closest StyleSheetManager target.

**Comment by mxstbr** [comment] 2017-12-15 19:02
Going to close this as a duplicate of #1333, we haven't thought of any solutions for `keyframes` yet though, feel free to suggest your API there!

**Closed by mxstbr** 2017-12-15 19:02 UTC
