### ISSUE TITLE
WebStorm/IntelliJ IDEA support

### ISSUE THREAD

**Issue by nkbt** [styled-components/styled-components#176] opened 2016-11-08 20:48 UTC
**EDIT(@mxstbr): Please upvote this YouTrack issue to let the Jetbrains folks know you want this feature! https://youtrack.jetbrains.com/issue/WEB-24148**

![20161109-074426](https://cloud.githubusercontent.com/assets/175264/20116505/9280bf62-a650-11e6-9ab7-393534081661.png)

It is probably possible to do something with language injections, but I could not figure out how to do it yet. 

Would appreciate any help, since without proper CSS syntax support with completion/code formatting aso - it is a major blocker for us to use styled components (instead of CSS Modules)

**Comment by nkbt** [comment] 2016-11-08 20:59
With help of "Intentions" menu I managed to set language as CSS, but then webstorm appears to expect proper CSS there with selectors and everything is parsed as error

![20161109-075529](https://cloud.githubusercontent.com/assets/175264/20116859/1ab7a200-a652-11e6-94cb-8bc4df4c0d4b.png)


The other potential solution could be a TextMate bundle. Temporary tho, since it only gives syntax highlighting but you cannot use any of webstorm code intelligence on that bit. It is treated as just a plain text.

**Comment by nkbt** [comment] 2016-11-08 21:09
Example of language support plugin, just in case anyone is interested (vue-js) https://github.com/henjue/vue-for-idea

**Comment by Dattaya** [comment] 2016-11-12 22:16
Please, also vote for this ticket: https://youtrack.jetbrains.com/issue/WEB-22106

**Comment by smeijer** [comment] 2016-11-22 09:43
@nkbt , is it not possible to define the language as being `stylus` or `scss`? I guess the `&:hover` is valid syntax for both these `css-parsers`?

**Comment by nkbt** [comment] 2016-11-22 09:44
@smeijer sure, but properties without selector are not valid for either, and that is the actual problem

**Comment by Dattaya** [comment] 2016-11-22 13:04
I think I've found a temporary workaround:

![image](https://cloud.githubusercontent.com/assets/387256/20524555/a63f7a48-b0c3-11e6-85f1-b146df02cdab.png)

I used `SCSS` language injection:
![image](https://cloud.githubusercontent.com/assets/387256/20524671/35293276-b0c4-11e6-9e72-6182e6fd6170.png)

**Comment by nkbt** [comment] 2016-11-22 20:27
Sick! 💯

**Comment by davidctj** [comment] 2016-11-24 10:33
WebStorm [2016.3 EAP, 163.4830](https://blog.jetbrains.com/webstorm/2016/09/webstorm-2016-3-eap-163-4830-stylelint-usages-for-default-exports-and-more/) recently released and support styleLint, and then I do the same step as mentioned on the homepage [styleLint processor](https://github.com/styled-components/stylelint-processor-styled-components), but it is not working, here's the error:
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\WebstormProjects\webroot\node_modules\stylelint\dist\augmentConfig.js:300:23
    at Array.forEach (native)
    at addProcessorFunctions (C:\WebstormProjects\webroot\node_modules\stylelint\dist\augmentConfig.js:290:58)
```

So, is someone has the same error as mine or the styled component for webstorm linting still not supported yet? any idea?

**Comment by danieldunderfelt** [comment] 2016-11-29 07:29
Is someone working on a plugin for WebStorm/PhpStorm? If not, I'll have a stab at it.

**Comment by nkbt** [comment] 2016-11-29 07:30
I don't know anyone, that would be fantastic!

**Comment by kitze** [comment] 2016-12-02 10:43
@danieldunderfelt please do 🙌

**Comment by Gregoor** [comment] 2016-12-19 15:08
Heya @danieldunderfelt, did you already have a chance to look into it? If not I'd give it a shot.

**Comment by danieldunderfelt** [comment] 2016-12-19 15:17
@Gregoor I did look into it, but it required a bit too much Java knowledge for me. I had planned to fork the SCSS language, but that wasn't readily available as a base plugin. As far as I know, I'd have to re-implement 90% of the SCSS stuff and figure out how to use language injection.

It would be awesome if you could take a look! Good luck!

**Comment by smeijer** [comment] 2016-12-19 21:13
For the person that is able to get this thing done; the `graphql` project can be of help. It add's support for the `gql` template tag.

> The plugin is activated as soon as you view or edit GraphQL in the editor. This includes GraphQL inside `Relay.QL` and `gql` templates in JavaScript and TypeScript. You can also use .graphql physical files and scratch files. These files allow you to query your endpoint directly from your IDE.

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

**Comment by Gregoor** [comment] 2016-12-21 07:08
Yaiks, I forgot how much Java pains me.

Fortunately I stumbled over Language Injections, also mentioned in the [styled-components Webstorm issue](https://youtrack.jetbrains.com/issue/WEB-24148). The fight between my dislike for Java vs my dislike for Regex was won by the former, hence I regexed a language injection, that's good enough for me for now:

![styled](https://cloud.githubusercontent.com/assets/4051932/21379649/002141ca-c750-11e6-9889-c78418943ea4.png)

As one can see, the only thing not working is JS string interpolation. There might just be a way to exclude it via regex, but haven't yet found out how.

Here is my current version, it's just a zipped XML, can be imported in the "Language Injection" Setting.
[styled-components-injection.zip](https://github.com/styled-components/styled-components/files/665671/styled-components-injection.zip)

**Comment by danieldunderfelt** [comment] 2016-12-23 07:00
@Gregoor Java pain is understandable :D

Thanks for the injection, it works well. The interpolation is weird, as it kind of notices that we're back to Javascript but the highlighting still throws tantrums. Still, it's much better than we webstormers have had until now!

**Comment by kitze** [comment] 2016-12-23 08:52
@Gregoor cool, getting somewhere! 👍 

I think it should also inject css for the keyframes function from styled-components:

```
const floatAnimation = keyframes`
  from {
    scale: 1;
  }
  to {
    scale: 1.1;
  }
`;
```

**Comment by Gregoor** [comment] 2016-12-24 22:25
Ah right, forgot about that, here we go: [styled-components-injection-v2.zip](https://github.com/styled-components/styled-components/files/671983/styled-components-injection-v2.zip)

Also, if someone else wants to tinker, you can see that all it is this:

## Language
ID: `SCSS`
Prefix; `dummy {`
Suffix: `}`
## Places Pattern
```
+ jsLiteralExpression().withText(string().matchesBrics("styled\\..*?\\`(.*?)\\`"))
+ jsLiteralExpression().withText(string().matchesBrics("styled\\(.*?\\)\\`(.*?)\\`"))
+ jsLiteralExpression().withText(string().matchesBrics("keyframes\\`(.*?)\\`"))
```

**Comment by erikras** [comment] 2016-12-30 11:26
I gave this an hour, but now my brain hurts. I'm pretty sure [it's not possible to capture multiple groups, ignoring intermediary parts, in java](http://stackoverflow.com/questions/6939526/java-regex-repeating-capturing-groups#6939587).

**Comment by nkbt** [comment] 2017-03-15 21:01
Here is a great example of tagged literals plugin for intellij

https://plugins.jetbrains.com/plugin/8097-js-graphql

source: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/

**Comment by kitze** [comment] 2017-03-15 21:37
yes @nkbt I'm using it and I can confirm that it works flawlessly. There's still hope for  💅 in WS 😞

**Comment by HejdesGit** [comment] 2017-03-23 08:39
@Gregoor:s styled-components-injection-v2.zip was great and was working with Webstorm 2016. Has anyone got this working with Webstorm 2017? I have injected but is not working...

**Comment by Alex-Mann** [comment] 2017-03-25 04:19
Would love to see this working / supported as a plugin for Webstorm. If I was confident in Java I would attempt myself but alas...

**Comment by gr4yscale** [comment] 2017-03-28 10:34
Just found this thread. 

Also interested, and it seems that the suggestion of @nkbt to take examples of the intelligj plugins supporting tagged template literals would be the way to go. Currently in the middle of a crunch on a project, so my time is limited, but if no one else has taken a stab at it in a week or two I'll give it a go.

**Comment by Geczy** [comment] 2017-04-19 16:20
@Gregoor @HejdesGit can confirm, no longer works in webstorm 2017. Can it be updated?

**Comment by StrikeForceZero** [comment] 2017-04-23 22:15
Haven't tested this just yet but I'd imagine this would work:  `// language=SCSS`

![image](https://cloud.githubusercontent.com/assets/983413/25317903/89cb51ca-2850-11e7-9fea-984fd3da8a74.png)

**Comment by Maxincredible52** [comment] 2017-04-25 18:39
@gr4yscale that would be super awesome 🚀

**Comment by csprance** [comment] 2017-04-28 06:11
@StrikeForceZero Ya but that kinda sucks because you need to add the braces and the & sign

It would be really nice to have this feature in the IDE. Hopefully someone is out there that can save us! :)

**Comment by hadfieldn** [comment] 2017-05-08 21:00
I'm guessing something broke in WebStorm 2017 that prevents this from working properly: 
```js
+ jsLiteralExpression().withText(string().matchesBrics("styled\\..*?\\`(.*?)\\`"))
```

@csprance Until we get a fix for the issue in IntelliJ/Webstorm 2017 that prevents the language injection from working, you can add `prefix` and `suffix` args to the language-injection comment to avoid having to add the braces and ampersand: 
```JS
// language=SCSS prefix=dummy{ suffix=}
```
![image](https://cloud.githubusercontent.com/assets/22274/25824873/0c0bc4d6-33fe-11e7-98fe-03e31ac6d472.png)

Unfortunately it's still very hacky.

**Comment by nkbt** [comment] 2017-05-25 14:18
This solution looks reasonably ok

https://medium.com/@iamssen/webstorm-intellij-%EB%93%B1%EC%9D%98-jetbrains-ide%EC%97%90%EC%84%9C-styled-components-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-b0bc79418e1f

**Comment by Geczy** [comment] 2017-05-25 16:41
@nkbt that's the solution i've been using. either that or @hadfieldn 's solution will work

**Comment by geelen** [comment] 2017-05-25 23:23
That medium post is awesome, it totally works... except for indentation and interpolations :(

So close though!!

**Comment by cdharris** [comment] 2017-06-07 11:37
While not a complete solution yet, I've managed to get something together that works for me (after poking around in undocumented APIs  :hammer_and_pick: ) Hopefully this helps some others too :)

![sc-screenshot](https://user-images.githubusercontent.com/3830518/26876314-ec16ce4c-4b85-11e7-8564-16e7eab086a5.png)

Import the `styled-components.xml` language injection here :
https://github.com/cdharris/styled-components-intellij-syntax

**Comment by Maxincredible52** [comment] 2017-06-07 12:18
@cdharris this is great but it still does not solve the problem of having JavaScript stuff in the css language

![image](https://user-images.githubusercontent.com/15246773/26877979-0b1d685e-4b8c-11e7-8825-1aa3cf6a42bf.png)

**Comment by kusmierz** [comment] 2017-06-08 09:21
And [style lint](https://stylelint.io) doesn't work inside :(

**Comment by hadfieldn** [comment] 2017-06-08 10:39
@cdharris thank you! At least with your injection we don't have to add the language comment -- back to the functionality we had before it was broken with WS 2017.

**Comment by ImanMh** [comment] 2017-07-09 05:27
I hop an official plugin is released for styled components. I really need them.

**Comment by lixiaoyan** [comment] 2017-07-09 17:08
@cdharris seems `language=PostCSS` would be a bit better than `language=SCSS`: it supports injection like `margin: ${props => props.margin}`
(but not `${"margin: 0;"}`)

**Comment by danikenan** [comment] 2017-08-14 03:38
added support for `injectGlobal` and `extend`:
```
+ jsLiteralExpression().and(jsArgument("styled", 0))
+ jsLiteralExpression().withParent(psiElement().withParent(psiElement().withText(string().startsWith("Styled"))))
+ jsLiteralExpression().withParent(psiElement().withText(string().contains(".extend")))
+ jsLiteralExpression().withParent(psiElement().withText(string().startsWith("injectGlobal")))
+ jsLiteralExpression().withParent(psiElement().withText(string().startsWith("styled")))

```

**Comment by daedlock** [comment] 2017-08-29 00:57
I will implement this if I get enough upvotes :P

**Comment by danikenan** [comment] 2017-08-29 01:38
+1

**Comment by MathieuLorber** [comment] 2017-08-29 07:35
Please, not a notification-storm of "+1" posts, upvote with the thumb on @daedlock post.

**Comment by mxstbr** [comment] 2017-08-29 08:45
I feel like the 107 upvotes on the OP speak for themselves :wink:

**Comment by philpl** [comment] 2017-08-29 10:55
I’m locking this issue — Just in case — Since there is not a lot to be discussed here anymore. However, if someone decides to implement this and push a repo on GitHub, we’re happy to move it into our org of course. :smile:

**Comment by geelen** [comment] 2017-08-29 11:10
Us webstorm users: 
![there are dozens of us!](https://media.tenor.com/images/88b9219dee67dcd72201f336956988d3/tenor.gif)

**Comment by mxstbr** [comment] 2017-08-30 16:03
@daedlock has started working on a Webstorm plugin and is already quite far based on previous suggestions in this thread: https://github.com/styled-components/styled-components/issues/1131 :tada: 

Please try it out and contribute to it, it'd be awesome to finally have an officially recommended solution for Webstorm users.

**Comment by mxstbr** [comment] 2017-09-08 17:39
There's finally an official WebStorm plugin, partly built by @daedlock and partly built by JetBrains employees!!

Go use it, star it, recommend it: https://plugins.jetbrains.com/plugin/9997-styled-components 
Also give the repo a star on GitHub while you're at it: https://github.com/styled-components/webstorm-styled-components

I'm going to unlock and close this issue, feels so great :tada:

**Closed by mxstbr** 2017-09-08 17:39 UTC
Labels: help wanted

**Comment by daviddelusenet** [comment] 2018-01-12 08:41
Plugin worked for me! Now on to the next part: support for Stylelint. 

I've tried to set [this](https://www.styled-components.com/docs/tooling#stylelint) up with the native Stylelint package but I can't select files `.js` files as the files to lint. 

Anyone has any ideas on this? :)

**Comment by mxstbr** [comment] 2018-01-12 09:13
Please submit a new issue, no need to notify everybody who participated in this one of your individual troubles.
