### ISSUE TITLE
Typescript 2.4 Error: Variable StyledComponentClass from external module cannot be named.

### ISSUE THREAD

**Issue by kevcenteno** [styled-components/styled-components#1063] opened 2017-08-04 14:30 UTC
## Version
2.1.1
Typescript: 2.4.2

## Reproduction
Given a styled-component `src/wrapper.tsx`
```
import * as React from 'react';
import styled from 'styled-components';

const Wrapper = styled.header`
  background-color: red;
  height: 50px;
  width: 100%;
`

export default Wrapper;
```

and tsconfig.json 
```
{
 "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "lib": ["dom", "es2015", "es2016"],
    "outDir": "dist",
    "baseUrl": "./src",
    "jsx": "react",
    "sourceMap": true,
    "declaration": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

The following error occurs:
```
[ts] Exported variable 'Wrapper' has or is using name 'StyledComponentClass' from external module "/path/project/node_modules/styled-components/typings/styled-components" but cannot be named.
```

## Expected Behavior
Doesn't throw error

## Actual Behavior
Throws error
```
[ts] Exported variable 'Wrapper' has or is using name 'StyledComponentClass' from external module "/path/project/node_modules/styled-components/typings/styled-components" but cannot be named.
```

**Comment by philpl** [comment] 2017-08-04 14:34
We'll need more information on your tsconfig, I suspect. Otherwise it's just a duplicate of the other issue with a different version if TS :wink:

cc @styled-components/typers

**Comment by kevcenteno** [comment] 2017-08-04 14:45
@philpl Updated with full tsconfig.json and wrapper.tsx

**Comment by kevcenteno** [comment] 2017-08-04 14:55
A not so nice workaround would be to wrap the styled component with an SFC:
```
const StyledWrapper = styled.header`
  background-color: red;
  height: 50px;
  width: 100%;
`;

const Wrapper : React.SFC = () => {
  return ( <StyledWrapper />);
};

export default Wrapper;
```

**Comment by philpl** [comment] 2017-08-04 15:36
Actually, I just realised I recognise the error in combination with the enabled `declaration` option. When the compiler is trying to generate the type definitions, it can only do that if the class definition is in turn in scope as well.

@Igorbek I think something is going very wrong when some people use `declaration`. Is there anything we can do to make this use case easier?

**Comment by Igorbek** [comment] 2017-08-04 18:03
Yes, that is annoying TS error that prevents writing **declaration** files when they use inferred types that are defined externally. There're 2 issues here:
1. `StyledComponentClass` is not exported
2. The name should imported even if it's not used explicitly

The first we can fix, and we will. The second you'd have fix yourself.

**Comment by Igorbek** [comment] 2017-08-04 20:24
Ah, I though it was not exported, but it was. If you write your code that way, it should work:

```ts
import * as React from 'react';
import styled, { StyledComponentClass } from 'styled-components'; // <-- note additional export here

const Wrapper = styled.header`
  background-color: red;
  height: 50px;
  width: 100%;
`

export default Wrapper;
```

We cannot fix this on our side, that is TypeScript's intended behavior, but [the fix is under consideration](https://github.com/Microsoft/TypeScript/issues/9944).

**Comment by kevcenteno** [comment] 2017-08-04 21:31
Should we close this issue, or keep it open for future reference?

**Comment by philpl** [comment] 2017-08-05 00:09
@kevcenteno we generally don't keep issues open, but link to them when we see fit :wink: It might be worth adding to the docs though. Sounds about right, @Igorbek? :)

**Closed by philpl** 2017-08-05 00:09 UTC

**Comment by trusktr** [comment] 2019-12-21 20:10
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
