### ISSUE TITLE
StyleSheetManager with stylisPlugins prop always reconstruct styles and append to Html Head, But never remove it when it unmounted.

### ISSUE THREAD

**Issue by CareyToboo** [styled-components/styled-components#2890] opened 2019-11-22 04:05 UTC
## Environment

`react: 16.8.3,  styled-components:  5.0.0-beta.9`

## Steps to reproduce
Here is the simple code to explain this problem.
```javascript
import React, { useState } from 'react'
import { render } from 'react-dom'
import styled, { StyleSheetManager } from 'styled-components'

const Wrapper = styled.div``

const Title = styled.div`
  color: red;
`
const App = () => {
  const [toggle, setToggle] = useState(false)

  return (
    <Wrapper>
      <button onClick={() => setToggle(!toggle)}>Toggle</button>
      {toggle && (
        <StyleSheetManager stylisPlugins={[anyPlugin]}>
          <Title>hello world</Title>
        </StyleSheetManager>
      )}
    </Wrapper>
  )
}

render(<App />, document.getElementById('root'))

```

when I click toggle button, StyleSheetManager produce many new same styles with old style. 

```
// here is chrome develop tool 'Styles' tab

<style>
.euQbIR {
    color: red;
}
<style>
.euQbIR {
    color: red;
}
<style>
.euQbIR {
    color: red;
}
``` 

## Expected Behavior
when StyleSheetManager is unmounted it should remove the styles.
## Actual Behavior
StyleSheetManager only produce styles.

**Comment by probablyup** [comment] 2019-12-30 04:01
I think this should be fixed with https://github.com/styled-components/styled-components/releases/tag/v5.0.0-rc.3, can't test since you didn't supply a reproduction.

**Closed by probablyup** 2019-12-30 04:01 UTC

**Comment by CareyToboo** [comment] 2020-01-15 08:10
It's a great help, thanks a lot  : )
