### ISSUE TITLE
Provide better ESM support for importing `styled` in node

### ISSUE THREAD

**Issue by jmurzy** [styled-components/styled-components#3601] opened 2021-10-11 21:15 UTC
@JacobLey has done a great job describing the underlying issue in #3437 but for reasons not obvious to me, the issue was closed.

There is currently **no way** to cleanly import `styled` running in node with ESM support. 

### Binaries:
 - Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v16.1.0/bin/yarn
 - npm: 7.24.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
 - Watchman: 2021.06.07.00 - /usr/local/bin/watchman

## Steps to reproduce

To reproduce, create a new file `test.mjs`, then run: `node test.mjs`  

```js
import styled from 'styled-components'; 
const Container = styled.div``;
``` 

You will get: "styled.div is not a function"

To fix, you'd have to do:

```js
import _styled from 'styled-components'; 
const styled = _styled.default;
const Container = styled.div``;
``` 

which, I'm sure you'd agree, is not ideal.

## Expected Behavior

Should provide better ESM support for importing `styled` in node.

## Actual Behavior

Thoroughly described in  #3437.

**Comment by JayaKrishnaNamburu** [comment] 2021-12-06 07:06
Effecting for using `styled-components` from [jspm](https://jspm.org/) too

**Comment by gregberge** [comment] 2021-12-22 07:52
Fixed in https://github.com/gregberge/xstyled/commit/a080d9609c6bdf02fb91de9e989de7157b131133 in xstyled.

**Comment by freshollie** [comment] 2022-01-23 17:08
For those having this issue in jest only, you can try this

```typescript
jest.mock("styled-components", () => {
  const actual = jest.requireActual(
    "styled-components"
  ) as typeof import("styled-components");
  const styled = actual.default;

  return Object.assign(styled, actual);
});
```

(This may not work for all cases)

**Comment by psychobolt** [comment] 2022-02-20 18:17
I am running a module setup and Jest set with `--experimental-vm-modules`. This solution works for me, as Jest allows to use the transform with `babel-jest` and `babel-plugin-module-resolver`.

e.g.
```js
// babel.config.js
export default () => {
   return {
     plugins: [
       [
        'module-resolver',
        {
          alias: {
            'styled-components': './cjs/styled-components.cjs', // <!-- cjs or js depending on your package.json `type: `
          },
        },
       // other plugins
     ]
   };
}
```

Then, I can alias `styled-components` in my babel config which I can configure styled-components to be imported as a commonjs. Note, Jest runtime will load cjs and esm.
```js
// ./cjs/styled-components.cjs
const { default: styled, ...rest } = require('styled-components');

module.exports = { ...styled, ...rest };
```

**Comment by chentsulin** [comment] 2022-02-21 15:42
@probablyup @kitten Is there any chance to reconsider providing `styled` as a named export (#3437 #3438)? This issue definitely blocks the adoption of using styled-components with [Next.js 12 Native ES Modules Support](https://nextjs.org/blog/next-12#es-modules-support-and-url-imports).

**Comment by karol-f** [comment] 2022-04-19 20:15
This is a temporary workaround that works for me - https://github.com/styled-components/styled-components/issues/3437#issuecomment-1103085056

**Comment by The-Code-Monkey** [comment] 2022-05-01 21:38
I am having this issue in my jest tests, has any progress been made on this issue yet?

**Comment by The-Code-Monkey** [comment] 2022-05-02 13:18
@freshollie 

Got chance to try your fix today and doing this in a jest setup file worked 

```
import { jest } from "@jest/globals";

jest.mock("styled-components", () => {
  const actual = jest.requireActual(
    "styled-components"
  ) as typeof import("styled-components");
  const styled = actual.default;

  return Object.assign(styled, actual);
});
```

Styled-component guys would be nice to have a better solution than this though.

**Comment by scott-lc** [comment] 2022-05-20 17:28
Because of the "missing" named export, you can't use `styled-components` with the upcoming TypeScript 4.7 `nodenext` resolution mode.

https://github.com/microsoft/TypeScript/issues/49189

**Comment by JacobLey** [comment] 2022-05-21 21:00
I published a mini package to help work around that https://www.npmjs.com/package/default-import because I was still running into this issue. Tested with 4.7 locally.

Pretty much just does the behavior described in https://github.com/styled-components/styled-components/issues/3437#issuecomment-1103085056 with a bit more generalized logic.

```ts
import { defaultImport } from 'default-import';
import defaultStyled from 'styled-components';

const styled = defaultImport(defaultStyled);

export const myComponent = styled.div`
    color: red;
`;
```

Hopefully that helps

**Comment by steve-taylor** [comment] 2022-07-06 14:20
I have a reproduction for `styled-components` not being properly bundled in Next.js.

https://github.com/steve-taylor/next-styled-esm-repro

In addition to the `main` branch, I have tried various other things in different branches in an attempt to narrow down the issue:

| Branch                                           | Experiment                                                                                                                | Built |
|--------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------|-------|
| `without-styled-components`                      | Removed `styled-components` to see if it's just a Next.js issue                                                           | ✅     |
| `without-styled-components-default-import-react` | Directly imported `React` instead of `{Component}`                                                                        | ✅     |
| `without-styled-components-react-markdown`       | Used an ESM-only dependency (`react-markdown`)                                                                            | ✅     |
| `with-module-field`                              | Created a package that has `main` and `module` fields for CommonJS and ESM fields respectively (like `styled-components`) | ✅     |
| `commonjs`                                       | Made all packages CommonJS, which provides no way to consume ESM packages, such as `react-markdown`                       | ✅     |

Separate to this reproduction repo, I've also tried disabling SWC in Next.js in favour of Babel, but I get exactly the same result.

At this stage, all signs point to `styled-components` being misbundled.

**Comment by steve-taylor** [comment] 2022-07-07 08:49
I have a workaround. The issue is caused by `styled-components` and some of its dependencies (looking at you, Emotion) being hybrid packages but not using conditional exports to tell Node.js which bundle is ESM vs. CommonJS. However, those dependencies don't need to do that if you make your own packages that use those dependencies hybrid as well.

See https://github.com/steve-taylor/next-styled-esm-repro/tree/with-preconstruct-react-markdown-conditional-exports

**Comment by The-Code-Monkey** [comment] 2022-09-08 13:42
@steve-taylor @jmurzy Do either of you know if any more work has been done to rectify this issue, or do we still have to use the workaround as above.

**Comment by mariuslundgard** [comment] 2022-12-22 20:34
What's the status of this issue? Would love to contribute if possible.

**Comment by probablyup** [comment] 2022-12-23 21:58
You can import styled as a named import in v6.0.0-beta.7

**Closed by probablyup** 2022-12-23 21:58 UTC

**Comment by dimitur2204** [comment] 2023-01-30 09:46
I was using Rollup to bundle my library and `@emotion/styled` was a peerDependency.
 In the cjs bundle it was required like that: `const styled = require("@emotion/styled")` and I was getting the `styled is not a function error` since the actual function is on `styled.default`

Adding the `interop: "auto"` flag to the cjs output resolved my issue.

Hopes it helps someone!

**Comment by gajus** [comment] 2023-08-31 12:18
I ended up writing a script where I re-export the members of `styled-components`. The rest of the app then imports from this file:

```ts
import styledComponents from 'styled-components';

type Styled = typeof styledComponents;

// https://github.com/styled-components/styled-components/issues/3601#issue-1023120934
// @ts-expect-error incompatibility between styled-components and @types/styled-components
export const styled = styledComponents.default as Styled;

export { css } from 'styled-components';
```
