### ISSUE TITLE
Styled components with typescript and semantic-ui

### ISSUE THREAD

**Issue by vincaslt** [styled-components/styled-components#1233] opened 2017-10-12 05:29 UTC
I am using styled-components along with typescript and semantic-ui-react. The problem I'm dealing with is that types are incorrectly understood, when they define keys as any list: `[key: string]: any`.

Consider this snippet, that uses semantic-ui:

```
import { Header } from 'semantic-ui-react'
import styled from 'styled-components'

const StyledHeader = styled(Header)`
   *some style*
`
```

I will not be able to use any of the Header props: `<Header content="text" />` says content is not found, even though HeaderProps define it.

Workaround I've found which I don't like is:

```
import { Header, HeaderProps } from 'semantic-ui-react'
import styled, { StyledComponentClass } from 'styled-components'

const StyledHeader = styled(Header)`
   *some style*
` as StyledComponentClass<HeaderProps, {}>
```

Now I can use the props. For some reason in the first case the type is understood as: `StyledComponentClass<HeaderProps, any, Pick<HeaderProps, never>>`

Another workaround is removing key list (`[key: string]: any;`) definition from semantic-ui typedefs:
`
export interface HeaderProps {
  [key: string]: any;
  content?: React.ReactNode;
  ...
}
`

**Comment by philpl** [comment] 2017-10-12 09:47
cc @styled-components/typers

**Comment by Igorbek** [comment] 2017-10-12 18:25
Ok, that is caused by an edge case of `Omit` type operator which is [discussed here](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-325123790). In styled components we use it in order to make `theme` prop optional. Let me think what we could do here.

**Comment by rasdaniil** [comment] 2017-12-05 23:21
@vincaslt thanks for workaround

**Comment by mxstbr** [comment] 2017-12-15 13:03
@Igorbek any ideas?

**Comment by rasdaniil** [comment] 2017-12-15 17:54
@mxstbr @Igorbek @vincaslt 

Btw, I think I've updated some typings and reinstalled node_modules and the problem seems to have disappeared:

![screenshot at 2017-12-15 19-50-35](https://user-images.githubusercontent.com/24467138/34054010-b4f5248a-e1d1-11e7-8456-e64ec0d265d0.png)

**Comment by mxstbr** [comment] 2017-12-15 19:16
NICE, awesome! Thanks for confirming @rasdaniil, closing 👌

**Closed by mxstbr** 2017-12-15 19:16 UTC
Labels: question
