### ISSUE TITLE
grid-template-columns with repeat(3, 1fr) doesn't work

### ISSUE THREAD

**Issue by schabluk** [styled-components/styled-components#2274] opened 2018-12-05 19:55 UTC
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 891.78 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.13.0 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 3.10.5 - ~/npm/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: 4.1.2 => 4.1.2

## Reproduction

https://codesandbox.io/s/5yzop08904

## Expected Behavior

Should work the same as:
```
  display: grid
  grid-template-columns: 1fr 1fr 1fr
  grid-template-rows: 50px 50px
  grid-gap: 5px;
```

## Actual Behavior

Produces invalid property:

```
    display: grid;
    grid-template-columns: repeat(3,1fr) grid-template-rows:50px 50px;
    grid-gap: 5px;
```

**Comment by probablyup** [comment] 2018-12-05 19:57
So the issue is you're missing a semicolon after the closing paren. stylis (the library we use to process CSS) does best-effort semicolon insertion, but at the end of the day it's up to you to make sure your CSS is valid.

**Closed by probablyup** 2018-12-05 19:57 UTC

**Comment by schabluk** [comment] 2018-12-05 20:07
:( I liked it a lot better without those pesky semicolons

**Comment by probablyup** [comment] 2018-12-05 20:07
Try using object styles instead

**Comment by schabluk** [comment] 2018-12-05 20:08
I think I'll start by reading docs :)
