### ISSUE TITLE
v5 client/server class names don't match using next.js

### ISSUE THREAD

**Issue by brianqian** [styled-components/styled-components#2631] opened 2019-06-19 15:30 UTC
## System:
 - OS: macOS Sierra 10.12.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 127.02 MB / 8.00 GB
 - Shell: 5.2 - /bin/zsh
## Binaries:
 - Node: 12.1.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.1 => 1.10.1
 - styled-components: ^5.0.0-beta.3 => 5.0.0-beta.3

## Steps to reproduce

Here's a simple sandbox to illustrate

https://codesandbox.io/s/styled-components-v5-issue-xggd1

Using v 4.3.1 there are no problems with classnames, in v5 there's the error:

Warning: Prop `className` did not match. Server: "pages__TestDiv-sc-6et416-0" Client: "pages__TestDiv-sc-6et416-0 jFHMWg"

**Comment by kitten** [comment] 2019-06-19 15:43
I think this could be our `isStatic` optimisation that we disable when hot-module replacement/reloading is active. So I suppose this check could be causing it, since it wouldn't trigger on the server-side necessarily:

https://github.com/styled-components/styled-components/blob/canary/packages/styled-components/src/models/ComponentStyle.js#L11-L12

**Comment by mxstbr** [comment] 2019-06-19 15:53
That sounds very sensible to me to avoid issues like this.

**Comment by probablyup** [comment] 2019-06-19 18:57
Yeah I'm fine with that

**Comment by probablyup** [comment] 2019-06-22 16:04
@brianqian can you try out beta 5 and let us know what you see?

**Comment by danhollick** [comment] 2019-06-23 06:48
I can still reproduce this on `5.0.0-beta.5`.

```
Warning: Prop `className` did not match. Server: "ProfilePic__ProfileBubble-jmob3-1 gRFbLj" Client: "ProfilePic__ProfileBubble-jmob3-1 cweNff"
```

**Packages:**
babel-plugin-styled-components: ^1.10.1
styled-components: ^5.0.0-beta.5
next: ^8.0.0

**Comment by danhollick** [comment] 2019-06-23 07:43
EDIT:

I seem to have inadvertently used `(typeof window === 'undefined')` somewhere which was actually causing this for me. 
If I remove that, `5.0.0-beta.5` works.

**Comment by probablyup** [comment] 2019-06-23 13:25
Awesome! I have one more patch I'm making to the babel plugin https://github.com/styled-components/babel-plugin-styled-components/pull/227 that handles a particular combo of syntaxes but will close this since as far as this lib is concerned it appears to be fixed :)

**Closed by probablyup** 2019-06-23 13:25 UTC
Labels: 5.0, bug :bug:
