### ISSUE TITLE
Prod build issues with 5.0.0-beta.8 and CRA 3.1.0

### ISSUE THREAD

**Issue by berdyshev** [styled-components/styled-components#2730] opened 2019-08-31 13:01 UTC
I'm using 5.0.0-beta.8 version with CRA 3.1.0 under the lerna's packages. 

In the dev mode, all styles look good, but in production mode, huge part of styles is missing. I found it in css map file but not in the css itself. 

What can be a cause? Where should I look to debug/resolve this issue? 

## System:
 - OS: macOS 10.14.6
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

**Comment by BjoernRave** [comment] 2019-09-05 21:16
I have the same problem, but it only happens in chrome for me

**Comment by R-Bower** [comment] 2019-09-17 19:39
Same issue here.  Happens only in prod with MSEdge.

**Comment by sbrichardson** [comment] 2019-09-18 03:24
It's due to vendor prefix selectors `::-` or `:-` (so far). It will stop processing any styles after it hits one, that's why some styles work.

@probablyup  One workaround is to wrap your app in a StyleSheetManager and disable CSSOM Injection. In dev mode it's disabled, that's why the styles work.

```js

// Using true will fix temporarily.

render(
  <StyleSheetManager disableCSSOMInjection={true}>
    <App />
  </StyleSheetManager>,
  document.getElementById('root')
)
```

Another workaround is to remove any vendor prefix styles from the global styles, etc. until fixed.

**Comment by R-Bower** [comment] 2019-09-18 21:12
I'll give it a go and report back.  Thanks!

**Comment by probablyup** [comment] 2019-09-23 13:41
Any chance you could provide a codesandbox for reproduction? It's hard to fix this without a repro.

**Comment by sbrichardson** [comment] 2019-10-06 18:54
@R-Bower Checking back in, was that your issue?

**Comment by Leonya** [comment] 2019-11-01 10:55
This is a blocker for us, can't move the offending styles and don't want to disable CSSOM injection either, it doesn't make sense performance-wise.

**Comment by FrediLehmann** [comment] 2019-11-14 10:13
We have the same Issue but with background properties. The Properties `background-repeat/size/position` get removed on Prod build. Which results in distorted images.

It **works with Firefox/IE** but **not in Chrome**, also it works with version `v4.4.1`.

Additionaly we noticed that the SSR component renders correctly. Then on client side the css attributes get removed and the image "moves".

Our component looks like this:

```JavaScript
const Card = styled.div`
  display: flex;
  height: 320px;
  margin-bottom: 20px;
  border-radius: 8px;
  padding: 16px;
  background: linear-gradient(rgba(0, 0, 0, 0) 50%, rgba(0, 0, 0, 0.7)), url("${props => props.img}");
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
  :hover {
    cursor: pointer;
  }
`
```

**Comment by probablyup** [comment] 2019-11-14 10:28
Can you please try the latest rc?

**Comment by FrediLehmann** [comment] 2019-11-14 11:28
The `v5.0.0-rc.2` version doesn't have this bug 👍 we will go with that one i guess 😄

**Comment by mrmckeb** [comment] 2019-11-19 07:10
I've just hit this issue with CRA on v5.0.0-rc.2... I can't find any vendor prefixes. Any other ideas?

**Comment by probablyup** [comment] 2019-11-19 16:15
@mrmckeb I think your issue is potentially a different bug. If you could come up with a reproduction in codesandbox, that would be helpful.

**Comment by probablyup** [comment] 2020-01-02 17:48
This should be fixed in rc2

**Closed by probablyup** 2020-01-02 17:48 UTC

**Comment by greg5green** [comment] 2020-01-14 21:03
This seems to be an issue in 5.0.0 for me -- was there a regression? We have stylesheets with things like `::-webkit-file-upload-button`.

**Comment by probablyup** [comment] 2020-01-14 21:10
Please open a new issue with a reproduction, thanks.
