### ISSUE TITLE
Simplifying the public API

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1087] opened 2017-08-13 18:47 UTC
Currently there are a few ways to use the `styled` API:

1. Creating a new styled-component: `styled.div`
2. Adding styles to an existing React component: `styled(MyComponent)`
3. Extending an existing styled-component: `StyledThing.extend`

I believe the API can be made much simpler by making use case `#3` an implementation detail, rather than something the developer needs to think about and cross-check.

### Rationale
`styled-components` knows when it is passed another styled component. At the point of element creation, it knows what the most optimal way to generate the styles is and has the ability to select that path for the user. As a developer, it's not great that I constantly need to be looking at the implementation of components I consume to know if I need to use `styled()` or `.extend`.

Furthermore, if a component you are consuming switches from being a normal React component to a styled-component or vice versa, that becomes a breaking change as far as this library is concerned because you must/should always use the specific `.extend` API for styled components and the `styled()` API for everything else.

This is confusing and causes a maintenance burden for developers consuming element families containing styled components. A unified `styled()` API that adjusts its implementation under the hood solves these issues in a way that is transparent to the developer and will save headaches.

### Bonus Round: Get rid of the tag whitelist
The API can be made even simpler by doing away with the tag whitelist entirely and always requiring the function syntax, e.g.

```js
🚫 styled.div
✅ styled('div')
```

Now there is only one way to do everything and the library remains eminently approachable. It also means that styled-components will automatically support new HTML tags with zero effort.

With the above suggestions, the API becomes equivalent for all three use cases:

```js
styled('div')
styled(MyComponent)
styled(StyledThing)
```

**Comment by probablyup** [comment] 2017-08-13 18:53
As an aside, I'm happy to take the lead on implementing this.

**Comment by k15a** [comment] 2017-08-13 19:14
You can currently use `styled('div')` currently without problems. It's not different to `styled.div` at all. We have these shorthands on one side because it's nicer to write and because you also can be sure that the tag is valid with `styled.div`. 

In addition, you can also use `styled(StyledThing)`. The difference is that `styled(StyledThing)` only adds the 2 different classes together. `styled(StyledThing)` on the other hand merges the CSS together and only adds a single class to the element. You can read more about why we made this change here: https://github.com/styled-components/styled-components/pull/518

**Comment by philpl** [comment] 2017-08-13 19:26
I'd refer to the "UNIX" way here. Overloading APIs is not a good idea. All our methods and APIs do a single thing and are very predictable. So predictable in fact, that you could read about them without much explanation and use them immediately.

To bring over your argument from the other issue which is kind of missing here:

> .extend doesn't work on non styled-components. What I'm saying is your API is made confusing for no reason by giving two ways to do the same thing that require impl knowledge to differentiate.

It's not confusing, since it's not supposed to work on non-styled-components. In fact, we don't want to encourage the factory `styled(Component)` to be used for your own components, but only third-party components.

This is all to maintain the "Container / Logic -> Structural -> Presentational" component order.

I've referenced why it was added in the other issue (https://github.com/styled-components/styled-components/issues/1083): #45 and #46

### Summary

> Bonus Round: Get rid of the tag whitelist

We had multiple discussions about this as well, and it's a matter of taste, but we prefer not to have to explicitly type the string there. That's something though that glamorous has chosen to go for.

> styled-components knows when it is passed another styled component. At the point of element creation, it knows what the most optimal way to generate the styles is and has the ability to select that path for the user.

Yes, but we can't just overload an API that is meant for something else with a new ability.

> As a developer, it's not great that I constantly need to be looking at the implementation of components I consume to know if I need to use styled() or .extend.

It was made clear in the transition to v2 and the docs that the factory is now to be used only for third-party components. And `extend` (which exists for the same reason as the tag shorthands: brevity) for StyledComponents.

Optimally you'll never have to wrap your own components or wrap a StyledComponent. So the ambiguity resolves itself.

https://www.styled-components.com/docs/basics#styling-any-components
https://www.styled-components.com/docs/basics#extending-styles

**Comment by probablyup** [comment] 2017-08-13 19:27
@k15a I understand that you can use styled(StyledThing) today, but it's not using the semantics of .extend which is suboptimal and can lead to unexpected consequences like classes out of order. Hence the desire to adjust the implementation

**Comment by philpl** [comment] 2017-08-13 19:28
@probablyup see my comment (and also the edit for the reason of why I closed this)

> I understand that you can use styled(StyledThing) today

The keyword is *can*, but *shouldn't*. Maybe a docs issue can help here.

**Comment by probablyup** [comment] 2017-08-13 19:31
> It was made clear in the transition to v2 and the docs that the factory is now to be used only for third-party components. And extend (which exists for the same reason as the tag shorthands: brevity) for StyledComponents.

Perhaps, but you aren't addressing the core DX issue I brought up that the consumer shouldn't have to have perfect knowledge of the TYPE of component they're consuming. 

At best it's irritating, at worst it's nigh impossible if you're consuming a third party library and don't know the impl of their components. Could be a mix of direct styled component primitives and React components...

**Comment by probablyup** [comment] 2017-08-13 19:33
Also, it bothers me that you close issues without allowing some discussion around the subject. Maybe the original decision was suboptimal or made without some use cases in mind. 

I don't mind contributing, but this behavior is hostile and I'm getting to the point where I'd rather just fork than try to convince you of things.

**Comment by philpl** [comment] 2017-08-13 19:39
@probablyup 

> Perhaps, but you aren't addressing the core DX issue I brought up that the consumer shouldn't have to have perfect knowledge of the TYPE of component they're consuming.

There is no type here. Third-party or your own is not a type but perfectly normal knowledge that can even just be inferred by the import statement.

> At best it's irritating, at worst it's nigh impossible if you're consuming a third party library and don't know the impl of their components.

You don't have to know anything except whether they accept a className. It's captured by a note here in the docs which are visually "marked" to look important: https://www.styled-components.com/docs/basics#styling-any-components

> Also, it bothers me that you close issues without allowing some discussion around the subject. Maybe the original decision was suboptimal or made without some use cases in mind.

We had some fair discussions around it. I'm happy to reopen it, but please reconsider the reasons I've brought to the table and address them directly. I've resolved the DX question for you, and I think it's only partly confusing due to the new docs and v2 not agreeing with best practices in v1. Other than that, all the cases are documented in the docs.

**Comment by probablyup** [comment] 2017-08-13 19:41
> perfectly normal knowledge that can even just be inferred by the import statement.

How so?

```js
import { Thing } from 'place';
```

does not tell me if `Thing` is a normal React component or a styled component. That knowledge is required in order to select the proper API and get the expected behavior.

**Comment by probablyup** [comment] 2017-08-13 19:48
> You don't have to know anything except whether they accept a className.

This is not always easy to obtain. Many libraries strip out their propTypes for production builds and/or don't mention `className` at all because they simply spread-apply given props. A component is effectively opaque to the consumer with the exception of any documentation (if available.)

The `styled` function however knows which components are their own and has the information to make that decision every time.

**Comment by philpl** [comment] 2017-08-13 19:53
There are several places to look through, if you'd like to know why we chose to add the three methods that are now part of v2 (in order):

- https://github.com/styled-components/styled-components/issues/45
- https://github.com/styled-components/styled-components/issues/291#issuecomment-272659197
- https://github.com/styled-components/styled-components/issues/494#issuecomment-296374445
- https://github.com/styled-components/styled-components/pull/46
- https://github.com/styled-components/styled-components/pull/814

We even have some references to what you're proposing here:

> I'm kinda thinking that when we call styled(X) we should do something different if X is a StyledComponent itself. Maybe just take its rules set and append ours? Gonna try it.

The problem is that this introduces inelegance. This is doing something unexpected and totally different from what is usually done by the factory.

So then the need for `withComponent` arises. Which was `extendWith` before. This was because the most common use-case that wasn't covered was: "I want to use this StyledComponent again but with slightly different styling and a different tag". This was then simplified to `withComponent` and `extend`.

It was chosen because of the elegance. It is very easy to understand what `.extend` does, since it's very expressive. `styled(StyledComponent)` introduces a special case, like what you are already stating yourself. We'd get issues regarding the special behaviour and how it can be prevented, or why it's there. On the other side, I haven't seen an issue about `.extend` or class ordering anymore since the release of v2 until now.

I'd like to add that we almost never add new methods, except when we know that they solve actual problems. We've had and have a lot of API proposals. Some unfortunately just don't go on long, if they simply don't fit the original vision of simplicity.

Edit: If the argument just hinges on whether you know whether a component is yours or whether a third-party component does things you'd expect it to do, then is the argument really about our API? :wink: Because I think it works, has proven itself, has stabilised, and suits our taste (and it is just a matter of taste)

I think I've made my standpoint clear here. Maybe @mxstbr or @geelen would like to add 2 or 3 more sentences, but we'll see :smile:

**Comment by probablyup** [comment] 2017-08-13 19:59
> It was chosen because of the elegance.

I get what you're saying, but I strongly feel it inhibits productivity and introduces unnecessary cognitive load. As with the axiom of function over form when it comes to engineering, productivity should always prevail over elegance/aesthetics where it makes sense.

Like I'm not bringing this up just because I don't personally like it. Actual other people have commented to me that this is confusing and subtle bugs crop up due to the choices around which API to use.

It also doesn't help if the underlying component changes, like if someone is able to simplify their setup enough to discard the outer React component layer and directly export a styled component. That isn't a breaking change in semver land, but it is in terms of what API you're supposed to use with this library. The unified `styled` function would handle that use case perfectly.

**Comment by geelen** [comment] 2017-08-14 04:35
I agree with @philpl here totally. The API that we have has come about because _each_ case fits the ergonomics of a _single_ use-case better than one that tries to fit them all. Working with primitives? `styled.div`. Working with components? Use `styled(Comp)` and make sure `Comp` accepts a `className` prop. Extending an existing component? `Foo.extend`. Want to change the tag underneath a component? `Foo.withComponent`.

These all produce styled components and so on the surface they might seem similar enough to unify, but they're really not. I always prefer explicit APIs, especially when there are meaningful differences between similar-looking things. Whitelisting, as you touched on, is a crucial difference between styling primitives and components (I actually implemented to have `styled.div` include the whitelist and `styled('div')` not, but that work was tied up with a branch that has gotten totally stuck).

To pick up on one point: using `extend` across package boundaries is _absolutely not recommended_. You should _never_ depend on the internals of a package, only its public API. And for most cases that should just be "a React component that accepts a className prop". **All styled components pass that test**, so do virtually all components created with other CSS-in-JS approaches, so it's the only public API you should be expecting.

Phil's linked off to _a lot_ of the existing discussion around this, which you're welcome to read to better understand how we came to these decisions. In particular, we used to have `styled(X)` and now we have `X.extend`, and it took a major version bump to change it. So, it's not something we haven't thought about, and there's nothing in this thread that we haven't already considered.

I'm going to close this issue as well, since the issues at hand have already been decided on. It doesn't mean the end of the discussion, but I prefer to keep open issues for things that are still undecided. Of course, it would be even better if you could find the issues where some aspect of the API was originally discussed and reply to the arguments _there_. That way we can have any further ideas debated in the context in which they arose.

> I don't mind contributing, but this behavior is hostile and I'm getting to the point where I'd rather just fork than try to convince you of things.

You're free to fork the project, but if I were you I'd simply implement a shim on top of our API to get the API you want. It should be as simple as:

```js
import styled from 'styled-components'

export default arg => {
  if (typeof arg.extend === "function") return arg.extend
  else return styled(arg)
}

export { css, keyframes, injectGlobal, ThemeProvider, withTheme, ServerStyleSheet, StyleSheetManager } from 'styled-components'
```

If you try that out for a while and really like it, and other folks do too, then it might be worth reopening this. But IMO it hides an important difference between primitives/components/extension, without actually _abstracting_ over it. So I think it's just setting up an expectation that's going to be invalidated somewhere down the track, which is what the current design is trying to avoid.

**Closed by geelen** 2017-08-14 04:35 UTC
Labels: discussion

**Comment by probablyup** [comment] 2017-08-14 04:41
I'm getting mixed signals here. Phil specifically said not to use `styled(StyledComponent)` because it's apparently not supported or well tested because you're supposed to use `.extend` for overriding a styled component. Is that not the case?

**Comment by geelen** [comment] 2017-08-14 04:51
No it's perfectly fine, it's just... when you usually use it, you don't actually _want_ a hierarchy of components. You want multiple variants of one component:

```js
const X = styled.div` ... `

const BetterX = X.extend` ... `
const DifferentBetterX = BetterX.extend` ... `
```

In this case, each component is flattened, simply taking the rules of the previous and creating a new component rendering a `div`. That's pretty different to adding styles to a component that comes from somewhere else. In general, use `extend` when there's no ambiguity about the fact that you're cloning a new variation of an existing SC. Use `styled(Comp)` everywhere else.

**Comment by mxstbr** [comment] 2017-08-14 05:07
Yep, we should add that note to the docs @geelen @philpl!
