### ISSUE TITLE
Using with React-Native and TypeScript, import implicity has 'any' type

### ISSUE THREAD

**Issue by wesleyguirra** [styled-components/styled-components#2370] opened 2019-02-04 12:55 UTC
When using styled-components/native importing default has an implicity any, causing IDE showing the following error:

```
Error:(2, 20) TS7016: Could not find a declaration file for module 'styled-components/native'. '/Users/<user>/Development/<project>/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.
```

## System:
 - OS: macOS 10.14.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 290.28 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.14.1 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3 

## Reproduction
just import  styled-components/native

## Steps to reproduce
insert `import styled from 'styled-components/native';`

## Expected Behavior
Don't show TS7016 error.

## Actual Behavior
Showing the following error: Error:(2, 20) TS7016: Could not find a declaration file for module 'styled-components/native'. '/Users/<user>/Development/<Project>/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.

**Comment by JKillian** [comment] 2019-02-06 22:30
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29795 I believe. I have a [PR open in DT](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843) to fix this issue

**Comment by probablyup** [comment] 2019-02-06 22:32
Thanks @JKillian

**Closed by probablyup** 2019-02-06 22:32 UTC

**Comment by B3ns44d** [comment] 2020-12-09 13:49
import styled from 'styled-components/native';

The Error was like this:
Error:(2, 20) TS7016: Could not find a declaration file for module 'styled-components/native'. '/Users/<user>/Development/<project>/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.

**Solution**: All you have to do is edit your TypeScript Config file (tsconfig.json) and add a new key-value pair as
**"noImplicitAny": false**

**Comment by AndreCosta101** [comment] 2021-01-20 20:30
Add types for react-native:
`❯ yarn add @types/styled-components-react-native -D `

**Comment by jbrmaiden** [comment] 2021-01-21 14:58
I have `"styled-components": "5.2.0" `  and `"@types/styled-components-react-native": "5.1.0",`, but the error remains.

I have tried removing node_modules, deleting yarn.lock and everything, but it still does not work.

May you give me some advice?

> Add types for react-native:
> `❯ yarn add @types/styled-components-react-native -D `

**Comment by B3ns44d** [comment] 2021-01-21 23:05
> I have `"styled-components": "5.2.0" ` and `"@types/styled-components-react-native": "5.1.0",`, but the error remains.
> 
> I have tried removing node_modules, deleting yarn.lock and everything, but it still does not work.
> 
> May you give me some advice?
> 
> > Add types for react-native:
> > `❯ yarn add @types/styled-components-react-native -D `

check this out its works for me 

https://github.com/styled-components/styled-components/issues/2370#issuecomment-741783005

**Comment by capdilla** [comment] 2021-04-13 10:54
My problem was because i have the `"typeRoots": ["./src/types"]` in `tsconfig.json`, so what i did was add `node_modules/@types` and let the `typeRoots` like this `"typeRoots": ["node_modules/@types", "./src/types"],`

**Comment by carlos-cne** [comment] 2021-04-19 02:57
> My problem was because i have the `"typeRoots": ["./src/types"]` in `tsconfig.json`, so what i did was add `node_modules/@types` and let the `typeRoots` like this `"typeRoots": ["node_modules/@types", "./src/types"],`

Thanks! This solution solves my problem. :)

**Comment by luizeduul** [comment] 2021-04-19 18:41
> Add types for react-native:
> `❯ yarn add @types/styled-components-react-native -D `

Thanks brow.
I was with the same error and you helped me.

**Comment by chrisarts** [comment] 2021-04-26 18:13
> My problem was because i have the `"typeRoots": ["./src/types"]` in `tsconfig.json`, so what i did was add `node_modules/@types` and let the `typeRoots` like this `"typeRoots": ["node_modules/@types", "./src/types"],`

This solve my problem, thanks.

**Comment by almeidacavalcante** [comment] 2021-06-26 16:06
> Add types for react-native:
> `❯ yarn add @types/styled-components-react-native -D `

Thank you very much indeed...

**Comment by hlspablo** [comment] 2021-07-29 16:13
> My problem was because i have the `"typeRoots": ["./src/types"]` in `tsconfig.json`, so what i did was add `node_modules/@types` and let the `typeRoots` like this `"typeRoots": ["node_modules/@types", "./src/types"],`

My Hero

**Comment by sylvainlg** [comment] 2022-09-25 15:37
Hi,

For VSCode users, I found this tips on [StackOverflow](https://stackoverflow.com/a/73221043/2532137).
The error was still present before i did this (don't forget to restart VSCode after).

```
{
  "extends": "some/tsconfig.base",
  "compilerOptions": {
    // ...
    "types": [
      "jest",
      "cypress",
      "@testing-library/cypress",
      "@types/styled-components-react-native"
    ]
  },
  // ...
}
```

**Comment by jzamituy** [comment] 2023-01-13 14:52
> Hi,
> 
> For VSCode users, I found this tips on [StackOverflow](https://stackoverflow.com/a/73221043/2532137). The error was still present before i did this (don't forget to restart VSCode after).
> 
> ```
> {
>   "extends": "some/tsconfig.base",
>   "compilerOptions": {
>     // ...
>     "types": [
>       "jest",
>       "cypress",
>       "@testing-library/cypress",
>       "@types/styled-components-react-native"
>     ]
>   },
>   // ...
> }
> ```

Worked for me! Thank you!

**Comment by thomascostta** [comment] 2023-09-11 12:28
This way it worked for me:

**"styled-components": "^6.0.7"**

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "typeRoots": ["node_modules/@types", "./src/@types"],
    "types": [
      "jest",
      "@types/styled-components-react-native"
    ]
  }
}
```

thank you gentlemen!

**Comment by erie-e9** [comment] 2025-03-15 04:24
Hey guys, any advice for it in 2025?
 
I just tested next solutions using "styled-components": "^6.1.15" but no success:

1. edit tsconfig.json:
```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "typeRoots": ["node_modules/@types", "./src/@types"],
    "types": [
      "jest",
      "@types/styled-components-react-native"
    ]
  }
}
```

2. Install dev package: 
`yarn add @types/styled-components-react-native -D`


3. "noImplicitAny": false (It's not really a fix, just turn off warnings, I guess)

### My current tsconfig.json file:


```
{
  "compilerOptions": {
    "target": "esnext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "lib": ["es2017"],
    "isolatedModules": true,
    "strict": true /* Enable all strict type-checking options. */,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "noEmit": true,
    "moduleResolution": "node",
    "skipLibCheck": false,
    "jsx": "react-native",
    "types": ["react-native", "jest", "node", "@types/styled-components-react-native"],
    "typeRoots": ["node_modules/@types", "./src/types"],
    "baseUrl": "./",
    "paths": {
      "@*": ["./src/*"],
      "@hooks/*": ["./src/hooks/*"],
      "@hooks": ["./src/hooks/index.ts"],
      "@navigators/*": ["./src/navigators/*"],
      "@navigators": ["./src/navigators/index.ts"],
      "@components/*": ["./src/components/*"],
      "@components": ["./src/components/index.ts"],
      "@redux/*": ["./src/redux/*"],
      "@redux": ["./src/redux/index.ts"],
      "@store/*": ["./src/redux/store/*"],
      "@store": ["./src/redux/store/index.ts"],
      "@slices/*": ["./src/redux/store/slices/*"],
      "@slices": ["./src/redux/store/slices/index.ts"],
      "@assets/*": ["./src/assets/*"],
      "@assets": ["./src/assets"],
      "@services/*": ["./src/services/*"],
      "@services": ["./src/services"],
      "@env": [".env"],
      "@libs/*": ["./src/utils/libs/*"],
      "@libs": ["./src/utils/libs/index.ts"],
      "@utils/*": ["./src/utils/*"],
      "@utils": ["./src/utils/index.ts"],
      "@theme/*": ["./src/theme/*"],
      "@theme": ["./src/theme/index.ts"],
      "@types/*": ["./src/utils/types/*"],
      "@types": ["./src/utils/types/index.ts"]
    }
  },
  "extends": "@react-native/typescript-config/tsconfig.json",
  "exclude": ["node_modules", "babel.config.js", "metro.config.js", "jest.config.js"]
}

```

**Comment by DeepakCodeWaves** [comment] 2025-07-07 10:13
> Hi,
> 
> For VSCode users, I found this tips on [StackOverflow](https://stackoverflow.com/a/73221043/2532137). The error was still present before i did this (don't forget to restart VSCode after).
> 
> ```
> {
>   "extends": "some/tsconfig.base",
>   "compilerOptions": {
>     // ...
>     "types": [
>       "jest",
>       "cypress",
>       "@testing-library/cypress",
>       "@types/styled-components-react-native"
>     ]
>   },
>   // ...
> }
> ```

@sylvainlg  It fixed the issue
