### ISSUE TITLE
styled-components does not load dynamic styles with Loom extension

### ISSUE THREAD

**Issue by brandon-leapyear** [styled-components/styled-components#2885] opened 2019-11-20 00:01 UTC
### System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 1.83 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 12.13.0
 - Yarn: 1.19.1
 - npm: 6.12.0

## Reproduction

https://repl.it/@brandonleapyear/styled-components-loom-bug
```tsx
const MyDiv = styled.div<{ error: boolean }>`
  color: ${(p) => p.error ? 'red' : 'blue'};
`

export const MyComponent = () => {
  const [error, setError] = useState(false)
  return (
    <div>
      <button onClick={() => setError(!error)}>Toggle error</button>
      <MyDiv error={error}>Message</MyDiv>
    </div>
  )
}
```

## Steps to reproduce

1. Install the Loom Chrome extension
2. Go to https://styled-components-loom-bug--brandonleapyear.repl.co/
3. Click the button repeatedly

## Expected Behavior

The text should flash between red and blue

## Actual Behavior

The text flashes between red and no style (black)

**Comment by coderbyheart** [comment] 2019-11-20 12:50
Can reproduce this on Linux w/ Chromium | 78.0.3904.97 (Official Build) Arch Linux (64-bit)

**Comment by vladpasculescu** [comment] 2019-11-20 14:56
Wow, you're a life saver - I've been pounding at my keyboard since yesterday to try to figure out why I was getting issues.

**Comment by tomdracz** [comment] 2019-11-20 17:14
Can reproduce this also on 4.4.1 but NOT on 5.0.0 RC2

**Comment by toanjo** [comment] 2019-11-22 14:57
Can also confirm this, can also confirm it made me pull my hair out trying to figure out why the styles were not loading correctly on my app.
Chrome 78 on macOS Catalina.

Thanks for the catch!

**Comment by esetnik** [comment] 2019-11-22 22:37
This is bizarre but true. Thanks for reporting. I had no idea why all of my projects suddenly had their styles broken.

**Comment by coderbyheart** [comment] 2019-11-23 11:17
The Loom team is tracking this bug as LOOM-1401.

```
Hey Markus!

My name is Michael and I'm from the technical support team here at Loom! 👋

Thanks for bringing up the Loom<>StyledComponents bug on Twitter.

https://twitter.com/useloom/status/1197206017072869377

I have discussed this bug with our Engineers, and we decided to fill a bug report.

Our Engineering team will now prioritize your ticket.

The bug is registered under the name of LOOM-1401in case you ever need to follow up with us.

I will let you know as soon as I have new details or the next steps!
​
Thanks for your patience!

Have a great day!

michael
Loom Support Team
```

**Comment by probablyup** [comment] 2019-12-30 04:04
Going to close this since it's a third-party issue

**Closed by probablyup** 2019-12-30 04:04 UTC
