### ISSUE TITLE
Props not passing in react native.

### ISSUE THREAD

**Issue by irakli-janiashvili** [styled-components/styled-components#178] opened 2016-11-09 10:22 UTC
## Version
1.0.10

## Reproduction
This happens with the react native, props inside style not passing, I tried styling that way Text and View components, none of them are able to receive props.

## Steps to reproduce

Component styling:

```js
const Text = styled.Text`
  text-decoration-line: ${props => props.completed ? 'line-through' : 'none' };
  text-decoration-style: solid;
  text-decoration-color: #DB2B39;
`
```

In render:

```js
render () {
  return (
    ....
    <Text completed>This is a test text</Text>
    ....
  )
}
```

## Expected Behavior

![image](https://cloud.githubusercontent.com/assets/962095/20135181/d4ada558-a687-11e6-9f4f-da5a9e8c2047.png)

## Actual Behavior

![image](https://cloud.githubusercontent.com/assets/962095/20135193/e3952b86-a687-11e6-8b76-647ef4c31919.png)

Side note: this is associated on `text-decoration-line`, fact is that props are not received at all.

**Comment by rtkhanas** [comment] 2016-11-09 10:32
Duplicate of #138

**Comment by irakli-janiashvili** [comment] 2016-11-09 10:34
@rtkhanas oh haven't noticed this one, seems like that. closing.

**Closed** 2016-11-09 10:34 UTC
