### ISSUE TITLE
Could not find a declaration module for 'styled-theming'.

### ISSUE THREAD

**Issue by FantasticSWT** [styled-components/styled-components#1947] opened 2018-08-24 02:30 UTC
![image](https://user-images.githubusercontent.com/38369131/44561716-a165e300-a788-11e8-9b17-a5e619a5bb71.png)

Anyone got solution for this?

Please help.

**Comment by imbhargav5** [comment] 2018-08-24 02:48
Can you explain what exactly happened? It's hard to help when we don't know what the issue is in detail.

**Comment by FantasticSWT** [comment] 2018-08-24 02:50
I installed the module using "npm install --save styled-theming" version is 2.2.0.

But then, when i try to import this API, i facing the issue.

**Comment by imbhargav5** [comment] 2018-08-24 04:36
Did you try `npm install @types/styled-theming` as well?

**Comment by FantasticSWT** [comment] 2018-08-24 05:03
![image](https://user-images.githubusercontent.com/38369131/44566063-0415a980-a79e-11e8-98fc-706a0b0d7d8b.png)
I tried, but seem not working

**Comment by probablyup** [comment] 2018-08-24 06:53
Going to close this since it’s not even our library. Please open an issue with them.

**Closed by probablyup** 2018-08-24 06:53 UTC
Labels: typings :wrench:
