### ISSUE TITLE
Classes and styles not aplied after Gatsby Build

### ISSUE THREAD

**Issue by BraveLilToaster** [styled-components/styled-components#2629] opened 2019-06-18 17:43 UTC
I have been experiencing some unexpected behavior when trying to use `styled-components` in a Gatsby build that only seems to happen in production builds. I have a hook that changes the value of props being passed to a styled component. When the page is loaded in the browser it appears as though the styles are correct in react dev tools but the DOM does not reflect these changes.

It works as intended with `npm start`, but not with `npm build`
Example CodeSandbox: https://codesandbox.io/s/styled-components-issue-2629-js89j
Example Repo: https://github.com/BraveLilToaster/styled-components-issue-2629

### System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - Memory: 5.31 GB / 15.12 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
### Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.12.1 - /usr/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.10.1 => 1.10.1
 - styled-components: ^4.3.1 => 4.3.1

## Reproduction
1. Create new Gatsby project from the default-starter
2. `npm install --save gatsby-plugin-styled-components styled-components babel-plugin-styled-components`
3. Add a styled component that takes a prop like color.
4. Add a hook to set the color based on screen size. 

## Steps to reproduce
1. Run `npm run build`
2. Run `npm run serve`

## Expected Behavior
Screen size is detected to be over 900px wide. Value of props passed down to the styled components change. Classes/styles update in the DOM.
![image](https://user-images.githubusercontent.com/8815195/59778999-799abb00-9285-11e9-99b8-ebc70cb96a83.png)

## Actual Behavior
Screen size is detected to be over 900px wide. Value of props passed down to the styled components. Classes/styles update in react dev tools, but the DOM maintains the same classes/styles from the initial load.
![image](https://user-images.githubusercontent.com/8815195/59778936-612aa080-9285-11e9-9509-91f9355d2a76.png)

**Comment by Slashgear** [comment] 2019-06-18 21:18
You should consider reading this [documentation about styled component with gatsby](gatsby-plugin-styled-components)

You forgot to add `gatsby-plugin-styled-components` in your dependencies.

**Comment by BraveLilToaster** [comment] 2019-06-19 15:12
Thanks @Slashgear. I totally forgot to add `gatsby-plugin-styled-componets` to `gatsby-config.js` in the code sandbox. I do have it on my local environment and am still experiencing this issue in production builds. I have updated the CodeSandbox so you can see it working in the dev environment, and I am including a repo to clone since I was unable to find a way to run the production build in CodeSandbox.

**Comment by probablyup** [comment] 2019-06-20 18:23
@BraveLilToaster I just booted up your sandbox and it looks like it's working as expected?

**Comment by BraveLilToaster** [comment] 2019-06-21 18:10
@probablyup thanks for checking out my issue. I have no problem getting it to work in the sandbox because it is using the the Development build of Gatsby. When I try it with the production build I experience the issue that I reported. I included a repo so you may try it for yourself. Apologies for any confusion.

**Comment by BraveLilToaster** [comment] 2019-06-25 16:03
@probablyup, did you get a chance to try building for production yet. I am still experiencing this bug and haven't made any headway.

**Comment by probablyup** [comment] 2019-07-01 15:06
This is a weird one... I see the class being injected into the stylesheet but the dynamic style class on the HTML itself isn't changing...

Aside from that you're actually violating the rules of hooks with your `useMedia` hook. Rewritten to be compliant:

```js
import { useCallback, useMemo, useState, useEffect } from "react"

function useMedia(queries, values, defaultValue) {
  console.log("check media query", queries, values)

  // Array containing a media query list for each query
  const mediaQueryLists = useMemo(
    () =>
      typeof window === "undefined"
        ? []
        : queries.map(q => window.matchMedia(q)),
    [queries]
  )

  // Function that gets value based on matching media query
  const getValue = useCallback(() => {
    // Get index of first media query that matches
    const index = mediaQueryLists.findIndex(mql => mql.matches)

    // Return related value or defaultValue if none
    return typeof values[index] !== "undefined" ? values[index] : defaultValue
  }, [defaultValue, mediaQueryLists, values])

  // State and setter for matched value
  const [value, setValue] = useState(getValue)

  useEffect(
    () => {
      // Event listener callback
      // Note: By defining getValue outside of useEffect we ensure that it has
      // current values of hook args (as this hook callback is created once on mount).
      const handler = () => setValue(getValue)

      // Set a listener for each media query with above handler as callback.
      mediaQueryLists.forEach(mql => mql.addListener(handler))

      // Remove listeners on cleanup
      return () => mediaQueryLists.forEach(mql => mql.removeListener(handler))
    },

    [] // Empty array ensures effect is only run on mount and unmount
  )

  return value
}

export default useMedia

```

**Comment by probablyup** [comment] 2019-07-01 15:14
I even debugged the s-c injection phase and see the correct class going through into render. Appears to some sort of strange React behavior

**Comment by probablyup** [comment] 2019-07-01 22:31
cc @gaearon there might be a react bug in production mode w/ hooks here. It definitely can see a render() pass happening with the correct props and the DOM partially updates (the explicit text of "color") in production mode but the `className` is not updated in the DOM.

If a render happens before rehydration completes would that explain devtools having correct values but the DOM being out of sync?

**Comment by BraveLilToaster** [comment] 2019-07-02 16:19
@probablyup, thank you for taking a look at this and for helping me make the useMedia. I put an [issue](https://github.com/gatsbyjs/gatsby/issues/15033#issuecomment-505854244) in the Gatsby with as well. They suggested that the issue may be a hydration problem too.

**Comment by BraveLilToaster** [comment] 2019-07-11 14:39
Hey @probablyup and @gaearon,

Here is a link to the [response](https://github.com/gatsbyjs/gatsby/issues/15033#issuecomment-505854244) I got from The issue I opened with Gatsby. 

From my limited understanding it seems like it is an issue of a mismatch in the HTML and the virtual DOM. Is this right or am I misunderstanding something?

From https://reactjs.org/docs/react-dom.html

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

**Comment by JCQuintas** [comment] 2019-08-18 11:49
Hi, I've come across a similar issue. The way I came up to _alleviate_ this was to render `null` at first and then display the component. Hardly a fix, but at least the layout is correct on initialization.

In your example the `IndexPage` would look something like this

```jsx
const IndexPage = () => {
  const color = useMedia(["(min-width: 900px)"], ["green"], "red")
  const [render, setRender] = useState(false)

  useEffect(() => {
    // setRender(true)
    const timeout = setTimeout(() => setRender(true), 100)
    return () => clearTimeout(timeout)
  }, [])

  if (!render) return null

  return (
    <Layout>
      <SEO title="test" />
      <p>color: {color}</p>
      <ColorBox color={color}>
        <h1>box should be green on screens larger than 900px</h1>
      </ColorBox>
    </Layout>
  )
}
```

The **pro** is that layout is correct. The **con** is that the page will always blink when reloading and takes `~100ms` to appear.

**Comment by iDVB** [comment] 2019-12-03 19:25
We're experiencing this same issue.

## System:
**OS:** macOS 10.14.5
**Node:** 10.16.0 
**Yarn:** 1.17.3
**npm:** 6.9.0

**gatsby:** ^2.15.14
**babel-plugin-styled-components:** ^1.10.6
**styled-components:** ^4.3.2

Everywhere on the site where we have a variable (`enhanced` comes from `localstore`) that affects the style, these styles are NOT be applied/rendered.

Example:
![image](https://user-images.githubusercontent.com/189506/70082305-19e86000-15d8-11ea-81fd-846b3d212fea.png)

Everything above in that style definition DOES render... but everything in that `!enhanced` test DOES NOT. Even though it work in dev/local and works if you make the value of enhanced MATCH what was rendered during SSR. 

Also, when we TEST that `enhanced` value inside of the style definition is consoles as the correct `false` value. So we know styled-components is getting the right value.... its just not applying THESE styles dependant on this variable to the component on hydrate.

**Comment by probablyup** [comment] 2020-01-02 18:20
Can people test this with v5 rc3?

**Comment by decepulis** [comment] 2020-01-27 21:17
I _think_ I'm still encountering this as of v5.
(if I understand the issue correctly 😳Gatsby, styled components, and hydration are pretty new turf for me)

My Gatsby site provides an item from localStorage to the styled-components ThemeProvider.

In dev mode, this is fine. The site loads in whatever mode was stored in localStorage.
In production mode, however, upon loading the mode from localStorage, my `GlobalStyle` responds to the theme, whereas my styled components do not.

I tried to make a demo of this, both in [a repo](https://github.com/decepulis/styled-components-issue-2629), and below in the Reproduction section.

Happy to answer questions or provide details!

## Environment
`package.json`
```json
  "dependencies": {
    "babel-plugin-styled-components": "^1.10.7",
    "gatsby": "^2.19.7",
    "gatsby-plugin-styled-components": "^3.1.18",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "styled-components": "^5.0.0"
  },
```
`gatsby-config.js`
```js
module.exports = {
  plugins: [`gatsby-plugin-styled-components`],
}
```

## Reproduction
`src/pages/index.js`
```jsx
import React, { useState, useEffect } from "react"
import styled, { createGlobalStyle, ThemeProvider } from "styled-components"

// GlobalStyle should set the body background to red
// unless the theme is localstorage; then the background is green
const GlobalStyle = createGlobalStyle`
  body {
    color: white;
    background-color: red;
    ${props =>
      props.theme.mode === "localstorage" && "background-color: green;"}
  }
`

// StyledP should set its background to blue
// unless the theme is localstorage; then the background is green
const StyledP = styled.p`
  background-color: blue;
  ${props => props.theme.mode === "localstorage" && "background-color: green;"}
`

export default () => {
  // We load the state from localstorage,
  // defaulting to 'default' if localstorage is unavailable or unset.
  // This means that the ssr site will always be rendered as 'default'
  const [theme, setTheme] = useState(
    typeof window !== "undefined"
      ? localStorage.getItem("storageTheme") ?? "default"
      : "default"
  )

  // enabling this effect alleviates the issue,
  // but causes a flash of un-themed content

  // useEffect(() => {
  //   setTheme(localStorage.getItem("storageTheme") ?? "default")
  // }, [setTheme])

  const changeTheme = event => {
    localStorage.setItem("storageTheme", event.target.value)
    setTheme(event.target.value)
  }
  return (
    <ThemeProvider theme={{ mode: theme }}>
      <GlobalStyle />

      <h1> The theme is {theme} </h1>

      <p>
        GlobalStyle turns the body red when 'default', green when 'localstorage'
      </p>
      <StyledP>
        StyledP turns this blue when 'default', green when 'localstorage'
      </StyledP>

      <select value={theme} onChange={changeTheme}>
        <option value="default">Default</option>
        <option value="localstorage">LocalStorage</option>
      </select>
    </ThemeProvider>
  )
}
```

**Comment by matthova** [comment] 2020-04-07 22:16
@decepulis thanks for putting this minimal repro together 🙌🏻
Can confirm this same behavior, even with the current latest versions of all of the packags
```
  "dependencies": {
    "babel-plugin-styled-components": "^1.10.7",
    "gatsby": "^2.20.13",
    "gatsby-plugin-styled-components": "^3.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "styled-components": "^5.1.0"
  },
```

**Comment by decepulis** [comment] 2020-04-07 22:18
This is what we're running into, isn't it?
https://joshwcomeau.com/react/the-perils-of-rehydration/

**Comment by FrancisCalizo** [comment] 2020-05-05 19:35
@decepulis Thank you for the example repo! This was (I guess still is) driving me crazy. 

I have nearly identical code to yours and exact same issues: My theme styles are loaded perfectly from localStorage in development mode. But when it comes to production, only some styles load and some do not (seems to be all the child components that do not load the theme styles). But if I were to change the theme through user interaction, voila! Everything works perfectly.

I currently am using your "useEffect" temporary solution. I suppose the "flash" is better than the mess of colors of multiple themes. I suppose we're still not at a resolution to this issue?

**Comment by decepulis** [comment] 2020-05-05 19:42
I haven’t tried it myself because my projects have taken me a different direction, but Josh Comeau has a great follow-up article to the one I posted earlier that presents a potential solution to this hydration-caused flash.  


https://www.joshwcomeau.com/gatsby/dark-mode/

His solution isn’t specific to styled-components but maybe his work could still point you in the right direction!

**Comment by DekiGk** [comment] 2020-07-15 19:13
@BraveLilToaster did you solve your initial issue?

I followed the response you got on your issue within Gatsby project. In my case I could see this error in dev mode:

```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```

It was an element a bit earlier than the element I had problem with. When I fixed that, everything was back to normal. Hopefully this helps someone out there.

**Comment by AdamAnSubtractM** [comment] 2021-06-03 01:54
> @decepulis Thank you for the example repo! This was (I guess still is) driving me crazy.
> 
> I have nearly identical code to yours and exact same issues: My theme styles are loaded perfectly from localStorage in development mode. But when it comes to production, only some styles load and some do not (seems to be all the child components that do not load the theme styles). But if I were to change the theme through user interaction, voila! Everything works perfectly.
> 
> I currently am using your "useEffect" temporary solution. I suppose the "flash" is better than the mess of colors of multiple themes. I suppose we're still not at a resolution to this issue?

I too am having almost an identical issue. Its a bit disheartening.

**Comment by AdamAnSubtractM** [comment] 2021-06-04 02:24
> I haven’t tried it myself because my projects have taken me a different direction, but Josh Comeau has a great follow-up article to the one I posted earlier that presents a potential solution to this hydration-caused flash.
> 
> https://www.joshwcomeau.com/gatsby/dark-mode/
> 
> His solution isn’t specific to styled-components but maybe his work could still point you in the right direction!

Update -- In the above comment, i mentioned I was feeling pretty disheartened by the hydration issue. I just read Josh's blog post on rehydration and setting up dark mode in Gatsby and I'm feeling much better about his solution! I'm definitely going to give it a try!

**Comment by koraysels** [comment] 2021-07-02 10:21
So how did you guys solved this ? we are facing the same issue with a simple styled component..

**Comment by AdamAnSubtractM** [comment] 2021-07-02 13:34
> So how did you guys solved this ? we are facing the same issue with a simple styled component..

I had to rework the way I was implementing dark mode entirely and follow the approach the Josh w Comedy took for dark mode here. It wasn't ideal but worked well for my case.

https://www.joshwcomeau.com/gatsby/dark-mode/

**Comment by kitten** [comment] 2021-08-09 18:30
This seems like an external issue, but for now I'm closing this, since the topic is "SC with X" and not an issue with styled-components on its own or itself.

**Closed by kitten** 2021-08-09 18:30 UTC
