### ISSUE TITLE
Flow errors being returned in 1.4.3

### ISSUE THREAD

**Issue by garetmckinley** [styled-components/styled-components#458] opened 2017-02-05 16:01 UTC
## Version
1.4.3

## Description

Previously [hedron](https://github.com/JSBros/hedron) has been using `styled-components` 1.1.3, but after updating to 1.4.3, flow has started giving me an error when running `flow` inside my repos directory.

```
node_modules/styled-components/dangerfile.js:3
  3: import { danger, warn, fail, message } from 'danger'
                                                 ^^^^^^^^ danger. Required module not found

node_modules/styled-components/lib/models/StyleSheet.js.flow:18
 18:   get injected(): boolean {
       ^ Potentially unsafe get/set usage. Getters and setters with side effects are potentially unsafe and disabled by default. You may opt-in to using them anyway by putting `unsafe.enable_getters_and_setters=true` into the [options] section of your .flowconfig.


Found 2 errors
```

I'm not extremely well versed in flow, so I'm not 100% sure it's not a problem in my configuration of flow. But since it has previously been working fine, I'm thinking it must be related to `styled-components`. The second error looks like I can resolve it with the suggested `.flowconfig` change, but I'm not sure about the first one.

**Comment by nfarina** [comment] 2017-02-06 17:06
Confirming that the flow-suggested workaround for "unsafe get/set usage" works. However I'm not seeing the `danger` import problem (I also don't have `danger` anywhere in my `node_modules`). What version of flow are you running?

**Comment by mxstbr** [comment] 2017-02-06 18:19
cc @styled-components/typers

**Comment by relekang** [comment] 2017-02-06 19:04
This should be fixed by #334 I think.

**Comment by xcoderzach** [comment] 2017-02-08 23:15
The second error is strange, because it *is* in the config :-/

https://github.com/styled-components/styled-components/blob/master/.flowconfig#L18

**Comment by bdegreve** [comment] 2017-03-08 10:02
About the second one (get injected()):

It appears flow doesn't actually check if the getter has side effects or not (this one doesn't as far as I can tell), but just borks on getters in general.

Unless this has been added to the .flowconfig
```
unsafe.enable_getters_and_setters=true
```
This being present in styled-components' .flowconfig isn't enough as xcoderzach already has discovered :-) 

So this (single?) getter forces users of styled-components to add that configuration as well, even if they don't use any other getter anywhere else.  

This is a bit ugly IMHO. It's a big hammer for a small nail. Is this getter part of a public interface? And if not, any chance to replace it by a regular function?  Or are their other ways to get out of this?

(confirmed with 1.4.4)

**Comment by lachlanjc** [comment] 2017-03-25 21:15
I was getting these same errors. Adding `danger` and `expect` as dependencies to my project worked (they're devDependencies on styled-components but seem to be required for Flow to pass), though I'd rather not have them as I don't use either package in my own project. I also had to set the option mentioned in the first comment.

**Comment by relekang** [comment] 2017-04-05 17:18
styled-components now has libdefs in [flow-typed]. Try out 

```shell
npm i -g flow-typed # if you do not already have flow-typed
flow-typed install styled-components@1.4
```

[flow-typed]: https://github.com/flowtype/flow-typed

**Comment by hph** [comment] 2017-04-05 19:21
@relekang Thanks! Do you reckon adding types for v2 would be difficult?

**Comment by 0x80** [comment] 2017-04-10 09:54
I'm using 1.4.4 and followed all the instructions I could find, and installed the 1.4 libdefs, but I'm still getting these flow errors:

<img width="574" alt="screenshot 2017-04-10 11 51 28" src="https://cloud.githubusercontent.com/assets/1193520/24856166/15a6fe0a-1de4-11e7-8074-7a7f5e55e9d8.png">

Below is my config.  Am I missing something?

```
[ignore]
.*/scrape-from-contentful/.*
.*/fbjs/.*

# We vendor our src directory, which is not needed for type-checking
.*/styled-components/src/.*

.*/hedron/.*
.*/polished/.*
.*/typography/src/.*
.*/typography-plugin-code/src/.*

[include]

[libs]
# This is where your own flow-typed libdefs go
flow-typed

# These declarations are super explicit...
# We want to show what libdef files we need to make
# flow understand all external dependencies
#
# If you have similar dependencies, you will need to
# check which libdef files are covered by your flow-typed
# directory!
#
# A more generic approach (please use with caution!):
# node_modules/styled-components/flow-typed/*.js

node_modules/styled-components/flow-typed/react-native.js
node_modules/styled-components/flow-typed/lodash_v4.x.x.js
node_modules/styled-components/flow-typed/inline-style-prefixer_vx.x.x.js


[options]
esproposal.class_instance_fields=enable
esproposal.class_static_fields=enable
suppress_type=$FlowIssue

```

**Comment by hph** [comment] 2017-04-10 11:18
@0x80 The following worked for me (some of the rules may not be relevant for you):

```ini
[ignore]
<PROJECT_ROOT>/node_modules/styled-components/src/.*

[include]
<PROJECT_ROOT>/src

[libs]
<PROJECT_ROOT>/flow-typed

[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src

**Comment by relekang** [comment] 2017-04-10 11:52
> @relekang Thanks! Do you reckon adding types for v2 would be difficult?

I have not looked into it yet, but plan to do so.

**Comment by relekang** [comment] 2017-04-10 11:53
@0x80 @hph See updated docs in #656 as it has not been merged yet.

**Comment by ryyppy** [comment] 2017-04-10 12:15
@0x80 You should remove everything styled-components related from your `[libs]` section... so it should look like this:

```ini
[libs]
flow-typed
```

**Comment by 0x80** [comment] 2017-04-10 14:35
With the suggested configs the following seems to still be problematic:

```javascript
import styleSheet from 'styled-components/lib/models/StyleSheet'
```

I get a module not found error.

**Comment by ryyppy** [comment] 2017-04-10 19:54
A import path with `styled-components/lib` looks suspicious... is this public api?

If you need support for that, you will need to extend the library definition in your `flow-typed/npm` directory yourself by following the library definition convention.

It's perfectly fine to modify official library definitions, because a lot of people have different use-cases.

**Comment by 0x80** [comment] 2017-04-10 20:04
@ryyppy It is used by [Gatsby](https://github.com/gatsbyjs/) to inject styles into the head in production like so:

```javascript
import styleSheet from 'styled-components/lib/models/StyleSheet'
...

    let css
    if (process.env.NODE_ENV === 'production') {
      const styles = styleSheet.rules().map(rule => rule.cssText).join('\n')
      css = <style dangerouslySetInnerHTML={{ __html: styles }} />
    }

...
<head>
 {css}
</head>
```

**Comment by ryyppy** [comment] 2017-04-10 20:08
Ah, okay... well, I still couldn't find any API on the docs, so it's hard to tell what public API it should expose (@mxstbr ?) ...

For now, you can fix this by adding this to your styled-components libdef:

```
declare module 'styled-components/lib/models/StyleSheet' {
 declare module.exports: Object;
}
```

Not the cleanest solution, but hey: a good foundation for a contribution? :D

**Comment by ffxsam** [comment] 2017-05-16 00:27
Don't know if this is related, but I'm getting a whole slew of Flow errors:

```
node_modules/styled-components/flow-typed/npm/express_v4.x.x.js:5
  5: import type { Server } from 'http';
                   ^^^^^^ Named import from module `http`. This module has no named export called `Server`.

node_modules/styled-components/lib/models/InlineStyle.js.flow:3
  3: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/native/index.js.flow:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/utils/autoprefix.js.flow:2
  2: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/lib/utils/autoprefix.js.flow:3
  3: import hyphenateStyleName from 'fbjs/lib/hyphenateStyleName'
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/lib/utils/flatten.js.flow:2
  2: import hyphenate from 'fbjs/lib/hyphenateStyleName'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:3
  3: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:15
 15: describe('injectGlobal', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:16
 16:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:20
 20:   it(`should inject rules into the head`, () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:2
  2: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/keyframes.test.js:14
 14: describe('keyframes', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:15
 15:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:20
 20:   it('should return its name', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/constructors/test/styled.test.js:2
  2: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/styled.test.js:6
  6: describe('styled', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/styled.test.js:7
  7:   it('should have all valid HTML5 elements defined as properties', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/models/InlineStyle.js:3
  3: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/models/test/ThemeProvider.test.js:5
  5: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/models/test/ThemeProvider.test.js:9
  9: describe('ThemeProvider', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/models/test/ThemeProvider.test.js:10
 10:   it('should not throw an error when no children are passed', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/native/index.js:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/test/basic.test.js:3
  3: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/test/basic.test.js:5
  5: import jsdom from 'mocha-jsdom'
                       ^^^^^^^^^^^^^ mocha-jsdom. Required module not found

node_modules/styled-components/src/test/basic.test.js:12
 12: describe('basic', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/basic.test.js:16
 16:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/basic.test.js:20
 20:   it('should not throw an error when called', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/css.test.js:9
  9: describe('css features', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/css.test.js:10
 10:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/css.test.js:14
 14:   it('should add vendor prefixes in the right order', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/extending.test.js:4
  4: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/test/extending.test.js:11
 11: describe('extending', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/extending.test.js:15
 15:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/extending.test.js:19
 19:   it('should generate a single class with no styles', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/props.test.js:9
  9: describe('props', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/props.test.js:10
 10:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/props.test.js:14
 14:   it('should execute interpolations and fall back', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/styles.test.js:9
  9: describe('with styles', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/styles.test.js:13
 13:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/styles.test.js:17
 17:   it('should append a style', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/theme.test.js:2
  2: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/test/theme.test.js:3
  3: import jsdom from 'mocha-jsdom'
                       ^^^^^^^^^^^^^ mocha-jsdom. Required module not found

node_modules/styled-components/src/test/theme.test.js:13
 13: describe('theming', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/theme.test.js:14
 14:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/theme.test.js:18
 18:   it('should inject props.theme into a styled component', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/theme.test.js:214
214:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/theme.test.js:218
218:   it('should properly render with the same theme from default props on re-render', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/utils.js:6
  6: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/utils/autoprefix.js:2
  2: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/src/utils/autoprefix.js:3
  3: import hyphenateStyleName from 'fbjs/lib/hyphenateStyleName'
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found


... 18 more errors (only 50 out of 68 errors displayed)
To see all errors, re-run Flow with --show-all-errors
error Command failed with exit code 2.
```

**Comment by mxstbr** [comment] 2017-12-15 12:27
Closing this since it's for v1.4.3 and we're on v2.3.0 by now.

If you're still experiencing errors with flow, even after following our [flow setup documentation](https://www.styled-components.com/docs/api#flow) please open a new issue.

**Closed by mxstbr** 2017-12-15 12:27 UTC
Labels: bug
