### ISSUE TITLE
Is styled-components rehydration costly?

### ISSUE THREAD

**Issue by udayRedI** [styled-components/styled-components#3518] opened 2021-06-18 02:42 UTC
I'm using nextjs for SSR. I'm using [this](https://styled-components.com/docs/advanced#nextjs) technique to render styles on server side. So when DOM is downloaded it not just gets HTML but also all the CSS it needs to paint in a style tag.

Once the HTML is parsed it starts painting - good so far, the problem starts once JS is downloaded and parsed. Especially _app.js, styled-components deletes existing styles.
https://github.com/styled-components/styled-components/blob/902e72945712288b05dce3ee6d35e0af70005f1e/packages/styled-components/src/sheet/Rehydration.ts#L82

How does this affect performance?

My consensus:
- FCP and LCP will be delayed because of the repaint
- With the browser busy painting and repainting, main thread is blocked and might be unable to process user interaction, eventually resulting in framerate drop.

Does the same thing happen when route changes because it'll pull new JS files and compile and set styles. Is this the cost we have for styled-components?
Can we avoid this on first paint?

**Comment by kitten** [comment] 2021-07-28 14:29
This is a complex question; The short answer is: yes, it does impact performance, since it's an additional process. However, it does not impact FCP for SSR since we'll get a first paint without JS. What it does impact is TTI, time to interactivity.

The longer answer is more complex. In a dynamic styling library we inherently care about the order of styles as they're injected. styled-components cares about this more so even than other libraries. We group rules by the component that inserts them, and those groups are kept in order.

The rehydration process itself can hence not be skipped. Even more so, because we have an SSR mode where style tags are interspersed on the page if streamed SSR is used, we have to collect them all.

We actually had a more performant rehydration method even, where reading information out from the SSR process was sped up by using CSSOM for that as well. However, this caused some edge cases and other issues, so we specifically reverted that part of the implementation.

Now, the complex part of the answer is, in a perfect world inserting rules with CSSOM is fast and will almost never cause unnecessary style recalculations and paints until that process is done. In reality, I recently figured out that this process is broken in Chromium. (See https://bugs.chromium.org/p/chromium/issues/detail?id=1216451 and https://bugs.chromium.org/p/chromium/issues/detail?id=1046319)

This essentially increases the cost of using the CSSOM API linearly during normal use and exponentially for rehydration. There's currently not much we can do about this except for waiting for this to be addressed.

My advice generally is to monitor these costs and see if they remain acceptable. Up until thousands of rules it should remain fine, but past that all bets are off. CSS-in-JS is generally moving to a space where more precalculated styles are used via design tokens. In other words, if all values and style variables are known, not much if anything has to be handled dynamically, which is afaik more like what stitches does.

Overall, I had some approaches to reducing the cost of the rehydration process, but as mentioned that didn't quite pan out. And with the issue of Chromium's CSSOM performance regression, we've got fast times but non-trivial performance cliffs that may occur once you have a "huge" amount of rules per page.

**Closed by kitten** 2021-07-28 14:29 UTC

**Comment by udayRedI** [comment] 2021-08-03 18:08
> We group rules by the component that inserts them, and those groups are kept in order.


@kitten What do you mean by `rules` in general? 
```
const Container = styled("div")`
  height: 100vh;
`
```

Is height a rule grouped by `Container` component? Is this a fair interpretation ?

**Comment by kitten** [comment] 2021-08-09 16:13
@udayRedI: When you create a styled component, e.g. `ComponentA`, and then another one, e.g. `ComponentB`, then all rules from `ComponentB` will appear _after_ `ComponentA`'s rules in the style sheet.
