### ISSUE TITLE
[v4.0.0-beta.9] - argv.indexOf undefined (React Native)

### ISSUE THREAD

**Issue by pontusab** [styled-components/styled-components#2044] opened 2018-09-30 14:43 UTC
## Environment
```
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Memory: 2.87 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: v4.0.0-beta.9 => 4.0.0-beta.9 
```

<img width="415" alt="screenshot 2018-09-30 at 16 41 29" src="https://user-images.githubusercontent.com/655158/46258726-bb08f180-c4cf-11e8-835e-6b5d32c92ece.png">

Looks like a similar issue as this one: https://github.com/styled-components/styled-components/issues/409

**Comment by probablyup** [comment] 2018-09-30 19:10
I don't think this is on our side since we don't read argv anywhere in our codebase...

**Comment by probablyup** [comment] 2018-09-30 20:35
What version of RN? Just did a fresh install of both here and it's working fine.

**Comment by pontusab** [comment] 2018-10-01 11:03
Ah okey, I will investigate on my side then :), `0.57.1`

**Comment by nikhildaga** [comment] 2018-10-01 15:33
Facing the same issue on a new build.

```
    "react-native": "0.57.1",
    "styled-components": "^4.0.0-beta.9"
```

**Comment by probablyup** [comment] 2018-10-01 19:21
0.57.1 is actually broken in RN core isn't it? I know they're dealing with some issue around a deep react file they use being moved to a different folder

**Comment by nikhildaga** [comment] 2018-10-02 02:00
@probablyup : Its probablyTrue 😄  . 
Facing too many issues with the latest react native. I will try a different version.
Btw, were you able to resolve this issue?

**Comment by probablyup** [comment] 2018-10-02 05:10
@nikhildaga I'd stick with the 0.55.x or 0.56.x branch for now, they seem more stable.

**Comment by dawidk92** [comment] 2018-10-13 12:51
I have exacly the same issue here.

styled-components: `4.0.0-beta.11.3`
react-native: `0.55.4`

Btw I'm forced to use 0.55.x version of React Native because I use react-native-web in my project

**Comment by probablyup** [comment] 2018-10-13 15:12
I still don't think this is actually on our end. The only thing I can think of is we haven't moved to Babel 7 yet internally and maybe that somehow has a weird effect

**Comment by probablyup** [comment] 2018-10-15 22:14
May or may not be related, but check out https://github.com/styled-components/styled-components/issues/1495#issuecomment-430032938

**Comment by ohsory1324** [comment] 2018-10-16 02:43
This code help you.
`yarn add supports-color`

**Comment by reywright** [comment] 2018-10-16 08:28
This is indeed an issue with the new official Styled Components v4 release. This isn't present whatsoever in Styled Components v3.

In line with what @ohsory1324 said above:

If you'd like to get this working, you mostly just need to do this (I'm on a Mac btw)

```
yarn add -D supports-color os
```

**Comment by dawidk92** [comment] 2018-10-16 09:15
I can confirm it. It works after installing `supports-color`

**Comment by probablyup** [comment] 2018-10-16 16:14
I really do think this is coincidental and exposing some sort of bundler bug. You pull down the s-c repo and run `yarn --production`, supports-color is nowhere to be found.

**Comment by ru88s** [comment] 2018-10-17 06:08
There is a bug in Styled Components v4.
Styled Components v3.4.10 will fix it.

**Comment by takahiro-saeki** [comment] 2018-10-17 12:08
@probablyup I do not think it's coincidental bug. I reproduced it. I got same error to this issue on react-native@0.57.0 when I installed `styled-components@4.0.0` . so if someone is in a hurry to use `styled-components@4.0.0` on `react-native@0.57.0` , to install `supports-color` would be helpful for you.

at the same time, I guess this error isn't relative to `styled-components` , I guess this error occur because of metro bundler unfortunately.

**Comment by probablyup** [comment] 2018-10-17 21:32
Going to close this as I'm now 100% sure this is a bundler bug and not something on our end.

**Closed by probablyup** 2018-10-17 21:32 UTC
Labels: react-native

**Comment by kcolton** [comment] 2018-10-29 22:39
@probablyup 100% sure? 

**Currently in master:**
https://github.com/styled-components/styled-components/blob/2b87a5f7e307b16e1b18dc31467d1f04cfe4738a/src/vendor/postcss/css-syntax-error.js#L2

Usage within css-syntax-error.js
https://github.com/styled-components/styled-components/blob/2b87a5f7e307b16e1b18dc31467d1f04cfe4738a/src/vendor/postcss/css-syntax-error.js#L161

When it was removed:
https://github.com/styled-components/styled-components/commit/f242f9acdb3efe77b89bcc78f5fb37d4c0d6553c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L80

I don't know enough about how postCSS is being used to determine if it's a valid dependency or not to create an appropriate PR.

React native is where styled-components functionality is the most compelling since there is no "real CSS" to fall back onto. 

Can't help but feel frustrated at finding this issue and #2163 closed with basically: `¯\_(ツ)_/¯`

Even the react-native [expo snack](https://snack.expo.io/@danielmschmidt/styled-components) is broken with the same error. I would say it's most definitely still an open issue.

**Comment by probablyup** [comment] 2018-10-29 22:43
Ahhhhhhhhhhh! You're so right. Will add it. I have that whole directory ignored 😬

**Comment by kcolton** [comment] 2018-10-29 22:53
📁 `src/vendor` uses cloak
🔍 attack misses

Been there, done that. All good! 😆
