### ISSUE TITLE
Upgrading from 5.1.1 to 5.3.3 and getting `& + &` issues with conditional props

### ISSUE THREAD

**Issue by bartzy** [styled-components/styled-components#3620] opened 2021-11-14 10:48 UTC
## Explanation

I upgraded from 5.1.1 to 5.3.3, and some `& + &` styles are "broken". By broken I just mean that the behavior is different and I'm trying to understand why, and how to get the old behavior with 5.3.3.

The issue is with sibiling components of the same type that have a conditional prop, and use that prop in `& + &` blocks. You can easily see the issue in the provided Codesandbox links.

## Reproduction

Working (5.1.1): https://codesandbox.io/s/styled-components-bug-5-1-1-c628i
"Broken" (5.3.3): https://codesandbox.io/s/styled-components-bug-5-3-3-0v2jq?file=/src/App.js

## Expected Behavior

Only the immediate Foo component after the `$active=true` one should have border-top-color set.

## Actual Behavior

In 5.1.1, this works. In 5.3.3, all Foo components have border-top-color set. It makes sense since this is just `& + &` and all of them are the same Foo component, but I wonder how can this be done in 5.3.3 and what was the PR/commit that changed this?

Thanks!

**Comment by stiboost** [comment] 2021-11-18 11:31
This happens whenever there is an `&` in the style of a component it seems like. 
I'm seeing this exact issue:

Working (5.1.1): https://codesandbox.io/s/styled-components--issue-5-1-1-p3int
Not working (5.3.3): https://codesandbox.io/s/styled-components--issue-5-3-3-84wuk

Any ideas what might be causing this?

**Comment by mctrl** [comment] 2021-11-29 15:35
I can confirm I have a similar issue using conditionals when I use a reference to a parent class `${Parent} & {}`

I also see a duplication in the styles:

```
.sc-ezbkAF .sc-bYoBSM {
  border: 1px solid transparent;
}

.sc-ezbkAF .sc-bYoBSM {
  border: 1px solid rgb(255, 82, 83)
}

```

**Comment by r0stig** [comment] 2021-12-17 13:15
> 

Just to chime in, I got the same issue as the quoted comment. Last version that this works is 5.1.1, same issue with 5.2.0 (and newer).

**Comment by hudochenkov** [comment] 2022-01-04 15:13
Related issue: https://github.com/styled-components/styled-components/issues/3265.

**Comment by kitten** [comment] 2022-01-04 15:18
Duplicate of #3265

**Closed by kitten** 2022-01-04 15:18 UTC
