### ISSUE TITLE
Cannot Import Component based on styled-components

### ISSUE THREAD

**Issue by Tri4Ty** [styled-components/styled-components#2682] opened 2019-07-16 08:54 UTC
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
 - Memory: 255.81 MB / 12.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^4.3.2 => 4.3.2 

## Reproduction
I've built a prototype theming component using styled-components [https://github.com/Tri4Ty/CatalogZero](https://github.com/Tri4Ty/CatalogZero) ... works great when I launch this component in development mode (Webpack devServer), but when I import it into any other component, I'm getting:

> Module parse failed: Unexpected token (142:2)
File was processed with these loaders:
 * ./node_modules/source-map-loader/index.js
You may need an additional loader to handle the result of these loaders.
| 
| const Button = (props) => (
>   <ThemedButton onClick={props.onClick}>{props.children}</ThemedButton>
| );
| export default Button;
 @ ./node_modules/catalog-zero/index.js 1:0-34 3:15-21
 @ ./src/ConfigurableForm.js
 @ ./dev/src/ConfigurableFormTest.js
 @ ./dev/src/index.js

## Steps to reproduce

> npm install --save catalog-zero

in your react class, add the following:

```
import Button from 'catalog-zero';

...

render() {
  return(
     <Button>My Test Button</Button>
  )
}
```

> npm start

## Expected Behavior
I expect your component to build and the "My Test Button" to render

## Actual Behavior
getting compile errors when I import this catalog-zero component into any other component:

> npm start
...
ERROR in ./node_modules/catalog-zero/src/Button.js 142:2
Module parse failed: Unexpected token (142:2)
File was processed with these loaders:
 * ./node_modules/source-map-loader/index.js
You may need an additional loader to handle the result of these loaders.
| 
| const Button = (props) => (
>   <ThemedButton onClick={props.onClick}>{props.children}</ThemedButton>
| );
| export default Button;
 @ ./node_modules/catalog-zero/index.js 1:0-34 3:15-21
 @ ./src/ConfigurableForm.js
 @ ./dev/src/ConfigurableFormTest.js
 @ ./dev/src/index.js

## Package.json

```
{
  "name": "catalog-zero",
  "version": "1.0.1-betaTesting",
  "description": "Component library that supports customizable theming and styling",
  "main": "/dist/catalog-one.bundle.js",
  "scripts": {
    "pre-commit": "lint-staged",
    "start": "webpack-dev-server --config ./webpack.dev.config.js --mode development",
    "build": "webpack --config ./webpack.prod.config.js --mode production"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Tri4Ty/CatalogZero.git"
  },
  "keywords": [
    "React",
    "Component Library",
    "Customized Theming"
  ],
  "author": "Tri4Ty",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Tri4Ty/CatalogZero/issues"
  },
  "homepage": "https://github.com/Tri4Ty/CatalogZero#readme",
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties",
      ["babel-plugin-styled-components", {
        "minify": false,
        "transpileTemplateLiterals": false
      }]
    ]
  },
  "pre-commit": [
    "pre-commit"
  ],
  "lint-staged": {
    "*.js": [
      "prettier --write",
      "git add"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.2",
    "babel-loader": "^8.0.6",
    "babel-plugin-styled-components": "^1.10.6",
    "circular-dependency-plugin": "^5.0.2",
    "clean-webpack-plugin": "^3.0.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.14.2",
    "html-webpack-plugin": "^3.2.0",
    "lint-staged": "^9.2.0",
    "pre-commit": "^1.2.2",
    "prettier": "^1.18.2",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-hot-loader": "^4.11.1",
    "source-map-loader": "^0.2.4",
    "webpack": "^4.35.0",
    "webpack-cli": "^3.3.5",
    "webpack-dev-server": "^3.7.2",
    "webpack-merge": "^4.2.1"
  },
  "dependencies": {
    "lodash": ">=4.17.13",
    "styled-components": "^4.3.2"
  },
  "peerDependencies": {
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}
```

## Webpack Core

```
const path = require("path");
const CircularDependencyPlugin = require("circular-dependency-plugin");

module.exports = {
  resolve: {
    extensions: ["*", ".js", ".jsx"]
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: ["source-map-loader"],
        enforce: "pre"
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "babel-loader",
            options: {
              presets: ["@babel/preset-env", "@babel/preset-react"],
              plugins: [
                "@babel/plugin-proposal-class-properties",
                "babel-plugin-styled-components"
              ]
            }
          },
          "eslint-loader"
        ]
      }
    ]
  },
  plugins: [
    new CircularDependencyPlugin({
      // exlude detection of files based on a RegExp
      exclude: /a\.js|node_modules/,
      // add errors to webpack instead of warnings
      failOnError: true,
      // set the current working directory for displaying module paths
      cwd: process.cwd()
    })
  ]
};
```

## Webpack Production

```
const path = require("path");
const merge = require("webpack-merge");
const core = require("./webpack.core.config");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const TerserJSPlugin = require("terser-webpack-plugin");

module.exports = merge(core, {
  mode: "production",
  devtool: "source-map",
  entry: {
    "catalog-zero": [path.join(__dirname, "/index.js")]
  },
  output: {
    filename: "[name].bundle.js",
    path: path.join(__dirname, "dist"),
    publicPath: "/",
    library: "catalogZero",
    libraryTarget: "umd"
  },
  externals: ["prop-types", "react", "react-dom"],
  plugins: [new CleanWebpackPlugin()],
  optimization: {
    minimizer: [new TerserJSPlugin({})]
  }
});
```

**Comment by chinesedfan** [comment] 2019-07-24 09:41
> @ ./node_modules/catalog-zero/index.js 1:0-34 3:15-21
@ ./src/ConfigurableForm.js
@ ./dev/src/ConfigurableFormTest.js
@ ./dev/src/index.js

Looks like your error logs are not corresponding to steps to reproduce. And `Unexpected token` errors usually occur when webpack loaders are not set correctly. You can comment `source-map-loader` rule temporarily. It should not be an issue of styled-components. 

```
// not this
import Button from 'catalog-zero';
// maybe
import Button from '../../';
```

**Comment by probablyup** [comment] 2019-10-28 22:31
Closing since it appears to be a third party issue.

**Closed by probablyup** 2019-10-28 22:31 UTC
