### ISSUE TITLE
[Proposal] Consider allowing implicit `extend`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [styled-components/styled-components#1136] opened 2017-09-01 23:16 UTC
Apologies if this has been suggested before, but I could not find it in the archives.

Let's say I have some component `OriginalComponent`
```
const OriginalComponent = styled.div`background-color: blue; color: red;`;
```
I can extend that component two ways
```
// The recommended way.  One class, target is `div`.
const ExtendedComponent = OriginalComponent.extend`color: yellow;`;
// The usual way.  Two classes, target is `OriginalComponent`.
const StyledComponent = styled(OriginalComponent)`color: yellow;`;
```
The recommend way performs better (since the tree is a level smaller) and gives fewer classes.  And while the API is very simple and obvious, the explicit requirement seems artificial.

What I propose is a slight change to the way `styled` works.  To simplify it, something like
```
function styled(component) {
  // Check if `component` is a `StyledComponent`.
  if (component.styledComponentId) {
    // If so, use `component.extend`.
    return component.extend;
  }
  // Otherwise, do usual `styled` stuff.
}
```
It can potentially give a performance boost to newer users.

**Comment by wtgtybhertgeghgtwtg** [comment] 2017-09-01 23:24
If you put the check in the `StyledComponent` model, it will potentially boost the performance of `withComponent`, as well, since[ that loops back through `createStyledComponent`](https://github.com/styled-components/styled-components/blob/ec8bb67e067d8e1187cca6fdd9468bfcc93cd364/src/models/StyledComponent.js#L239).

**Comment by philpl** [comment] 2017-09-02 00:07
Duplicate of https://github.com/styled-components/styled-components/issues/1087

**Closed by philpl** 2017-09-02 00:07 UTC
