### ISSUE TITLE
native: invalid undefined width of type string supplied

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#337] opened 2016-12-28 15:48 UTC
I am using Image component in order to achieve full screen background image as described here: http://blog.bigbinary.com/2016/04/28/using-image-as-a-container-in-react-native.html

One of the caveats is need to provide `width: undefined; height: undefined` to Image component in order to scale it correctly, hence my styled Image component looks like this:

```
const StyledImageContainer = styled(Image)`
  flex: 1;
  width: undefined;
  height: undefined;
  background-color: 'transparent';
`;
```

This produces error:

> native: invalid undefined width of type string supplied..

There is an easy work around where width and height can be specified in style prop, but thought it might be useful to open this issue for future.

**Comment by JamieDixon** [comment] 2016-12-28 17:41
Just a thought, what happens if you:

```
const StyledImageContainer = styled(Image)`
  flex: 1;
  width: ${undefined};
  height: ${undefined};
  background-color: 'transparent';
`;
```

I'm unable to test React-native things right now. If this helps, great. If not, sorry for the noise.

**Comment by brunolemos** [comment] 2016-12-29 03:28
Yeah apparently `styled-components` doesn't let you do that.
Neither `width: undefined` nor `width: ${undefined}` nor `${{ width: undefined }}`

Use `style={{ width: undefined, height: undefined }}` while it's not fixed.

**Comment by mxstbr** [comment] 2017-01-03 09:37
Man, that's such a weird use case! Thanks for submitting this issue @IljaDaderko, we'll get it fixed 😊

**Comment by jacobp100** [comment] 2017-02-23 13:54
This'll have to be fixed in `css-to-react-native`. It's going against the spec, so I'm hesitant. Am I right in thinking this is only for the `Image` component?

**Comment by IljaDaderko** [comment] 2017-02-23 14:39
@jacobp100 so far seems so, I think rn 0.42 will kinda fix this with support for `width: 100%` and `height: 100%`

**Comment by jacobp100** [comment] 2017-02-23 14:58
Oh we support those! Should we go with that?

**Comment by IljaDaderko** [comment] 2017-02-23 15:06
Thats something I am definitely refactoring once it is out, works for me, not sure about other folks.

**Comment by mxstbr** [comment] 2017-07-01 07:08
Since this isn't supported by design from the spec, nobody has reported this as an issue in a while and we've updated `css-to-react-native` to stick with the spec I'll close this for now.

If you're still running into this problem feel free to submit a new issue!

**Closed by mxstbr** 2017-07-01 07:08 UTC
Labels: bug
