### ISSUE TITLE
Get rid of whitelist, instead use prefix

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#1005] opened 2017-07-18 12:38 UTC
Related to #731

How about using  a prefix for "styled-components-private-props"? e.g. just prefix everything that's not a real React/DOM prop with `_`.  Then you'd have

```js
<Button _primary onClick={foo} disabled />
```

The whitelist would be gone, and it's very clear what is the "API" for the styling.

**Comment by philpl** [comment] 2017-07-18 12:42
Duplicate of https://github.com/styled-components/styled-components/issues/439

Please just add it there :)

Sorry for not having more updates in that discussion there, but it is looking like React might actually introduce prop namespacing, which would solve this more elegantly

**Closed by philpl** 2017-07-18 12:42 UTC
