### ISSUE TITLE
:root { .some-class & { ... } } does not work as expected

### ISSUE THREAD

**Issue by asistapl** [styled-components/styled-components#952] opened 2017-06-26 16:00 UTC
## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-Kn_3D4-c-UzcHsTAZyh

## Steps to reproduce
```js
injectGlobal`
  :root {
    .some-class & {
      color: red;
    }
  }
`
```

## Expected Behavior

Should produce `.some-class:root` selector

## Actual Behavior

instead of `.some-class :root` which does not work as expected. (Old parser was smart enough to remove that space).

**Comment by philpl** [comment] 2017-06-26 18:47
cc @thysultan

I think btw we've turned support for these css festures off. But I'm not sure if this affects in how stylis parses them

**Comment by thysultan** [comment] 2017-06-26 18:55
> I think btw we've turned support for these css festures off.

@philpl What do you mean?

**Comment by thysultan** [comment] 2017-06-26 20:12
@asistapl I think stylis handles this correctly – [REPL](https://stylis.js.org) `.some-class:root` what version of stylis is npm installing for you?

**Comment by thysultan** [comment] 2017-06-26 20:16
Managed to reproduce, it's when the namespace value is an empty string – `""`, Which is how i think `injectGlobal` uses stylis to process global css.

Should be fixed in the next patch release.

**Comment by philpl** [comment] 2017-06-26 20:58
sorry, was afk for a bit ;) yea, we're passing an empty namespace there, since it's global css :)

https://github.com/styled-components/styled-components/blob/master/src/utils/stringifyRules.js#L27

**Closed** 2017-06-29 19:24 UTC
