### ISSUE TITLE
Use defaultProps of original component to define theme defaults

### ISSUE THREAD

**Issue by danrot** [styled-components/styled-components#360] opened 2017-01-09 18:49 UTC
I've been playing around with the theming support of styled components, and wanted to see how the [defaults](https://github.com/styled-components/styled-components#defaults) are working. Therefore I build an own React Component, and tried to style it as follows:

```javascript
import React from 'react';
import styled from 'styled-components';

class Button extends React.Component {
    static defaultProps = {
        theme: {
            main: 'red'
        }
    };

    render() {
        return <a className={this.props.className}>Press me!</a>;
    }
}

export default styled(Button)`
    color: ${props => props.theme.main};
`;
```

The problem is that this doesn't work, since the `defaultProps` of the `Button` component do not apply for the styling. So the styling properties have to be added to the styled component like this:

```javascript
import React from 'react';
import styled from 'styled-components';

class Button extends React.Component {
    render() {
        return <a className={this.props.className}>Press me!</a>;
    }
}

const styledButton = styled(Button)`
    color: ${props => props.theme.main};
`;

styledButton.defaultProps = {
    theme: {
        main: 'red'
    }
};

export default styledButton;
```

@mxstbr also said in [this tweet](https://twitter.com/mxstbr/status/818168099593719808) that the first example should also be working. That would allow to save some lines here, resp. lead to a better DX, since I can imagine that this is a common gotcha.

**Comment by k15a** [comment] 2017-01-09 19:17
This might be related to #344. Could you share a reproduction on webpackbin?

**Comment by danrot** [comment] 2017-01-09 19:36
Not sure if it working correctly, missing a babel-plugin I cannot find in the configuration (`transform-class-properties`): http://www.webpackbin.com/N18_N0hSG

**Comment by diegohaz** [comment] 2017-01-10 03:45
To be honest, I don't think the first example should work. `styled(Button)` creates a new component  that wraps `Button` (composition, not inheritance).

In the example below, it doesn't make sense`StyledButton` inheriting `Button.defaultProps`.
```js
const Button = (props) => <a className={props.className}>Press me!</a>

Button.defaultProps = {...}

const StyledButton = (props) => <Button {...props} />
```

**Comment by geelen** [comment] 2017-01-10 04:02
Yeah, I don't think that first example makes sense. I'm a bit surprised Max suggested it should be added, but I'll wait until he weighs in here.

It seems like you're conflating two things here: the definition of a reusable component and the application of a theme. When you `styled(X)` you're passing information _to_ `X`, not reading information from it. And when you're using `props.theme`, you're pulling information from above yourself in the render tree, not below.

This might be more what you're after:

```js
import React from 'react';
import styled from 'styled-components';

const A = styled.a`
    color: ${props => props.theme.main};
`

export default class Button extends React.Component {
    static defaultProps = {
        theme: {
            main: 'red'
        }
    };

    render() {
        return <A className={this.props.className}>Press me!</A>;
    }
}
```

**Comment by danrot** [comment] 2017-01-10 06:41
@geelen You've rewrote the example to use the `styled.a` method, instead of a react component. Would you consider styling a react component that way as an antipattern? Can that be done without any drawbacks in an entire real-life application?

**Comment by mxstbr** [comment] 2017-01-11 06:44
> Would you consider styling a react component that way as an antipattern?

Not an antipattern necessarily, but definitely not the recommended way of doing this.

> Can that be done without any drawbacks in an entire real-life application?

Yes, that's what I (and @geelen) both do in all of our real, production apps with `styled-components`.

----

You're right, I'll close this issue!

**Closed by mxstbr** 2017-01-11 06:44 UTC

**Comment by danrot** [comment] 2017-01-11 06:55
Ok, one more question then: Where do you put more general rules, being valid for the entire application, and I want to cascade? Do you use something like `styled.body`, or do you have a separate stylesheet in that case?

**Comment by mxstbr** [comment] 2017-01-11 07:07
That's what we have `injectGlobal` for 😉

```JS
import { injectGlobal } from 'styled-components'

injectGlobal`
  body {
    margin: 0;
    background: mediumseagreen;
  }
`
```

**Comment by steve-a-jones** [comment] 2017-07-16 22:34
@geelen Correct me if my thinking is incorrect, but the example above shouldn't work unless props are passed explicitly to SC `A` ..

`return <A {...this.props} className={this.props.className}>Press me!</A>;`

Also, since `Button` in that example is not a SC, `this.props.className`  would be undefined (unless passed explicitly) by a parent component.

I'm new to SC and trying to wrap my head around how to export non SC react components while using `ThemeProvider` upstream. My thinking may be flawed but I would like to have a RC with defaultProps and pass them to SC children as needed.

So far defaultProps with ThemeProvider only seem to work with SC - by this I mean ThemeProvider will override defaultProps defined on a SC but not a raw react component. This make sense conceptually as I would not want ThemeProvider destroying props on all my components downstream.

Appreciate if you could point me the right direction.. should I be trying to achieve this with `withTheme`?

If so, it's seems that my components will then have a hard dependency on ThemeProvider upstream as mentioned here: https://github.com/styled-components/styled-components/issues/538

Perhaps another approach to take would be to create transparent SC wrappers for these situations.. I might be overthinking all of this..

**Comment by steve-a-jones** [comment] 2017-07-18 06:07
Okay - I get it now :) Took some experimenting, but it makes sense.

A few insights that helped...

1. Took me a while to realize (although after that fact it seemed obvious given how SC works) that regular react components will not just magically just pick up `props.theme` downstream from ThemeProvider - those components can only ever receive theme styling if they are passed a className explicitly containing a SC generated classname OR wrapped with `withComponent`, which in that case the "wrapping" SC component's style definitions are evaluated with the props supplied by `ThemeProvider`.

2. Evaluated SC styles result in injected stylesheets and auto generated class names - I know this is mentioned everywhere but it is important to understand this to make sense of why applying the supplied className to your wrapped react component is the only way to actually get the styles to take effect.. it doesn't happen on its own ;)

3. `defaultProps` defined on components wrapped with `withComponent` aren't updated by `ThemeProvider`  - this confused me for a bit as my `console.log(props.theme)` showed still showed the `defaultProps`. This means that the current state of `props.theme` is only accessible within the SC style definition itself. 

4. SC styles are evaluated before your component wrapped with `withComponent` is rendered... this makes sense since the className it is passed needs to already be injected into the style tag for the styles to take effect.

Apologies for being a bit dense - really loving SC so far. Major `props` to all the contributors!
