### ISSUE TITLE
Parent selectors resolve to different rules due to hash classnames

### ISSUE THREAD

**Issue by drFabio** [styled-components/styled-components#774] opened 2017-05-08 15:51 UTC
I think I found a possible missbehaviour when using props and siblings . (Or probably just the className placeholder in general).

## Version
1.0.5

## Reproduction
https://www.webpackbin.com/bins/-Kjc_PkTewh0QoJ0kJNn

## Steps to reproduce

Create a component with the sibling syntax that use some props for it's rules.

## Expected Behavior

The sibling rules would be applied to all props class variants

## Actual Behavior

The component get's styled with the sibling rules on the prop specific class.

**Comment by diondiondion** [comment] 2017-05-09 12:52
Interesting. This wouldn't happen if the `&` selector used the `sc-`-prefixed className that doesn't change based on props, but not sure if this would have other side effects.

**Comment by drFabio** [comment] 2017-05-09 13:34
Will take a look on this prefix and let you know. It may be at least a workaround for this specific case.
If this is indeed a missbehaviour I would be glad to make a PR with tests in the near future

**Comment by philpl** [comment] 2017-05-09 14:04
This is not misbehaviour but intended.

Imagine a case where you'd write this:

```js
const Button = styled.button`
  color: black;

  ${p => p.addHover && css`
    &:hover {
      color: violet;
    }
  `}
`

<Button />
<Button addHover />
```

What you're referring to with the `sc-*` classes are classes based on the component id. The button has a single component id, and its `sc-x` class refers to all its variations.

In the above example, if we'd target this `sc-x` class instead for the parental selector (i.e. ampersand selector), then both buttons would suddenly have the above pseudo class.

I'd suggest you to just avoid using this selector altogether while altering the classes. Don't forget that two components, with different props, rendering different CSS, will also be decoupled from each other. By this thinking, this behaviour does make sense ;)

**Comment by drFabio** [comment] 2017-05-09 14:10
I get the rationale that each component with a prop would be it's own thing.
I didn't quite got this "sc-" part. Can I leverage it to get this behaviour of the same rule for all siblings even if they use different props?

> I'd suggest you to just avoid using this selector altogether while altering the classes.

By that quote You are meaning sibling selectors?

**Comment by diondiondion** [comment] 2017-05-09 14:20
> This is not misbehaviour but intended.

Let's say it's intended misbehaviour then. ;)

I've always thought that generating an entirely new CSS class for each variation was kind of inelegant.

Ideally styled-components would (somehow) smartly split all the CSS rules for a given component into dynamic & static bits and assign each bit its own hashed className (and add all of these classes to the rendered component). Similar to how you'd write classes and modifier classes in a methodology like BEM.
This way static rules (which don't change based on props) would apply to all instances of a component, and the dynamic bits would all have their own dedicated "modifier" classes.

This would also make working with styled-components in browser dev tools much nicer.

**Comment by diondiondion** [comment] 2017-05-09 14:27
> I didn't quite got this "sc-" part. Can I leverage it to get this behaviour of the same rule for all siblings even if they use different props?

Not really. One workaround would be manually adding a component-specific static className which you can then target in your CSS, like this:

```
const Parent = styled.span.attrs({
  className: 'self'
})`
 color: ${(props) => props.isBlack? 'black' : 'palevioletred'};
 border: 2px palevioletred solid;
 .self + & {
   margin-left: 3em;
   color: tomato;
  }
`
```

If you were planning to do this in more than one component, you should prevent potential conflicts by randomising the className.

**Comment by geelen** [comment] 2017-05-09 14:28
Yeah the `sc-` is kind of a placeholder for the moment. Hoisting the static styles into another class is definitely doable, but you do run into a few potential difficulties when it comes to rule order. At the moment, we duplicate everything because it's safer. In the future, we might do something like extract every rule that is above the first function interpolation. It's sort of low on my priority list but I'd happily look at a PR for it.

**Comment by philpl** [comment] 2017-05-09 14:32
We basically just have to differentiate between dynamic and non-dynamic selectors. Which sounds easy, but is in fact tricky during runtime. Especially since we'd need to go through stylis.

One feasible solution is, before we resolve the nested interpolations (functions), we can replace all the parental selectors `&` with the `sc-` classname.

**Comment by drFabio** [comment] 2017-05-09 14:33
@geelen I can do the PR soonish. I would appreciate if you could point me to the part on the code where this thing is being made. Also just for me to get the correct problem enunciation, would you say that this would be fixed with:

> Separating the rules that leverage props from the rules that don't use it and keep these rules on the root class and the props on the child generated classes?

**Comment by philpl** [comment] 2017-05-09 14:38
@geelen @drFabio 

> Separating the rules that leverage props from the rules that don't use it and keep these rules on the root class and the props on the child generated classes?

Sounds to me like it's the exact same code, as the static css extraction, that I already primed on the babel plugin.

https://github.com/styled-components/babel-plugin-styled-components/blob/static-css-extraction/src/css/staticExtractionUtils.js

This is giving me a crazy idea! What if we use "preprocessing" every time we create a component e.g. `styled.div`. By moving the preprocessing to the runtime we can achieve 100% reusability with the babel plugin, ensure that the logic stays the same, *AND* use the code that I've already written for the static CSS extraction

**Comment by geelen** [comment] 2017-05-09 14:44
Great @drFabio! Definitely work against the `v2` branch, and `ComponentStyle.js` is the file that will most need to change. A good start would be to create a branch and add a bunch of failing tests that describe exactly what output you're expecting. Then if you raise a PR at that point we can have a look and make sure it won't lead to any unexpected output, and point you in the right direction for the implementation as well.

**Comment by geelen** [comment] 2017-05-09 14:50
Oh wow @philpl that might be a much more promising option!

**Comment by drFabio** [comment] 2017-05-09 14:51
Ok @geelen thanks. I will keep that in mind and make a branch on the next couple of days.

>  if you raise a PR at that point

Are you meaning to make a PR while with the tests still failing just to get feedback?

**Comment by geelen** [comment] 2017-05-09 14:54
Just for the record, you can do what @drFabio originally wanted using an interpolation. This is the real reason for `sc-`, to allow a component to override another:

```js
const X = styled.div`
  > ${ Button } {
    color: red;
  }
`
```

Renders `.hashed-x > .sc-button { color: red; }`

Here we can do the same thing but we have to use a function interpolation to delay the value until render time, because `Parent` isn't defined while it's still being created.

**Comment by drFabio** [comment] 2017-05-09 14:56
Thanks @geelen  will workaround with that for today and make the PR soon

**Comment by geelen** [comment] 2017-05-09 14:57
> Are you meaning to make a PR while with the tests still failing just to get feedback?

Yep exactly. Good luck!

**Comment by philpl** [comment] 2017-05-09 15:19
@geelen Since you're here soon, we might be able to plan this out in person and start to move the preprocessing + extraction logic to SC :smile: It'd be great to have a momentary solution on v2 for now, @drFabio, since this preprocessing + extraction sounds like sth that'll need some time to stabilise (v3?).

**Comment by geelen** [comment] 2017-05-09 15:54
Definitely. Compile time extraction is the big thing for v3 I think.

**Comment by drFabio** [comment] 2017-05-12 00:56
I made a PR with the failing tests [here](https://github.com/styled-components/styled-components/pull/784).

I mostly definetely have this [rule wrong](https://github.com/drFabio/styled-components/blob/245e4d859b3ad76dd024ebd680ca9d716a1ca047/src/test/props.test.js#L55) but I think the intent is clear.

I tested enzyme to get the className and couldn't found the previously mentioned 'sc-' prefixed hash. I assume that since this is not a reliable feature it is not on the styled used for tests.

I can't quite see a way to do it without adding a ".root" hash and test upon it.

**Comment by philpl** [comment] 2017-05-22 03:24
Rounding up my previous conversations with @geelen:

- v3 will aim to have preprocessing styles built into the core library, so that the babel plugin just has to execute the same code at build time
- v3 will also include static CSS extraction in the same manner, which a webpack plugin can extract into external files (by using the/a babel plugin internally)
- This will give us the necessary "breathing room" to solve this issue. Other than that, I wouldn't go ahead with solving this now, as the stylis code will just accumulate cruft :/

**Comment by diondiondion** [comment] 2017-06-12 18:03
Hey, are there any benchmarks on the performance impact of unique classes being generated for lists of items where every item is considered unique due to non-sc props being passed to the underlying element?

I guess this question is somewhat related to #439 since it's about s-c not being able to know which props are actually relevant to styling.

Why I'm asking:
I just noticed that in a big list of items that contain styled `Link` and `img` components where each item has unique `href`/`to` and `src` attributes, styled-components will actually create a unique (but identical in content) class for each instance of these components. The list can easily consist of hundreds of items, so I imagine this could cause some problems, but I didn't look into it very far yet. (The whole page isn't very optimised yet (aka it's slow anyway), so it would be hard to reliably measure its performance at the moment.)

Do you have any insights about this to keep my premature optimisation muscle from acting on its itch to replace all of these styled links and images with plain elements & styling them via descendent selectors on a parent component? 😁

**Comment by geelen** [comment] 2017-06-13 04:02
@diondiondion the hashes are driven by the content of the CSS and the styled component ID. At least, they should be. So they should all have the same CSS if they are the same SC with the same CSS (regardless of the props generated).

Can you post a reproduction? You're not defining the SC inside a render method or loop or something, are you?

**Comment by diondiondion** [comment] 2017-06-13 08:32
> the hashes are driven by the content of the CSS and the styled component ID. At least, they should be.

And they are, mea culpa. I failed to notice a pseudo element with differing background images in it that caused the hashes to differ for my links; then rashly attributed it to the wrong thing, sorry. 🙈

**Comment by geelen** [comment] 2017-06-14 01:40
No worries. I'll close this issue now in favour of #784.

**Closed by geelen** 2017-06-14 01:40 UTC
Labels: discussion
