### ISSUE TITLE
Problem with using imported styled components

### ISSUE THREAD

**Issue by srosset81** [styled-components/styled-components#213] opened 2016-11-18 07:35 UTC
I have a global file with styled components that I use accross my whole website. When I import these global components to use them directly in React, there is no problem, but if I want to create a new styled components out of them, I get this error:

```
Uncaught TypeError: Cannot read property 'displayName' of undefined
    at createStyledComponent (eval at <anonymous> (http://localhost:3000/static/js/bundle.js:7296:2), <anonymous>:148:82)
    at eval (eval at <anonymous> (http://localhost:3000/static/js/bundle.js:7350:2), <anonymous>:20:14)
    at eval (eval at <anonymous> (http://localhost:3000/static/js/bundle.js:7575:2), <anonymous>:32:62)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:7575:2)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:554:30)
    at fn (http://localhost:3000/static/js/bundle.js:85:20)
    at eval (eval at <anonymous> (http://localhost:3000/static/js/bundle.js:7557:2), <anonymous>:16:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:7557:2)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:554:30)
    at fn (http://localhost:3000/static/js/bundle.js:85:20)
```

Here is an extract of the code generating this error:

```js
import React from 'react';
import styled from 'styled-components';
import {Div} from '../../global/layout';

const RoundedBar = styled(Div)`
  transition: all 500ms;
  border-radius: 15px;
  height: 15px;
  width: ${props => props.width || "100%"}
`;
```

If I put this `RoundedBar` SC inside the global file, there is no error.
If I use `styled.div` instead, there is also no error.

**Comment by mxstbr** [comment] 2016-11-18 09:55
That's very weird, and sounds like an issue with your exports from `global/layout`.

Can you `console.log(Div)` above the `const RoundedBar` please? And also post the code from `global/layout.js`? Thank you!

**Comment by srosset81** [comment] 2016-11-18 10:21
Here's the beginning of the global/layout.js file:

```js
import styled from 'styled-components';
import {media, colors} from '../../core/constants';
import {backgroundImage, vhAlign, fullSize, width, mx} from './mixins';

export const Div = styled.div`
    margin: 0;
    padding: ${props => props.padding ? props.padding : '0px'};
    min-height: ${props => props.minHeight ? props.minHeight : 0};
    background-color: ${props => props.bgColor ? colors[props.bgColor] : "none"};
    ${backgroundImage}
    ${vhAlign}
    ${fullSize}
`;
```

And the partial result of the `console.log(Div)` (the Dev Tools only show this)

```
StyledComponent() {
        _classCallCheck(this, StyledComponent);

        var _this2 = _possibleConstructorReturn(this, (StyledComponent.__proto__ || Object.getPrototypeOf(StyledComponent)…
```

**Comment by mxstbr** [comment] 2016-11-18 10:35
Can you try and replicate this on [webpackbin](http://www.webpackbin.com/VkbO4mdR-) with your code?

**Comment by srosset81** [comment] 2016-11-18 14:00
@mxstbr Well, I don't get this error with webpackbin...

http://www.webpackbin.com/4JXeSxuZz

Must have something to do with my webpack setup, but I use a little-modified create-react-app config (after ejection).

**Comment by srosset81** [comment] 2016-11-18 15:28
I solved the problem by removing an export at the bottom of the global/layout.js file.

```js
export {default as ImagesList} from './ImagesList';
```

This `ImagesList` is a pretty complex component, which is itself using several styled components from global file. I thought at first that it was due to some sort of "loop problem" (exporting a component which was itself using some of the exported components), but the error didn't appear when exporting another, more simple, component.

Anyway, my problem is fixed but just in case you want to have a quick glance, here is the `ImageList` component which generated the error.

```js
import React, {Component, PropTypes} from 'react';
import ReactDOM from 'react-dom';
import _ from 'lodash';
import {Row, Cell, Div} from '../../global/layout';
import {Button} from '../../global/form';
import {Icon, Loading} from '../../global/utils';

class ListItem extends Component {

    static propTypes = {
        title: PropTypes.string.isRequired,
        image: PropTypes.string,
        onAdd: PropTypes.func.isRequired,
        onRemove: PropTypes.func.isRequired
    };

    renderSelected() {
        if (this.props.selected) {
            return (
                <Icon name="Check" color="green" size="32" onClick={this.props.onRemove}/>
            );
        }
    }

    render() {
        let {PreviewComponent} = this.props;
        const mdCol = 12 / this.props.maxNumColumns;

        return (
            <Cell md={mdCol / 12} sm={4 / 12} xs={6 / 12}>
                <a onClick={this.props.onAdd}>
                    <Div>
                        <PreviewComponent {...this.props}>
                            {this.renderSelected() /* pass the checkbox as a children, since this is the easiest (only?) way to pass components with arguments*/}
                        </PreviewComponent>
                    </Div>
                </a>
            </Cell>
        );
    }
}

export default class ImagesList extends Component {

    static propTypes = {
        fullList: PropTypes.array,
        onChange: PropTypes.func,
        maxNumColumns: PropTypes.number,
        loadMore: PropTypes.func,
        autoLoadMore: PropTypes.bool  // infinite scrolling activated? (only if loadMore is defined)
    };

    static defaultProps = {
        maxNumColumns: 4,
        autoLoadMore: false
    };

    constructor(props) {
        super(props);
        this.state = {
            isLoadingMore: false
        };
    }

    componentDidMount() {
        if (this.props.autoLoadMore && this.props.loadMore) {
            let debouncedHandleScroll = _.debounce(this.handleScroll.bind(this), 1000, {leading: true, trailing: true});
            window.addEventListener('scroll', debouncedHandleScroll);
        }
    }

    componentWillUnmount() {
        // TODO: remove specific listener?
        window.removeEventListener('scroll');
    }

    componentWillReceiveProps(nextProps) {
        if (typeof this.props.fullList !== 'undefined') {
            // has the list been updated ?
            if (this.props.fullList.length !== nextProps.fullList.length) {
                this.setState({isLoadingMore: false});
            }
        }
    }

    handleScroll() {
        const node = ReactDOM.findDOMNode(this);
        const rect = node.getBoundingClientRect();

        // calculate how many pixels above the screen bottom the list is
        const listBottom = rect.bottom - window.innerHeight;

        if (listBottom < 100) {
            this.props.loadMore();
            this.setState({isLoadingMore: true});
        }
    }

    // add item to list
    handleAdd(id) {
        if (!this.props.value.includes(id)) {
            let newValue = [...this.props.value, id];
            this.props.onChange(newValue); // update the state value (redux-form utils)
        }
    }

    // remove item to list
    handleRemove(id) {
        if (this.props.value.includes(id)) {
            let newValue = this.props.value.filter(valueID => valueID !== id);
            this.props.onChange(newValue); // update the state value (redux-form utils)
        }
    }

    renderLoadMore() {
        if (this.props.loadMore) {
            if (!this.state.isLoadingMore) {
                return (
                    <Cell xs={1}>
                        <Div align="middle" minHeight="100px">
                            <Button onClick={this.props.loadMore}>Plus</Button>
                        </Div>
                    </Cell>
                );
            } else {
                return (
                    <Cell xs={1}>
                        <Div align="middle" minHeight="100px">
                            <Loading/>
                        </Div>
                    </Cell>
                );
            }
        }
    }

    render() {

        if (typeof this.props.fullList === 'undefined' || this.props.fullList.length === 0) {
            return (
                <p>Aucun résultat</p>
            );
        }

        return (
            <Row spaced>
                {this.props.fullList.map(
                    (item) => <ListItem key={item.id}
                                        {...item}
                                        PreviewComponent={this.props.PreviewComponent}
                                        maxNumColumns={this.props.maxNumColumns}
                                        selected={this.props.value.includes(item.id)}
                                        onAdd={this.handleAdd.bind(this, item.id)}
                                        onRemove={this.handleRemove.bind(this, item.id)}
                    />
                )}
                {this.renderLoadMore()}
            </Row>
        );
    }
}
```

**Comment by jimmyheaddon** [comment] 2017-02-01 08:53
Hello, I've just started getting this when using styled-components with React and TSX.  Essentially I want to pass some props in and be able to interrogate them in my styled components.  The error message is right at the bottom of this post.

I've created a [WebPackBin instance](http://www.webpackbin.com/VkWBOFqPz), but I can't quite get it to work with TSX.  The documentation online for this is a bit thin, essentially I'm passing my React component in to a styled() call, trying to get the props defined in the component d.ts file.

Any help or pointing out my glaring errors would be much appreciated!

For reference I'm using these versions:
- TypeScript v2.1.4
- React v15.4.1
- Styled-Components v1.4.2

> `Uncaught TypeError: Cannot read property 'displayName' of undefined
    at createStyledComponent (styled-components.es.js:6299)
    at styled-components.es.js:6323
    at Object./Tile/Styles.js (styles.js:3)`

**Comment by srosset81** [comment] 2017-02-01 09:01
> Any help or pointing out my glaring errors would be much appreciated!

I keep on getting this error pretty often and it is always due to some sort of cyclic import (ie. A imports B which imports C, which is itself importing A). Cyclic import is generally a sign of bad code architecture, I know. Nonetheless, it seems styled-components doesn't like them at all.

**Comment by jimmyheaddon** [comment] 2017-02-01 09:06
@srosset81 That's an interesting point, and it's complicated further by TypeScript and definitions.  It's probably something like that, I just need some pointers as I'm pretty new to this library, and it's a seldom touched upon area in documentation.

**Comment by jimmyheaddon** [comment] 2017-02-01 16:49
@srosset81 any chance we can reopen this, until we get a response as to whether I'm being a dunce or not? :)

**Comment by xcoderzach** [comment] 2017-02-02 18:57
There isn't anything styled-components can do about this.  `TileStyle` needs `Tile`, because that's the component that's rendering, and `Tile` needs `TileStyle`, because it uses it in render.  So basically, `TileStyle` can't exist until `Tile` does, and `Tile` can't exist until `TileStyle`.  Catch-22 😉.

I think what you want to do is just make `TileStyle` a `styled.div`.

**Comment by jimmyheaddon** [comment] 2017-02-02 20:54
That makes sense, I guess I'm just not sure how you're supposed to architect it such that you can pass props in to the style, given that webpackbin?

**Comment by xcoderzach** [comment] 2017-02-03 21:34
What's the issue when you just turn StyleStyle into a div?  It looks like you're passing props into it, is that not working?

**Comment by jimmyheaddon** [comment] 2017-02-03 22:47
TypeScript moans that the JSX element doesn't support those props, but I can't pass the props interface the component is using either as that fails. Short of having the styled-component in the same .tsx file I'm not sure how you get the props in?

**Comment by BrandoIsNotASword** [comment] 2017-05-16 02:45
Has anyone found a solution to this?

**Comment by mxstbr** [comment] 2017-07-01 07:03
Since this seems to be a TypeScript problem and not related to the OP would you mind opening a new issue if you're still running into this? I'll close this issue meanwhile as it's pretty old and very out of date.

**Closed by mxstbr** 2017-07-01 07:03 UTC
Labels: question

**Comment by pak11273** [comment] 2018-01-25 00:39
I'm getting this type of error with a very simple component:
```
Uncaught Error: Cannot create styled-component for component: undefined
    at constructWithOptions (styled-components.es.js:2109)
    at styled (styled-components.es.js:2044)
    at eval (index.js:43)
    at Object.<anonymous> (bundle.js:2569)
    at m (bundle.js:1)
    at t (bundle.js:1)
    at eval (index.js:48)
    at Object.<anonymous> (bundle.js:101)
    at m (bundle.js:1)
    at t (bundle.js:1)
```
This component produces the error:

```javascript
import {Container} from '../../components/index.js'

const ProfileContainer = styled(Container)`
  width: 100%; 
`
class Profile extends Component {
  render() {
    return (
      <ProfileContainer />
    )
  }
}

export default Profile
```
Here is the file that I export my components:

```javascript
import Container from '../components/Container'
import Box from '../components/Box'
import List from '../components/List'

export {
  Container,
  Box,
  List
}

```

Here is the imported Container component:

```javascript
import React, {Component} from 'react'
import styled from 'styled-components'

const Container = styled.div`
  display: ${props => props.display};
  grid-template-columns: ${props => props.gridtemplatecolumns};
  overflow-x: ${props => props.overflowx};
  overflow-y: ${props => props.overflowy};
`
export default Container
```
There is no issue if I import the Container component directly but I would rather keep using my export file so I can do things like this:

```javascript
import {Container, Box, List} from '../../components/index.js'
```

**Comment by philpl** [comment] 2018-01-25 00:44
@pak11273 this seems to be completely unrelated. Can you please open a new issue :)

In general please avoid commenting on issues that have been closed or that are old/stale

**Comment by pak11273** [comment] 2018-01-25 00:54
This is absolutely relevant to the OP.  It's almost the identical problem and his solution to his own problem doesn't fix mine :(.  I didn't want to duplicate an issue but I'm happy to post this as you requested.

**Comment by philpl** [comment] 2018-01-25 01:35
@pak11273: Even if both are similar or the same usage error you're pinging people who're not interested anymore (July!), you're less likely to receive the reply you're searching for (bias from the old issue), and since it's a usage issue it highly depends on the setup, structure, and version

**Comment by ryall** [comment] 2018-02-19 16:51
For anyone else getting this using TypeScript, I can confirm the same issue was cyclic references as @srosset81 and @jimmyheaddon found. 

Abstracting the style components into a new file resolved the problem.
