### ISSUE TITLE
Component loses its style

### ISSUE THREAD

**Issue by alanzanattadev** [styled-components/styled-components#977] opened 2017-07-07 13:40 UTC
## Version
2.1.0

## Reproduction
I really don't know, it's on a big projects that has migrated to Styled component v2, I can't share the source code unfortunately :/.

## Steps to reproduce
Run the same code that used to work on SCv1 on SCv2. 

## Expected Behavior
The same style is kept between both versions.

## Actual Behavior
Some div lose their style (only "display: block" is left in the chrome inspector), instead of keeping the style that it used to have (display: flex, flex-shrink: 0, overflow: auto). It happens on two div. Both are in the middle of the component hierarchy, they are layout components. I've checked for syntax errors and I haven't found any. No complex CSS is used, only basic styling.

**Comment by philpl** [comment] 2017-07-07 15:17
We do unfortunately need some kind of reproduction :wink:

Can you submit some details on whether you're using the babel plugin, and try to isolate the bug in a webpackbin/codesandbox? You can find templates in the issue template :smile:

**Comment by alanzanattadev** [comment] 2017-07-07 15:20
Yes I know I'm not helping so much :/

Let me try later to get a repro :) Can you let the issue opened during this time ?

**Comment by k15a** [comment] 2017-07-07 15:44
Could you also check if the CSS is syntactically correct? Maybe you forgot a comma or something in this direction. :)

**Comment by philpl** [comment] 2017-07-07 16:45
@alanzanattadev yes, we'll leave the issue open of course :) But for now I'll tag it as a question

**Comment by jckhang** [comment] 2017-07-13 17:09
Hey guys, we are experiencing the same problem. One of our styled components' styles are not being injected into the DOM. A classname hash is being generated, but the styles are simply not there. It seems like the issue is related to [dynamic imports](https://facebook.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html#code-splitting-with-dynamic-import). We have two components being dynamically imported as siblings. The first sibling is loading just fine, and all of the second component's styles are being loaded **except** for the outermost div. Here are a couple things we have checked/tried:

* the style tags in the chrome inspector are showing up but the tag related to our problematic component is not showing the outermost div's style
* we tried editing the styles so that the hash changes but that doesn't help
    * our application hot reloads and when we changed the style, the styles were hot loaded and it looked fine, however a hard refresh reset it back to nothing

**Comment by philpl** [comment] 2017-07-13 17:23
@jckhang since the original description of this issue is really vague, we don't know whether it's the same issue 

Can you open a new issue with a minimal reproduction and full description please? The issue template will tell you more

Also, I suspect it's either related to SSR or a duplicated SC lib in your case. At least it sounds like it

**Comment by jamiewinder** [comment] 2017-11-12 20:57
I had something similar to this before when webpack was bundling and importing two versions of styled-components.

**Comment by philpl** [comment] 2017-11-13 00:55
@jamiewinder thanks for resurfacing this issue

There are a couple of candidate “root causes” that would fit the bill here. Most were addressed, some are usage issues. What Jamie is describing here could very well be the cause.

Seeing that this issue didn’t receive any updates and has been rather imprecise from the start, I’ll close it for now. Feel free to search through similar issue, open a new one, or come back to me here if the same project is still having these problems.

For anyone else who’s seeing this, you might **not** be experiencing the same issue, but it might look the same since the description here applies to a generic observation, not a specific root cause, so please open a new issue :)

**Closed by philpl** 2017-11-13 00:55 UTC
Labels: question
