### ISSUE TITLE
createGlobalStyle rule incorrectly overrides local style in tests

### ISSUE THREAD

**Issue by robCrawford** [styled-components/styled-components#3329] opened 2020-11-18 09:43 UTC
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 2.00 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
 - Yarn: 1.22.5 - /usr/local/bin/yarn
 - npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
## npmPackages:
 - styled-components: ^5.2.1 => 5.2.1 

## Reproduction
https://codesandbox.io/s/react-playground-forked-5638j?file=/button.spec.js:202-223

## Steps to reproduce
Run the tests, the second run fails even though it's the same function.

## Expected Behavior
Both tests should pass because the global style has less specificity than the margin set by `styled.button`. You can see that it is correct in the `browser` tab of codesandbox.

## Actual Behavior
In the second run of the test the styles set by `createGlobalStyle` override the element styles. In debug output you can see that `window.getComputedStyle(button).margin` returns `0px` the second time.

**Comment by kitten** [comment] 2021-08-09 17:13
Duplicate of #3146

**Closed by kitten** 2021-08-09 17:13 UTC
