### ISSUE TITLE
How change priority hashClass over globalStyles created with createGlobalStyles()?

### ISSUE THREAD

**Issue by moguelor** [styled-components/styled-components#3221] opened 2020-08-10 19:21 UTC
Is there any way to change the priority when styled-components inject styles in head tag? 

I need put first the global styles created with API createGlobalStyles(), and after overriding them with the styles generated with hash class. 

![Screen Shot 2020-08-10 at 14 10 25](https://user-images.githubusercontent.com/10202219/89821045-92ae9d00-db13-11ea-84e0-9726b8df6caa.png)

I need reorder them like: 

```
/*Global styles*/
.button-blue{background-color:blue;}
/*Hash classes*/
.EEPoM{background-color:red;}
```

Thank you for your help.

**Comment by kitten** [comment] 2021-08-09 17:26
Duplicate of #3146

**Closed by kitten** 2021-08-09 17:26 UTC
