### ISSUE TITLE
Bizarre behavior: styles not generated, then they are, then they aren't

### ISSUE THREAD

**Issue by t3db0t** [styled-components/styled-components#2911] opened 2019-12-03 20:04 UTC
I'm experiencing some very bizarre behavior: `styled-component` classes, i.e. `.fxNsrI` etc., are not created for ANY components. However, if I manually add a `style` prop to any of the affect components, all the styles come back. Wat!? I don't know how to reproduce this yet, and I'm not clear how I got into this state. Here's what I know:

- I'm using `react-boilerplate`, so all my webpack/babel config is _straight_ out of that, no modifications. Everything was working as expected until the other day.
- The code I was working on when this started didn't have anything to do with styling. The first time it occurred was after a minor redux reducer bug. I can't imagine how that could possibly have anything to do with `styled-components` though.
- Traditional styles work normally (css files, inline etc)
- Restarting server makes no difference
- This was happening with v4 but I upgraded to v5 just to test, no difference
- A fresh git clone makes no difference
- Reverting to a known good commit makes no difference (!!)
- Cache cleared, hard reload, delete service workers, etc. etc. all to no avail
- A regular build (i.e. `npm run build`) works correctly.

Given those data points, this seems like some kind of configuration issue but I have no idea where to look next. Any ideas? Is there any more information I can dig up, or things I can test?

# Environment
## System:
 - OS: macOS Mojave 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 784.21 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 11.14.0 - /usr/local/bin/node
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.10.0 => 1.10.0 
 - styled-components: ^5.0.0-rc.2 => 5.0.0-rc.2

# Expected Behavior
`styled-component` custom class generated as expected
![Screen Shot 2019-12-03 at 2 44 59 PM](https://user-images.githubusercontent.com/203307/70084307-1060f700-15dc-11ea-8e18-5ee6d428531e.png)

# Actual Behavior
no custom class at all (for ANY components anywhere in the entire project)
![Screen Shot 2019-12-03 at 2 44 22 PM](https://user-images.githubusercontent.com/203307/70084370-2bcc0200-15dc-11ea-8983-f501a848679e.png)

Here's a video of this in action. The video starts in the 'broken' state. I add a `style` prop, and after rebuilding and rerendering, ALL styles are suddenly back!?
https://youtu.be/uP0H_6IkLeg

**Comment by d640k** [comment] 2019-12-16 20:58
I am also experiencing this. Using version `4.3.2`.

**Comment by t3db0t** [comment] 2019-12-16 21:10
Wow, it's not just me! That's comforting, in a sense. I am still experiencing this issue but it doesn't block production. It seems that when I hard reload, styles do not render. If I change seemingly any renderable content, styles come back with the auto refresh (using React Boilerplate). Like all I have to do is add `style={{}}` to some component and styles come back. After that, I'm fine until the next hard reload...

**Comment by d640k** [comment] 2019-12-16 22:11
Like your situation @t3db0t, this does not affect production on our app, just local development.

**Comment by lmuntaner** [comment] 2019-12-18 09:34
I am having a similar issue.

I am using it in a new react app built with **create-react-app**.

**Comment by henrik1234** [comment] 2019-12-18 19:30
I'm also having this issue. Everything works in prod, in local development styles are not generated. 
Using React Boilerplate,  styled-components 4.2.0

**Comment by probablyup** [comment] 2019-12-30 04:04
My guess is they changed something in `babel-plugin-macros` which is having downstream effects

**Comment by BipinBhandari** [comment] 2019-12-30 12:50
Any updates on this?

**Comment by d640k** [comment] 2019-12-30 15:09
@BipinBhandari We were able to solve it by upgrading to the latest version (`5.0.0-rc.2` at the time; haven't yet tested with `rc.3`) and upgrading React to `16.12.0`. Not really a _solution_ but it got us out of the woods.

**Comment by probablyup** [comment] 2020-01-03 15:26
Really need a reproduction case (ideally in a codesandbox) to be able to help

**Comment by t3db0t** [comment] 2020-01-03 16:18
@probablyup Yeah, part of the frustration is that I have zero idea how it started or how to cause it to happen. In my case, I had a redux bug crop up and then all of a sudden styles were gone. I hadn't changed any dependencies, done any upgrades, anything. I can't possibly imagine the connection :(

Does anyone else have any idea what caused or at leased preceded the appearance of the problem?

**Comment by lucasraziel** [comment] 2020-01-06 16:54
Same situation for me. Version rc.2 didin resolve

**Comment by atmortensen** [comment] 2020-01-09 20:50
I'm seeing the same thing after updating. I had to revert to an older version.

**Comment by morgancmartin** [comment] 2020-01-10 08:20
@d640k You are a god among men and I am forever in your debt.

To everyone else, I did not try `5.0.0-rc.2` but `^5.0.0-rc.3` did the trick for me. I already had `"react": "^16.12.0"`.

@probablyup I put together a repro repo. I tried to do so in codesandbox but I think it may not be compatible with Next.js or I'm just not familiar enough with it to get it working. But I did create a test-case repo over on gitlab for you to check out. Apologies for any extra junk not pertaining to the bug.

https://gitlab.com/morgancmartin/styled-components-bug-reproduction

Feel free to ping me with any questions about my env/setup.

And thanks for the great lib!

**Comment by colepeters** [comment] 2020-01-14 18:15
Having a very similar issue, on **both v4.x and v5**. **Updating from 16.9 to 16.12 to React has not fixed anything** for me. I've narrowed it down to production builds, and further noticed that on production builds, the `<style />` element that SC creates is in fact completely empty:

<img src='https://user-images.githubusercontent.com/1713932/72369968-d1d45700-36c6-11ea-8ad4-06bb7b6f57df.png' width='400' />

…which is very odd because my components look styled but _how are any of my components being styled?_

![image](https://user-images.githubusercontent.com/1713932/72370049-fdefd800-36c6-11ea-969c-e838d3304175.png)

I've further noticed that given the right random interaction with my app (specifically on iOS Safari), the app seems to lose any knowledge it had of these styles (even though they don't exist??) and multiple components lose their styling.

I wish I could provide more concrete information or a consist repro. This is too weird to believe. Will be overjoyed with any further insight!

**Comment by probablyup** [comment] 2020-01-14 18:30
I need to add a FAQ page for this. The style element appears to be empty but that’s just because we use a set of special, faster DOM APIs to inject the styles called CSSOM. 

The browser dev tools haven’t supported showing these styles in a useful way yet for some reason. You can see them by grabbing the DOM element and using $0.sheet.cssRules though

**Comment by lucasraziel** [comment] 2020-01-18 11:37
Is It possible that It has sth related to this issue?

https://github.com/thysultan/stylis.js/issues/147

**Comment by lucasraziel** [comment] 2020-01-18 12:06
The error in my app was appearing only in dev mode. But now, It also is appearing in prod mode. I already am using styled-components@rc.3 and react@16.12.0

**Comment by lucasraziel** [comment] 2020-01-18 12:12
I can also assure you that it is not being loaded any css. I used the $0.sheet.cssRules and there is no any sheet style

![Screenshot from 2020-01-18 09-10-08](https://user-images.githubusercontent.com/26093830/72663544-9e4d4180-39d2-11ea-9904-c40c1311f59d.png)
![Screenshot from 2020-01-18 09-10-26](https://user-images.githubusercontent.com/26093830/72663545-9ee5d800-39d2-11ea-861f-d772177ded6d.png)

**Comment by kitten** [comment] 2020-01-18 12:17
@lucasraziel `.sheet.cssRules` are properties on style tags so if you’re getting an `undefined` error, you’re not accessing the style tag, so you’ll probably have to check the style tag that SC inserts.

Also do note that this will show you the rules in prod, but in development we don’t use CSSOM.

**Comment by lecstor** [comment] 2020-02-27 15:06
So I've just resolved this by removing a style import from my site's global style.
ie I removed the `@import` from this global style:
```
import modernNormalize from "styled-modern-normalize";
import { createGlobalStyle } from "styled-components";

export const GlobalStyle = createGlobalStyle`
  @import url('https://fonts.googleapis.com/css?family=Roboto:400,500,600');  
  ${modernNormalize}

  html, body {
    font-family: Roboto, sans-serif;
    font-size: 10px;
    line-height: 1.5;
  }

  * {
    box-sizing: border-box;
  }
`;
```
Before the fix only the body showed any style, the text, input elements, etc were completely unstyled. I could see rules in the style tag in head with `.sheet.cssRules` but they were all from this global style, none had the hash-style styled-components class names.

After removing the import the style returned to my page elements and all the rules had sc hashed class names.

This all worked in dev & prod until I upgraded to SCv5 when this issue appeared in prod builds.

Hope that helps, but if you need a repo I can provide it once I clean up my mess here and push a commit (it's way too late to do that now).

**Comment by lecstor** [comment] 2020-02-27 15:07
So I've just resolved this by removing a style import from my site's global style.
ie I removed the `@import` from this global style:
```
import modernNormalize from "styled-modern-normalize";
import { createGlobalStyle } from "styled-components";

export const GlobalStyle = createGlobalStyle`
  @import url('https://fonts.googleapis.com/css?family=Roboto:400,500,600');  
  ${modernNormalize}

  html, body {
    font-family: Roboto, sans-serif;
    font-size: 10px;
    line-height: 1.5;
  }

  * {
    box-sizing: border-box;
  }
`;
```
Before the fix only the body showed any style, the text, input elements, etc were completely unstyled. I could see rules in the style tag in head with `.sheet.cssRules` but they were all from this global style, none had the hash-style styled-components class names.

After removing the import the style returned to my page elements and all the rules had sc hashed class names.

This all worked in dev & prod until I upgraded to SCv5 when this issue appeared in prod builds.

Hope that helps, but if you need a repo I can provide it once I clean up my mess here and push a commit (it's way too late to do that now).

**Comment by josipbrcina** [comment] 2020-02-27 16:22
> So I've just resolved this by removing a style import from my site's global style.
> ie I removed the `@import` from this global style:
> 
> ```
> import modernNormalize from "styled-modern-normalize";
> import { createGlobalStyle } from "styled-components";
> 
> export const GlobalStyle = createGlobalStyle`
>   @import url('https://fonts.googleapis.com/css?family=Roboto:400,500,600');  
>   ${modernNormalize}
> 
>   html, body {
>     font-family: Roboto, sans-serif;
>     font-size: 10px;
>     line-height: 1.5;
>   }
> 
>   * {
>     box-sizing: border-box;
>   }
> `;
> ```
> 
> Before the fix only the body showed any style, the text, input elements, etc were completely unstyled. I could see rules in the style tag in head with `.sheet.cssRules` but they were all from this global style, none had the hash-style styled-components class names.
> 
> After removing the import the style returned to my page elements and all the rules had sc hashed class names.
> 
> This all worked in dev & prod until I upgraded to SCv5 when this issue appeared in prod builds.
> 
> Hope that helps, but if you need a repo I can provide it once I clean up my mess here and push a commit (it's way too late to do that now).

Wow this is just really bizarre. I was having the same issue, started debugging like 2 hours ago and now I ran on this comment that actually solved my issue.

**Comment by pitops** [comment] 2020-03-07 12:33
Have the same issue, seems removing @import from globalStyles is the way to go.

**Comment by jeancrus** [comment] 2020-03-18 15:42
Same.... if u are using globalStyles and have @import i, it doesnt inject the styles in production.

**Comment by nkhil** [comment] 2020-05-02 05:48
Thank you, removing @imports fixes it. However, I'd like to know what a good alternative to set font-family at the global level is.

**Comment by henriqueweiand** [comment] 2020-05-21 18:27
> Thank you, removing @imports fixes it. However, I'd like to know what a good alternative to set font-family at the global level is.

import './styles/global.css';

**Comment by awaisayub149** [comment] 2020-09-21 07:51
i am having same issue today, using `5.2.0`, not using `globalStyle`.

**Comment by huksley** [comment] 2021-01-21 08:45
Same problem, and I am using styled components 5.2.1 and not using globalStyle.
Working fine for NextJS 10.x app in production. 

However, I am also creating browser extension with the same codebase where I do not have full control over the HTML document. So it makes it difficult to inject font without using `@import`.

**Comment by bitworking** [comment] 2021-02-05 11:37
Me too. What I have seen is that for the problematic styles I only have something like this in the sourcecode:

data-styled.g186[id="sc-ehsPrw"]{content:"conNwD,"}/*!sc*/

I have no @import in the globalStyles.

Also REACT_APP_SC_DISABLE_SPEEDY=true in.env makes no difference, or I don't know where to put it. (Windows/NextJs/Docker)

**Comment by bitworking** [comment] 2021-02-05 12:06
Seems that "data-styled." is now in the sourcecode for every class. But my behaviour is very strange. Sometimes the styles are in the sourcecode sometimes not. Sometimes it looks like the styles get lost after the hydration.

**Comment by bitworking** [comment] 2021-02-05 14:37
It seems that I fixed it. I had to downgrade the "babel-plugin-styled-components" to 1.10.2 and in my babel config I had to add it with "styled-components" and not "babel-plugin-styled-components".

**Comment by bryanwhitehead** [comment] 2021-02-16 11:20
Same problem I think (I'm new to React), and I was unable to fix.  I did not have success uninstalling styled-components, but was able to get style-components version 4.2.0 working.   
`npm i styled-components@4.2.0`

**Comment by petlys** [comment] 2021-02-23 13:26
Same problem here. 
Not using `globalStyle`.
Downgrading to 4.2.0 does nothing.
Just suddenly started to appear. Prod builds work fine...

<img width="902" alt="Screenshot 2021-02-23 at 14 19 40" src="https://user-images.githubusercontent.com/6960273/108849690-c13d2280-75e2-11eb-93bf-bf1a0b281b97.png">

**Comment by jlopezxs** [comment] 2021-03-10 14:11
Same problem, 
Next.js 10.0.8 without any custom webpack config
But I have problems in dev and prod build too. When you are using client side looks like all the styles are not ok.
Downgrading to 4.x and nothing

**Comment by kitten** [comment] 2021-08-09 18:25
Closing due to age of issue, lack of addressability, or lack of reproduction.

**Closed by kitten** 2021-08-09 18:25 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
