### ISSUE TITLE
How do you deal with multiple style props in a single component?

### ISSUE THREAD

**Issue by GollyJer** [styled-components/styled-components#2697] opened 2019-07-31 18:48 UTC
For example, how do I implement styled-components with the this chat bubble?

```typescript
<Bubble
  textStyle={{
    color: '#000',
  }}
  wrapperStyle={{
    backgroundColor: '#f0f0f0',
  }}
/>
```

**Comment by PaulACoroneos** [comment] 2019-08-02 19:04
Pass the style (left/right) as a prop. Then within your component do something like

color: ${(props) => props.direction === 'left ? #000 : #f0f0f0;
backgroundColor: ${(props) => props.direction === 'left ? f0f0f0 : #000;

If you have more than left/right you can put a switch statement or something similar.

**Comment by GollyJer** [comment] 2019-08-04 04:10
Hi @PaulACoroneos. Thanks for the help. Can you use this example to help further. I can't figure out how to pass the style to multiple props.

```

**Comment by GollyJer** [comment] 2019-08-04 04:59
Hi @PaulACoroneos. Thanks for the help. I edited the question to better represent the real problem. Left/Right weren't where I was having trouble. 

What I can't figure out is how to pass two "stylesheets" inside one styled-component.

```typescript
export const StyledBubble = styled(({ style, ...remainingProps }) => (
  <Bubble 
    {...remainingProps}
    textStyle={{ style }}
    wrapperStyle={{ ???? }} 
  />
))`
  color: '#000';
`,  // this is pseudo code. How would you get something like this into the wrapperStyle?
`
  backgroundColor: '#f0f0f0',
`;
```

**Comment by PaulACoroneos** [comment] 2019-08-04 17:24
I think I understand your intention. However that's not really a pattern I would recommend. You don't pass different style sheets into a styled component. You modify the style by 

1) using the themeprovider (object that is passed into the apps context)

2)  by extending base styles ie:

export const Styledbubble = styled(Bubble)``

3) Just created more styled components

So like in your code above inside the styled component you will have access to your styled props. You might create a prop on the component that if passed will instruct the styled component to use some style on one or many attributes. 

Then after that you just write your code like a standard css class. so if we consider wrapperstyle just to be a prop on the styled component:

`color: ${(props) => props.wrapperStyle.color};
backgroundColor:${(props) => props.wrapperStyle.backgroundColor};
`
You could also create the themeprovider and have something like this i believe:

` color: ${(props) => props.theme.wrapperStyle[props.direction]} `

where essentially inside your theme file you have the different types of styles for your bubble and you pass a prop into the component that then picks the appropriate theme based on which type you want to use.

There are a lot of examples out there. I would recommend maybe looking through the documents again and finding some popular repos on github who utilize the library. I hope this was somewhat helpful.

**Comment by GollyJer** [comment] 2019-08-04 18:38
Thanks @PaulACoroneos. 
Those are all good ideas. I'm using the traditional approach `export const StyledBubble = styled(Bubble)` for many other components. This bubble is out of my control and doesn't use a traditional `style` prop, only this combination of multiple different style props.

I'm going with your theme approach. Thanks!

**Comment by PaulACoroneos** [comment] 2019-08-04 18:39
Not a problem! I learn something new about styled components every week. If anyone else reading this thread has suggestions I'd be happy to see those as well. Take care.

**Comment by probablyup** [comment] 2019-08-07 02:21
Closing as this is a usage thing not a bug or enhancement request, glad you got some help with your case!

**Closed by probablyup** 2019-08-07 02:21 UTC
