### ISSUE TITLE
Separated selectors generate empty component class name

### ISSUE THREAD

**Issue by ourstudio-erikblomqvist** [styled-components/styled-components#2875] opened 2019-11-13 09:48 UTC
Hi!

I'm working on a project where we're using [styleguidist](https://github.com/styleguidist/react-styleguidist) together with styled-components to present our components and then reference that library in our app to use the components. I've now run in to an issue that only occurs in the app, but not in the styleguidist project.

## System:
 - OS: macOS 10.15
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 243.12 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.11.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ~1.10.6 => 1.10.6
 - styled-components: ~4.3.2 => 4.3.2

## The component

This is an icon component and the code is supposed to add a margin to the side of it, if it's 1) preceded by anything else and 2) inside a CTA button/CTA link component.

The code looks like this:

```
const IconWrapper = styled.span<IIconWrapperProps>`
  ${CTALink} * ~ &,
  ${CTAButton} * ~ & {
    [dir="ltr"] & {
      margin-left: ${sizeCalc()};
    }

    [dir="rtl"] & {
      margin-right: ${sizeCalc()};
    }
  }
`
```

## Expected Behavior
 
The CSS code being generated in the styleguidist project looks like this:

```
[dir="ltr"] .CTALink-sc-1uvchy5-0 * ~ .gmSsLu,
[dir="ltr"] .CTAButton-sc-5jwiqv-0 * ~ .gmSsLu {
    margin-left: 8px;
}
```

## Actual Behavior

In the app, this is the CSS code:

```
[dir="ltr"] .sc-gqjmRU * ~ .dQRngX,
[dir="ltr"] * ~ .dQRngX {
    margin-left: 8px;
}
```

As you can see, it leaves out the CSS class name on the second line for the CTAButton component. At first, I thought this would be because the CTAButton isn't used on the specific page, but it is (as well as the CTALink).

I have tried to _not_ to separate them by a comma (i.e. `${CTALink} * ~ & {…}` and `${CTAButton} * ~ & {…}`), without any difference.

**Comment by mxstbr** [comment] 2019-11-13 09:54
What does `console.log(CTAButton)` output in both cases? It looks like the Babel plugin is not applied in the failing case (although that shouldn't matter)?

**Comment by ourstudio-erikblomqvist** [comment] 2019-11-13 10:08
> What does `console.log(CTAButton)` output in both cases? It looks like the Babel plugin is not applied in the failing case (although that shouldn't matter)?

Let me know if I should expand any parts here:

- [styleguidist](https://imgur.com/FosmSKA)
- [app](https://imgur.com/kreJG5z)

I tried turning off the `babel-plugin-styled-components` in the styleguidist project, and it still renders renders correctly in that project.

**Comment by mxstbr** [comment] 2019-11-13 10:52
Huh this definitely looks like it should work in both cases 🤔🤔🤔

**Comment by ourstudio-erikblomqvist** [comment] 2019-11-13 11:54
> Huh this definitely looks like it should work in both cases 🤔🤔🤔

I know, right? Any other ways I could troubleshoot this, to your knowledge?

**Comment by probablyup** [comment] 2020-01-03 17:09
Really need a reproduction to be able to help in some way

**Comment by kitten** [comment] 2021-08-09 18:26
Closing due to age of issue, lack of addressability, or lack of reproduction.

**Closed by kitten** 2021-08-09 18:26 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
