### ISSUE TITLE
Flow errors when using react-create-app

### ISSUE THREAD

**Issue by msmfsd** [styled-components/styled-components#177] opened 2016-11-08 23:55 UTC
## Version
1.0.10

Guys love styled-components so thanks!
Am on v1.0.10 and still getting flow-type errors. Note I am using create-react-app.

My flow config is as per create-react-app guidelines:
```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*
```

Mu deps:
```
"devDependencies": {
    "babel-eslint": "6.1.2",
    "eslint": "3.5.0",
    "eslint-plugin-flowtype": "2.18.1",
    "eslint-plugin-import": "1.12.0",
    "eslint-plugin-jsx-a11y": "2.2.2",
    "eslint-plugin-react": "5.2.2",
    "flow-bin": "^0.34.0",
    "react-scripts": "0.7.0"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "recompose": "^0.20.2",
    "styled-components": "^1.0.10"
  }
```

Here are the errors:
```
node_modules/styled-components/src/models/InlineStyle.js:3
  3: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/src/models/InlineStyle.js:5
  5: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/native/index.js:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/utils/flatten.js:2
  2: import hyphenate from 'fbjs/lib/hyphenateStyleName'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found
```

**Comment by mxstbr** [comment] 2016-11-09 13:52
Handing over to @relekang @ryyppy, they should know what's going on here! The thing about `react-native` is that we require it in the code, but it's not in our dependencies to avoid bundling it in. (you'll have it in your dependencies anyway when using `styled-components` with it)

**Comment by relekang** [comment] 2016-11-09 14:38
I think this will be resolved by #151. The problem is that in the flowconfig fbjs is ignored, but fbjs is imported in styled-components. 

When we are able to generate the flow imports will not be read by flow since they will not be a part of the flow files.

**Comment by ryyppy** [comment] 2016-11-10 09:27
@relekang I am a little bit worried about the optional `react-native` dependency... not sure how to deal with that... probably we should add some instructions for `.flowconfig` options to map the `react-native` imports to `any`... in case you don't use `react-native` of course?

**Comment by relekang** [comment] 2016-11-12 17:29
@ryyppy I am not sure I follow. What is the problem with the react-native dependency?

**Comment by ryyppy** [comment] 2016-11-13 20:59
If you don't `npm install react-native`, `styled-components` will probably always cause typing errors because it internally imports `react-native` somewhere. If you don't install `react-native`, there won't be any typings for it, right? so we need some instructions to create a `any` libdef for that regard

**Comment by relekang** [comment] 2016-11-14 08:06
I think that if we have flow.js files for all files then flow won't read the source files, which means that it will be ok if we are able to export all types from native files without relying on react-native imports in the flow.js files.

**Comment by msmfsd** [comment] 2016-11-15 23:37
Thanks for looking at this guys. Is this fixed in 1.0.11?

**Comment by ryyppy** [comment] 2016-11-16 11:59
Looked at the build scripts... apparently not yet... maybe I will do this today!

**Comment by mxstbr** [comment] 2016-11-20 07:11
Done in #219, thanks to the amazing @ryyppy!

**Closed by mxstbr** 2016-11-20 07:11 UTC
Labels: bug, help wanted

**Comment by msmfsd** [comment] 2016-11-20 23:36
Updated to v1.0.11 and now getting 14 flow errors. NOTE I am using create-react-app and deps are:
```
  "devDependencies": {
    "babel-eslint": "6.1.2",
    "eslint": "3.5.0",
    "eslint-plugin-flowtype": "2.18.1",
    "eslint-plugin-import": "1.12.0",
    "eslint-plugin-jsx-a11y": "2.2.2",
    "eslint-plugin-react": "5.2.2",
    "flow-bin": "^0.34.0",
    "react-scripts": "0.7.0"
  },
  "dependencies": {
    "approved-browser": "^1.0.2",
    "fetch-jsonp": "^1.0.2",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "styled-components": "1.0.11",
    "webrtcsupport": "^2.2.0",
    "whatwg-fetch": "^1.0.0"
  }
```

Flow errors:
```
node_modules/styled-components/src/constructors/test/keyframes.test.js:2
  2: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/keyframes.test.js:13
 13: describe('keyframes', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:14
 14:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:19
 19:   it('should return its name', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/models/InlineStyle.js:3
  3: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/src/models/InlineStyle.js:5
  5: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/models/StyledNativeComponent.js:22
 22:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 22:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/src/native/index.js:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/utils/autoprefix.js:2
  2: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/src/utils/autoprefix.js:3
  3: import hyphenateStyleName from 'fbjs/lib/hyphenateStyleName'
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/src/utils/flatten.js:2
  2: import hyphenate from 'fbjs/lib/hyphenateStyleName'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/src/utils/flatten.js:26
 26:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with
  7: export const objToCss = (obj: Object): string => (
                                   ^^^^^^ object type
```

**Comment by ryyppy** [comment] 2016-11-21 01:14
You need to ignore the `styled-components/src` directory, as stated in our [flow-support](https://github.com/styled-components/styled-components/blob/master/docs/flow-support.md) docs...

Add following ignore rule in your `.flowconfig`:

```
# We vendor our src directory, which is not needed for type-checking
.*/styled-components/src/.*
```

@mxstbr Is there a reason why `styled-components` needs to deliver the `src` content in the npm package?

**Comment by mxstbr** [comment] 2016-11-21 09:25
We haven't released the improvements yet, will do asap.

> @mxstbr Is there a reason why styled-components needs to deliver the src content in the npm package?

It's nice for users to be able to check what the source looks like 😊 same reason we ship the `docs/` folder even though it's not strictly needed, can't hurt!

**Comment by msmfsd** [comment] 2016-11-22 03:30
OK this was not a create-react-app specific issue. I just followed the [flow-support](https://github.com/styled-components/styled-components/blob/master/docs/flow-support.md) docs as recommended by @ryyppy - thanks all 👍
