### ISSUE TITLE
Runtime error "__WEBPACK_IMPORTED_MODULE_0_stylis___default.a.set is not a function"

### ISSUE THREAD

**Issue by IIIristraM** [styled-components/styled-components#914] opened 2017-06-13 14:30 UTC
v2.0.1
webpack v2.6.1
babel-core v6.24.1
awesome-typescript-loader v3.1.3

tsconfig:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "suppressImplicitAnyIndexErrors": true,
    "jsx": "react",
    "baseUrl": ".",
    "typeRoots" : ["./types", "./node_modules/@types"],
    "paths": {
      "*": [
        "app/scripts/*",
        "types/*",
        "node_modules/*"
      ]
    }
  }
}
```

Error: `__WEBPACK_IMPORTED_MODULE_0_stylis___default.a.set is not a function`
Error source (/node_modules/styled-components/dist/styled-components.es.js):
```
__WEBPACK_IMPORTED_MODULE_0_stylis___default.a.set({
  global: false,
  cascade: true,
  keyframe: false,
  prefix: true,
  compress: false,
  semicolon: true
});
```

**Comment by k15a** [comment] 2017-06-13 15:22
Could you try #901 please?

**Comment by k15a** [comment] 2017-06-14 17:31
Pretty sure this is a duplicate of #901.

**Closed** 2017-06-14 17:31 UTC
Labels: bug
