### ISSUE TITLE
Bug with closing braces in block comments can cause infinite loop or wrong styles generated

### ISSUE THREAD

**Issue by AllainPL** [styled-components/styled-components#1842] opened 2018-07-11 18:07 UTC
Hi, i found a bug in stylis.js, but as styled-components is affected I am posting it here to remember about addressing it when stylis will fix it.

Putting `/* } */` inside a rule can cause bad code generated.
Using `/*}*/` or `/* )} */` or as in my case `/* lighten(___, 5%) ___} darken(___, 10%); */` causes an infinite loop while generating styles.

I just reported the bug in stylis.js - https://github.com/thysultan/stylis.js/issues/110

**Comment by probablyup** [comment] 2018-07-11 20:01
Have you tried using the other comment syntax? `// something`

**Comment by aczekajski** [comment] 2018-07-12 15:55
Using inline comments does not cause infinite loops but can still cause improper styles generation because of errors in stylis.js (see https://github.com/thysultan/stylis.js/issues/110).

This is not really an issue with styled components. However, other users might file an issues related to this stylis error.

See this simple example:
https://codepen.io/anon/pen/QBbmWX
Letter "T" should be red but the `/* } */` causes it to not contain the `color: red` style. If you remove comment, it behaves correctly. If you replace this comment with `/*}*/`, the codepan will fall into infinite loop.

**Comment by probablyup** [comment] 2018-07-12 15:56
We don’t support the other syntax btw. At least not in sc. our comment
regex only removes single line comments

**Comment by aczekajski** [comment] 2018-07-12 16:01
@probablyup How can you not support block comments while it's the only proper way to comment things out in raw CSS and the single line comments are "the additional method"?

**Comment by aczekajski** [comment] 2018-07-12 16:07
Btw, look at this example too:
https://codepen.io/anon/pen/VBLXWd
This time, whole "Text" is red, while it shouldn't. I believe this is also caused by the same problem in stylis.js.

**Comment by aczekajski** [comment] 2018-07-12 20:06
Bug got fixed in stylis.js release https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md#352-july-12-2018

**Comment by probablyup** [comment] 2018-07-13 18:31
Cool. We use a semver range for stylis, so there should be nothing to do here on our end.

**Closed** 2018-07-13 18:31 UTC
