### ISSUE TITLE
Inconsistent attrs behaviour

### ISSUE THREAD

**Issue by aczekajski** [styled-components/styled-components#2372] opened 2019-02-07 12:36 UTC
## Environment
styled-components: 4.1.3

## Reproduction
While the props from `attrs` take precedence before props passed to the component when we look at them in interpolation, things go weird and inconsistent when you look at html or do `styled(...)`.

Take a look at this example (you can paste it directly into these little editors in SC docs or visit https://codesandbox.io/embed/5wo2893zmn):
```js
const X = (props) => {
  console.log('Gimme props', props.children, props.color);
  return <div {...props} />
};

const A = styled(X)`
  border: 5px solid ${props => props.color};
`;

const B = styled(A).attrs({
  color: "red",
  'data-test': 'red',
})`
  color: ${props => props.color};
`;

const C = styled(B)`
  background: ${props => props.color || 'none'};
`;

render(
  <div>
    <C>First</C>
    <br />
    <C color="blue" data-test="blue">Second</C>
  </div>
);
```

## Expected Behavior
What I'd expect from it? First div should have no background (as the `C` component doesn't receive `color` prop and has no `attrs`), red text (received from `attrs` defined by `B`) and red border (a `color` prop should get populated down from `B` to `A`). Following the same pattern, second div should have blue background, red text and red border.

## Actual Behavior
They both have red backgrounds. How in the world the `color` prop defined in `attrs` of `B` gets populated **up** to props of component `C`?

Also, if the props from `attrs` really are being populated down, why the console logs coming from `X` component say
```
Gimme props First red // this got populated down
Gimme props Second blue // but here the prop from render method took precedence
```
and thus the resulting html markup for the second div looks like this:
```html
<div color="blue" data-test="blue" class="sc-fVHxE kvtWkp">Second</div>
```

It seems to have something in common with the SCv4 merging mechanism. If I create another component
```js
const Z = (props) => <B {...props} />
```
and "cut" the styled components path C->B->A by changing C from `styled(B)` into `styled(Z)` (so now we have C->Z->B->A), the first div expectedly gets no background and the second - blue background.

Might also be related to https://github.com/styled-components/styled-components/issues/2246

If any part of it is somehow intended, it should be thoroughly described in the docs.

**Comment by oomathias** [comment] 2019-03-19 13:05
Here is why https://github.com/styled-components/styled-components-website/issues/56#issuecomment-474354536

**Comment by stephan-noel** [comment] 2019-09-08 09:57
@oomathias thank you for referencing this diagram, this is exactly the behavior I'm seeing as well, the problem is that the behavior seems incorrect (please correct me if I'm wrong).  

The semantics of the API seems to imply that attrs is supposed to "override" props, and it does, but only inside of our StyledComponents and their template string arguments.  When it comes to the DOM node itself, the props passed to the JSX takes priority over attrs.  This creates an inconsistency between my styles and my HTML attributes in the DOM.  Does this mean that my styles should never depend on an HTML attribute?

The example that brought me here is the following:

```
const Input = styled.input.attrs({type:'password'})`

    // Here, props have type: "password"
    ${props => console.log(props)}
`
const Header = props => {
    return (
    <div id='myWrapper'>

    // In the DOM, type="text" will take precedence over attrs
       <Input type='text'/>
    </div>
    );
}
```

In the DOM I have: 

```
<div id="myWrapper">
    <input type="text" class="sc-ifAKCX blnnqO">
</div>
```

If I were to add styles that read the "type" HTML attribute and varied based on that, or did something similar in some StyledComponent that extends or composes this `Input `component, the styles would be out of sync with what is in the DOM and displayed to the user.  This really seems like a bug to me.

**Environment**
styled-components 4.3.2.

**Comment by probablyup** [comment] 2020-01-02 18:11
This has been fixed in later versions, precedence is as follows: attrs > props > defaultProps.

If you need to access the props value, you can do so via attrs function:

```js
.attrs(p => ({ color: p.color || "red" }))
```

**Closed by probablyup** 2020-01-02 18:11 UTC
