### ISSUE TITLE
Nested CSS Function inside escaped string breaks stylis conversion

### ISSUE THREAD

**Issue by olegreznichenko** [styled-components/styled-components#2121] opened 2018-10-18 17:17 UTC
## Environment
Command from the template is failed with error `UnhandledPromiseRejectionWarning: Error: The system cannot find the path specified.` but before fail displayed this info
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
 - Memory: 1.94 GB / 7.91 GB
## Binaries:
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
 - node 10.12.0
 - babel-plugin-styled-components 1.8.0
 - styled-components 4.0.0-beta.3 

Unfortunately, some global styles are missing with latest (4.0.2) styled. Not sure if not global styles also missing because hard to debug. I migrate to new API when released the first beta and it was working fine with beta3 but not with all next beta releases. And now with stable also.

**Comment by kitten** [comment] 2018-10-18 22:15
Can you post some code samples please? Or better yet, a Codesandbox? Otherwise this is not enough info to help you :)

**Comment by olegreznichenko** [comment] 2018-10-19 06:55
Its relative with ssr, as I know Codesandbox does not support any server setup. I will try to create repo example.

**Comment by olegreznichenko** [comment] 2018-10-19 15:41
@kitten https://codesandbox.io/s/5wn3z7z71x

**Comment by olegreznichenko** [comment] 2018-10-21 19:56
Any rules after .bad-css will not be applied

**Comment by kitten** [comment] 2018-10-21 20:17
This seems like a usage issue to me; I forked your CodeSandbox and all seems fine: https://codesandbox.io/s/03n5260nmp

Please check the docs on `createGlobalStyle` for clarification: https://www.styled-components.com/docs/api#createglobalstyle

The relevant points are:

- It does not accept `children`
- If you inject rules, just like in regular CSS they'll need to be used to take effect

**Comment by olegreznichenko** [comment] 2018-10-22 08:33
Please reopen, I forked your code sandbox. It's definitely a bug, not usage issue. Read again my problem, after `.bad-css` all next styles not applied. the body hasn't background and even `.hello` rule also.
https://codesandbox.io/s/1qxl697vjj

**Comment by olegreznichenko** [comment] 2018-10-22 08:35
@mxstbr, please make attention for this issue.

**Comment by kitten** [comment] 2018-10-22 14:05
It looks like all subsequent rules are changed to include the first className, i.e. `.bad-css body {}`. Furthermore, this seems to occur because of `fill='rgba(...)'`. I'd guess the inclusion of a non-escaped CSS function inside another CSS function (`url()`) confuses stylis.

I'd recommend you to replace this fill colour with a hex code for now.

cc @thysultan: This might be a stylis bug where `()` inside another function in this specific combination throws "something" off in stylis, if I'm not mistaken? I'd totally understand if it's too obscure to fix for now

**Comment by thysultan** [comment] 2018-10-22 14:11
It's likely. Could you open an issue with the repro/test case(outside of s-c) there.

**Comment by olegreznichenko** [comment] 2018-10-22 14:59
finally, me understand :)
@thysultan
I created in https://codepen.io/Nonlimit/pen/XxBQYR

**Comment by probablyup** [comment] 2018-10-25 18:36
Closing since this isn't on our end. @olegreznichenko I recommend opening an issue against stylis if you haven't already with your reproduction

**Closed by probablyup** 2018-10-25 18:37 UTC
Labels: question :question:
