### ISSUE TITLE
Understanding styled-components performance issues

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#744] opened 2017-04-25 05:28 UTC
I recently stumbled upon this CSS in JS Benchmark: https://github.com/A-gambit/CSS-IN-JS-Benchmarks and was surprised to find styled component score low there, hence wanted to start this discussion to see if:

1) This benchmark is accurate ?
2) What is `decouple-cell` they refer to that seems to improve performance?
3) Why is there such a big difference between `styled-components` and `styletron` for example, as their API seems to be very similar (see below)

```
const Panel = styled('div', (props) => ({
  backgroundColor: props.alert ? 'orange' : 'lightblue',
  fontSize: '12px'
}));
```

It would be good to hear any plans / ideas about improving performance in v2 if you guys are working on some :)

**Comment by kopax** [comment] 2017-04-25 11:51
Thanks for sharing this, I would be glad to have the authors opinions about it. I haven't done any benchmark myself but I feel that debugging can be slow probably due to the developer console.

I haven't got any application that use styled released in production yet but I will write a feedback as soon as I have.

**Comment by philpl** [comment] 2017-04-25 15:06
We have an ongoing issue that tracks some perf regressions in v2 where we can discuss this.

Btw only look at the second section for SC perf: "Average results of table where all static styles use css and dynamic styles use inline-styles." We don't recommend highly dynamic styles to be generated with SC.

I also doubt the accuracy of the first set of tests, since v2 ranks higher than v1, which is inconsistent with our own benchmarks.

https://github.com/styled-components/styled-components/issues/583

**Closed by philpl** 2017-04-25 15:06 UTC
Labels: discussion
