### ISSUE TITLE
Flow errors with latest versions

### ISSUE THREAD

**Issue by msmfsd** [styled-components/styled-components#302] opened 2016-12-09 19:40 UTC
### v1.1.3
I am getting flow errors when using latest versions of styled-components with create-react-app. 

My flow config is as per create-react-app and styled-components docs and I have done a flow-typed install as well. My deps:
```
"react-scripts": "0.8.3"
"flow-bin": "^0.36.0",
"react": "^15.4.1",
"react-dom": "^15.4.1",
"styled-components": "^1.1.3"
```

Flow errors:
```
node_modules/styled-components/lib/utils/autoprefix.js.flow:2
  2: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/lib/utils/autoprefix.js.flow:3
  3: import hyphenateStyleName from 'fbjs/lib/hyphenateStyleName'
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/lib/utils/flatten.js.flow:2
  2: import hyphenate from 'fbjs/lib/hyphenateStyleName'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string
```

This below seems to fix it for now:
```
.*/styled-components/lib/utils/autoprefix.js.flow
.*/styled-components/lib/utils/flatten.js.flow
.*/styled-components/lib/models/StyledNativeComponent.js.flow
```

**Comment by mxstbr** [comment] 2016-12-09 20:22
@styled-components/typers any ideas?

**Comment by relekang** [comment] 2016-12-10 08:30
The problem here is that react-create-app documentation says to add the following to ignore sections of the flowconfig.

```
<PROJECT_ROOT>/node_modules/fbjs/.*
```

Since we import that and have not provided a libdef for it flow will give `Required module not found`. We can fix this two ways:
* Add to flow docs that one should only ignore problematic paths in fbjs.
* Add a bundled libdef for fbjs.

For this issue: 
```
node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string
```

I think this might be a problem introduced lately, I will look into it and hopefully come up with a PR.

**Comment by msmfsd** [comment] 2016-12-12 04:09
@relekang thanks for looking at his

**Comment by AsaAyers** [comment] 2016-12-12 21:08
I'm also using `create-react-app@0.7` with `styled-components@1.0.8` and I'm not building a `react-native` app. But I'm unable to add flow because I keep getting:

```
node_modules/styled-components/src/models/InlineStyle.js:5
  5: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/native/index.js:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found
```

How can I configure these two to be ignored? I don't seem to be able to ignore them the way I ignore `fbjs`. I also just tried upgrading `styled-components` and I went from those two errors to 86 errors.

**Comment by hongymagic** [comment] 2016-12-19 00:12
This should be fixed with 1.2.1

**Closed** 2016-12-20 12:59 UTC
Labels: bug

**Comment by Augustin82** [comment] 2016-12-22 14:40
It's not =/ Am I doing something wrong?

```
node_modules/styled-components/lib/models/InlineStyle.js.flow:4
  4: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/native/index.js.flow:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/utils/autoprefix.js.flow:2
  2: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/lib/utils/autoprefix.js.flow:3
  3: import hyphenateStyleName from 'fbjs/lib/hyphenateStyleName'
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/lib/utils/flatten.js.flow:2
  2: import hyphenate from 'fbjs/lib/hyphenateStyleName'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ number. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:3
  3: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:4
  4: import { shallow } from 'enzyme'
                             ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:15
 15: describe('injectGlobal', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:16
 16:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/constructors/test/injectGlobal.test.js:20
 20:   it(`should inject rules into the head`, () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:2
  2: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/keyframes.test.js:13
 13: describe('keyframes', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:14
 14:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/constructors/test/keyframes.test.js:19
 19:   it('should return its name', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/constructors/test/styled.test.js:2
  2: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/constructors/test/styled.test.js:6
  6: describe('styled', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/constructors/test/styled.test.js:7
  7:   it('should have all valid HTML5 elements defined as properties', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/models/InlineStyle.js:4
  4: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/models/StyledNativeComponent.js:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/src/models/test/ThemeProvider.test.js:4
  4: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/models/test/ThemeProvider.test.js:5
  5: import { shallow, render } from 'enzyme'
                                     ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/models/test/ThemeProvider.test.js:8
  8: describe('ThemeProvider', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/models/test/ThemeProvider.test.js:9
  9:   it('should not throw an error when no children are passed', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/native/index.js:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/test/basic.test.js:3
  3: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/test/basic.test.js:4
  4: import { shallow, mount } from 'enzyme'
                                    ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/test/basic.test.js:5
  5: import jsdom from 'mocha-jsdom'
                       ^^^^^^^^^^^^^ mocha-jsdom. Required module not found

node_modules/styled-components/src/test/basic.test.js:12
 12: describe('basic', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/basic.test.js:16
 16:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/basic.test.js:20
 20:   it('should not throw an error when called', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/css.test.js:3
  3: import { shallow } from 'enzyme'
                             ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/test/css.test.js:9
  9: describe('css features', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/css.test.js:10
 10:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/css.test.js:14
 14:   it('should add vendor prefixes in the right order', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/extending.test.js:3
  3: import expect from 'expect'
                        ^^^^^^^^ expect. Required module not found

node_modules/styled-components/src/test/extending.test.js:4
  4: import { shallow } from 'enzyme'
                             ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/test/extending.test.js:10
 10: describe('extending', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/extending.test.js:14
 14:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/extending.test.js:18
 18:   it('should generate a single class with no styles', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/props.test.js:3
  3: import { shallow } from 'enzyme'
                             ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/test/props.test.js:9
  9: describe('props', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/props.test.js:10
 10:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/props.test.js:14
 14:   it('should execute interpolations and fall back', () => {
       ^^ identifier `it`. Could not resolve name

node_modules/styled-components/src/test/styles.test.js:3
  3: import { shallow } from 'enzyme'
                             ^^^^^^^^ enzyme. Required module not found

node_modules/styled-components/src/test/styles.test.js:9
  9: describe('with styles', () => {
     ^^^^^^^^ identifier `describe`. Could not resolve name

node_modules/styled-components/src/test/styles.test.js:13
 13:   beforeEach(() => {
       ^^^^^^^^^^ identifier `beforeEach`. Could not resolve name

node_modules/styled-components/src/test/styles.test.js:17
 17:   it('should append a style', () => {
       ^^ identifier `it`. Could not resolve name
```

**Comment by relekang** [comment] 2016-12-22 14:44
@Augustin82 Have you followed the [flow setup docs](https://github.com/styled-components/styled-components/blob/master/docs/flow-support.md)?

**Comment by Augustin82** [comment] 2016-12-22 14:57
Hi @relekang, and thanks for your help.

I had not followed the doc: I'm trying to extract some of our code into an external module, and it worked fine in the main project.

Now, I have followed the instructions, and get less errors... but still some (from fbjs and styled-components).

```
node_modules/fbjs/lib/countDistinct.js.flow:22
 22: function countDistinct<T1, T2>(iter: Iterable<T1>, selector: (item: T1) => T2): number {
                                          ^^^^^^^^^^^^ type application of identifier `Iterable`. Too few type arguments. Expected at least 2
 32: declare class Iterable<K, V> extends _Iterable<K, V, typeof KeyedIterable, typeof IndexedIterable, typeof SetIterable> {}
                            ^^^^ See type parameters of definition here. See lib: node_modules/immutable/dist/immutable.js.flow:32

node_modules/fbjs/lib/countDistinct.js.flow:26
 26:   for (var val of iter) {
       ^ property `@@iterator` of $Iterable. Property not found in
 26:   for (var val of iter) {
                       ^^^^ Iterable

node_modules/fbjs/lib/countDistinct.js.flow:26
 26:   for (var val of iter) {
                       ^^^^ type application of identifier `Iterable`. Too few type arguments. Expected at least 2
 32: declare class Iterable<K, V> extends _Iterable<K, V, typeof KeyedIterable, typeof IndexedIterable, typeof SetIterable> {}
                            ^^^^ See type parameters of definition here. See lib: node_modules/immutable/dist/immutable.js.flow:32

node_modules/fbjs/lib/maxBy.js.flow:24
 24:   return minBy(as, f, (u, v) => (compare: any)(v, u));
                    ^^ type application of identifier `Iterable`. Too few type arguments. Expected at least 2
 32: declare class Iterable<K, V> extends _Iterable<K, V, typeof KeyedIterable, typeof IndexedIterable, typeof SetIterable> {}
                            ^^^^ See type parameters of definition here. See lib: node_modules/immutable/dist/immutable.js.flow:32

node_modules/fbjs/lib/minBy.js.flow:19
 19: function minBy<A, B>(as: Iterable<A>, f: (a: A) => B, compare?: ?(u: B, v: B) => number): ?A {
                              ^^^^^^^^^^^ type application of identifier `Iterable`. Too few type arguments. Expected at least 2
 32: declare class Iterable<K, V> extends _Iterable<K, V, typeof KeyedIterable, typeof IndexedIterable, typeof SetIterable> {}
                            ^^^^ See type parameters of definition here. See lib: node_modules/immutable/dist/immutable.js.flow:32

node_modules/fbjs/lib/minBy.js.flow:25
 25:   for (var a of as) {
       ^ property `@@iterator` of $Iterable. Property not found in
 25:   for (var a of as) {
                     ^^ Iterable

node_modules/fbjs/lib/minBy.js.flow:25
 25:   for (var a of as) {
                     ^^ type application of identifier `Iterable`. Too few type arguments. Expected at least 2
 32: declare class Iterable<K, V> extends _Iterable<K, V, typeof KeyedIterable, typeof IndexedIterable, typeof SetIterable> {}
                            ^^^^ See type parameters of definition here. See lib: node_modules/immutable/dist/immutable.js.flow:32

node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ number. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type
```

Here is our .flowconfig. Sorry if it's a newbie mistake and I'm just missing something obvious.
```
[ignore]
.*/styled-components/src/.*

[include]

[libs]
./Types.js
./node_modules/immutable/dist/immutable.js.flow
./node_modules/styled-components/flow-typed/*.js
./node_modules/styled-components/flow-typed/react-native.js
./node_modules/styled-components/flow-typed/glamor_vx.x.x.js
./node_modules/styled-components/flow-typed/lodash_v4.x.x.js
./node_modules/styled-components/flow-typed/inline-style-prefixer_vx.x.x.js

[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
module.system.node.resolve_dirname=node_modules
experimental.strict_type_args=true
munge_underscores=true
suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe
```

**Comment by relekang** [comment] 2016-12-22 18:54
@Augustin82 Which flow version do you use?

**Comment by Augustin82** [comment] 2016-12-23 07:39
The 'extracted' module uses 0.37.4, the main project uses 0.34.0.

**Comment by Augustin82** [comment] 2016-12-23 08:14
I have managed to kill all my errors, except for styled-components ones.

Errors:
```
node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ number. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type
```

.flowconfig (Types.js contains our own type definitions):
```
[ignore]
.*/node_modules/redux-saga-test-plan/.*
.*/node_modules/styled-components/src/.*
.*/node_modules/config-chain/test/broken.json
.*/node_modules/npmconf/test/.*

[include]

[libs]
./Types.js
node_modules/styled-components/flow-typed/react-native.js
node_modules/styled-components/flow-typed/glamor_vx.x.x.js
node_modules/styled-components/flow-typed/lodash_v4.x.x.js
node_modules/styled-components/flow-typed/inline-style-prefixer_vx.x.x.js

[options]
module.system.node.resolve_dirname=app
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
module.system.node.resolve_dirname=node_modules
experimental.strict_type_args=true
munge_underscores=true
suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe
```

**Comment by ryyppy** [comment] 2016-12-23 14:56
Any pointers to an actual repository? It's hard to tell what's wrong without a minimal reproducible example project :-)

**Comment by Augustin82** [comment] 2016-12-23 15:06
I'm afraid the code is closed source for now.

However, it is close to being minimalistic, in that I have just "yarn add"-ed styled-components and used it in one of our files, nothing particularly fancy.

I could try and set up a demo if you think it's necessary, but apparently it's not the first time the problem I mention has occurred. Could it be the fix didn't fix every case?

**Comment by Augustin82** [comment] 2016-12-23 21:58
@ryyppy I have created a repo with what I think is the minimal reproducible example: https://github.com/Augustin82/styled-bug

`npm run build` builds fine, `npm run flow` show the same three errors I have quoted:
```
node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ number. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type
```

Do you need any kind of additional information?

**Comment by ryyppy** [comment] 2016-12-24 00:04
Thanks for the extra effort,.. will look into it this weekend (I am on holidays right now) :-)

**Comment by Augustin82** [comment] 2016-12-24 09:19
Heh, that's cool. Thank you for taking the time to look into this. Happy holidays.

**Comment by relekang** [comment] 2016-12-26 09:58
I think we still might not run flow correctly on CI 🙈 
It is fixed in [#fix-flow-ci-config](https://github.com/styled-components/styled-components/compare/fix-flow-ci-config), but there is a few flow errors. Will have a look at those when I have time. Kind of in vacation mode now though 🏂 ❄️

**Comment by Augustin82** [comment] 2016-12-29 08:53
Any update on this? Could this be reopened, so that it doesn't get swallowed in the Pit of Forgotten Issues? =P

Cheers!

**Comment by Augustin82** [comment] 2017-01-03 12:13
That PR was merged, but from (admittedly limited) my preliminary checks, I haven't been able to confirm it suppresses the type errors I have mentioned in my messages.

Could you please tell me if it specifically fixes them? Many thanks.

(Also, if anyone knows when a package containing those fixes will be published, that'd be ace!)

**Comment by hongymagic** [comment] 2017-01-16 05:24
No those three errors are back in 1.3.0, perfectly fine in 1.2.1

**Comment by Augustin82** [comment] 2017-01-16 07:47
@hongymagic I have a demo repo (https://github.com/Augustin82/styled-bug) that shows that those three errors are present on a brand new install of 1.2.1.

**Comment by hongymagic** [comment] 2017-01-16 07:59
The `.flowconfig` is wrong. `suppress_type` => `suppress_comment`, and the regex would be better with `.*\\$FlowIssue`

Please try and minimise config when replicating. I can confirm your repo works without those extra, incorrect config values.

**Comment by Augustin82** [comment] 2017-01-16 08:35
>>> The `.flowconfig` is wrong. `suppress_type` => `suppress_comment`, and the regex would be better with `.*\\$FlowIssue`
The config was done following this advice from Sam Goldman, who works on Flow at Facebook:
https://github.com/facebook/flow/issues/1895#issuecomment-223873623

I have removed our comments, put in the one comment that is in the 1.2.1 doc, and I can confirm it works fine.

The same repo with 1.3.0 produces four errors: the same three we've been talking about, and `danger` missing (since it's not declared a dependency anywhere).

However, the documentation for 1.3.0 shows no `suppress_comment` at all: removing the option from the .flowconfig file suppresses those three errors.

**Comment by Gregoor** [comment] 2017-04-13 15:00
any update on this? Getting the error with Flow 42 and styled 1.4.4

**Comment by stevenmusumeche** [comment] 2017-04-14 16:41
Same here

```
node_modules/styled-components/dangerfile.js:3
  3: import { danger, warn, fail, message } from 'danger'
                                                 ^^^^^^^^ danger. Required module not found

node_modules/styled-components/lib/models/InlineStyle.js.flow:4
  4: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/lib/models/StyleSheet.js.flow:18
 18:   get injected(): boolean {
       ^ Potentially unsafe get/set usage. Getters and setters with side effects are potentially unsafe and disabled by default. You may opt-in to using them anyway by putting `unsafe.enable_getters_and_setters=true` into the [options] section of your .flowconfig.

node_modules/styled-components/lib/native/index.js.flow:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found
```

**Comment by relekang** [comment] 2017-04-16 07:14
Have you tried the libdef on flow-typed?

**Comment by rovansteen** [comment] 2017-04-21 12:11
@relekang how do I install that? I've tried `flow-typed install styled-components@1.4.5` but I get the error message `!! No libdefs found in flow-typed for styled-components@1.4.5. !!`, same for every other version in the `1.4.x` range.

**Comment by relekang** [comment] 2017-04-21 12:30
@rovansteen Which version of flow do you have and do you have latest version of flow-typed?

**Comment by rovansteen** [comment] 2017-04-21 13:52
@relekang I'm using `flow-typed@2.1.0` and `flow@0.44.1`

**Comment by relekang** [comment] 2017-04-23 16:45
Seems like a bug with `flow-typed@2.1.x` got the same error with a bunch of libraries when I upgradeded. Downgraded to 2.0.0 and it works 🙂
