### ISSUE TITLE
Extends function ignoring child style with server side rendering

### ISSUE THREAD

**Issue by zegs21** [styled-components/styled-components#3094] opened 2020-04-07 15:05 UTC
I tried upgrading from version 4 to version 5, but it broke all extends features in our application. We do server side rendering with Rails 5. I have look for other issues but have not found anything that could help me so I'm reaching out here to see if this may be a bug.

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
 - Memory: 358.81 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.8.0 - /usr/local/bin/node
 - Yarn: 1.19.2 - ~/Documents/rtb-trader/ui/node_modules/.bin/yarn
 - npm: 6.2.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0 
 - styled-components: ^5.1.0 => 5.1.0

## Reproduction

I have this really simple code snippet that isn't working.

```
import React from 'react';
import { render } from 'react-dom';
import styled from 'styled-components';

const Button = styled.button`
  color: blue;
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid blue;
  border-radius: 3px;
`;

const RedButton = styled(Button)`
  color: red;
  border-color: red;
`;

const root = document.getElementById('app');
if (root) {
  render(
    <div>
      <Button>Blue Button</Button>
      <RedButton>Red Button</RedButton>
    </div>
    , root
  );
}
```

## Expected Behavior

For the styles to be extended

## Actual Behavior
![image](https://user-images.githubusercontent.com/25963408/78685159-61049b80-78bf-11ea-826f-6f4768878f1e.png)

**Comment by endymion1818** [comment] 2020-04-08 13:14
✋ I'm also getting a similar issue on a Gatsby site, where the ordering of the CSS changes, especially when you've navigated around and back to a page. We found it's something to do with components that have been extended but haven't got any further into the investigation yet.

**Comment by clgeoio** [comment] 2020-06-30 07:52
+1 We are experiencing similar issues!

**Comment by TylerBrownHarrys** [comment] 2020-11-02 21:07
Just wanted to bump this and say we're also experiencing this issue on our Gatsby site as well.

`gatsby@2.23.3`
`styled-components@5.1.1`

**Comment by antoinerousseau** [comment] 2020-11-12 18:26
same here with Gatsby in production! how did you resolve this?

**Comment by Alphavader** [comment] 2021-07-06 07:48
+ still an issue with gatsby 3

**Comment by kitten** [comment] 2021-08-09 18:11
Duplicate of #3482

**Closed by kitten** 2021-08-09 18:11 UTC
