### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by oscar-b** [styled-components/styled-components#271] opened 2016-11-29 14:54 UTC
## Version
1.1.1

Using Sentry to catch errors, I've seen quite a lot from the Facebook IAB. Today I managed to get some kind of error out of it, on a dev build, and it points towards styled-components..

```
TypeError: Super expression must either be null or a function, not undefined
  at inherits(/js/styled-90015a73.js:315:11)
  at ? (/js/styled-90015a73.js:6484:3)
  at Object.<anonymous>(/js/styled-90015a73.js:6556:2)
  at Object.webpackJsonp(/js/styled-90015a73.js:7595:30)
  at __webpack_require__(/js/manifest-dd4e8c24.js:54:30)
  at webpackJsonpCallback(/js/manifest-dd4e8c24.js:25:23)
  at ? (/js/styled-90015a73.js:2:1)
```

A quick goggling suggested it might be related to Rollup? I have no experience with it at all.

![image](https://cloud.githubusercontent.com/assets/85102/20714356/0deadeca-b64c-11e6-9c2a-cd76c368627f.png)
[styled-90015a73.js.txt](https://github.com/styled-components/styled-components/files/619276/styled-90015a73.js.txt)

I'm bundling with webpack 2, beta 25.

Please note that it does work in other browsers without problems, this is only in the Android Facebook in app browser, as far as I've seen.

**Comment by mxstbr** [comment] 2016-11-29 15:16
That's super weird! @Rich-Harris have you heard of this before?

**Comment by oscar-b** [comment] 2016-11-29 15:26
Yeah it's really strange, or I'm doing something really stupid.

Debugging us a real pain as well, since you have to post a link to yourself on Facebook to be able to open it, and the browser seems to cache very aggressively. No console of course, and it almost seems as if React is already loaded in some strange way?

In the prod build, I've been seeing these types of messages. Not 100% exactly the same code since I removed Radium from the equation to get the trace above.

```Invariant Violation
EventPluginRegistry: Cannot inject event plugins that do not exist in the plugin ordering, `__symbol:undef0.278585934528204463`.```

**Comment by Rich-Harris** [comment] 2016-11-30 03:29
> That's super weird! @Rich-Harris have you heard of this before?

When I've encountered that in the past it's usually been because of a module ordering issue – if you have a situation like this...

```js
class A extends B {
  constructor () {
    super();
    this.isA = true;
  }
}

class B {
  constructor () {
    this.isB = true;
  }
}
```

...then B is `undefined` at the point of extension, so `super()` is meaningless. Looking at the [equivalent ES5](https://buble.surge.sh/#class%20A%20extends%20B%20%7B%0A%20%20constructor%20()%20%7B%0A%20%20%20%20super()%3B%0A%20%20%20%20this.isA%20%3D%20true%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20B%20%7B%0A%20%20constructor%20()%20%7B%0A%20%20%20%20this.isB%20%3D%20true%3B%0A%20%20%7D%0A%7D) makes it clearer.

In ES modules the order is determined by the order of imports. 9 times out of 10 a situation like the one above is caused by cyclical dependencies, which can be a *little* tricky to get to the bottom of 😬

**Comment by oscar-b** [comment] 2016-11-30 06:54
But in this case, it's `ThemeProvider` trying to extend `React.Component`? Not sure why that's not working here, but everywhere else. Will try to do some more debugging today.

**Comment by oscar-b** [comment] 2016-11-30 07:51
@mxstbr I just tried opening https://styled-components.com in the Facebook IAB on Android, and it doesn't work. Just a white page. I can't see any console errors of course, but it's the same behaviour I'm seeing.

**Comment by mxstbr** [comment] 2016-11-30 08:04
That sounds like it's an issue on our side then, ugh

**Comment by oscar-b** [comment] 2016-11-30 09:20
I'm testing with an older version of the Facebook app,  I can't upgrade it on this device running Android 5 something something. But I've seen errors in Sentry with the newer app as well, I will see if I can get a hold of a newer device to test on.

**Comment by oscar-b** [comment] 2016-12-08 10:00
@mxstbr I've been using Polyfill.io with the following request:

```
https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill&features=Intl.~locale.sv,Intl.~locale.en,fetch,String.prototype.includes,String.prototype.endsWith,String.prototype.startsWith,Array.prototype.findIndex,Map,WeakMap,Object.assign```

I now tried with `babel-polyfill` instead, and now it seems to work properly! Not sure which polyfill that's missing..

**Comment by mxstbr** [comment] 2017-07-01 07:07
Since this is fixed and nobody else has reported this issue in a long time I'll close this!

**Closed by mxstbr** 2017-07-01 07:07 UTC
Labels: bug

**Comment by Amanchouhan192** [comment] 2018-01-01 08:06
anybody can help me in the type error when i run my code that show me type error

TypeError: Super expression must either be null or a function, not undefined
_inherits
http://localhost:3000/static/js/bundle.js:35121:113
(anonymous function)
http://localhost:3000/static/js/bundle.js:35140:5
./src/index.js
C:/Users/Aman/helloreact/src/index.js:17
  14 | import ReactDOM from 'react-dom';
  15 | import registerServiceWorker from './registerServiceWorker';
  16 | 
> 17 | class HelloWorld extends React.component {
  18 | 
  19 |     render(){ 
  20 | 
View compiled
▼ 6 stack frames were expanded.
__webpack_require__
C:/Users/Aman/helloreact/webpack/bootstrap 11b02e0d7b28b7daaf28:678
fn
C:/Users/Aman/helloreact/webpack/bootstrap 11b02e0d7b28b7daaf28:88
0
http://localhost:3000/static/js/bundle.js:35298:18
__webpack_require__
C:/Users/Aman/helloreact/webpack/bootstrap 11b02e0d7b28b7daaf28:678
./node_modules/ansi-regex/index.js.module.exports
C:/Users/Aman/helloreact/webpack/bootstrap 11b02e0d7b28b7daaf28:724
(anonymous function)
http://localhost:3000/static/js/bundle.js:728:10
▲ 6 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this # error

**Comment by elmeerr** [comment] 2018-07-09 06:59
I just came across this issue and by you code, you're using lowercase in` React.component` ...try to use with capital C `React.Component`

**Comment by Balajisivakumar92** [comment] 2018-08-26 07:38
haha tq man.  @elmeerr
