### ISSUE TITLE
styled.compose?

### ISSUE THREAD

**Issue by MattHsiung** [styled-components/styled-components#1248] opened 2017-10-16 19:22 UTC
### Came across a use case for this today:

```javascript
const LabelWithFieldset = compose(
  Label.withComponent,
  Text.withComponent,
)('fieldset');

const Fieldset = LabelWithFieldset.extend`
  border: none;
  margin: 0;
  padding: 0;
`;
```
(where `Label` and `Text` are styled components ...incase that wasn't obvious 😆)

### Anyone else see any benefit to having something like `styled.compose/inherit`?

Something like this maybe:
```javascript
import { compose } from 'styled-components';

const LabelWithFieldset = compose(
  Label,
  Text,
)('fieldset')`
  border: none;
  margin: 0;
  padding: 0;
`;
```

It seems like a perfect tool for my current workflow with styled-components but maybe I'm off my rocker..

### Thoughts?

**Comment by mxstbr** [comment] 2017-10-16 19:25
Duplicate of https://github.com/styled-components/styled-components/issues/1209

I like your API more than the suggestions from there, mind copy and pasting to that issue? Thanks!

**Closed by mxstbr** 2017-10-16 19:25 UTC
Labels: discussion
