### ISSUE TITLE
Collecting style sheet on server broke after upgrading to v5.0.0

### ISSUE THREAD

**Issue by tbergq** [styled-components/styled-components#2962] opened 2020-01-14 15:02 UTC
## System:
 - OS: macOS 10.15.2
 - CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
 - Memory: 5.82 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.14.0 - /usr/local/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.13.4 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction
Upgrade to v5.0.0, start app. 

## Steps to reproduce
Upgrade to v5.0.0, start app. 

Barebones reproduction: https://github.com/StevenLangbroek/sc-v5-streaming-repro

## Expected Behavior
Styles should be collected on server

## Actual Behavior
The genereated style tag was empty. 

We are using next@9.1.7, and I upgraded today to styled-components@5.0.0, seeing that there were no breaking changes, I expected everything to work as before, however collecting styles on the server no longer works. Only this is created: 

![Screenshot 2020-01-14 at 16 02 00](https://user-images.githubusercontent.com/7705041/72355187-40c1a800-36e7-11ea-9f55-5003b64846ba.png)

edit: took the liberty of adding minimal reproduction link, hope that's ok ❤️

**Comment by probablyup** [comment] 2020-01-14 15:15
Not much we can do without more information. Please check out the with-styled-components example in the next project and ensure the same version number of s-c is being used throughout your project via something like yarn resolutions or webpack aliasing. 

If a dependency is using an older version and your app is using v5, that could cause problems.

**Comment by tbergq** [comment] 2020-01-14 15:18
Yeah, sorry, I get that this is not much to go on, but I don't know what more to provide you with 😞 

`yarn why styled-components`
![Screenshot 2020-01-14 at 16 16 28](https://user-images.githubusercontent.com/7705041/72356349-694aa180-36e9-11ea-9e72-3f14e2670fce.png)


I also checked `yarn.lock` and there is only 5.0.0 in our repo

**Comment by tbergq** [comment] 2020-01-14 15:19
Also, we are created our `_document.js` based on the example from nextjs repo. It works as expected with styled-components@4.x

**Comment by probablyup** [comment] 2020-01-14 15:20
Try using the yarn resolutions package.json field. If you search for that word in the issues you’ll find a few comments I’ve dropped sample code in

**Comment by tbergq** [comment] 2020-01-14 15:23
Not sure what I would use the resolutions field for, when there definitely is only one version of s-c installed, or am I missing something?

**Comment by PaulACoroneos** [comment] 2020-01-14 16:36
Yes I am seeing the same thing on our Next app as well. SSR render is broken in a couple of ways before CSR occurs. We do have import statements in our style sheet so I wanted to investigate that first.

**Comment by berkaey** [comment] 2020-01-15 10:40
Same here with next.js, but only with `createGlobalStyle`

PS: createGlobalStyle component nested inside a Provider

_app.js
```<UIProvider>bla</UIProvider>```

UIProvider
```
<Context.Provider>
  <ThemeProvider theme={generatedTheme.current}>
        <Document {...themeProps}>{props.children}</Document>
      </ThemeProvider>
    </Context.Provider>
```

and 
_document.js
```  static async getInitialProps(ctx) {
    // STYLED COMPONENTS
    const sheet = new ServerStyleSheet();
    const page = ctx.renderPage(App => props =>
      sheet.collectStyles(<App {...props} />)
    );
    const styleTags = sheet.getStyleElement();

    return {
      ...page,
      styleTags
    };
  }
```

**Comment by tbergq** [comment] 2020-01-15 11:46
Well, I stripped my _app.js down to

```
class MyApp extends App {
  render() {
    return <MyTest>What is this</MyTest>;
  }
}

const MyTest = styled.div`
  color: pink;
  font-size: 24px;
`;

export default MyApp;
```

And SSR styles were not collected correctly here either. The text did not become pink before the client render happened.

**Comment by djmarland** [comment] 2020-01-16 09:26
We are having the same issue, using nextjs in the _document.tsx

```typescript
const sheet = new ServerStyleSheet();
const page = renderPage((App: any) => (props: any) => {
    return sheet.collectStyles(<App {...props} />);
});
const styleTags = sheet.getStyleElement();
```

The GlobalStyles are not rendered on the server, but they hydrate on the client so there is a FOUC.
Our global style looks like this:

```typescript
import { createGlobalStyle } from 'styled-components';

import { modalStyles } from '../components/Molecules/Modal/Modal';
import { base } from './base';
import { reset } from './reset';

export const GlobalStyle = createGlobalStyle`
    ${reset}
    ${base}
    ${modalStyles}
`;
```
Does this mean we in violation of this statement from the 5.0.0 release note: "At this time we recommend not using @import inside of createGlobalStyle." and this is the cause?

Rolling back and locking styled-components to 4.4.1 fixes the issue

**Comment by donaldpipowitch** [comment] 2020-01-16 12:35
Is that a duplicate of my report or a different issue? The example from @djmarland looks very much like ours: https://github.com/styled-components/styled-components/issues/2972 We also added a clonable project to checkout the issue easily.

**Comment by StevenLangbroek** [comment] 2020-01-17 21:30
@probablyup Heya! This is what I tweeted about a couple of days ago. Our repo isn't public but if you want i can hop on a call and show you the issue.

**Comment by coderbyheart** [comment] 2020-01-20 15:22
In my case it was resolved by removing an `@import` statement in the `createGlobalStyle` element.

**Comment by probablyup** [comment] 2020-01-21 18:09
Yes as it says in the release notes, we are recommending not using `@import` in cGS at this time. We're discussing new behavior for this to be implemented perhaps in 5.1. Also worth mentioning if you have your cGS instance in _document, it should be moved to _app or somewhere else in your React tree.

**Comment by StevenLangbroek** [comment] 2020-01-21 19:02
Just for completeness, we do not have any `@import` statements and see the same behavior.

**Comment by tbergq** [comment] 2020-01-22 07:19
> Just for completeness, we do not have any @import statements and see the same behavior.

Yes, same for my project. I did start a new project from scratch, with just basic next, react and s-c, and then collecting styles on the server works, so it is possible that this is due to some duplicated package, not s-c it self, but possibly some plugin it uses to gather the styles on the server 🤷‍♂

**Comment by tbergq** [comment] 2020-01-22 14:34
<img width="897" alt="Screenshot 2020-01-22 at 15 32 45" src="https://user-images.githubusercontent.com/7705041/72902880-7d675200-3d2c-11ea-915d-e7b0dd0081f1.png">

☝️ this solved the issue for me

**Comment by StevenLangbroek** [comment] 2020-01-22 15:25
We're using streaming rendering:

```tsx
	const app = (
      <FlagsProvider value={req.flags}>
        <GraphQLProvider value={client}>
          <StaticRouter
            location={req.url}
            basename={req.params.locale ? `/${req.params.locale}` : undefined}
            context={routingContext}
          >
            <AuthProvider viewer={req.viewer}>
              <App locale={req.locale} messages={res.locals.messages} />
            </AuthProvider>
          </StaticRouter>
        </GraphQLProvider>
      </FlagsProvider>
    );

    const appWithChunks = chunkExtractor.collectChunks(app);
    const renderStream = renderToNodeStreamAsync(appWithChunks);
    const streamWithStyles = sheet.interleaveWithNodeStream(renderStream);
```

**Comment by tim-soft** [comment] 2020-01-26 06:00
@StevenLangbroek @probablyup I'm seeing the same issue with mostly the same ssr setup. v4.4.1 works fine, upgrading to v5 with the same code results in an empty style tag server-side

```js
const stream = sheet.interleaveWithNodeStream(renderToNodeStream(sheet.collectStyles(jsx)));
stream.pipe(res, { end: false });
```

**Comment by probablyup** [comment] 2020-02-05 02:10
@tim-soft It looks like the streaming rehydration is having some issues, the style tags in the body for streaming are expected but they should be removed immediately after the client JS is executed

**Comment by StevenLangbroek** [comment] 2020-02-05 09:59
@probablyup they're coming in entirely empty (like the second snippet shows) from the server. Only when hydrated are styles generated.

**Comment by ds009** [comment] 2020-02-13 10:48
Not sure same as you, but I met this bug too while using styled-components and material-ui with nextjs, it was buggy when I just collect styles with only one library( sc or material), after following [this example](https://github.com/MarchWorks/nextjs-with-material-ui-and-styled-components/blob/master/pages/_document.js), it's resolved. Styled-components and material-ui should both collect styles!

**Comment by StevenLangbroek** [comment] 2020-02-13 14:22
@probablyup heya! i created a barebones repro for you here:

https://github.com/StevenLangbroek/sc-v5-streaming-repro

```
yarn && yarn start
```

Go to localhost:3000. I've set a 3s timeout to hydration to make the issue easily discernable. Let me know if there's anything more I can do to help with this issue.

**Comment by dminkovsky** [comment] 2020-02-19 15:01
This might be related to https://github.com/styled-components/styled-components/issues/3026.

**Comment by tm1000** [comment] 2020-02-21 00:22
Same issue here using material-ui & styled-components 5.0.0. I am not using `createGlobalStyle`. The only thing that worked for me was using @ds009's solution which was setup my nextjs based on https://github.com/MarchWorks/nextjs-with-material-ui-and-styled-components/blob/master/pages/_document.js

Specifically @MarchWorks made changes for 5.0.0 in this commit: https://github.com/MarchWorks/nextjs-with-material-ui-and-styled-components/commit/cc60ac18599528854221f2246d59c49fd0e0fb69

**Comment by StevenLangbroek** [comment] 2020-02-23 20:03
@probablyup is there anything I can do to help fix this? I have time to work on it but am unsure where to even start...

**Comment by StevenLangbroek** [comment] 2020-03-01 10:26
cc @kitten? It seems SSR hydration broke in v5 for pretty much everyone, but I'm of little help here :(

**Comment by StevenLangbroek** [comment] 2020-03-12 12:05
Alright, I have some time over the weekend to do a deep dive and find the root cause. I'll make a pass at contribution docs for the server part as well.

**Comment by Fonger** [comment] 2020-04-13 09:52
> <img alt="Screenshot 2020-01-22 at 15 32 45" width="897" src="https://user-images.githubusercontent.com/7705041/72902880-7d675200-3d2c-11ea-915d-e7b0dd0081f1.png">
> 
> ☝️ this solved the issue for me

I think this is the correct answer.

The async function `Document.getInitialProps` calls `ctx.renderPage` function internally
so you have to patch it before calling `Document.getInitialProps()`

As you can see in the official next.js example:
https://github.com/zeit/next.js/blob/ec76d9265cbe61755e83a2f730db1239269dfb5f/examples/with-styled-components/pages/_document.js#L10-L16

**Comment by mintyfloss** [comment] 2020-04-23 19:21
> I think this is the correct answer.
> 
> The async function `Document.getInitialProps` calls `ctx.renderPage` function internally
> so you have to patch it before calling `Document.getInitialProps()`
> 
> As you can see in the official next.js example:
> https://github.com/zeit/next.js/blob/ec76d9265cbe61755e83a2f730db1239269dfb5f/examples/with-styled-components/pages/_document.js#L10-L16

Following that example worked for us! Our original `_document.js` looked a little different, but after changing the code to follow the example, our components are now styled when SSR. We're now using Next 9.1.7 and styled-components 5.1.0.

**Comment by aquelehugo** [comment] 2020-08-04 21:10
@probablyup about the multiple style tags in body when using streaming:
In our case it is problematic:
![image](https://user-images.githubusercontent.com/8480411/89344749-c0f82c80-d67c-11ea-9cea-ba07969d813f.png)

We are using an SVG filter in our global styles and the `<style>` tag is being injected inside an `<svg>` tag, before `<path>`.
Something like: `<svg viewBox="0 0 24 24" role="img" height="24" width="24" fill="currentColor"><style data-styled="true" data-styled-version="5.1.1">@-ms-viewport{{width:device-width;}}/*!sc*/`

What is inside `<svg>` and is not a known SVG tag is treated then as pure text until it finds a recognized tag, which in this case is `</svg>` in our CSS filter property.

We can remove the SVG filter from our CSS. But what about the ignored `<style>` tag when it is inserted inside `<svg>` tag scope??

**Comment by aquelehugo** [comment] 2020-08-04 22:37
@probablyup I was wrong. `<style>` tags are interpreted normally inside `<svg>`. Don't know what is the real issue here.
CSS is as follows:
```css
  .grayscale-filter {
    filter: url('data:image/svg+xml;utf8,<svg%20xmlns="http://www.w3.org/2000/svg"><filter%20id="grayscale"><feColorMatrix%20type="matrix"%20values="0.3333%200.3333%200.3333%200%200%200.3333%200.3333%200.3333%200%200%200.3333%200.3333%200.3333%200%200%200%200%200%201%200"/></filter></svg>#grayscale');
  }
```

After rehydration, everything is OK and the filter works as expected.
I tried to inject that a style tag with the same rule inside a svg tag manually. It worked also.
Part of the filter is being interpreted as inline tags only on SSR.

**Comment by probablyup** [comment] 2020-08-05 00:13
'#grayscale' at the end looks suspicious

**Comment by aquelehugo** [comment] 2020-08-05 11:06
@probablyup `#grayscale` is rendered because the tag inside the filter closes before it. The rule is then repeated because of the prefixes. Any thoughts? Could you give me some guidelines so I could investigate it further?

**Comment by lalidiaz** [comment] 2021-01-02 15:47
> @probablyup Heya! This is what I tweeted about a couple of days ago. Our repo isn't public but if you want i can hop on a call and show you the issue.

Hi, is possible to get some help from you please? I've tried all the solutions they mention here but seems like nothing is working for me...

**Comment by oscargws** [comment] 2021-01-03 22:59
I'm getting the same issue, i'm using the example implementation for styled-components + typescript but in production im receiving strange style issues where styles are either missing or on the wrong element

**Comment by oscargws** [comment] 2021-01-03 23:18
For an example, if you navigate to [this link](https://nomadradio.fm/residents) and then go the home page (top left nav item), all the styles will break.

**Comment by kitten** [comment] 2021-08-09 18:23
Closing due to inactivity. SSR issues and the likes often become places for people to add comments for unrelated issues or things that just sound vaguely related (which happens when the title/topic is "X doesn't work" 😅 ) If you read this and are about to comment, please just break the issue down further.

I haven't seen anything recently that demonstrates this issue, so for now I'll have to close this. New issues with reproductions are welcome, but we never managed to find a compelling reproduction demonstrating this issue.

**Closed by kitten** 2021-08-09 18:23 UTC
Labels: bug :bug:
