### ISSUE TITLE
Classname reordering when extending styles is inconsistent.

### ISSUE THREAD

**Issue by Aleksion** [styled-components/styled-components#1164] opened 2017-09-13 21:29 UTC
I'm reopening this since #1083 got closed without the issue being resolve. (or this might be another issue.

 I'm experiencing this 50% of the time, when I deploy my code to production. (On Netlify)

It seems to happen whenever I've used .extend or styled(COMPONENT), but then again, only 50% of the time. This is before and after a refresh:

<img width="214" alt="screen shot 2017-09-06 at 11 36 33" src="https://user-images.githubusercontent.com/3367641/30401319-d8c69a42-98a7-11e7-807c-d7dadc9506e7.png">
<img width="217" alt="screen shot 2017-09-06 at 11 36 49" src="https://user-images.githubusercontent.com/3367641/30401318-d8c33352-98a7-11e7-83ce-b7a6c26fd32d.png">

I've been trying different versions of styled-components and it seems to be an issue all the way back to 2.0.0

**Comment by philpl** [comment] 2017-09-13 22:45
That’s true! The discussion diverged a lot from the original issue and wasn’t resolved.

We’ll need a stable reproduction first, before tackling this issue apart from a screenshot unfortunately. Can you provide a CodeSandbox or sth similar to reproduce this?

cc @geelen: I think we pinned down the issue to styled(COMPONENT) any idea why it might take higher priority?

**Comment by Aleksion** [comment] 2017-09-14 00:29
What makes it so hard, is that I haven't been able to replicate it locally. I've been trying in code sandbox, without "luck"

One thing to note is that it doesn't do it on all styles throughout the page. It seems it becomes more of an issue on larger projects.

And I NEVER get it when I run it locally. I only get it when I serve the build online (through netlify's cdn). I don't think how it's served should affect it, but yeah, it only happens in production builds.

It happens for BOTH styled(COMPONENT) and STYLED_COMPONENT.extend

I initially changed all .extend to styled() because I thought it was only an issue with .extend

**Comment by Aleksion** [comment] 2017-09-14 00:34
Oh, and it's happening on a gatsby project. Might be relevant.

**Comment by philpl** [comment] 2017-09-14 01:31
@Aleksion:

> It happens for BOTH styled(COMPONENT) and STYLED_COMPONENT.extend

`.extend` combines the parent's rules with the new ones and creates a **single class** that's totally separate from the parent's. Thus it's impossible for it to trigger this bug. It must somehow be triggered by using `styled(StyledComponent)` where the deferred rule injection fails to work.

Generally I can only suggest you to keep using `.extend` when it's your own styled component and not `styled(StyledComponent)` at all. That's what we're recommending in the docs.

We need some more characteristics here, because the above screenshot is not at all sufficient. Some questions we need to answer:

- What are the sources for the StyledComponent's classes above?
- How are they wrapping each other?
- What's the order of classes? (inner SC to outer? Outer to inner? Something different)
- Are they all rendered at the same place, or in different places in different orders as well?

A reproduction is crucial, but the above questions should give us a hint. The size of the project is unlikely to be playing a role here, but the rendering order, order of creation, and wrapping order is what's likely important. :wink:

**Comment by Aleksion** [comment] 2017-09-14 01:37
Interesting. I was certain it happened when I was using extend, but I'll try to dig deeper and find out why and what happens. 

Wonder whether it can be https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-styled-components that causes the issues.

I'll try again to see if I can reproduce it independently of my project tomorrow. If not I'll report back on your bullet points based off my project. 

I really appreciate the work you guys have been doing. I usually dread doing styling, but styled-components has made me enjoy it. Good work!

**Comment by philpl** [comment] 2017-09-14 01:39
@Aleksion The approach I'd suggest is:

- Find the affected components
- Move them into an isolated project with the same setup
- Try to further minimise the resulting reproduction
- See if it happens in create-react-app with the same code and without SSR

It'd be amazing to find out what is causing this 😆  These kinds of "foundational quirks/bugs" make me really anxious.

**Comment by probablyup** [comment] 2017-09-14 01:43
Here's my theory: this is entirely due to module resolution order.

In my work projects, I've noticed we have the same issues when webpack's ModuleConcatenationPlugin is NOT enabled... meaning there's no guarantee of evaluation order in the code. That means that `Thing` in `styled(Thing)` could be evaluated after the file containing `styled(Thing)` and that would mean the rules are injected in the wrong order.

However, when ModuleConcatenationPlugin IS enabled, things are arranged in the proper order and the issues go away.

**Comment by probablyup** [comment] 2017-09-14 01:46
Long story short, @Aleksion if your codebase uses ESM, try turning on `ModuleConcatenationPlugin` and report back.

**Comment by philpl** [comment] 2017-09-14 01:47
@probablyup Unlikely to be this simple, because of dependencies. While it's now not best practice our original inheritance assumption is based on this: `A = styled.div; styled(A)`

If `A` is imported in the example it must've been created / evaluated first (otherwise `A` would of course be undefined; this is how module resolution works) this means that a deferred injection must've been triggered (the bug could be here).

It could also be a usage problem with SSR? Or a bug in SSR's rehydration. Hard to tell

**Comment by geelen** [comment] 2017-09-14 05:50
This is super weird. Guaranteed ordering is like feature number 1 for styled-components (literally issue #1), and I _really_ thought I caught all the edge cases...

As phil points out, it can't be module order because `styled(X)` depends on `X`, so you'd get a bunch of underfined errors if it was running out-of-order.

It could be something to do with rehydration injecting multiple styles... but no that doesn't make a lot of sense either since it'd be injecting _everything_ twice.

Good luck getting a reproduction @Aleksion!

**Comment by probablyup** [comment] 2017-09-18 15:40
@Aleksion are any of your styled components exported default without saving to a variable first? 

```js
export default styled.div`
  color: red;
`
```

**Comment by Aleksion** [comment] 2017-09-18 15:44
No, they're all exported as

```javascript
export const PrimaryButton = styled.button`
    color: red;
`
```

I haven't been able to properly replicate it by the way. I haven't been experiencing in prod for a while, and I never did figure out how to create the error locally. I'll update accordingly if I hit it again.

**Comment by probablyup** [comment] 2017-09-18 15:47
Ok, as of last week I could still repro. I'll try and put a minimal example
together.

**Comment by Aleksion** [comment] 2017-09-18 15:49
That would be great! as @geelen said, guaranteed ordering is a must for this library. And while it's working now, having experienced the errors makes me hesitant to go all in.

**Comment by Kauhsa** [comment] 2017-09-30 08:43
Hey,

So, while testing out #1102, I hit this (or similar) bug, and managed to create an example test case for it. Since in my example it's broken by the new feature introduced in #1102 I don't know if the bug is the same than in this issue, but in case the underlying issue is the same, here you are:

https://github.com/Kauhsa/styled-components-1102-issue

**Comment by philpl** [comment] 2017-09-30 12:39
@Kauhsa thanks a lot for linking to this! I’ll take a look tomorrow 😬

**Comment by mxstbr** [comment] 2017-10-07 07:22
@philpl has tracked down the bug! https://github.com/styled-components/babel-plugin-styled-components/issues/79#issuecomment-334799796

If anybody's up for a PR to resolve this that'd be amazing.

**Comment by Aleksion** [comment] 2017-10-07 09:50
@philpl you are my hero! While I haven't experienced the bug in a while, having these bugs that randomly occur in production is something I truly loathe. Now It's just Gatsby that's haunting me 🤣

**Comment by pedrokermitgoncalves** [comment] 2017-11-09 13:00
Any update on this, we're having the same problem.

We're implementing an Atomic Design approach with styled components, so we have something like this:

```
import React, { type Element } from 'react';
import styled from 'styled-components';
...

const Title = (props: Props) => {
  const TitleAtom = styled[props.tag]`
    font-family: ${props.bold ? titleBoldFont : titleFont};
    font-weight: normal;
    ${props.fontSize >= 0 && `font-size: ${props.fontSize}px;`};
    text-transform: ${props.uppercase && 'uppercase'};
    color: ${props.color};
    margin: 0;
  `;

  return <TitleAtom className={props.className}>{props.children}</TitleAtom>
};

export default Title;
```
and then reuse the atom like this:

```
import React, { type Element } from 'react';
import styled from 'styled-components';
import Title from 'tvg-atom/Title';
...

const RaceList = (props: Props) => {
  const TitleWithMargins = styled(Title).`
    margin: 20px;
  `;

  return <TitleWithMargins>Title text</TitleWithMargins>;
};

export default RaceList;
```

However the `20px` rule is overwrite by the initial Title comp.

**Comment by mxstbr** [comment] 2017-11-09 13:34
@pedrokermitgoncalves don't define your styled components inline.

<details>
  <summary>This is what they should look like: (click)</summary>

```JS
import React, { type Element } from 'react';
import styled from 'styled-components';
...

  const TitleAtom = styled.h1`
    font-family: ${props => props.bold ? titleBoldFont : titleFont};
    font-weight: normal;
    ${props => props.fontSize >= 0 && `font-size: ${props.fontSize}px;`};
    text-transform: ${props => props.uppercase && 'uppercase'};
    color: ${props => props.color};
    margin: 0;
  `;

const Title = (props: Props) => <TitleAtom className={props.className}>{props.children}</TitleAtom>;

export default Title;
```

```JS
import React, { type Element } from 'react';
import styled from 'styled-components';
import Title from 'tvg-atom/Title';
...

  const TitleWithMargins = styled(Title).`
    margin: 20px;
  `;

const RaceList = (props: Props) => <TitleWithMargins>Title text</TitleWithMargins>;

export default RaceList;
```

</details>

**Comment by pedrokermitgoncalves** [comment] 2017-11-09 14:09
@mxstbr that actually make total sense right now. We're fairly new to styled components and still trying to find our way around. Thanks a lot for the quick feedback.

**Comment by phyllisstein** [comment] 2017-11-09 17:20
Looks like the bug is still extant whether components are defined inline or not, though? <https://github.com/styled-components/babel-plugin-styled-components/issues/79#issuecomment-341797301>

**Comment by lipis** [comment] 2018-08-07 12:07
Any progress on this bug?

**Comment by probablyup** [comment] 2018-08-07 12:58
Nope. We are deprecating this functionality and removing it.

**Comment by lipis** [comment] 2018-08-07 13:09
@probablyup Can you elaborate on what exactly is being deprecated and removed?

**Comment by probablyup** [comment] 2018-08-07 14:11
.extend

**Comment by probablyup** [comment] 2018-08-12 17:35
Closing this since the API [is removed](https://github.com/styled-components/styled-components/pull/1908) in v4.

**Closed by probablyup** 2018-08-12 17:35 UTC
Labels: bug :bug:, help wanted :sos:

**Comment by Gisleburt** [comment] 2019-08-14 10:30
We're experiencing this problem iof classes being in the wrong order in one project consistently.

We have a styleguide that we import into multiple projects, all but one of which are fine, and the one that is wrong is consistently wrong, there's no randomness to it, and it only appears to be broken on one component, but it might be the only one where the defaults are being overridden (we extend/restyle other components but usually for margin to position them inside something else). I can't see anything special about the component.

The styleguide all consuming projects use styled-components `4.3.2`. The only quirk I can think of is that the one that is broken is attached to a shadow-dom.
