### ISSUE TITLE
GlobalStyles using an attribute selector are loaded after regular styles

### ISSUE THREAD

**Issue by joshuajaco** [styled-components/styled-components#2993] opened 2020-01-28 12:58 UTC
## System:
 - OS: macOS 10.15.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 1.12 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 13.7.0 - ~/.asdf/installs/nodejs/13.7.0/bin/node
 - Yarn: 1.21.1 - ~/.asdf/installs/nodejs/13.7.0/.npm/bin/yarn
 - npm: 6.13.6 - ~/.asdf/installs/nodejs/13.7.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7
 - styled-components: ^5.0.0 => 5.0.0
## Reproduction
v5.0.0: https://codesandbox.io/s/thirsty-kalam-hi5s8
v4.4.1:  https://codesandbox.io/s/strange-mendeleev-pindz

## Steps to reproduce
1. Create a global stylesheet using an attribute selector to set some styles.
2. Try to overwrite those styles on a component

## Expected Behavior
The global styles are overwritten by the component styles, as in v4.4.1

## Actual Behavior
The component styles are overwritten

**Comment by 4nduril** [comment] 2020-02-03 14:44
I can confirm that issue. Here is a sandbox where I tried to load the `createGlobalStyle` component from another file before the "App". But that doesn't help either. https://codesandbox.io/s/crimson-violet-mv5xy

 In the `<style>` tag in devtools here https://mv5xy.csb.app/ you can see that the global styles are coming after the StyledH1 declarations.

**Comment by probablyup** [comment] 2020-02-04 17:46
We currently don't guarantee an insertion order for global styles. I agree this should be fixed though.

**Comment by Leonya** [comment] 2020-02-06 12:03
Really hoping that this gets fixed, it's a major bummer for us 🙏

**Comment by davidx1** [comment] 2020-03-22 09:25
I have just ran into the same issue. Replicated here:
https://codesandbox.io/embed/great-grass-l9y63

Since attribute selector and class selector have the same specificity, and global style is meant to set a base-line for individual components to override, I think the library should gurantee that global styles are inserted first before normal styles.

**Comment by Leonya** [comment] 2020-03-22 10:31
I am quite disappointed that this isn't getting more recognition. v5 was released with a "no breaking changes!" headline. Well, going from a guaranteed order of stylesheet insertion to not guaranteed is quite literally a breaking change, which wasn't even mentioned anywhere.

**Comment by asafigan** [comment] 2020-04-15 18:20
Has anyone found a work around for this? I have a large project that can't upgrade until this is fixed or there is a work around that doesn't involve touching a large portion of the code base.

**Comment by etabard** [comment] 2020-06-15 07:30
Hi ! Any progress on this ? This is a major issue for us ... We need the v5 to decrease our bundle size and have decent score on lighthouse v6...

Thanks for your help here and your great job !

**Comment by probablyup** [comment] 2020-08-30 16:30
@asafigan this will be fixed in 5.2!

**Closed** 2020-08-30 18:49 UTC
Labels: bug :bug:
