### ISSUE TITLE
React Native performance

### ISSUE THREAD

**Issue by corysimmons** [styled-components/styled-components#1523] opened 2018-02-15 02:15 UTC
I've heard from a few people styled-components is slow on RN. Anyone know why? Is it possible this can be addressed?

(I really like how styled-components cleans up jsx and would love to use it everywhere)

**Comment by kitten** [comment] 2018-02-15 09:51
It very well might be true. We’re regarding CSS a couple of times in react native and the performance there has never been tested thoroughly.

The problem is that we don’t have a reliable benchmark to compare rendering times yet. But I can confidently say having used this in tens of apps, and many customer projects, slow is relative. It’s not notably slower than usual as far as I can tell, and once it is problems often stem from other parts of the app

**Comment by mxstbr** [comment] 2018-02-15 09:53
I think @brunolemos investigated RN performance a bit iirc, but I don't know if he ever published conclusive benchmarks somewhere. Would be great to see some, until then I'll close this issue since there's isn't much for us to do here.

/cc @jacobp100 for good measure.

**Closed by mxstbr** 2018-02-15 09:53 UTC

**Comment by corysimmons** [comment] 2018-02-15 15:19
No problem. If anyone has some approach to benchmarking this I'd be happy to offer more help in tracking it down.

I'll give it a shot on an app I'm working on now and get back to you guys if it seems particularly slow.

**Comment by kitten** [comment] 2018-02-15 15:33
@corysimmons sure thing!

Another thing to consider: The only risk for performance are long FlatLists. Animations are handled very well by using `Animated` and `Animated.View`s. And I've managed to make lists performant by calculating the heights

If anyone's interested, something along the lines of this yields perfectly acceptable scrolling perf:

```js
// In the app where this is from, I'm paginating & fetching using Apollo
const ITEMS_PER_QUERY = 40;
// Corresponds to your row / item height; constant is definitely better and the big perf win here
const ITEM_HEIGHT = 100;
const { height: SCREEN_HEIGHT } = Dimensions.get('window');

const Wrapper = styled.FlatList.attrs({
  keyExtractor: () => item => item.id,
  initialNumToRender: Math.floor(ITEMS_PER_QUERY / 2), /* make sure this fills your screen */
  maxToRenderPerBatch: Math.floor(ITEMS_PER_QUERY / 4), /* make sure this batch is not too large (smaller than the screen is acceptable) */
  updateCellsBatchingPeriod: 100, /* counterintuitively it's better to render less with a good batching period that doesn't correspond to a high fps */
  onEndReachedThreshold: p =>
    p.data.length > 2 * ITEMS_PER_QUERY
      ? ITEM_HEIGHT * ITEMS_PER_QUERY + SCREEN_HEIGHT /* account for initial render here */
      : ITEM_HEIGHT * Math.floor(ITEMS_PER_QUERY / 2) /* fetch BEFORE you reach the end */
}) /* ... */
```

**Comment by brunolemos** [comment] 2018-02-15 18:03
@corysimmons I made this benchmark: https://github.com/brunolemos/react-native-css-in-js-benchmarks
It's simple, it would need more benchmarks methodologies to get a conclusive result.

But yeah, the render seems to be a bit more expensive when using styled components, but if you use `.attrs` and `.extend` well you should have a good result. There is room for improvement though.

Usually the biggest performance bottleneck are on other place of your code, e.g. unnecessary rerenders.

**Comment by ntvinhit** [comment] 2019-07-16 06:26
@brunolemos 
As your result, is React Native StyleSheet is slower than React-Native inline only?
Something not right here.
