### ISSUE TITLE
Cleaner CSS classes while Developing

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/styled-components#948] opened 2017-06-25 02:05 UTC
Currently, when develing and inspecting my css I see the following:
![image](https://user-images.githubusercontent.com/390010/27513134-d16ae1d6-590f-11e7-9ca3-ce39a89b8a53.png)

I'd like for the compatibility properties to only be applied when in production. 
Or at least a way to not see them, it makes the code confusing and hard to debug.

Other than that, styled-components has rocked my front-end world. Awesome work!

**Comment by philpl** [comment] 2017-06-25 02:20
Duplicate of https://github.com/styled-components/styled-components/issues/719

**Closed by philpl** 2017-06-25 02:20 UTC
