### ISSUE TITLE
Add tests for react-native

### ISSUE THREAD

**Issue by brunolemos** [styled-components/styled-components#595] opened 2017-03-18 19:29 UTC
I've seen a few times some changes being made on styled-components for web and breaking the react-native part (e.g. https://github.com/styled-components/styled-components/pull/519, https://github.com/styled-components/styled-components/pull/311, https://github.com/styled-components/styled-components/commit/9edf5ba823c16c1777ce13f553c8c87eb79cdedd, etc).

Apparently there are not tests for react-native. Am I missing something?
Maybe we could create single shared tests for both of them?

**Comment by mxstbr** [comment] 2017-03-18 19:40
Duplicate of #94, the tests for the core cover all the shared code (~90% of all), the only thing that's missing is the StyledNativeComponent, InlineStyles etc.

Would be great if you want to tackle this!

**Closed by mxstbr** 2017-03-18 19:40 UTC
