### ISSUE TITLE
[v3] Typescript needs to switch typings over to RN automatically

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#1442] opened 2018-01-23 05:59 UTC
## Version
styled-components: 3.0.1
babel-plugin-styled-components: ---

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce
After adopting new import for native i.e. omitting `/native` all types are missing for things like `styled.Text`, `styled.ImageBackground` etc..

## Expected Behavior
These should exist in native on `styled` with new import.

## Actual Behavior
```
import styled from "styled-components";

const Test = Styled.Text``;

[ts] Property 'Text' does not exist on type 'ThemedBaseStyledInterface<any>'. Did you mean 'text'?
```

**Comment by philpl** [comment] 2018-01-23 09:12
cc @styled-components/typers any idea if we can do an automatic switch for TS? Otherwise we’ll just have to add a caveat note to the website I guess

**Comment by Igorbek** [comment] 2018-01-28 19:59
Unfortunately, I don't see any way how we can statically tell TypeScript which types to use depending on compilation target. To me, deprecating `/native` module will lead to very inconvenient development experience for TypeScript users.

**Comment by mxstbr** [comment] 2018-01-28 20:00
Let's have one set of types with all aliases then?

**Comment by Igorbek** [comment] 2018-01-28 20:07
Do you mean that we should merge all the component aliases? Then TS would allow to use both web and native components at the same time. That does make much sense I think.

**Comment by Igorbek** [comment] 2018-01-28 20:12
correction: does not make much sense :)

**Comment by Igorbek** [comment] 2018-01-28 20:18
We can file an issue in the TypeScript repo, asking how we can differentiate type modules resolution based on application target. The problem is that in react native compilation modules get resolved by package.json's hint in `react-native` field and TS does not know about this and uses either `typings` field or just `./index.tsx?` file.

**Comment by tjoskar** [comment] 2018-01-30 07:51
I have not update styled-components to 3.x in projects yet, due to this change. But I’m a little confused; according to the [release page](https://github.com/styled-components/styled-components/releases/tag/v3.0.1) we can now import styled-components for RN by just importing `styled-components` and not `/native`. In fact, importing `/native` is deprecated. 

But if I take a look at the [change log](https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v301---2018-01-22) (or the code inside [index.js](https://github.com/styled-components/styled-components/blob/d395c7658dd844ecedbcdb15f6755a7c2460bbd2/src/index.js#L33)) it states that from version 3.0.1 it gives you a warning if you don’t import from `/native`.

Anyhow, let’s say we can import RN components directly from styled-components. Is there a runtime check to only export RN components if the code is running in a RN-context? If not, that means we can access web-components in react native (?) and we should maybe expose all the types to reflect the reality? But at the same time I agree to @Igorbek, it doesn’t make any sense to be able to import web components inside a RN project. But I do not see any way to dynamically tell typescript to use a certain typings. The only way I see it is to extract the types into its own package and let the user decided what types to use. Eg.
```
npm install @types/styled-components
// or
npm install @types/styled-components-native
```
Or maybe something like: `@styled-components/typescript-native-types`

Does flow have the same problem?

**Comment by IljaDaderko** [comment] 2018-01-30 08:09
Is there any drawback in using `styled(View)` opposed to `styled.View` while this issue is being resolved by the way?

**Comment by FredyC** [comment] 2018-02-02 17:56
@IljaDaderko Small drawbacks is an extra import of the `View` and VSCode syntax highlighting have a trouble recognizing that for some reason. Otherwise, I don't think there is a difference.

I agree with @tjoskar, extracting types to separate packages seems like the only legit way to go. There are some [conditional types](https://github.com/Microsoft/TypeScript/pull/21316) coming in Typescript 2.8 that could solve this more elegantly, but it will take some time to get there.

**Comment by IljaDaderko** [comment] 2018-02-07 13:58
@FredyC gotcha 👍 and yep I think having separate typings package for `@types/styled-components` / `@types/styled-components-native` could do the trick, react does it this way as well.

**Comment by kitten** [comment] 2018-02-08 00:05
@IljaDaderko This would actually be quite nice. :+1: Like the flow-types it doesn't seem quite right to have the typings in our package. It makes it quite inflexible, and a lot of effort has to be put in to keep them up-to-date. Previously we sometimes neglected to publish some patches on time 🤕 

cc @mxstbr @styled-components/typers

**Comment by FredyC** [comment] 2018-02-08 07:39
I would even say, it might be worth it to split it into three packages, have one common with namespaced stuff (there is definitely a bunch of common typings) and other two for `web` and `native`. The common package could also include better theming support, something [along these lines](https://github.com/jacob-ebey/styled-components-ts/blob/master/src/styled-components-ts.ts).

**Comment by duro** [comment] 2018-03-16 02:09
Has any movement been made on this? I'm starting a new project, and considering downgrading to SC 2.x to resolve this, but would ideally not want to do that.

**Comment by FredyC** [comment] 2018-03-16 07:55
Yea, I am sticking to 2.x for now as well. I am not feeling that strong in TypeScript just yet to solo produce quality typings for this.

**Comment by mxstbr** [comment] 2018-03-16 11:13
You can still use `styled-components/native` in 3.x as a temporary fix for TypeScript.

**Comment by Igorbek** [comment] 2018-03-16 16:33
@mxstbr is it possible to not deprecate `styled-components/native` until it's sorted out?

**Comment by kitten** [comment] 2018-03-16 16:49
@Igorbek it's currently not outputting any warning or anything, and we're not planning to remove it for now :)

**Comment by tkow** [comment] 2018-07-12 09:00
This error is due to native types definitions are not included in style-components.d.ts file, and I fixed them with no breaking compatibility. Please check https://github.com/styled-components/styled-components/pull/1844 if it is needed.

**Comment by probablyup** [comment] 2018-09-01 07:03
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.

**Closed by probablyup** 2018-09-01 07:03 UTC
Labels: good first issue :octocat:, help wanted :sos:, typings :wrench:
