### ISSUE TITLE
React 18 Streaming SSR support?

### ISSUE THREAD

**Issue by alexanderoskin** [styled-components/styled-components#3765] opened 2022-07-04 06:59 UTC
Any plans to support React 18 streaming SSR? Now it's a big blocker for many folks.

Here's the upgrade guide for library authors - https://github.com/reactwg/react-18/discussions/110

**Comment by mattapperson** [comment] 2022-08-31 20:05
Dupe of https://github.com/styled-components/styled-components/issues/3658?

**Closed** 2022-12-24 16:13 UTC
