### ISSUE TITLE
Cannot find name 'Component'.

### ISSUE THREAD

**Issue by benbradford** [styled-components/styled-components#1882] opened 2018-08-03 21:01 UTC
When trying to use styled-component with React and typescript, as soon as I attempt to import styled-component I get the error:

node_modules/styled-components/typings/styled-components.d.ts (98,52): Cannot find name 'Component'.

Any ideas what I am missing please?

**Comment by PzYon** [comment] 2018-08-03 21:14
Same here. I updated to following versions then got above error:
- `"typescript": "^3.0.1"`
- `"react": "^16.4.2",`
- `"react-dom": "^16.4.2",`
- `"styled-components": "^3.4.0"`

I guess `Component` should be `React.Component` instead. I adjusted it directly in the `.d.ts` and then I'm able to build again.

**Comment by PzYon** [comment] 2018-08-03 21:16
Ah, I see there's already a PR for this: #1876

**Comment by probablyup** [comment] 2018-08-04 14:29
Duplicate of https://github.com/styled-components/styled-components/issues/1875

**Closed by probablyup** 2018-08-04 14:29 UTC
