### ISSUE TITLE
New Warning: Invalid hook call in development with latest react experimental

### ISSUE THREAD

**Issue by bbenezech** [styled-components/styled-components#3409] opened 2021-02-18 09:57 UTC
In development, react@experimental triggers a react warning.

## Environment
react-dom since `0.0.0-experimental-dc27b5aaa` (2 weeks ago)
all versions of `styled-components` affected

## Reproduction
https://codesandbox.io/s/styled-components-base-forked-yzpjn?file=/package.json

## Steps to reproduce
Open the sandbox => console

## Expected Behavior
No console.error in dev

## Actual Behavior
console.error `Warning: Invalid hook call. Hooks can only be called inside of the body of a function component.`

**Comment by doylemark** [comment] 2021-02-20 19:44
I'm experiencing this with a brand new project using react 17.0.1 I also tried 16.14.0, have tried all the suggested fixes on react issue tracker and docs too.. Any ideas what the last compatible pairing is?

**Comment by haneenmahd** [comment] 2021-03-05 10:33
Yes, I do have the same problem. when using the styled component element inside a ```React.Component``` class.

**Comment by haneenmahd** [comment] 2021-03-13 17:57
You could use it like this.
`
const MyComponent = () => (
      <YourComponent />
);

class App extends React.Component {
  render() {
    return(
       <div>
           <h1>Hello Styled Components</h1>
         <MyComponent />
       </div>
    );
  }
}
`

**Comment by haneenmahd** [comment] 2021-03-19 10:13
Now it also affects the function components too

**Comment by DannyvanderJagt** [comment] 2021-04-12 16:58
Any updates on this?

**Comment by DannyvanderJagt** [comment] 2021-04-12 20:12
Update: I switch to emotion for now, they work out of the box. Going to monitor this thread and switch back when it works in styled-components again.

**Comment by eps1lon** [comment] 2021-06-26 09:35
Duplicate of https://github.com/styled-components/styled-components/issues/3394

**Closed** 2021-07-01 18:45 UTC
