### ISSUE TITLE
Theme (flow) typing prevents use of more specific Theme types - should be read-only?

### ISSUE THREAD

**Issue by ruyasan** [styled-components/styled-components#1785] opened 2018-06-01 18:14 UTC
The use of `mixed` means we can't use more narrow types as our theme (see below) due to how `mixed` interacts with variance. The `Theme` type should either use `any` values or use read-only properties.

## Environment
```

## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 1.72 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
 - Yarn: 1.5.1 - /usr/local/bin/yarn
 - npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
## npmPackages:
 - styled-components: ^2.4.0 => 2.4.0 
```

## Reproduction
```
// @flow
import React from 'react';
import type { Node} from 'react';
import { withTheme } from 'styled-components';

type MyThemeType = {
  spacing: number,
}
type PropTypes = {
  theme: MyThemeType,
  children: Node
}
const MyTable = (props: PropTypes) => <table cellSpacing={props.theme.spacing}>{props.children}</table>;

export const ThemedTable = withTheme(MyTable);

```
## Expected Behavior
No flow errors.

## Actual Behavior

```
Error:(15, 28) Cannot call `withTheme` because number [1] is incompatible with mixed [2] in property `spacing`.
```

## Proposed Solution

Here is a simplified example of what's happening:

```
// @flow
type MyThemeType = {
  spacing: number,
}
type MixedObjTheme = {[string]: mixed};
function themeSomething(theme: MixedObjTheme) {
  return theme;
}
const theme: MyThemeType = { spacing: 2 };

themeSomething(theme);
// Error:(45, 16) Cannot call `withTheme` because: Either object literal [1] is incompatible with mixed [2] in property `breakpoints`. Or object literal [1] is incompatible with mixed [2] in property `breakpoints`.
```

This on the other hand works fine:
```
// @flow
type MyThemeType = {
  spacing: number,
}
type MixedObjTheme = {+[string]: mixed}; // /!\ Note the `+` /!\
function themeSomething(theme: MixedObjTheme) {
  return theme;
}
const theme: MyThemeType = { spacing: 2 };

themeSomething(theme);
```

**Comment by probablyup** [comment] 2018-06-02 16:47
@ruyasan I assume this is for the community flow typings. If so, could you move this issue over to https://github.com/flowtype/flow-typed? I don't think we keep them locally aside from internal flow types that are stripped out from the bundles.

**Comment by ruyasan** [comment] 2018-06-04 16:00
Are the `flow-typed` types not automatically derrived from the source annotations? I did double check to make sure this particular type was the same in `node_modules/styled-components/src` and that seems to be the case.

**Comment by PandaPacha** [comment] 2018-08-01 13:32
I made a PR: https://github.com/flow-typed/flow-typed/pull/2556

**Comment by kitten** [comment] 2018-08-01 16:56
I have some extra typings as well and I’d love to move them back to this repo so we have control over them as flow-types has not been working out well.

https://gist.github.com/kitten/4d71b5eb480098159d3ab1312de3bdac

The problem is that some of this is pointless, as Flow does not support any types that flow into or out of interpolations. You can test this by typing a tagged template literal function to accept numbers. In such a case you’ll still be able to pass non-number interpolations for instance.

**Comment by maxammann** [comment] 2018-08-30 08:04
Can confirm this. Right now it is not possible to use withTheme with flow, right?

**Comment by probablyup** [comment] 2018-09-01 07:00
Closing this since complete flow typings are not in this repo.

**Closed by probablyup** 2018-09-01 07:00 UTC
Labels: typings :wrench:
