### ISSUE TITLE
react-native typescript styled_components_1.default.Text is not a function

### ISSUE THREAD

**Issue by maciossek** [styled-components/styled-components#1542] opened 2018-02-21 09:30 UTC
styled_components_1.default.Text is not a function

## Version
styled-components: 3.1.6
typescript: 2.7.1

## Steps to reproduce
Run a simple test 
```
import 'react-native'
import * as React from 'react'
import App from '../App'
import * as renderer from 'react-test-renderer'

it('renders correctly', () => {
  const tree = renderer.create(
    <App />
  )
})

```
## Expected Behavior
Test does not fail
## Actual Behavior
```
    TypeError: styled_components_1.default.Text is not a function

      3 | import { palette } from 'styled-theme'
      4 |
    > 5 | export const SmallTextWrapper = styled.Text`
      6 |   font-size: 10px;
      7 | `
      8 |
```

**Comment by probablyup** [comment] 2018-02-28 06:11
Any idea @kitten? I'm not familiar with how the react native impl works.

**Comment by probablyup** [comment] 2018-02-28 06:13
Duplicate of #1495

**Closed by probablyup** 2018-02-28 06:13 UTC
Labels: duplicate :two_women_holding_hands:, needs more info :raised_hand_with_fingers_splayed:

**Comment by kevireilly** [comment] 2019-12-03 06:34
[import styled from 'styled-components/native';](https://www.styled-components.com/docs/basics#react-native)

**Comment by MariyaAntonenko** [comment] 2024-05-26 09:06
Faced with it with v5. Mocking of used styled components helped me to solve this issue.
`"styled-components": "^5.3.6"`
`moduleNameMapper: {
 'styled-components': '<rootDir>/node_modules/styled-components/native/dist/styled-components.native.cjs.js',
  }
`
`jest.mock('styled-components', () => {
  const styledMock = jest.fn();
  styledMock.attrs = () => jest.fn();
  const styled = () => styledMock;
  const mockBlock = jest.fn((props) => mockCreateElement('View', props, props.children));
  const mockText = jest.fn((props) => mockCreateElement('Text', props, props.children));
  const mockBtn = jest.fn((props) => mockCreateElement('TouchableOpacity', props, props.children));
  const mockImg = jest.fn((props) => mockCreateElement('Image', props, props.children));
  const mockImgBg = jest.fn((props) => mockCreateElement('ImageBackground', props, props.children));
  const mockInput = jest.fn((props) => mockCreateElement('TextInput', props, props.children));
  const mockKeyboardAvoidingView = jest.fn((props) => mockCreateElement('KeyboardAvoidingView', props, props.children));
  const mockScrollView = jest.fn((props) => mockCreateElement('ScrollView', props, props.children));
  styled.View = () => mockBlock;
  styled.Text = () => mockText;
  styled.TouchableOpacity = () => mockBtn;
  styled.Image = () => mockImg;
  styled.ImageBackground = () => mockImgBg;
  styled.TextInput = () => mockInput;
  styled.KeyboardAvoidingView = () => mockKeyboardAvoidingView;
  styled.ScrollView = () => mockScrollView;
  return {
    __esModule: true,
    default: styled,
  };
});`
