### ISSUE TITLE
Keyframes vs new Chromium version

### ISSUE THREAD

**Issue by rodrigojcmello** [styled-components/styled-components#2602] opened 2019-06-05 19:36 UTC
When using keyframes in Edge Chromium and Chrome Canary ALL texts flash when using the CSS animation attribute

Animations with transition attribute works fine.

## System:
 - OS: Windows 10
 - CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
 - Memory: 4.06 GB / 15.90 GB
## Binaries:
 - Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

"styled-components": "4.2.1"

**Comment by probablyup** [comment] 2019-06-05 19:38
This issue is not helpful without a reproduction case. Please provide something like a codesandbox.

**Comment by probablyup** [comment] 2019-06-05 20:51
Also since this is a brand new browser, you should probably report this bug directly to them if their performance differs from standard Chrome.

**Comment by probablyup** [comment] 2019-06-09 14:49
I'm going to close this since there's a) no reproduction case, b) a pre-release browser involved. When the browser is fully-released if the issue still exists, feel free to reopen with a reproduction case.

**Closed by probablyup** 2019-06-09 14:49 UTC
