### ISSUE TITLE
Ampersand (&) in selectors is sometimes wrongly resolved to component class rather than dynamic class

### ISSUE THREAD

**Issue by kgram** [styled-components/styled-components#3678] opened 2022-01-31 18:10 UTC
Some cases of selectors where an ampersand follows something else, the wrong class name seems to be used, leading to the last props to render for the first time to apply to all component instances.

### System:
 - OS: macOS 12.0.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 39.02 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
### Binaries:
 - Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm

## Reproduction

https://codesandbox.io/s/jovial-cerf-fjbwj

One box should have 1px border, the other 5px border. Instead, both has 5px, the last one declared. Each case has both a dynamic and a static rule, just to ensure that doesn't affect it.

## Steps to reproduce

Use an ampersand in a selector with something in front of it, like so: `.parent &`. In the code sandbox, a number of cases are established, some working, some not. To focus on the parent-class case, given the following style:

```
  .parent & {
    border: ${({ border }) => border}px solid black;
  }
```

and components with `border` set to `1` and `5`.

## Expected Behavior

The ampersand is replaced with the dynamic class, (either every time, or ideally only the last time it's used in each selector), like so:

```css
.parent .hYtajx {
 border:1px solid black;
}
.parent .bfuhxt {
 border:5px solid black;
}
```

## Actual Behavior

Both instances uses the component class, ensuring both components use the same style.

```css
.parent .sc-gsDKAQ {
 border:1px solid black;
}
.parent .sc-gsDKAQ {
 border:5px solid black;
}
```

I suspect this was introduced with #3236 in 5.2.0. It is not reproducible in 5.1.1, see this sandbox: https://codesandbox.io/s/inspiring-northcutt-lvl7s. It does seem `& + &` is being resolved to `dynamic + component` instead of the `component + dynamic` that I would expect, but I think this is still preferable to `component + component`.

**Comment by tenbajt** [comment] 2022-02-01 00:53
Just came across the same issue. I have 2 components with styling based on props. Everything worked fine until I used `&` in styling a child based on parent's `:hover` state. For the base styling the `component + dynamic` class is applied and it works as intended, but for a `parent:hover &`, it applies only `component + component`. It makes the prop passed to `:hover` state for the last component being applied to both of them.

**Comment by diogorighisl** [comment] 2022-02-01 15:01
Same problem here. It seems that if you use 2 &'s, the result is the expected one. Here is an example:

https://codesandbox.io/s/nervous-mendeleev-nsfq7

In this example, you can see that using 1 & results in 

`.sc-bdvvtL:hover .sc-gsDKAQ`

When using 2 &'s, the result is

`.sc-hKwDye:hover .kTtsBP.kTtsBP`

**Comment by mikekreeki** [comment] 2022-02-14 08:17
Probably the same issue here. Having the following style:

```
const MoodPopupColumn = styled(Flex)`
  & + & {
    border-left-width: 1px;
    border-style: solid;
    border-color: ${(props) => props.theme.habits.habitGroupHeader.borderColor};
  }
`;
```

Switching the theme from light to dark correctly updates the border color. However, switching back to light afterward, the border is stuck in dark color and does not update.

**Comment by kitten** [comment] 2022-02-14 10:13
Duplicate of https://github.com/styled-components/styled-components/issues/3265

**Closed by kitten** 2022-02-14 10:13 UTC
