### ISSUE TITLE
Undocumented pseudoselector breaking change between v5 and v6

### ISSUE THREAD

**Issue by jwld** [styled-components/styled-components#4180] opened 2023-09-26 10:03 UTC
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
 - Memory: 55.38 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 18.9.0 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.19.1 - /usr/local/bin/npm
 - Watchman: 2022.09.19.00 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.3.11 => 5.3.11

## Steps to reproduce
Before v6 pseudoselectors could be used without the ampersand like so:
```
:hover {

}
```

However from v6 onwards the above refers only to the children of the component, and needs to be replaced with:
```
&:hover {

}
```

This is a fairly significant breaking change for our codebase, hitting pretty much every pseudoselector we've written.

See also https://github.com/styled-components/styled-components/issues/4096

**Comment by andi1984** [comment] 2023-09-26 19:43
This is a duplicate of #4177.

**Closed** 2023-09-26 21:52 UTC
