### ISSUE TITLE
server rendering is buggy in v2?

### ISSUE THREAD

**Issue by jameslnewell** [styled-components/styled-components#455] opened 2017-02-04 12:59 UTC
## Version
2.0.0-1

## Reproduction

`npm i react react-dom styled-components@next babel-preset-react babel-preset-es2015` babel-cli

`.babelrc`
```
{
  "presets": ["react", "es2015"]
}
```

`index.js`
```js
import React from 'react';
import ReactDOM from 'react-dom/server';
import styled, {styleSheet} from 'styled-components';

const Container = styled.div`
  margin: auto;
  max-width: 1024px;
`;

styleSheet.reset();
const app = ReactDOM.renderToString(React.createElement(Container));
const css = styleSheet.getCSS();

console.log(css);
```

## Steps to reproduce
Run `babel-node index.js`.

## Expected Behavior
> prints `.xyz {margin: auto;max-width: 1024px;}`

## Actual Behavior
With `styleSheet.reset()` doesn't print any CSS classes
> prints ``.

Without  `styleSheet.reset()` prints redundant CSS classes
> prints `.sc-bdVaJa {}.kFMCtP {margin: auto;max-width: 1024px;}`

**Comment by jameslnewell** [comment] 2017-02-04 13:06
Might be a duplicate of https://github.com/styled-components/styled-components/issues/378

**Comment by mxstbr** [comment] 2017-02-04 13:45
Is a duplicate of #378, and those "redudant" class names are actually on purpose. We haven't talked about this much since it isn't released, but every unique component will now have an empty `className` for itself.

That makes it easy to edit all e.g. `<Button />`s on the page at once, which wasn't possible beforehand as they might have different classes based on which state they were in.

**Closed by mxstbr** 2017-02-04 13:45 UTC
Labels: question
