### ISSUE TITLE
[v4 beta] Server rendering not working 

### ISSUE THREAD

**Issue by vinpac** [styled-components/styled-components#1972] opened 2018-09-05 14:53 UTC
## Environment
![image](https://user-images.githubusercontent.com/9030018/45101641-593cae00-b102-11e8-951a-c4de7aa5de4c.png)

## Reproduction

```
git clone https://github.com/vinpac/test-react-custom-cms-intl/tree/styled-v4
cd test-react-custom-cms-intl
yarn
yarn dev
```

## Steps to reproduce

1. Open localhost:3000
2. See console. It will give you a `Prop 'className' did not match`
3. Click on 'vagas'. The search bar will not match with the first page.

## Screenshots

![image](https://user-images.githubusercontent.com/9030018/45101590-3611fe80-b102-11e8-8243-355e3654245a.png)

![image](https://user-images.githubusercontent.com/9030018/45101567-28f50f80-b102-11e8-9419-9e2bb980f4db.png)

This doesn't happen on v3. You can check it the same repository on master branch.

**Comment by imbhargav5** [comment] 2018-09-05 15:14
Hmm, taking a look now.

**Comment by vinpac** [comment] 2018-09-05 15:44
Strange, I couldn't replicate this check error. Is this the only error? If so, deleting the *.stories files is fine.

**Comment by kachkaev** [comment] 2018-09-05 21:11
Looks like I'm experience the same issue in my Next.js + TypeScript app after upgrading to styled-components v4, but I can't reproduce it in an MWE I've been trying to craft myself 🤔

**Comment by kachkaev** [comment] 2018-09-05 21:42
I still can't reproduce the bug in an MWE, but what I see is that all cases of it appear around this kind of code:

```tsx
const XXX = styled.div``;
const YYY = styled(XXX)``;

// <YYY />
```

```
index.js:2178 Warning: Prop `className` did not match. Server: "MyFile__YYY-sc-1dfk8wt-1 jxgVKZ" Client: "MyFile__XXX-sc-1dfk8wt-0 ditbzw"
```

The effect is produces looks exactly like @vinpac has described.

My setup includes:

```js
    "next": "^7.0.0-canary.12",
    "styled-components": "^4.0.0-beta.0",

    "@zeit/next-typescript": "^1.1.1-canary.3",
    "babel-plugin-styled-components": "^1.6.2",
    "@types/styled-components": "^3.0.0",
```

The was a duplicate `styled-components` package v 3 as this was a dependency of another package I use. However, I locked to v4 in `package.json` and now there is only once instance of it in `yarn.lock`.

```json5
  // package.json
  "resolutions": {
    "styled-components": "4.0.0-beta.0"
  },
```

**Comment by probablyup** [comment] 2018-09-06 01:10
@vinpac trying to run your project and getting this error:

```
TypeError: e.split is not a function
    at e.localeDataScript.e (/Users/bear/code/test-react-custom-cms-intl/src/server/intl/setup.ts:28:23)
```

**Comment by probablyup** [comment] 2018-09-06 01:30
ah, gotcha

**Comment by probablyup** [comment] 2018-09-06 04:33
@vinpac hmm after looking at this, I'm not really sure why. We don't guarantee className consistency across environments unless you're using the babel plugin. Have you explored using the new babel typescript integration? https://babeljs.io/docs/en/babel-preset-typescript

**Comment by kachkaev** [comment] 2018-09-06 06:39
@probablyup I'm using `babel-preset-typescript`, which is provided by [`@zeit/next-typescript`](https://github.com/zeit/next-plugins/tree/canary/packages/next-typescript)

**Comment by kachkaev** [comment] 2018-09-06 08:01
I was able to produce an MWE with no TypeScript involved:
https://github.com/kachkaev/styled-components-v4-ssr-mwe

What's happening is reeeeally strange though. If you `yarn && yarn next` on master, you'll get:

```
Warning: Prop `className` did not match. Server: "pages__StyledDiv2-sc-1cvwks4-1 LdUbX" Client: "pages__StyledDiv1-sc-1cvwks4-0 ddDAFj"
```

You can go to `another page` and back and see the styles partially lost in the second div.

However if you remove either `react-apollo` or `react-i18next` or both (`rm -rf node_modules
 yarn.lock && yarn && yarn next`), the bug won't reproduce any more! I have _no idea_ how these two libraries can affect anything given that I'm not using them in the code at all 😅 

I got to the MWE by deleting parts of my real app and here is the reason why those two unrelated dependencies are in `package.json`. Presence of both backages is a deal breaker for some reason.

**Comment by kachkaev** [comment] 2018-09-06 11:52
Upgrading to `next@7.0.0-canary.13` does not help either. MWE updated.

**Comment by probablyup** [comment] 2018-09-06 13:09
If you see that -0 and -1 on the className mismatch, I think that’s because the ordering of the components in that file is changing between server and client. Usually an issue of differing configs during transpilation

**Comment by probablyup** [comment] 2018-09-06 13:09
Or non-deterministic transpilation which is arguably worse 😐

**Comment by kachkaev** [comment] 2018-09-06 13:19
Where do you think the error can be coming from? What is different in v4 compared to v3 that could make the bug possible?

Interestingly, the wrong class name is on the client, not on the server.

**Comment by probablyup** [comment] 2018-09-06 20:29
I have absolutely no idea what's going on here. If I remove a dependency like react-apollo, it goes away. If I add it back, it comes back. So it's deterministically interdeterministic. This is really f*ing bizarre.

**Comment by probablyup** [comment] 2018-09-06 20:43
Okay this has been a fun debugging experience... hoist-non-react-statics v3 and v2 were both being used and they conflict with each other.

**Comment by probablyup** [comment] 2018-09-06 20:43
Adding this made it go away:

```
"resolutions": {
    "hoist-non-react-statics": "3.0.0"
}
```

**Comment by kachkaev** [comment] 2018-09-06 21:12
@probablyup OMG you are a star!!! 🌟 🎉  I'll check this tomorrow on on the weekend – had to revert upgrading to v4 for now.

**Comment by vinpac** [comment] 2018-09-06 21:26
@probablyup Indeed, putting `"hoist-non-react-statics": "3.0.0"` on `resolutions` solves it.

**Comment by probablyup** [comment] 2018-09-06 22:12
Going to leave this open until the PRs against next are merged

**Comment by vinpac** [comment] 2018-09-06 22:14
Thank you for your help!

**Comment by probablyup** [comment] 2018-09-07 13:28
Ok looks like updates are out for both versions of next, gonna close this. Thanks @
timneutkens!

**Closed** 2018-09-07 13:29 UTC

**Comment by kachkaev** [comment] 2018-09-07 13:43
Thank you for investigating this @probablyup! 🚀  I'm so keen to try styled-components v4 with Next 7.0.0-canary.14, just need to get back home for that 😅
