### ISSUE TITLE
Missing name in typescript definition 

### ISSUE THREAD

**Issue by tsantef** [styled-components/styled-components#1878] opened 2018-08-03 00:37 UTC
I started getting this error while compiling: 

```
...node_modules/styled-components/typings/styled-components.d.ts
(98,52): Cannot find name 'Component'.
```

https://github.com/styled-components/styled-components/blob/26be229adbc5629927dead3b95cf1076d88abcd6/typings/styled-components.d.ts#L98

This issue started happening in v3.3.3 
v3.3.2 does not have this issue.

**Comment by Ky6uk** [comment] 2018-08-03 08:17
`v3.3.3` also ok for me. Possible duplicate of #1875

**Comment by tlaak** [comment] 2018-08-03 09:49
I'm getting this with `v3.3.3` as well

**Comment by tlaak** [comment] 2018-08-03 10:01
Component is imported as ReactComponent alias, so changing the `Component<object>` to `ReactComponent<object>` on line `98` seems to resolve the issue. Not sure though if it's actually fixing it or just making the error go away 🤔

**Comment by kachkaev** [comment] 2018-08-03 11:39
There might be a fix in https://github.com/styled-components/styled-components/pull/1879

**Comment by probablyup** [comment] 2018-08-04 14:46
Duplicate of https://github.com/styled-components/styled-components/issues/1875

**Closed by probablyup** 2018-08-04 14:46 UTC
Labels: typings :wrench:
