### ISSUE TITLE
Collecting global styles does not work in browser

### ISSUE THREAD

**Issue by ccolgrove** [styled-components/styled-components#3369] opened 2021-01-07 01:15 UTC
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
 - Memory: 287.80 MB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.1 - /usr/local/bin/node
 - Yarn: 1.22.0 - ~/code/hex-inc/hex/node_modules/.bin/yarn
 - npm: 6.14.5 - /usr/local/bin/npm

In our app, we're constructing iframe contents as a string and relying heavily on styled-components' theming functionality. For this reason, we need to render the style tags from a styled component to a string. Per this issue: https://github.com/styled-components/styled-components/issues/2660 the SSR rendering functionality should be exactly what we need, and indeed for a while that did work, following the docs here: https://styled-components.com/docs/advanced#server-side-rendering. 

However, this recently started failing for us, with the styled components failing to render with the following error: 

```Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.```

Upon inspection, this seems to be due to this line, which is only hit for global styles based out of the browser: https://github.com/styled-components/styled-components/blob/72a6f642c3dedbcee91a2b5d76f96b93f345b86f/packages/styled-components/src/constructors/createGlobalStyle.js#L60

Right now there's no good way around this, since the `__SERVER__` flag is set at compile time. I know this is intended to be server side functionality, but there are a number of reasons you might want to render HTML to a string on the client side (including one in the original ticket), so it would be ideal if this could be fixed in the core library.

## Reproduction

Minimal repro: https://codesandbox.io/s/styled-components-base-forked-ilm86?file=/index.js

## Expected Behavior

`renderToString` should contain a stringified styles tag with the correct styles

## Actual Behavior

`renderToString` returns the empty string

**Comment by TeemuKoivisto** [comment] 2021-01-12 15:15
I had a similar problem with my project where where I wanted to use `useLayoutEffect` without getting those pesky React warnings when server-side rendering the page.

What I did was create a hook that used `useLayoutEffect` conditionally:

```js
import { useEffect, useLayoutEffect } from 'react'

const useSsrLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect

export default useSsrLayoutEffect
```

I'm not sure is it applicable for this case but at least for me it solved the problem.

**Comment by kitten** [comment] 2021-08-09 16:25
Seems like I found two issues for this. Generally, I'd close the newer one, but since I got to this one (the older one) second I'll close this one. Feel free to have a look at the fix mentioned above.

Duplicate of #3506

**Closed by kitten** 2021-08-09 16:25 UTC
