### ISSUE TITLE
Unable to collect style while doing "ssr in the browser"

### ISSUE THREAD

**Issue by Platane** [styled-components/styled-components#3506] opened 2021-06-01 09:45 UTC
`sheet.collectStyle` do not collect global style when called inside a browser environment.

[codesandbox for reproduction](https://codesandbox.io/s/styled-component-global-ssr-up2z5?file=/src/index.tsx)

The issue seems to be related this test:
https://github.com/styled-components/styled-components/blob/25d5a87c6bb5d22b1157c2355bd971e434ec2093/packages/styled-components/src/constructors/createGlobalStyle.ts#L52

It checks if the environment is node. Which is irrelevant since we might want to use ReactDOM.renderToString in a browser environment. It should instead check if the render was started from ReactDOM.renderToString.

I was thinking of a solution where the context used for collecting style ( [here](https://github.com/styled-components/styled-components/blob/30dab74acedfd26d227eebccdcd18c92a1b3bd9b/packages/styled-components/src/models/ServerStyleSheet.tsx#L42) ) exposes a flag to indicate that useLayoutEffect should not be used. Will that work ?

I understand that this issue represent an almost comically edgy case. Do you think a fix is worth it ?

**Comment by kitten** [comment] 2021-08-09 14:16
I believe #3551 may resolve this, if I'm not mistaken, but if you're able to build testing versions of styled-components, please give it a try and validate it :v:

**Comment by kitten** [comment] 2021-08-09 20:06
Duplicate of #3374

**Closed by kitten** 2021-08-09 20:06 UTC

**Comment by Platane** [comment] 2021-08-31 16:55
I tested with 5.3.1 and it is fixed indeed, thank you
