### ISSUE TITLE
fontVariant should return an array

### ISSUE THREAD

**Issue by jacobp100** [styled-components/styled-components#179] opened 2016-11-09 14:52 UTC
```css
font-variant: tabular-nums;
```

should return,

```js
{ fontVariant: [‘tabular-nums’] }
```

**Comment by mxstbr** [comment] 2016-11-09 14:56
What's else can be in there? How would you write multiple elements?

**Comment by jacobp100** [comment] 2016-11-09 15:04
`{ fontVariant: [‘tabular-nums’, ‘small-caps’] }`

**Comment by mxstbr** [comment] 2016-11-09 15:14
Ah yeah, that makes sense! Are there any other properties that have such a notation in ReactNative?

**Comment by jacobp100** [comment] 2016-11-09 15:16
Not the exact same, but `shadowOffset` and `transform` are also funky. I’m just working on some of these cases for my project very similar to styled-components. I’ll post it when I’m done, but it would be good if we could have the same results.

**Comment by mxstbr** [comment] 2016-11-09 16:17
Just realized that this is a duplicate of #139, mind posting your implementation there again? I'd love to make it a standalone module. (`css-to-react-native`?)

**Closed** 2016-11-09 16:35 UTC
Labels: bug, help wanted
