### ISSUE TITLE
v3.2.0 Breaks some styles

### ISSUE THREAD

**Issue by dmitrizzle** [styled-components/styled-components#1576] opened 2018-03-06 10:07 UTC
## Version
styled-components: 3.2.0

## Reproduction
I believe this is partially related to #1454, which was closed in favour in #1473 and fixed in #1529. However, some issues still persist. Most notably it's the inconsistency between production and development build and ignored styles in development build. None of this used to be an issue before 3.1.0

## Steps to reproduce
I wasn't able to isolate the exact place or cause where the issue happens. I plaid around with this file in my app to get all I know so far about the issue -> https://github.com/dmitrizzle/Analog.Cafe/blob/develop/src/app/components/Picture/styles.js

Basically, adding conditional styles to my `<Figure />` component in this fashion:
```
[top styles]
{props => props.feature && '
  [conditional styles]
'}
```
...tends to remove all of the [top styles] from it. There are some [media queries](https://github.com/roast-cms/react-sugar-styled/blob/develop/src/utils.js) involved (i.e. `props.theme.size.breakpoint.min.xxl`) but removing them does not seem to solve the issue.

## Expected Behavior
In production I run 3.0.2, this is how [one of the views](https://www.analog.cafe/submit/compose) looks with some sample content (below). Please note the the size of the "Test heading" as well as location of the image below (and box-shadow on it, if you can see it):

<img width="600" alt="Production server with 3.0.2" src="https://user-images.githubusercontent.com/8587882/37025227-bb6ecc3c-215d-11e8-8baa-ca7fcdcdc096.png">

## Actual Behavior

On my local machine I am trying 3.2.0, and in this case the styles that dictate the image to float left, have a shadow and other properties are thrown out (they do not appear in browser's console on "inspect element"):

<img width="600" alt="Development server with 3.2.0" src="https://user-images.githubusercontent.com/8587882/37025800-3d166d0c-215f-11e8-8968-3bb11b80ac51.png">

I tried compiling the code generated with 3.2.0 into production package. This created some strange effects. The styles I mentioned above (shadow, float) are no longer ignored and are properly added to the stylesheet, however the heading text size has changed:

<img width="600" alt="Package compiled for production with 3.2.0" src="https://user-images.githubusercontent.com/8587882/37025972-a79ae5e0-215f-11e8-970d-855087c89457.png">

**Comment by kingatok** [comment] 2018-03-06 10:59
Recently I updated styled components to version 3.2.0 and I had an issue with greater-than sign being converted to &gt in styles

Example
.jVkaeD > *:not(:first-child)
was converted to 
.jVkaeD &gt *:not(:first-child)

**Comment by kitten** [comment] 2018-03-06 11:01
Can you isolate the affected CSS / component please? Otherwise it'll unfortunately be kind of tricky to go after anything here.

@kingatok Can you open a new issue please? This might be a bug in stylis

**Comment by bnhovde** [comment] 2018-03-06 12:59
I am also experiencing differences between dev and production after updating from `3.1.0` to `3.2.0`:

I think this is the same issue. The `>` character is the culprit for me, which I only use in a few cases.

Here's a simple example:
```
// ...
${props =>
  props.isNarrow &&
  css`
    // ...
    > * {
      // The below line is applied in both dev and prod
      padding-left: 10px;
      ${breakpoints.large`
        // The below line is applied only in dev
        padding-left: 20px;
      `};
    }
  `};
```

I have a breakpoint helper, but this is the standard min-width breakpoint that works in development

**Comment by dmitrizzle** [comment] 2018-03-06 13:06
The CodeSandbox component I built to approximate some of the things I'm doing works fine; I wasn't able to isolate the issue yet, sorry @kitten. I'll keep looking and trying.

As for `>` symbol, that's not likely the case for the issue I'm describing as I'm not using it in this particular stylesheet. Though it may be elsewhere in my code; will check for that too.

**Comment by kitten** [comment] 2018-03-06 14:03
@dmitrizzle do you have a link to said codesandbox?

@bnhovde or can you post a reproduction please?

**Comment by bnhovde** [comment] 2018-03-06 14:19
@kitten I would if I could find a way to run react/sc in production mode on codesandbox.

**Comment by dmitrizzle** [comment] 2018-03-06 14:31
Here's the link for the CodeSandbox: https://codesandbox.io/s/7z659x0jkj
It works fine though and doesn't replicate my issue, unfortunately.

**Comment by kitten** [comment] 2018-03-06 14:33
@dmitrizzle @bnhovde I guess the way to go would be to load it up into CRA and run it in prod mode there.

@dmitrizzle If you can tell me what'll break in production (btw it's not on version 3.2.0), then I can take a look in CRA offline.

**Comment by bnhovde** [comment] 2018-03-06 14:56
@kitten Created a super simple example here: https://github.com/bnhovde/styled-components-issue-demo

I know the example seems contrived, and a way around it is to reverse the nesting order (media query outside of selector), but it seems like a bug regardless, as it works in dev mode.

**Comment by dmitrizzle** [comment] 2018-03-06 15:11
@kitten thanks for the tip, I've changed version to 3.2.0 yet I still can not reproduce the issues I've been having. With this version my code is broken in both production and development, but I can't get it to break the same way with CodeSandbox just yet...

**Comment by kitten** [comment] 2018-03-06 15:28
@bnhovde It seems that media at-rules inside style rules somehow produce an extra closing curly brace on stylis' end. Might be worth avoiding that for now ;)

@thysultan I've got a small failing test case here: https://github.com/styled-components/styled-components/pull/1578

Essentially this is generating a rule with an extra closing curly brace:

```
            > * {
                @media (min-width: 500px) {
                    color: pink;
                }
            }
```

**Comment by thysultan** [comment] 2018-03-06 16:20
@kitten Can you open the issue upstream with the repro outside of s-c.

**Comment by ryanditjia** [comment] 2018-03-06 16:24
### 3.2.0
![image](https://user-images.githubusercontent.com/16177372/37044109-35059f62-2195-11e8-9fdb-af5e57c3e458.png)
### 3.1.6
![image](https://user-images.githubusercontent.com/16177372/37044122-3f937d3c-2195-11e8-8a03-098e6ed4c7cf.png)

### Source
![image](https://user-images.githubusercontent.com/16177372/37044182-6726285e-2195-11e8-83ba-ff2d19b1c12e.png)

Problem isn’t isolated to injectGlobal.

**Comment by kitten** [comment] 2018-03-06 16:32
@thysultan I'll post a codesandbox for you at stylis as soon as I find the time for it.

@ryanditjia please don't just post a screenshot or anything for that matter that is not a reproduction that will help us isolate an issue. For all we know, your issue could be a usage error or something unrelated, so please either open a separate issue, or refrain from posting anything that is not another reproduction :wink:

**Comment by kitten** [comment] 2018-03-06 16:39
@thysultan done https://github.com/thysultan/stylis.js/issues/99

**Comment by sanex3339** [comment] 2018-03-06 18:59
Same. 3.1.* breaks many styles in production, now with 3.2.0 this styles were fixed in production, but keep breaking in development mode.

**Comment by jowy** [comment] 2018-03-07 01:49
Just ran in to this issue tonight. Here is a quick reproduction.

https://jsfiddle.net/osp86jsu/

**Comment by pablen** [comment] 2018-03-08 15:28
Maybe related to this same issue (not sure), I have a slightly different case where 3.2.0 introduced an unexpected output.

Working example using 3.1.6
https://codesandbox.io/s/34r2my2jz5

Unexpected output using 3.2.0
https://codesandbox.io/s/344q4wxo46

Notice how the "root level" property (`text-decoration`) in 3.2.0 example is only honored on the component with the computed `big` style.

**Comment by kitten** [comment] 2018-03-08 16:03
@pablen as shown here https://github.com/thysultan/stylis.js/issues/99 media at-rule inside style rules are broken right now. Please reverse the order for now until a fix is released on stylis :wink:

I’ll lock this issue for now since two bugfixes have gone out, and an issue is present on stylis.

If anyone discovers a bug that’s **unrelated** to these three on 3.2.1, please open a new issue

**Closed** 2018-03-10 22:03 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
