### ISSUE TITLE
Add Support For CSS Variables

### ISSUE THREAD

**Issue by bhough** [styled-components/styled-components#108] opened 2016-10-17 21:14 UTC
## Version
1.0.6

## Reproduction
http://www.webpackbin.com/Vys62X0RZ

## Steps to reproduce
Declare and use a CSS variable anywhere in a styled component.

## Expected Behavior
Leading `-`should remain intact so that browsers can properly identify variable declarations.

## Actual Behavior
the first `-` is being striped from the variable declaration causing browsers that support native CSS variables to view them as bad properties. If you go into dev tools and add the leading `-` back in, everything works as expected.

**Comment by geelen** [comment] 2016-10-17 21:15
Wow that's a straight up miss on my part. Sorry!

**Comment by geelen** [comment] 2016-10-18 09:09
Fixed in #110 will close when that's released.

**Comment by mxstbr** [comment] 2016-10-18 11:10
Done, released as v1.0.7!

**Closed by mxstbr** 2016-10-18 11:10 UTC
Labels: bug

**Comment by camsjams** [comment] 2017-02-24 01:08
@mxstbr or @geelen - since PostCSS is not an option, are there any methods to converting css variables back into something less cutting edge? Something like this https://github.com/MadLittleMods/postcss-css-variables

**Comment by k15a** [comment] 2017-02-24 08:31
@camsjams why are you not using JS variables?

**Comment by camsjams** [comment] 2017-02-24 17:13
@k15a Like this:
```javascript
const EnterToWinWrapper = styled.div`
	background-color: ${COLOR_YELLOW};
`;
```

Yea, I have used that on other projects. I would like to stick to real standards as much as possible. 

Unfortunately a traditional poly-fill for CSS variables is just not feasible with styled-components, so I will just stick with JS interpolation for now, unless there is something that can be done (I am willing to implement myself, but figured I'd ask first).

**Comment by geelen** [comment] 2017-02-24 23:05
The "polyfill" for css variables has some serious edge cases: https://github.com/MadLittleMods/postcss-css-variables#differences-from-postcss-custom-properties and the "Caveats" section below.

These all arise _because_ it's a PostCSS transform, and thus only has visibility into the CSS, not the DOM. This is part of the reason I am so opposed to postcss transforms being available in SC—they're built for a different environment, and supporting/reproducing their limitations (or divergence from the specification as in this case) would weaken the whole proposal.

HOWEVER, if you're feeling like a challenge :wink: Styled Components _does_ have knowledge of both the DOM and the CSS rules, and so **a true CSS custom properties polyfill is possible**. I've had this in the back of my mind to implement for ages but it's a lot of work. It would be amazing though!

In general, I've found that the combination of JS variables and inheritance using theming is everything I wanted CSS variables for anyway, so I haven't missed them too much.

**Comment by camsjams** [comment] 2017-02-25 01:21
Thanks for the insight @geelen - as I've already adopted JS variables in another project, it is something I'm comfortable with.
