### ISSUE TITLE
FlatList scrolls to beginning at data refresh

### ISSUE THREAD

**Issue by XenorPLxx** [styled-components/styled-components#1288] opened 2017-11-02 13:59 UTC
## Version
styled-components: 2.2.1
react-native: 0.49.2

## Steps to reproduce

1. Set up styled FlatList, for example ```const StyledFlatList = styled.FlatList`height: 200px;`;```
1. Set up data refreshing..
1. Render it with some data so it's possible to scroll list.
1. Scroll list (a little bit is enough, start can't be visible).
1. Refresh data. For example add some button to refresh under list, in make case it's Apollo data polling. It also work when I refresh on pull and while it's still refreshing I scroll list a little bit down.

## Expected Behavior

Data should refresh in place without list automatically scrolling anywhere.

## Actual Behavior

List scrolls to beggining.

## Comment

I'll be able to setup some sample project if there will be problem reproducing this bug, but I wouldn't be able to do that before the weekend.

**Comment by philpl** [comment] 2017-11-02 16:00
This is probably a usage problem, but we'll need some source code to be able to help you

**Comment by brunolemos** [comment] 2017-12-24 21:05
Cannot reproduce. Maybe the issue is not being cause by styled components?
https://snack.expo.io/BJNKLcTzf

**Comment by XenorPLxx** [comment] 2017-12-25 00:30
I've expanded example a little to add refreshing I've used in my app and in expo it works as it's supposed to.

[https://snack.expo.io/HknxLTaMM](https://snack.expo.io/HknxLTaMM)

The only thing missing in the example is apollo/redux - instead of local state my component used apollo query to update data when list was pulled down.

We decided to go with different way of styling components, so I won't be able to prove any other example soon.

**Comment by philpl** [comment] 2017-12-25 14:30
@XenorPLxx hiya, sorry to hear that it hasn’t worked out for you 😉 in general all hints at a small usage problem, since it’s not reproducible. I myself am using a FlatList with Apollo and SC in a project, and there’s nothing fancy we’re doing that would cause this behaviour.

All in all, I’m forced to close this. Sorry again 😅 I hope that you’ll try it out again sometime. Feel free to reopen/comment on this issue if you experience it again and can create a reproduction.

In general, please read the template carefully. It does ask for some reproduction code for the reason of us being able to experience and debug the problem.

I wish you awesome holidays! ✨

**Closed by philpl** 2017-12-25 14:30 UTC
Labels: needs more info, question

**Comment by XenorPLxx** [comment] 2017-12-25 14:32
Happy holidays to you too! 

I hope I'll have time in the future to check this out again, and for now thank you for trying to solve this thing despite the shortages in my description.
