### ISSUE TITLE
Browser rerenders for every injection

### ISSUE THREAD

**Issue by saschagehlich** [styled-components/styled-components#400] opened 2017-01-23 13:30 UTC
Hey there,

we've been using styled-components in a new project for two weeks now, and so far it's a great experience. But as our application gets larger and more complex, we start running into performance issues, which I'd like to talk about here.

Please see the following video: https://vid.me/5rlI

### Problem 1: Re-rendering the whole application when rules are added

I've enabled paint flashing, so you see which parts of the screen are re-rendered. As soon as new rules are added to the <style> tag, the browser has to re-parse the whole CSS and re-render the whole screen. This happens for example when moving the cursor to the navigation bar, but it only happens the first time, when the CSS rule is created. Subsequent hovering works as expected.

### Problem 2: Reloading web-fonts, causing text to flicker

As you see in the networks tab, web fonts are re-loaded when new rules are added. This is happening, because styled-components adds new CSS rules to the same <style> tag as our global font-face rules. Reloading the font causes all texts to flicker and re-render.

Is this being worked on? Is this a problem with my application or is this actually a problem with styled-components? For me it looks like a styled-components issue and a generic issue with changing the contents of a global <style> tag.

**Comment by diegohaz** [comment] 2017-01-24 16:12
Related #238

**Comment by mxstbr** [comment] 2017-01-24 16:32
This is interesting, thanks for kicking off this discussion! Just to confirm, you're running into actual performance issues with your app where `styled-components` is the bottleneck and creates a worse user experience?

I remember @geelen did a bunch of benchmarking around the injection mechanism to make sure it's as performant as possible, I'd be interested to see if we can maybe fix this by editing that? Any ideas Glen?

**Comment by saschagehlich** [comment] 2017-01-24 17:53
Yes, `styled-component` is the reason why we're experiencing flickering and performance issues. It's probably due to styled-components' concept of dynamic styles inside <style> tags - updating rules that are at the beginning of a <style> tag might sometimes case following rules to re-apply and re-render the whole screen.

**Comment by mxstbr** [comment] 2017-01-24 18:58
That should definitely not be happening and sounds like a bug on our side. Let's get this resolved asap!

**Comment by k15a** [comment] 2017-01-24 20:22
I think a solution would be to inject every newly generated style in a seperate style tag?

**Comment by xcoderzach** [comment] 2017-01-24 22:34
Problem 1:
I think the solution here might be to enable the "speedy" option on the glamor sheet in "production", so that classes get added via `insertRule`, rather than string manipulation.

Problem 2: 
Given that `injectGlobal` should only be called at initialization time, the solution here is probably to create a single separate sheet for global styles.

**Comment by geelen** [comment] 2017-01-24 22:46
Hey I'm super swamped with work at the moment so it'll be a few days before I can look at this. @xcoderzach is right though about needing a separate `<style>` tag for global styles that don't get updated, can someone PR that?

The component stuff is more subtle, and has implications for SSR and rehydration as well. I've noticed the style invalidations before (natural consequence of injecting CSS) but didn't think it was triggering repaints. I also haven't seen any flashes like @saschagehlich describes. Could someone create a webpackbin that demonstrates both the errors, and then test it in Firefox as well. The font-face bug is Chrome-only I believe.

Will get this fixed before v2 drops but yeah I'm rammed for the next few days, sorry!

**Comment by xcoderzach** [comment] 2017-01-25 16:36
I can hopefully make a PR tonight

**Comment by xcoderzach** [comment] 2017-01-27 15:24
So I played around with this issue in the app I'm working on, and I think the issue is that when an @font-face changes, it invalidates any rule that uses or inherits the typeface.  Which is probably almost everything.  Given that, I think #415 should fix all of the issues raised here.

**Comment by mxstbr** [comment] 2017-01-28 21:11
Thanks so much for digging into this @xcoderzach, super appreciated! 👏

Published as `v1.4.2`, so I'll close this for now assuming this is fixed. @saschagehlich please do test the changes and let us know if your issues still persist.

**Closed by mxstbr** 2017-01-28 21:11 UTC
Labels: discussion

**Comment by AlexanderRichey** [comment] 2018-03-28 22:42
I am using version 3.2.3 and am experiencing the same behavior described above. Every time a new style is injected - when I click on a dropdown and a new class is generated, for example - all of the fonts are reloaded and the page flickers. I am using `injectGlobal` to declare my fonts.

When I inspect the dom, I can see the two styled-components style tags, but it seems that the one that holds the global styles is being modified when new styles are generated, which causes the fonts to be refetched.

I developed a quick fix where I manually inject my fonts and other global styles myself and do not use styled-component's `injectGlobal` feature. But it would be better to streamline all of my app's css through styled-components.

Is anyone else facing this issue or has anyone else developed a better solution?

**Comment by kitten** [comment] 2018-03-28 23:03
@AlexanderRichey this is an older and stale issue, so please don't revive it :wink: we have a newer one here for this exact same behaviour: https://github.com/styled-components/styled-components/issues/1593

But there's some reasons why it's not a big deal:

- In production with `insertRule` this won't happen
- As long as you're using `@import` you should be fine

Feel free to check out the issue above, but I unfortunately don't have time currently to completely address and fix it. It would involve to completely extract every at-rule related to fonts.
