### ISSUE TITLE
ServerStyleSheet constructor fails in jsdom jest environment

### ISSUE THREAD

**Issue by Igorbek** [styled-components/styled-components#975] opened 2017-07-07 05:59 UTC
## Version
styled-components: 2.1.1
jest: 20.0.4

### package.json
```json
{
  "dependencies": {
    "styled-components": "^2.1.1"
  },
  "devDependencies": {
    "jest": "^20.0.4"
  }
}
```

### jsdom.test.js

```js
const { default: styled, ServerStyleSheet } = require('styled-components');

it('jsdom fails', () => {
    styled.div` color: red; `;
    new ServerStyleSheet();
});
```

## Steps to reproduce

```
> jest
```

## Expected Behavior

Test passes.

## Actual Behavior

Test fails with an exception:

```
 FAIL  .\jsdom.test.js
  ● jsdom fails

    BrowserTag cannot be cloned!

      at BrowserTag.clone (node_modules/styled-components/lib/models/BrowserStyleSheet.js:96:11)
      at node_modules/styled-components/lib/models/StyleSheet.js:167:18
      at Array.map (native)
      at Function.clone (node_modules/styled-components/lib/models/StyleSheet.js:166:74)
      at new ServerStyleSheet (node_modules/styled-components/lib/models/ServerStyleSheet.js:104:42)
      at Object.<anonymous>.it (jsdom.test.js:5:5)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

  × jsdom fails (14ms)
```

## Additional info

Similar issue #893 with other use-case.
I'm using this in jest snapshot testing when I'm capturing components output along with css produced by them. So the SSR API is used in jsdom environment (required for proper component mounting).

**Comment by philpl** [comment] 2017-07-07 10:41
Duplicate of https://github.com/styled-components/styled-components/issues/893

**Closed by philpl** 2017-07-07 10:41 UTC
