### ISSUE TITLE
Bug [Export default]

### ISSUE THREAD

**Issue by dmitweb** [styled-components/styled-components#115] opened 2016-10-18 11:57 UTC
## Version

1.0.6, 1.0.7
## Reproduction

Update from 1.0.5 to 1.0.6 or 1.0.7.
## Steps to reproduce

Normal use
## Expected Behavior

Render div or another component
## Actual Behavior

![1](http://i.imgur.com/FbyOphZ.png)
![2](http://i.imgur.com/rtMA0V3.png)
![3](http://i.imgur.com/HinpAOU.png)
![4](http://i.imgur.com/48SEUwY.png)
![5](http://i.imgur.com/CbHMuv1.png)

I hope these screenshots enough to understand the problem =)

**Comment by mxstbr** [comment] 2016-10-18 12:18
Hmm, that makes sense though, if anything the previous behaviour was a bug. Are you using webpack or rollup? (i.e. the `.es.js` bundle?) /cc @Rich-Harris

**Comment by dmitweb** [comment] 2016-10-18 12:22
I'm use webpack 2 with babel.

**Comment by Rich-Harris** [comment] 2016-10-18 12:25
If you're using Webpack 2 it's presumably using the new `es.js` bundle. Might be a case where Babel and Webpack are *both* trying to deal with `import` and `export`. You could try disabling module transformations in Babel so that Webpack deals with it:

```js
{
  presets: [
    ["es2015", { "modules": false }]
  ]
}
```

**Comment by mxstbr** [comment] 2016-10-18 12:28
Oh sorry, I misread the screenshot, `styled.default.default` is definitely not the expected behaviour!

**Comment by dmitweb** [comment] 2016-10-18 12:37
If I disabled modules I get a ton of errors =)

**Comment by stephenkingsley** [comment] 2016-10-18 13:27
I want to fix this, can I?

**Comment by mxstbr** [comment] 2016-10-18 13:29
Yes please @stephenkingsley!

**Comment by Rich-Harris** [comment] 2016-10-18 13:32
Please do @stephenkingsley! I've been going round in circles trying to figure out how the hell you configure loaders in Webpack 2. My minimal example works just fine, but that's without the Babel loader, which is evidence for the hypothesis that it's the combination of both that is causing the problem.

**Comment by stephenkingsley** [comment] 2016-10-19 06:59
when I `console.log(styled)` in chrome, it show an object that is not my want.
<img width="344" alt="2016-10-19 2 28 04" src="https://cloud.githubusercontent.com/assets/13380370/19507927/9f06d42c-9608-11e6-9e54-0f43e67c65cf.png">

and I think that is the `rollup's` bug, what do you think? 

I think we can do a temporary solution to fix it, and when `rollup` fix this bug, we change back.

`my solution`: we can map the `styled` to export each key in styled. just like

```js
// before
export default styled
export { css, keyframes, injectGlobal, ThemeProvider }

// after
// temporary solution to exports
exports.h1 = styled('h1')
exports.section = styled('section')
// .... Shorthands for all valid HTML Elements
/* Export everything */
export default styled
export { css, keyframes, injectGlobal, ThemeProvider }
```

<img width="915" alt="2016-10-19 2 57 15" src="https://cloud.githubusercontent.com/assets/13380370/19508573/7d8b6692-960c-11e6-9de7-2d11ba0ab523.png">

what do you think?

**Comment by mxstbr** [comment] 2016-10-19 07:46
That seems like a pretty hacky/unnecessary workaround – something obviously amiss either with our build process or the bundling step, this isn't something we should be doing in the source!

**Comment by stephenkingsley** [comment] 2016-10-19 09:43
Let me keep trying! I will do my best.

**Comment by dmitweb** [comment] 2016-10-19 12:25
Ok. Yesterday, I was prepared to wait until someone will solve the problem. Today, I'm not ready. I can't wait until someone finds a fix, because I use your wonderful component, I really liked it =). I can send a detailed report of rectification of the problem if necessary. How can I offer a fix? Problem solved.

**Comment by stephenkingsley** [comment] 2016-10-19 13:50
@dmitweb I am looking for the solution for this problem, I think it can not take long time.

**Comment by Rich-Harris** [comment] 2016-10-19 14:05
The UMD build behaves exactly as before, so by process of elimination this must be related to Webpack's handling of the `.es.js` bundle (possible in combination with the Babel loader as mentioned above). If it comes down to it, removing the `jsnext:main` and `module` fields from `package.json` would presumably fix the problems Webpack users are experiencing, though that's not an ideal solution.

**Comment by dmitweb** [comment] 2016-10-19 14:07
@stephenkingsley @Rich-Harris no. Just little fix:
Before:
`
export default styled
export { css, keyframes, injectGlobal, ThemeProvider }
`
After:
`
module.exports = styled;
module.exports.css = css;
module.exports.keyframes = keyframes;
module.exports.injectGlobal = injectGlobal;
module.exports.ThemeProvider = ThemeProvider;
`
And all works great.

**Comment by dmitweb** [comment] 2016-10-19 15:45
This is my final solution:
```
/* Export everything */
if (typeof module !== 'undefined') {
	module.exports = styled;
	module.exports.css = css;
	module.exports.keyframes = keyframes;
	module.exports.injectGlobal = injectGlobal;
	module.exports.ThemeProvider = ThemeProvider;
} else {
	exports['default'] = styled;
	exports.css = css;
	exports.keyframes = keyframes;
	exports.injectGlobal = injectGlobal;
	exports.ThemeProvider = ThemeProvider;
}
```
It works in all bundles.

**Comment by Rich-Harris** [comment] 2016-10-19 15:48
@dmitweb no, that doesn't work – the `.es.js` is an *ES module bundle*, i.e. it uses `import` and `export`. What you've created is a CommonJS bundle.

**Comment by dmitweb** [comment] 2016-10-19 15:50
@Rich-Harris just test this now. All works fine.

**Comment by mxstbr** [comment] 2016-10-19 17:34
> @Rich-Harris just test this now. All works fine.

Yes of course it works, but now it's the exact same as the normal `styled-components.js` bundle – that's not what we want. We need those exports to be actual ES6 `export`s so webpack and rollup can do treeshaking.

**Comment by stephenkingsley** [comment] 2016-10-20 02:13
>  We need those exports to be actual ES6 exports so webpack and rollup can do treeshaking.

Yes! I think other temporary solutions we should stop discussion.

**Comment by dmitweb** [comment] 2016-10-20 14:35
Well, I had to spend an extra few hours to search for other solutions to this problem. I found it, it would be more acceptable than the previous hope. Little hack babel:
Before:
```
export default styled
export { css, keyframes, injectGlobal, ThemeProvider }
```
After:
```
export default styled
export { css, keyframes, injectGlobal, ThemeProvider }
exports.__esModule = true
```
I test it already. Work's great.

**Comment by k15a** [comment] 2016-10-20 14:51
The problem is that webpack doesn't set the __esModule flag to true when it exports ES6 modules internally. Babel in the other hand checks if the __esModule flag is true and otherwise wraps the whole module in an object where the default key is the module.

```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

In the end we get a object which looks like

```
{
  styled: {
    default: { // babel's wrapper because it thinks that we have a commonjs module
      default: { // webpack's default export
        div,
        h1,
        section,
        ...
      }
    }
  }
}
```

This only happens if you use webpack 2 with the babel-plugin-transform-es2015-modules-commonjs plugin. Don't know if rollup handles exports the same way babel does.

A temporary workaround would be @dmitweb's solution but that would be kind of a hack. I think we should file an issue at webpack to handle es6 modules the same way as babel does.

**Comment by stephenkingsley** [comment] 2016-10-20 14:51
> 
```js
export default styled
export { css, keyframes, injectGlobal, ThemeProvider }
exports.__esModule = true
```

@dmitweb I do not agree it. I do not think this is a solution in this bug.

**Comment by dmitweb** [comment] 2016-10-20 14:55
@stephenkingsley your have better solution ?

**Comment by stephenkingsley** [comment] 2016-10-21 02:18
@dmitweb when `npm run build`,  it created `styled-components.es.js`, `styled-components.js` and `styled-components.min.js` files. 

and then if the html file like this

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Basic Example</title>
  </head>
  <body>
    <h1>Basic Example</h1>
    <div id="container"></div>
    <script src="https://unpkg.com/react@15.3.2/dist/react.min.js"></script>
    <script src="https://unpkg.com/react-dom@15.3.2/dist/react-dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.24/browser.min.js"></script>
    <script src="/styled-components.js"></script>
    <script type="text/babel">
      console.log(styled)
      const Title = styled.default.h1`
        font-size: 1.5em;
        text-align: center;
        color: palevioletred;
      `;
      const Wrapper = styled.default.section`
        padding: 4em;
        background: papayawhip;
      `;
      class Example extends React.Component {
        render() {
          return (
            <Wrapper>
              <Title>Hello World, this is my first styled component!</Title>
            </Wrapper>
          )
        }
      }

      ReactDOM.render(
        <Example />,
        document.getElementById('container')
      );
    </script>
  </body>
</html>
```

the

**Comment by stephenkingsley** [comment] 2016-10-21 15:09
tonight I test styled-component, I found in commonJS, everything was right. only run `npm run build`, and in html use `<script />` has bug. @mxstbr 

when I wrote a little demo in rollup.js webpage, I also find this problem. [this is the example](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnVtZCUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBUaGVyZSUyMGFyZSUyMG1hbnklMjB3YXlzJTIwdG8lMjBleHBvcnQlMjBiaW5kaW5ncyU1Q24lMkYlMkYlMjBmcm9tJTIwYW4lMjBFUzIwMTUlMjBtb2R1bGUlNUNuZXhwb3J0JTIwdmFyJTIwZm9vJTIwJTNEJTIwMSUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBiYXIlMjAoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwZm9vJTNCJTIwJTJGJTJGJTIwdHJ5JTIwY2hhbmdpbmclMjB0aGlzJTIwdG8lMjAlNjBmb28lMkIlMkIlNjAlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGJheiUyMCgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBiYXIoKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGJheiUyMCU3RCUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGcXV4JyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJxdXguanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwdmFyJTIwcXV4JTIwJTNEJTIwJ1FVWCclM0IlMjIlN0QlNUQlN0Q=)

## the demo's code:

### main.js

```js
import fun1 from './qux.js';

var fun3 = function() {
	console.log('func3');
}

var func4 = function() {
	console.log('func4');
}

var func = func1(func4);
export default func1;
export { func3 }
```

### qux.js

```js
var func1 = function() {
 	var func2 = function(str) {
    	console.log('func2' + str)
    }
    
    func2.a = func2('a');
  	func2.b = func2('b');
  
  	return func2;
}

export default func1
```

### bundle.js

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (factory((global.myBundle = global.myBundle || {})));
}(this, (function (exports) { 'use strict';

var func4 = function() {
    console.log('func4');
};

var func = func1(func4);

exports['default'] = func1;
exports.func3 = func3;

Object.defineProperty(exports, '__esModule', { value: true });

})));

```

when `index.html` use `<script src="bundle.js"></script>`, the logger is like the pic
![image](https://cloud.githubusercontent.com/assets/13380370/19603136/9b29e796-97e2-11e6-8445-59fae92c6df2.png)

I don't know if I made it clear.

**Comment by Ginhing** [comment] 2016-10-24 14:51
I make a temporary fix in my local environment of Webpack 2:

1.Make a file named `styled-componentes-fixed.js` or you like, put this code in it:
```javascript
module.exports = require('styled-components/lib/index.js').default
```

2.In webpack.config.js, alias `styled-components` to the file made in 1):
```javascript
alias: {
  // ...
  'styled-components$': path.join(PATH_OF_FIXED_FILE, 'styled-components-fixed.js'),
}
```

**Comment by mxstbr** [comment] 2016-11-01 13:55
I can't replicate this, so I'm going to close it until somebody uploads a repo with a minimal reproduction. This seems to be an issue with your individual setups.

----

I added `styled-components` to `react-boilerplate` (which has the most intricate tree shaking setup ever) using the `.es.js` build, and everything worked as expected...

![screen shot 2016-11-01 at 14 50 50](https://cloud.githubusercontent.com/assets/7525670/19891999/f385566a-a042-11e6-9789-7604024339ad.png)

![screen shot 2016-11-01 at 14 53 37](https://cloud.githubusercontent.com/assets/7525670/19892010/009db73e-a043-11e6-8806-51f202e9050e.png)

![screen shot 2016-11-01 at 14 51 08](https://cloud.githubusercontent.com/assets/7525670/19892001/f4ea713e-a042-11e6-9f06-2b0ac62252e6.png)

**Closed by mxstbr** 2016-11-01 13:55 UTC
Labels: bug, Hacktoberfest

**Comment by BLamy** [comment] 2016-11-04 19:13
For what it's worth I also ran into this issue today when migrating a project to styled-components. Setting es2015 modules to false and adding an alias did work around the issue but isn't ideal.

**Comment by k15a** [comment] 2016-11-05 08:29
Why is setting es2015 modules to false not ideal?

**Comment by BLamy** [comment] 2016-11-06 01:48
I personally already had modules set to false, adding the alias on the other hand kind of felt like a hack. Not the end of the world but I figured I would throw my 2 cents in since the ticket was closed and I could definitely reproduce. 

With that said some other people might have issues setting es2015 modules to false because it can be a breaking change for people who were relying on non-spec compliant behavior of the babel implementation.

**Comment by Ginhing** [comment] 2016-11-06 05:40
@BLamy The alias of `styled-components/lib/index.js` isn't necessary if have set the es2015 modules to false.

**Comment by rohmanhm** [comment] 2016-12-21 23:45
@Ginhing that's work for me, thanks

**Comment by timfuhrmann** [comment] 2022-03-12 17:23
> when I `console.log(styled)` in chrome, it show an object that is not my want. <img alt="2016-10-19 2 28 04" width="344" src="https://cloud.githubusercontent.com/assets/13380370/19507927/9f06d42c-9608-11e6-9e54-0f43e67c65cf.png">

The seems to be a pretty old issue, but we are currently facing the same behavior for rollup `esm` output. What the sate on this?

**Comment by timfuhrmann** [comment] 2022-03-12 17:25
> when I `console.log(styled)` in chrome, it show an object that is not my want. <img alt="2016-10-19 2 28 04" width="344" src="https://cloud.githubusercontent.com/assets/13380370/19507927/9f06d42c-9608-11e6-9e54-0f43e67c65cf.png">

The seems to be a pretty old issue, but we are currently facing the same behavior for our rollup `esm` output. What the sate on this?

**Comment by psychobolt** [comment] 2022-03-29 06:10
With v5.3.5 and using Webpack 5 alias config will workaround this issue:
```js
resolve: {
   alias: {
      'styled-components': 'styled-components/dist/styled-components.js',
      // etc
    },
   // etc
}
```
