### ISSUE TITLE
CSS grows during successive server-side rendering

### ISSUE THREAD

**Issue by tp** [styled-components/styled-components#2607] opened 2019-06-07 16:42 UTC
In our SSR we see an increase in CSS response size whenever a new route / React-loadable page component has been triggered.

For example the CSS sizes would grow as follows:

- Homepage: 70 kB
- Product detail page: 80 kB
- Homepage: 75 kB

## Reproduction

I don't have a separate reproduction, and saw that there is already a test case for SSR that checks that styles don't leak. But maybe we're triggering some special path (e.g. Global Styles?) that are not covered by the test?

## Steps to reproduce

In our app:

```typescript

    const styleSheet = new ServerStyleSheet();

      renderToString(
        styleSheet.collectStyles(
          <>
            <GlobalStyle />
            <HelmetProvider context={context}>
              <Capture report={moduleName => modules.push(moduleName)}>
                {children}
              </Capture>
            </HelmetProvider>
          </>
        )

console.error(styleSheet.getStyleTags().length); // this grows after a different page was rendered

```

## Expected Behavior

When loading the same page / route, the CSS size should be the same from the first to the last request.

## Actual Behavior

CSS size grows over time when switching between different pages / routes.

## Workaround

I found the follow workaround: Resetting the `master` `StyleSheet` (no idea why we'd need that anyway, as it's empty for the first render, so I thought it wouldn't hurt to be also empty on successive renders. But maybe it helps with caching / performance?):

```
const StyleSheet = require('styled-components')
  .__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS.StyleSheet;


    StyleSheet.reset(true); // ⬅️ the fix
    const styleSheet = new ServerStyleSheet();
```

Might this be a repetition / related to #1602?

**Comment by probablyup** [comment] 2019-06-07 16:51
v5 has a lot of changes in this regard… we should be dropping the first
beta in the near future and I’d love to get your feedback on it to see if
it fixes your issue


On June 7, 2019 at 11:42:14 AM, Timm Preetz (notifications@github.com)
wrote:

In our SSR we see an increase in CSS response size whenever a new route /
React-loadable page component has been triggered.

For example the CSS sizes would grow as follows:

   - Homepage: 70 kB
   - Product detail page: 80 kB
   - Homepage: 75 kB

Reproduction

I don't have a separate reproduction, and saw that there is already a test
case for SSR that checks that styles don't leak. But maybe we're triggering
some special path (e.g. Global Styles?) that are not covered by the test?
Steps to reproduce

In our app:

    const styleSheet = new ServerStyleSheet();



      renderToString(

        styleSheet.collectStyles(

          <>

            <GlobalStyle />

            <HelmetProvider context={context}>

              <Capture report={moduleName => modules.push(moduleName)}>

                {children}

              </Capture>

            </HelmetProvider>

          </>

        )


console.error(styleSheet.getStyleTags().length); // this grows after a
different page was rendered

Expected Behavior

When loading the same page / route, the CSS size should be the same from
the first to the last request.
Actual Behavior

CSS size grows over time when switching between different pages / routes.
Workaround

I found the follow workaround: Resetting the master StyleSheet (no idea why
we'd need that anyway, as it's empty for the first render, so I thought it
wouldn't hurt to be also empty on successive renders. But maybe it helps
with caching / performance?):

const StyleSheet = require('styled-components')

  .__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS.StyleSheet;





    StyleSheet.reset(true); // ⬅️ the fix

    const styleSheet = new ServerStyleSheet();


Might this be a repetition / related to #1602
<https://github.com/styled-components/styled-components/issues/1602>?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/styled-components/styled-components/issues/2607?email_source=notifications&email_token=AAELFVS6VOBUOSHTIPLJM3LPZKFWNA5CNFSM4HVYUWM2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYJNI4Q>,
or mute the thread

**Comment by mxstbr** [comment] 2019-06-08 08:45
Can you try `yarn add styled-components@canary-sheet`?

**Comment by tp** [comment] 2019-06-08 19:58
@mxstbr Sure. Here are the measurements:

```
sizes are measured using:
styleSheet.getStyleTags().length
renderToString(<>{styleElement}</>).length


### Before

route /

86198
86216


route /p

114885
114903

route /

114885
114903


### After

// styled-components@^5.0.0-5.canary-sheet:
//  version "5.0.0-5.canary-sheet"
//  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-5.0.0-5.canary-sheet.tgz#7d2bfd9721d73f2d54d729f9b08d31e35df55c08"

// NOT calling styleSheet.seal() anymore

route /

85988
86009

second try:

83421
83442

route /p

86394
86415

route /

83421
83442

second try:

86982
87003
```

I am not sure why the measurements for `/` fluctuate like that, but since it's a full-blown app I can't completely discard the possibility that some API response might change during request and lead to some components rendering a little differently.

Overall though the growth issue seems fixed though! 🎉

For the time being, do you have any arguments against the `StyleSheet.reset` workaround?

**Comment by tp** [comment] 2019-06-12 06:39
@probablyup Should I retry with `styled-components@alpha` now (I see you changed the comment)? 

Wasn't `styled-components@alpha` enough?

And could somebody still comment on whether the workaround of `StyleSheet.reset` seems OK for now?

Thanks

**Comment by mxstbr** [comment] 2019-06-12 07:56
Up to v5, we inserted marker comments into the stylesheet to make sure that components' styles were always rendered into the correct order. When you render a different page, more components are registered, thusly the stylesheet size grows. It should not grow unbounded, only until all components are registered.

As far as I understand, that is expected behavior. (cc @kitten) Calling `StyleSheet.reset` manually could lead to some strange style mishaps. I would recommend simply keeping everything around for now until v5 launches (soon).

**Comment by tp** [comment] 2019-06-12 09:16
@mxstbr But the final `<style>` tag that ends up in our pages after some time (nodes running for a few days) approaches 1MB (!) (920kB at the last measurement). That is just not tenable for a mobile website.

Also everything looks fine / the same in SSR with `reset` in place, so I don't really get why it should grow / why that'd be desired or OK.

(A colleague saw that the "huge" style tag on some pages contained rules for components from other pages, which are not relevant for the current page.)

**Comment by kitten** [comment] 2019-06-12 11:22
@tp To be honest, the alpha has been running on some production sites I've worked on for a while now with tens of thousands of visitors. It's really stable and as long as your setup isn't unusual, you could already consider upgrading if you need this fixed urgently.

Resetting the Stylesheet in v4 might actually break more things rather than improve the situation which can have bad repercussions in the long run obviously.

**Comment by probablyup** [comment] 2019-06-12 16:41
@tp yeah retry, the old version was recommending the `@canary-sheet` tag which was outdated and missing something for backward compat.

**Comment by tp** [comment] 2019-06-12 17:27
> Resetting the Stylesheet in v4 might actually break more things rather than improve the situation which can have bad repercussions in the long run obviously.

@kitten I still don't see how that could be the case, since the style sheet is fine on the first render and then continues to be the same size on subsequent ones. So what could go missing by a `reset`?

Regardless, we'll explore switching to v5 and keep you updated as to whether this is fully fixed in the latest version still.

**Comment by kitten** [comment] 2019-06-13 09:26
@tp resetting the Stylesheet in v4 gets rid of all component markers which was in prior versions our approach to keep track of the order of components.

Hence when you reset it in v4 it deletes all markers as well and it will fall back to rendering order. This will likely lead to specificity issues. And once the guarantees of specificity are gone you're more likely to work around them and write brittle css again 😅

**Comment by probablyup** [comment] 2019-06-15 20:36
@tp how's v5 beta looking on your end for this issue?

**Comment by probablyup** [comment] 2019-06-16 16:19
Going to close this as we won't be doing any major reworkings of the v4 stylesheet going forward and this simply can't happen in v5 since we don't do stylesheet cloning anymore.

**Closed by probablyup** 2019-06-16 16:19 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:

**Comment by tp** [comment] 2019-06-17 11:24
@probablyup Sorry for the late reply, we've been busy shipping other updates.

Just checked with alpha (`954ab995b8b3a5efed5403249c1014aa3432effb`), and the behavior is indeed good (no size variations across requests).

**Comment by probablyup** [comment] 2019-06-17 18:33
Awesome, great to hear! There's a bunch of fixes in the beta channel so if you ship that at work I recommend using `styled-components@beta` now.
