### ISSUE TITLE
Styles finding their way into completely unrelated components

### ISSUE THREAD

**Issue by abubakir1997** [styled-components/styled-components#3457] opened 2021-04-10 15:45 UTC
## System:
 - OS: macOS 11.2.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 113.60 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v12.21.0/bin/yarn
 - npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm

## Reproduction

I recently divided my project into a monorepo using lerna and yarn workspaces. I am running `styled-components: 5.2.3` along with `react: 17.0.1` and `react-dom: 17.0.1`. After switching to a monorepo a weird bug occurred where styles from another styled component were finding their way into another component that has no connection. This is a simple example of what is happening.

```js
const StyledComponentA = styled.div`
  background: red;
`
```

```js
const StyledComponentB = styled.span`
  font-size: 14px;
`
```

Locally everything works as expected, but when I build for production and deploy my application for some reason the styles for `StyledComponentA` find their way into `StyledComponentB`. Below is the exact code that is facing the issue:

![code-printables](https://user-images.githubusercontent.com/18533628/114275541-ebab3980-99f0-11eb-9a81-8e31be485e33.png)
> The above image shows two components that live inside a shared package used by the client side and the server.

![code-client](https://user-images.githubusercontent.com/18533628/114275563-067dae00-99f1-11eb-800a-c38039c4c0b9.png)
> The above image shows two client side components that are getting effected by the components in the shared package

![ui-development](https://user-images.githubusercontent.com/18533628/114275583-21502280-99f1-11eb-928f-e6ddec962d60.png)
> A screenshot of the UI in development (locally)

![ui-production](https://user-images.githubusercontent.com/18533628/114275624-2d3be480-99f1-11eb-8a1b-25c49bb87819.png)
> A screenshot of the same UI in production

![styles-FormSelectFormGroup](https://user-images.githubusercontent.com/18533628/114275640-3927a680-99f1-11eb-93dd-bcec63faddc7.png)
![styles-FormSelectTagText](https://user-images.githubusercontent.com/18533628/114275643-3b8a0080-99f1-11eb-835b-46756b9469c6.png)
> The above two images shows how the styles are somehow getting injected (in production)

## Expected Behavior

Styles should only effect their respective components.

## Actual Behavior

Styles getting injected into another component that has no remote connection.

Just to clarify further this happens only to one component (as far as I can tell) and only in production.

**Comment by abubakir1997** [comment] 2021-04-10 15:47
Just to clarify further this happens only to one component (as far as I can tell) and only in production.

**Comment by abubakir1997** [comment] 2021-04-10 17:13
![code-client](https://user-images.githubusercontent.com/18533628/114278522-41d2a980-99fe-11eb-918d-ed151d6d5353.png)
Using the component `FormGroup` with css for the `max-width: 100%` style instead of using `styled(FormGroup)` works as expected. So the issue is definitely with `styled-components`

**Comment by balthazar** [comment] 2021-05-10 18:17
I'm experiencing something similar, was quite unsure as to what was happening.

**Comment by balthazar** [comment] 2021-05-10 18:22
For people who want a quick fix: you should use version 5.1.1, installing anything after makes the bug appear

**Comment by balthazar** [comment] 2021-05-10 18:24
Pinging @probablyup for visibility

**Comment by probablyup** [comment] 2021-05-10 18:26
Really need a reproduction to even begin to help

**Comment by dylanmrowe** [comment] 2021-05-21 21:46
We were seeing the same thing on styled-components v5.1.0. Components, seemingly at random, would get injected styles that we didn't specify. It worked fine locally but doing a production build (using `next build`) broke things. 

Refreshing the page would sometimes manifest the issue, sometimes not. 

Using:
NextJS 9.5.2 
@material-ui/core 4.11.0
Node 12.x
react 16.13.1

We had to downgrade to v4.4.1 to fix the issue.

**Comment by probablyup** [comment] 2021-06-02 14:22
This is often due to multiple versions of s-c being bundled. If you use `yarn` I highly recommend setting up a resolutions entry (see the yarn section): https://styled-components.com/docs/basics#installation

**Comment by dcorb** [comment] 2021-06-07 06:57
`npm ls styled-components` says only 1 version, 4.4.1

**Comment by andywampir** [comment] 2021-06-09 05:57
If you using `babel-plugin-styled-components` [namespace](https://styled-components.com/docs/tooling#namespace) might help you, in my case it's worked

**Comment by kitten** [comment] 2021-08-09 14:58
Closing due to missing reproduction

**Closed by kitten** 2021-08-09 14:58 UTC

**Comment by jcrben** [comment] 2021-09-19 03:46
Note for those running into an issue like this: 5.3.1 fixed my issue of wrong styles applied when built but not in dev (while running 5.2.3), perhaps due to https://github.com/styled-components/styled-components/pull/3553
